### ISSUE TITLE
Installation on OS X Sierra

### ISSUE THREAD

**Issue by gdillon77** [firedrakeproject/firedrake#1054]
Hello, I tried installing firedrake using the install script and got the following error:
Installing command line tools...
Installing required packages via homebrew. You can safely ignore warnings that packages are already installed
Creating firedrake virtualenv in '/Users/gdillon/firedrake'.
Traceback (most recent call last):
  File "firedrake-install", line 1251, in <module>
    virtualenv.create_environment(firedrake_env, site_packages=False)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1004, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 969, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 910, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/gdillon/firedrake/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1

I am attaching the logfile as requested.  If I look in the firedrake/ directory all I see are bin/ include/ and lib/ all of which only contain python related files.

[firedrake-install.log.txt](https://github.com/firedrakeproject/firedrake/files/956204/firedrake-install.log.txt)

**Comment by wence-** [comment]
Hmm, something broke very early, when we were trying to create the python virtualenv.

Can you do:

```sh
python -c "import virtualenv; virtualenv.create_environment('test', site_package=False)"
```

And report what happens?

**Comment by gdillon77** [comment]
Sorry for the delayed response:
python -c "import virtualenv; virtualenv.create_environment('test', site_package=False)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: create_environment() got an unexpected keyword argument 'site_package'

**Comment by wence-** [comment]
Sorry, typo: `site_packages` with an s at the end.

**Comment by gdillon77** [comment]
python -c "import virtualenv; virtualenv.create_environment('test', site_packages=False)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1004, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 969, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 910, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/gdillon/test/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1

**Comment by wence-** [comment]
Hmm, this is strange.  A few things strike me as possibilities.

Do you have any other python installations (e.g. conda, from macports or similar)?  The only issues I can find reported that are similar to this involve conda python.

What does:

```
which python
python --version
```

Say?

Similarly, what about:

```
which pip
pip --version
```

```
which virtualenv
virtualenv --version
```

and

```
pip list
```

?

**Comment by gdillon77** [comment]
I do have anaconda:
1st:
which python
/Users/gdillon/anaconda/bin/python
turing:~ gdillon$ python --version
Python 2.7.12 :: Anaconda 4.2.0 (x86_64)
2nd:
which pip
/Users/gdillon/anaconda/bin/pip
turing:~ gdillon$ pip --version
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)

3rd:
which virtualenv
/usr/local/bin/virtualenv
turing:~ gdillon$ virtualenv --version
13.1.2

4th:
pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
alabaster (0.7.9)
anaconda-clean (1.0)
anaconda-client (1.5.1)
anaconda-navigator (1.3.1)
appnope (0.1.0)
appscript (1.0.1)
argcomplete (1.0.0)
astroid (1.4.7)
astropy (1.2.1)
Babel (2.3.4)
backports-abc (0.5)
backports.shutil-get-terminal-size (1.0.0)
backports.ssl-match-hostname (3.4.0.2)
beautifulsoup4 (4.5.1)
bitarray (0.8.1)
blaze (0.10.1)
bleach (1.5.0)
bokeh (0.12.2)
boto (2.42.0)
Bottleneck (1.1.0)
cdecimal (2.3)
certifi (2016.9.26)
cffi (1.7.0)
chardet (2.3.0)
chest (0.2.3)
click (6.6)
cloudpickle (0.2.1)
clyent (1.2.2)
colorama (0.3.7)
conda (4.3.16)
conda-build (2.0.2)
configobj (5.0.6)
configparser (3.5.0)
contextlib2 (0.5.3)
cryptography (1.5)
cycler (0.10.0)
Cython (0.24.1)
cytoolz (0.8.0)
dask (0.11.0)
datashape (0.5.2)
decorator (4.0.10)
dijitso (2016.2.0)
dill (0.2.5)
docutils (0.12)
dynd (0.7.3.dev1)
entrypoints (0.2.2)
enum34 (1.1.6)
et-xmlfile (1.0.1)
fastcache (1.0.2)
FFC (2016.2.0)
FIAT (2016.2.0)
filelock (2.0.6)
Flask (0.11.1)
Flask-Cors (2.1.2)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
futures (3.0.5)
gevent (1.1.2)
greenlet (0.4.10)
grin (1.2.1)
h5py (2.6.0)
HeapDict (1.0.0)
html5lib (0.9999999)
idna (2.1)
imagesize (0.7.1)
instant (2016.2.0)
ipaddress (1.0.16)
ipykernel (4.5.2)
ipython (5.1.0)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
itsdangerous (0.24)
jdcal (1.2)
jedi (0.9.0)
Jinja2 (2.9.4)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.0.0)
jupyter-core (4.2.1)
lazy-object-proxy (1.2.1)
llvmlite (0.13.0)
locket (0.2.0)
lxml (3.6.4)
MarkupSafe (0.23)
matplotlib (1.5.3)
mercurial (4.1)
mistune (0.7.3)
mpmath (0.19)
multipledispatch (0.4.8)
nb-anacondacloud (1.2.0)
nb-conda (2.0.0)
nb-conda-kernels (2.0.0)
nbconvert (5.0.0)
nbformat (4.2.0)
nbpresent (3.0.2)
networkx (1.11)
nltk (3.2.1)
nose (1.3.7)
notebook (4.3.1)
numba (0.28.1+0.gfe99fbc.dirty)
numexpr (2.6.1)
numpy (1.10.4)
numpydoc (0.6.0)
odo (0.5.0)
openpyxl (2.3.2)
pandas (0.18.1)
pandocfilters (1.4.1)
partd (0.3.6)
path.py (0.0.0)
pathlib2 (2.2.0)
patsy (0.4.1)
pep8 (1.7.0)
petsc4py (3.7.0)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (3.3.1)
pip (9.0.1)
pkginfo (1.3.2)
ply (3.9)
prompt-toolkit (1.0.9)
protobuf (3.0.0a3)
psutil (4.3.1)
ptyprocess (0.5.1)
py (1.4.32)
pyamg (3.2.1)
pyasn1 (0.1.9)
PyAudio (0.2.7)
pycosat (0.6.1)
pycparser (2.14)
pycrypto (2.6.1)
pycurl (7.43.0)
pyflakes (1.3.0)
Pygments (2.1.3)
pylint (1.5.4)
pyOpenSSL (16.2.0)
pyparsing (2.1.10)
pytest (3.0.5)
python-dateutil (2.6.0)
pytz (2016.10)
PyYAML (3.12)
pyzmq (16.0.2)
QtAwesome (0.4.1)
qtconsole (4.2.1)
QtPy (1.1.2)
redis (2.10.5)
requests (2.12.4)
rope (0.9.4)
ruamel-yaml (-VERSION)
scandir (1.4)
scikit-image (0.12.3)
scikit-learn (0.18)
scikit-tensor (0.1)
scipy (0.18.1)
setuptools (32.1.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
slepc4py (3.7.0)
snowballstemmer (1.2.1)
sockjs-tornado (1.0.3)
Sphinx (1.4.6)
spyder (3.1.0)
SQLAlchemy (1.0.13)
statsmodels (0.6.1)
subprocess32 (3.2.7)
sympy (1.0)
tables (3.2.3.1)
TBB (0.1)
tensorflow (0.7.0)
terminado (0.6)
testpath (0.3)
toolz (0.8.0)
tornado (4.4.2)
traitlets (4.3.1)
UFL (2016.2.0)
unicodecsv (0.14.1)
virtualenv (13.1.2)
wcwidth (0.1.7)
Werkzeug (0.11.11)
wheel (0.29.0)
widgetsnbextension (1.2.6)
wrapt (1.10.6)
xlrd (1.0.0)
XlsxWriter (0.9.3)
xlwings (0.10.0)
xlwt (1.1.2)

**Comment by miklos1** [comment]
@gdillon77: well, anaconda is not supported:
> The installation script does not work with anaconda based python installations, because it uses virtualenvs which anaconda does not support.
http://firedrakeproject.org/download.html#supported-python-distributions

**Comment by gdillon77** [comment]
I deleted anaconda and did some housecleaning.  Now for the above queries I get:

> which python
/usr/local/bin/python
Turing:~ gdillon$ python --version
Python 2.7.10

> which pip
/usr/local/bin/pip
Turing:~ gdillon$ pip --version
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 

> which virtualenv
/usr/local/bin/virtualenv
Turing:~ gdillon$ virtualenv --version
13.1.2

> pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appnope (0.1.0)
backports-abc (0.5)
backports.shutil-get-terminal-size (1.0.0)
bleach (1.5.0)
certifi (2016.9.26)
configparser (3.5.0)
cycler (0.10.0)
decorator (4.0.10)
entrypoints (0.2.2)
enum34 (1.1.6)
functools32 (3.2.3.post2)
html5lib (0.9999999)
ipykernel (4.5.2)
ipython (5.1.0)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
Jinja2 (2.9.4)
jsonschema (2.5.1)
jupyter-client (4.4.0)
jupyter-core (4.2.1)
MarkupSafe (0.23)
matplotlib (1.5.3)
mercurial (4.1)
mistune (0.7.3)
nbconvert (5.0.0)
nbformat (4.2.0)
networkx (1.11)
notebook (4.3.1)
numpy (1.10.4)
pandocfilters (1.4.1)
pathlib2 (2.2.0)
pexpect (4.2.1)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.9)
protobuf (3.0.0a3)
ptyprocess (0.5.1)
py (1.4.32)
pyamg (3.2.1)
Pygments (2.1.3)
pyparsing (2.1.10)
pytest (3.0.5)
python-dateutil (2.6.0)
pytz (2016.10)
pyzmq (16.0.2)
scandir (1.4)
scipy (0.18.1)
setuptools (32.1.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
smop (0.0.0)
TBB (0.1)
tensorflow (0.7.0)
terminado (0.6)
testpath (0.3)
tornado (4.4.2)
traitlets (4.3.1)
virtualenv (13.1.2)
wcwidth (0.1.7)
wheel (0.29.0)
widgetsnbextension (1.2.6)


The installation proceeds much further now, but I get an error as shown in the attached log.
[firedrake-install.log.txt](https://github.com/firedrakeproject/firedrake/files/962677/firedrake-install.log.txt).   The crash error I got was:

> Traceback (most recent call last):
  File "firedrake-install", line 1310, in <module>
    install("petsc/")
  File "firedrake-install", line 754, in install
    run_pip_install(["--ignore-installed", package])
  File "firedrake-install", line 624, in run_pip_install
    check_call(pipinstall + pipargs)
  File "firedrake-install", line 364, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=env))
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/Users/gdillon/firedrake/bin/pip', 'install', '--no-binary', 'mpi4py', '--no-deps', '-vvv', '--ignore-installed', 'petsc/']' returned non-zero exit status 1

**Comment by wence-** [comment]
Hmm, this basically all went fine, except that during the installation of PETSc the internet decided not to play ball.  For some reason clone eigen is always a problem (some of these issues are mentioned in #1051).

Unfortunately, if the installation fails half way through, we are not able to recover and continue from this broken state, so can you please blow away the `firedrake/` directory and try again?

**Comment by gdillon77** [comment]
I deleted the firedrake directory and tried again.  Same thing happened.  Should I try to install eigen first?  I'm not doing any fancy petsc options either, just using the instructions on the firedrake site as is.  I'm pretty sure it's exactly the same, but I'm attaching the log file again.
[firedrake-install.log.txt](https://github.com/firedrakeproject/firedrake/files/964690/firedrake-install.log.txt)

**Comment by wence-** [comment]
Hmm, that looks like a different error.  Eigen is providing all sorts of problems for us right now, sorry!

Can you try the same as proposed in #1058:

```
cd firedrake/src/petsc
./configure --prefix=/Users/gdillon/firedrake/test-petsc-install PETSC_ARCH=arch-python-linux-x86_64 --with-shared-libraries=1 --with-debugging=0 --with-c2html=0 --with-cc=/usr/bin/mpicc --with-cxx=/usr/bin/mpicxx --with-fc=/usr/bin/mpif90 --download-chaco --download-metis --download-parmetis --download-scalapack --download-hypre --download-mumps --download-netcdf --download-hdf5 --download-exodusii --download-eigen
```

And if that fails, post the output of `configure.log` (and, if requested, `make.log`)?

Apologies again for all the troubles.

**Comment by wence-** [comment]
Dear @gdillon77, we just made some changes to the install script that hopefully makes downloading and install eigen more robust. Please download the install script anew from https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install and try again. Hopefully things will work, but if not, we would love to know so we can attempt to fix them.

**Comment by gdillon77** [comment]
Got past the difficulty with eigen, but got the following message:

> Failed to clone libspatialindex using ssh, falling back to https.
Successfully cloned repository libspatialindex.
Checking out branch master
Successfully checked out branch master
Traceback (most recent call last):
  File "firedrake-install", line 1104, in <module>
    build_and_install_libspatialindex()
  File "firedrake-install", line 802, in build_and_install_libspatialindex
    check_call(["make"])
  File "firedrake-install", line 357, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=env))
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2


I am attaching my log file.  Thanks for working on this!
[firedrake-install.log.txt](https://github.com/firedrakeproject/firedrake/files/994050/firedrake-install.log.txt)

**Comment by rckirby** [comment]
Geoffrey, I had a similar problem last night.  It went away when I ran the
script a second time in the same spot.

**Comment by wence-** [comment]
Hmmm, something went wrong linking `libspatialindex`.

If I compare the link line that libtool produces on your system (where things did not work) with my Sierra laptop, I see this:

```
# Broken:
gcc -dynamiclib  -o .libs/libspatialindex.4.dylib [...] -Wl,-force_load,src/tools/.libs/libtools.a  /usr/local/lib/libstdc++.dylib -L/Users/admin/build/x86_64-apple-darwin15.0.0/libstdc++-v3/src -L/Users/admin/build/x86_64-apple-darwin15.0.0/libstdc++-v3/src/.libs -L/Users/admin/build/x86_64-apple-darwin15.0.0/libstdc++-v3/libsupc++/.libs [...] 

# Working
gcc -dynamiclib  -o .libs/libspatialindex.4.dylib [...] -Wl,-force_load,src/tools/.libs/libtools.a  -lstdc++ [...]
```

So there's a small amount of difference in the link line.  But that appears to be it.

In the failed firedrake install can you do:

```
cd firedrake/src/libspatialindex
./libtool --config
```

So we can see what libtool thinks is going on.

**Comment by gdillon77** [comment]
Sorry to resurrect this, but I did what you said and saved the output of ./libtool --config to a text file.  I've attached it.
[libtool_output.txt](https://github.com/firedrakeproject/firedrake/files/1120654/libtool_output.txt)

**Comment by wence-** [comment]
Apologies for the slow response.

Hmmm, that looks identical to what I have.  Can you also provide the contents of `libspatialindex/Makefile`?

**Comment by gdillon77** [comment]
In the firedrake/src/libspatialindex folder there is a Makefile, Makefile.am, and Makefile.in.  I am attaching all 3 just to be safe.  I had to change the file extensions to .txt.
[Makefile.txt](https://github.com/firedrakeproject/firedrake/files/1152894/Makefile.txt)
[Makefile.in.txt](https://github.com/firedrakeproject/firedrake/files/1152895/Makefile.in.txt)
[Makefile.am.txt](https://github.com/firedrakeproject/firedrake/files/1152893/Makefile.am.txt)

**Comment by wence-** [comment]
Assuming this is no longer problematic.
