### ISSUE TITLE
Empty blocks in R FunctionSpace lead to error

### ISSUE THREAD

**Issue by florianwechsung** [firedrakeproject/firedrake#1096]
This throws an index out of range exception because `form.ufl_domains()` is empty. 
Adding artificial blocks (see comments) fixes it.

```
from firedrake import *
mesh = UnitSquareMesh(10, 10)
V = VectorFunctionSpace(mesh, "CG", 1) * FunctionSpace(mesh, "R", 0)
(u, p) = TrialFunctions(V)
(v, q) = TestFunctions(V)

L = inner(grad(u), grad(v)) * dx(domain=mesh) + div(u) * q * dx(domain=mesh) \
    + div(v) * p * dx(domain=mesh) # + Constant(0.0) * p * q * dx(domain=mesh)
assemble(L)

rhs = Constant(1.0) * div(v) * dx # + Constant(0.0) * q * dx
assemble(rhs)
```

**Comment by wence-** [comment]
The initial problem can be fixed with this patch:
```diff
diff --git a/firedrake/tsfc_interface.py b/firedrake/tsfc_interface.py
index 9b20867..a5f996f 100644
--- a/firedrake/tsfc_interface.py
+++ b/firedrake/tsfc_interface.py
@@ -188,6 +188,8 @@ def compile_form(form, name, parameters=None, inverse=False):
                                for (n, c) in enumerate(form.coefficients()))
     for idx, f in split_form(form):
         f = _real_mangle(f)
+        if not len(f.integrals()):
+            continue
         # Map local coefficient numbers (as seen inside the
         # compiler) to the global coefficient numbers
         number_map = dict((n, coefficient_numbers[c])
```

You then run into the problem that the implementation doesn't work for the case of VFS*Real.  

If you then apply this patch in PyOP2:

```diff
diff --git a/pyop2/petsc_base.py b/pyop2/petsc_base.py
index a6e2f76..dfc4550 100644
--- a/pyop2/petsc_base.py
+++ b/pyop2/petsc_base.py
@@ -950,9 +950,11 @@ def _DatMat(sparsity, dat=None):
     """A :class:`PETSc.Mat` with global size nx1 or nx1 implemented as a
     :class:`.Dat`"""
     if isinstance(sparsity.dsets[0], GlobalDataSet):
-        sizes = ((None, 1), (sparsity._ncols, None))
+        dset = sparsity.dsets[1]
+        sizes = ((None, 1), (dset.size*dset.cdim, None))
     elif isinstance(sparsity.dsets[1], GlobalDataSet):
-        sizes = ((sparsity._nrows, None), (None, 1))
+        dset = sparsity.dsets[0]
+        sizes = ((dset.size * dset.cdim, None), (None, 1))
     else:
         raise ValueError("Not a DatMat")
 
@@ -967,10 +969,10 @@ class _DatMatPayload(object):
     def __init__(self, sparsity, dat=None, dset=None):
         if isinstance(sparsity.dsets[0], GlobalDataSet):
             self.dset = sparsity.dsets[1]
-            self.sizes = ((None, 1), (sparsity._ncols, None))
+            self.sizes = ((None, 1), (self.dset.size * self.dset.cdim, None))
         elif isinstance(sparsity.dsets[1], GlobalDataSet):
             self.dset = sparsity.dsets[0]
-            self.sizes = ((sparsity._nrows, None), (None, 1))
+            self.sizes = ((self.dset.size * self.dset.cdim, None), (None, 1))
         else:
             raise ValueError("Not a DatMat")
 
```

It appears to work.  Can you confirm?

**Comment by florianwechsung** [comment]
Thanks @wence-, that fixes the problem above, however, when I assemble first and then solve, then I get a new problem.

```
from firedrake import *
mesh = UnitSquareMesh(10, 10)
V = FunctionSpace(mesh, "CG", 1) * FunctionSpace(mesh, "R", 0)
(u, p) = TrialFunctions(V)
(v, q) = TestFunctions(V)

L = inner(grad(u), grad(v)) * dx + (u) * q * dx \
    + (v) * p * dx
rhs = Constant(1.0) * (v) * dx
u = Function(V)

solve(L==rhs, u, bcs=[DirichletBC(V.sub(0), 1, 1)]) # works

solve(assemble(L), u, assemble(rhs), bcs=[DirichletBC(V.sub(0), 1, 1)]) # doesn't work
```
results in 
```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    solve(assemble(L), u, assemble(rhs), bcs=[DirichletBC(V.sub(0), 1, 1)])
  File "/Users/florianwechsung/bin/firedrake/src/firedrake/firedrake/solving.py", line 127, in solve
    return _la_solve(*args, **kwargs)
  File "/Users/florianwechsung/bin/firedrake/src/firedrake/firedrake/solving.py", line 227, in _la_solve
    solver.solve(x, b)
  File "/Users/florianwechsung/bin/firedrake/src/firedrake/firedrake/linear_solver.py", line 142, in solve
    b_bc.assign(b - self._Abcs)
  File "<decorator-gen-273>", line 2, in assign
  File "/Users/florianwechsung/bin/firedrake/src/firedrake/firedrake/utils.py", line 62, in wrapper
    return f(*args, **kwargs)
  File "/Users/florianwechsung/bin/firedrake/src/firedrake/firedrake/function.py", line 356, in assign
    assemble_expressions.Assign(self, expr), subset)
  File "<decorator-gen-278>", line 2, in evaluate_expression
  File "/Users/florianwechsung/bin/firedrake/src/firedrake/firedrake/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/Users/florianwechsung/bin/firedrake/src/firedrake/firedrake/assemble_expressions.py", line 578, in evaluate_expression
    evaluate_preprocessed_expression(k, args, subset)
  File "/Users/florianwechsung/bin/firedrake/src/firedrake/firedrake/assemble_expressions.py", line 546, in evaluate_preprocessed_expression
    op2.par_loop(kernel, itset, *parloop_args)
  File "/Users/florianwechsung/bin/firedrake/src/PyOP2/pyop2/base.py", line 4435, in par_loop
    return _make_object('ParLoop', kernel, it_space, *args, **kwargs).enqueue()
  File "/Users/florianwechsung/bin/firedrake/src/PyOP2/pyop2/base.py", line 68, in _make_object
    return getattr(sequential, name)(*args, **kwargs)
  File "<decorator-gen-19>", line 2, in __init__
  File "/Users/florianwechsung/bin/firedrake/src/PyOP2/pyop2/utils.py", line 130, in wrapper
    return f(*args, **kwargs)
  File "/Users/florianwechsung/bin/firedrake/src/PyOP2/pyop2/base.py", line 4032, in __init__
    self._is_layered = iterset._extruded
AttributeError: 'NoneType' object has no attribute '_extruded'
```

**Comment by wence-** [comment]
OK, you're lucky you get that far, I get segfaults.

It turns out this is more broken, since no-one has tried to solve problems with real variables and boundary conditions.  As a result, the way in which we assemble into the two off-diagonal blocks is broken.

**Comment by wence-** [comment]
WIP that might work in the `mixed-real-bcs` branch.  It's a horrible solution though.
