### ISSUE TITLE
Cannot interpolate or assign to functions in R

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#1203]
```
from firedrake import *
mesh = UnitIntervalMesh(2)
V = FunctionSpace(mesh, "R", 0)
u = Function(V)
#u.assign(Constant(1))
u.interpolate(Constant(1))
```
yields

```
Traceback (most recent call last):
  File "ex.py", line 7, in <module>
    u.interpolate(Constant(1))
  File "/home/pefarrell/local/firedrake/firedrake-dev-20180319/src/firedrake/firedrake/function.py", line 334, in interpolate
    return interpolation.interpolate(expression, self, subset=subset)
  File "/home/pefarrell/local/firedrake/firedrake-dev-20180319/src/firedrake/firedrake/interpolation.py", line 37, in interpolate
    return Interpolator(expr, V, subset=subset).interpolate()
  File "/home/pefarrell/local/firedrake/firedrake-dev-20180319/src/firedrake/firedrake/interpolation.py", line 57, in __init__
    self.callable = make_interpolator(expr, V, subset)
  File "/home/pefarrell/local/firedrake/firedrake-dev-20180319/src/firedrake/firedrake/interpolation.py", line 112, in make_interpolator
    loops.extend(_interpolator(V, f.dat, expr, subset))
  File "/home/pefarrell/local/firedrake/firedrake-dev-20180319/src/firedrake/firedrake/interpolation.py", line 192, in _interpolator
    args.append(dat(op2.WRITE, V.cell_node_map()[op2.i[0]]))
TypeError: 'NoneType' object is not subscriptable
```

If I try `u.assign` instead, it yields

```
Traceback (most recent call last):
  File "ex.py", line 6, in <module>
    u.assign(Constant(1))
  File "<decorator-gen-519>", line 2, in assign
  File "/home/pefarrell/local/firedrake/firedrake-dev-20180319/src/firedrake/firedrake/utils.py", line 61, in wrapper
    return f(*args, **kwargs)
  File "/home/pefarrell/local/firedrake/firedrake-dev-20180319/src/firedrake/firedrake/function.py", line 362, in assign
    assemble_expressions.Assign(self, expr), subset)
  File "<decorator-gen-524>", line 2, in evaluate_expression
  File "/home/pefarrell/local/firedrake/firedrake-dev-20180319/src/firedrake/firedrake/utils.py", line 58, in wrapper
    return f(*args, **kwargs)
  File "/home/pefarrell/local/firedrake/firedrake-dev-20180319/src/firedrake/firedrake/assemble_expressions.py", line 575, in evaluate_expression
    evaluate_preprocessed_expression(k, args, subset)
  File "/home/pefarrell/local/firedrake/firedrake-dev-20180319/src/firedrake/firedrake/assemble_expressions.py", line 543, in evaluate_preprocessed_expression
    op2.par_loop(kernel, itset, *parloop_args)
  File "/home/pefarrell/local/firedrake/firedrake-dev-20180319/src/PyOP2/pyop2/base.py", line 4250, in par_loop
    return _make_object('ParLoop', kernel, iterset, *args, **kwargs).enqueue()
  File "/home/pefarrell/local/firedrake/firedrake-dev-20180319/src/PyOP2/pyop2/base.py", line 68, in _make_object
    return getattr(sequential, name)(*args, **kwargs)
  File "<decorator-gen-18>", line 2, in __init__
  File "/home/pefarrell/local/firedrake/firedrake-dev-20180319/src/PyOP2/pyop2/utils.py", line 133, in wrapper
    return f(*args, **kwargs)
  File "/home/pefarrell/local/firedrake/firedrake-dev-20180319/src/PyOP2/pyop2/base.py", line 3930, in __init__
    self._is_layered = iterset._extruded
AttributeError: 'NoneType' object has no attribute '_extruded'
```

**Comment by dham** [comment]
Clearly the special cases for R aren't in for these cases. As a workaround you should be able to assign into `u.dat.data[0]`
