### ISSUE TITLE
Install scripts fails on macOS with MPICH

### ISSUE THREAD

**Issue by prj-** [firedrakeproject/firedrake#1241]
I'm using MPICH instead of OpenMPI. The install script fails with the following error:
```
Traceback (most recent call last):
  File "firedrake-install", line 953, in <module>
    brew_install("openmpi")
  File "firedrake-install", line 398, in brew_install
    check_call(["brew", "install"] + arguments)
  File "firedrake-install", line 366, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=env).decode())
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['brew', 'install', 'openmpi']' returned non-zero exit status 1.
```
I do not which to have two MPI implementations on my system, is OpenMPI a hard-dependency?
Thanks.

**Comment by jandrej** [comment]
No, OpenMPI is not a dependency. Many users use MPICH as their MPI implementation of choice.

**Comment by prj-** [comment]
So... how may I make the install script _not_ fail with MPICH?

**Comment by wence-** [comment]
You can say `firedrake-install --no-package-manager`, and then we just assume the packages we need are already there.  The homebrew packages we go for are:

```
            brew_install("gcc")
            brew_install("openmpi")
            brew_install("python3")
            brew_install("autoconf")
            brew_install("automake")
            brew_install("cmake")
            brew_install("libtool")
            brew_install("mercurial")
```
