### ISSUE TITLE
Function.at gives ImportError for set_scalar_type in complex

### ISSUE THREAD

**Issue by orpembery** [firedrakeproject/firedrake#1289]
Running
```
mesh = UnitSquareMesh(2,2)
V = FunctionSpace(mesh,"CG",1)
func = Function(V)
func.at([0.5,0.5])
```
in complex gives me
```
Traceback (most recent call last):
  File "/home/owen/progs/firedrake-complex/firedrake/src/firedrake/firedrake/function.py", line 469, in _c_evaluate
    return cache[tolerance]
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/owen/progs/firedrake-complex/firedrake/src/firedrake/firedrake/function.py", line 555, in at
    single_eval(points[i:i+1], p_result)
  File "/home/owen/progs/firedrake-complex/firedrake/src/firedrake/firedrake/function.py", line 533, in single_eval
    err = self._c_evaluate(tolerance=tolerance)(self._ctypes,
  File "/home/owen/progs/firedrake-complex/firedrake/src/firedrake/firedrake/function.py", line 471, in _c_evaluate
    result = make_c_evaluate(self, tolerance=tolerance)
  File "/home/owen/progs/firedrake-complex/firedrake/src/firedrake/firedrake/function.py", line 611, in make_c_evaluate
    from firedrake.pointeval_utils import compile_element
  File "/home/owen/progs/firedrake-complex/firedrake/src/firedrake/firedrake/pointeval_utils.py", line 15, in <module>
    from tsfc.parameters import default_parameters, set_scalar_type, scalar_type
ImportError: cannot import name 'set_scalar_type'
```

It works fine on master, but I don't know what's happening in complex.

**Comment by orpembery** [comment]
A little bit of digging indicates that the functions set_scalar_type and scalar_type haven't been defined (either in tsfc.parameters, or anywhere else).

**Comment by dham** [comment]
Yes, this is not fixed yet.

**Comment by orpembery** [comment]
No worries - thought I'd try and be a bit helpful and do some investigating myself!

**Comment by dham** [comment]
Sorry. Being half time has nuked my research hours. I'm back full time from 1 October and hope to nail a bunch of this stuff.

**Comment by wence-** [comment]
Fixed in complex merge candidate.
