### ISSUE TITLE
File is not a valid Gmsh file

### ISSUE THREAD

**Issue by aterenin** [firedrakeproject/firedrake#1291]
Minimum working example using latest version of FireDrake. Spoke to @dham at Imperial today, suspect petsc not yet updated to support latest version of gmsh.

Error
```
>>> firedrake.Mesh("/Users/aterenin/line.msh")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-506>", line 2, in Mesh
  File "/Users/aterenin/Git/firedrake/src/PyOP2/pyop2/profiling.py", line 60, in wrapper
    return f(*args, **kwargs)
  File "/Users/aterenin/Git/firedrake/src/firedrake/firedrake/mesh.py", line 1325, in Mesh
    plex = _from_gmsh(meshfile, comm)
  File "/Users/aterenin/Git/firedrake/src/firedrake/firedrake/mesh.py", line 218, in _from_gmsh
    gmsh_plex = PETSc.DMPlex().createGmsh(gmsh_viewer, comm=comm)
  File "PETSc/DMPlex.pyx", line 119, in petsc4py.PETSc.DMPlex.createGmsh
petsc4py.PETSc.Error: error code 62
[0] DMPlexCreateGmsh() line 292 in /private/var/folders/dp/_gvn1gp57ylgkp_p3nx51lkh0000gn/T/pip-req-build-mf_dak8a/src/dm/impls/plex/plexgmsh.c
[0] Invalid argument
[0] File is not a valid Gmsh file
```

line.geo
```
Point(1) = { 0.0, 0.0, 0.0 };
Point(2) = { 1.0, 0.0, 0.0 };
Line(1) = { 1, 2 };
```

line.msh
```
$MeshFormat
4 0 8
$EndMeshFormat
$Entities
2 1 0 0
1 0 0 0 0 0 0 0 
2 1 0 0 1 0 0 0 
1 0 0 0 1 0 0 0 2 1 -2 
$EndEntities
$Nodes
3 6
1 0 0 1
1 0 0 0
2 0 0 1
2 1 0 0
1 1 0 4
3 0.2000000005225674 0 0
4 0.400000001085815 0 0
5 0.600000001093951 0 0
6 0.8000000005469755 0 0
$EndNodes
$Elements
3 7
1 0 15 1
1 1 
2 0 15 1
2 2 
1 1 1 5
3 1 3 
4 3 4 
5 4 5 
6 5 6 
7 6 2 
$EndElements
```

**Comment by wence-** [comment]
Yes. If you make the mesh with `-format msh2` Things should work.

**Comment by wence-** [comment]
PETSc's gmsh reader has now been updated to support v4 of the mesh
file format.
