### ISSUE TITLE
Cannot use nullspaces with problems with Real components

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#1295]
I'm trying to solve a mixed problem that has R as one of the sub function spaces and a nullspace on another component. It seems that there's a bug in the nullspace construction that makes this crash. A minimal reproducing example is the Neumann Poisson problem with a real-valued equation tacked on:

```
from firedrake import *

mesh = UnitSquareMesh(20, 20)
V = FunctionSpace(mesh, "CG", 1)
R = FunctionSpace(mesh, "R",  0)
Z = MixedFunctionSpace([V, R])
z = Function(Z)
(u, c) = split(z)
(v, d) = split(TestFunction(Z))
f = Constant(1)

# Poisson-Neumann but with a dummy R-valued equation tacked on
F = inner(grad(u), grad(v))*dx - inner(f, v)*dx + inner(c - f, d)*dx
nsp = MixedVectorSpaceBasis(Z, [VectorSpaceBasis(constant=True), Z.sub(1)])
solve(F == 0, z, nullspace=nsp)
```

yields

```
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    solve(F == 0, z, nullspace=nsp)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20180927/src/firedrake/firedrake/solving.py", line 124, in solve
    _solve_varproblem(*args, **kwargs)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20180927/src/firedrake/firedrake/solving.py", line 171, in _solve_varproblem
    appctx=appctx)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20180927/src/firedrake/firedrake/variational_solver.py", line 179, in __init__
    transpose=False, near=False)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20180927/src/firedrake/firedrake/solving_utils.py", line 164, in set_nullspace
    nullspace._apply(self._jac, transpose=transpose, near=near)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20180927/src/firedrake/firedrake/nullspace.py", line 326, in _apply
    self._apply_monolithic(matrix, transpose=transpose, near=near)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20180927/src/firedrake/firedrake/nullspace.py", line 284, in _apply_monolithic
    self._build_monolithic_basis()
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20180927/src/firedrake/firedrake/nullspace.py", line 255, in _build_monolithic_basis
    v /= v.dat.norm
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20180927/src/PyOP2/pyop2/base.py", line 1928, in norm
    return sqrt(self.inner(self))
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20180927/src/PyOP2/pyop2/base.py", line 2310, in inner
    ret += s.inner(o)
AttributeError: 'Global' object has no attribute 'inner'
```

**Comment by pefarrell** [comment]
The following patch lets it run:

```
diff --git a/pyop2/base.py b/pyop2/base.py
index df5a6179..b90f4492 100644
--- a/pyop2/base.py
+++ b/pyop2/base.py
@@ -2529,6 +2529,9 @@ class Global(DataCarrier, _EmptyDataMixin):
 
         other.data = np.copy(self.data_ro)
 
+    def inner(self, other):
+        return self.data_ro * other.data_ro
+
     class Zero(LazyComputation):
         def __init__(self, g):
             super(Global.Zero, self).__init__(reads=[], writes=[g], incs=[])

```

but then the mixed problem doesn't give the same answer as the unmixed Neumann Poisson problem. Shouldn't it?

```
from firedrake import *

mesh = UnitSquareMesh(20, 20)
V = FunctionSpace(mesh, "CG", 1)
pvd = File("output/neumann.pvd")

# Case 1: Poisson-Neumann problem

u = Function(V, name="Neumann")
v = TestFunction(V)
f = Constant(1)
F = inner(grad(u), grad(v))*dx - inner(f, v)*dx
nsp = VectorSpaceBasis(constant=True)
sp = {"snes_type": "ksponly", "ksp_type": "preonly", "pc_type": "lu"}
solve(F == 0, u, nullspace=nsp, solver_parameters=sp)
pvd.write(u)


# Case 2: with a dummy Real equation
R = FunctionSpace(mesh, "R",  0)
Z = MixedFunctionSpace([V, R])
z = Function(Z)
(u, c) = split(z)
(v, d) = split(TestFunction(Z))

F = inner(grad(u), grad(v))*dx - inner(f, v)*dx + inner(c - f, d)*dx
nsp = MixedVectorSpaceBasis(Z, [VectorSpaceBasis(constant=True), Z.sub(1)])
solve(F == 0, z, nullspace=nsp) # use default solver parameters

u = z.split()[0]
u.rename("Neumann")
pvd.write(u)
```

**Comment by dham** [comment]
Does the difference in solution lie in the nullspace?

**Comment by pefarrell** [comment]
No, they don't look like they're related by a constant and if I plug the mixed solution back in to the original problem, it has a nonzero residual:

```
from firedrake import *

mesh = UnitSquareMesh(20, 20)
V = FunctionSpace(mesh, "CG", 1)
pvd = File("output/neumann.pvd")

# Case 1: Poisson-Neumann problem

u = Function(V, name="Neumann")
v = TestFunction(V)
f = Constant(1)
F = inner(grad(u), grad(v))*dx - inner(f, v)*dx
nsp = VectorSpaceBasis(constant=True)
sp = {"snes_type": "ksponly", "ksp_type": "preonly", "pc_type": "lu"}
solve(F == 0, u, nullspace=nsp, solver_parameters=sp)
pvd.write(u)


# Case 2: with a dummy Real equation
R = FunctionSpace(mesh, "R",  0)
Z = MixedFunctionSpace([V, R])
z = Function(Z)
(u, c) = split(z)
(v, d) = split(TestFunction(Z))

F = inner(grad(u), grad(v))*dx - inner(f, v)*dx + inner(c - f, d)*dx
nsp = MixedVectorSpaceBasis(Z, [VectorSpaceBasis(constant=True), Z.sub(1)])
solve(F == 0, z, nullspace=nsp)

u = z.split()[0]
u.rename("Neumann")
pvd.write(u)

v = TestFunction(V)
b = assemble(inner(grad(u), grad(v))*dx - inner(f, v)*dx)
import numpy
print("norm(b): %s" % numpy.linalg.norm(b.dat.data))
```

yields

`norm(b): 0.048749999999999946`

**Comment by wence-** [comment]
FWIW, I don't think your non-mixed case has a zero residual either?

**Comment by pefarrell** [comment]
I'm happy to close the bug.
