### ISSUE TITLE
facet_avg is broken

### ISSUE THREAD

**Issue by tkarna** [firedrakeproject/firedrake#1320]
UFL `facet_avg` operator does not work. A small failing example

```python
from firedrake import *

mesh = UnitSquareMesh(10, 10)
V = FunctionSpace(mesh, 'DG', 1)
V0 = FunctionSpace(mesh, 'DGT', 0)

x, y = SpatialCoordinate(mesh)
f = Function(V, name='f').interpolate(x)
g = Function(V0, name='g')

test = TestFunction(V0)
tri = TrialFunction(V0)
a = test*tri*ds
l = facet_avg(f)*test*ds
solve(a == l, g, solver_parameters={"ksp_type": "preonly", "pc_type": "jacobi"})
```

Currently dies with
```
Traceback (most recent call last):
  File "test_facet_avg.py", line 15, in <module>
    solve(a == l, g, solver_parameters={"ksp_type": "preonly", "pc_type": "jacobi"})
  File "/home/tuomas/sources/firedrake/src/firedrake/firedrake/solving.py", line 124, in solve
    _solve_varproblem(*args, **kwargs)
  File "/home/tuomas/sources/firedrake/src/firedrake/firedrake/solving.py", line 153, in _solve_varproblem
    appctx=appctx)
  File "/home/tuomas/sources/firedrake/src/firedrake/firedrake/variational_solver.py", line 309, in __init__
    super(LinearVariationalSolver, self).__init__(*args, **kwargs)
  File "/home/tuomas/sources/firedrake/src/firedrake/firedrake/variational_solver.py", line 158, in __init__
    options_prefix=self.options_prefix)
  File "/home/tuomas/sources/firedrake/src/firedrake/firedrake/solving_utils.py", line 119, in __init__
    form_compiler_parameters=self.fcp)
  File "/home/tuomas/sources/firedrake/src/firedrake/firedrake/assemble.py", line 145, in create_assembly_callable
    collect_loops=True)
  File "<decorator-gen-715>", line 2, in _assemble
  File "/home/tuomas/sources/firedrake/src/firedrake/firedrake/utils.py", line 61, in wrapper
    return f(*args, **kwargs)
  File "/home/tuomas/sources/firedrake/src/firedrake/firedrake/assemble.py", line 214, in _assemble
    kernels = tsfc_interface.compile_form(f, "form", parameters=form_compiler_parameters, inverse=inverse)
  File "/home/tuomas/sources/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 203, in compile_form
    number_map).kernels
  File "/home/tuomas/sources/firedrake/src/PyOP2/pyop2/caching.py", line 199, in __new__
    obj = make_obj()
  File "/home/tuomas/sources/firedrake/src/PyOP2/pyop2/caching.py", line 189, in make_obj
    obj.__init__(*args, **kwargs)
  File "/home/tuomas/sources/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 113, in __init__
    tree = tsfc_compile_form(form, prefix=name, parameters=parameters)
  File "/home/tuomas/sources/firedrake/src/tsfc/tsfc/driver.py", line 53, in compile_form
    kernel = compile_integral(integral_data, fd, prefix, parameters)
  File "/home/tuomas/sources/firedrake/src/tsfc/tsfc/driver.py", line 179, in compile_integral
    **config)
  File "/home/tuomas/sources/firedrake/src/tsfc/tsfc/fem.py", line 643, in compile_ufl
    result = map_expr_dags(context.translator, expressions)
  File "/home/tuomas/sources/firedrake/src/ufl/ufl/corealg/map_dag.py", line 84, in map_expr_dags
    r = handlers[v._ufl_typecode_](v)
  File "/home/tuomas/sources/firedrake/src/tsfc/tsfc/fem.py", line 292, in facet_avg
    config.update(quadrature_degree=degree, interface=self.context,
AttributeError: 'tuple' object has no attribute 'update'
```

**Comment by wence-** [comment]
as in runs, or runs and produces the correct answer?!

**Comment by tkarna** [comment]
In this particular dS case the answer is correct. I'll try to invent a test or two.

**Comment by tkarna** [comment]
Projecting facet_avg on a trace space seems to be broken?
```python
from firedrake import *

mesh = UnitSquareMesh(10, 10, quadrilateral=False)

Vt = FunctionSpace(mesh, 'DGT', 1)
ft = Function(Vt, name='f_trace')
source = Constant(1.0)

test = TestFunction(Vt)
trial = TrialFunction(Vt)
a = test*trial*ds + avg(test)*avg(trial)*dS
l = facet_avg(source)*test*ds + facet_avg(avg(source))*avg(test)*dS
solve(a == l, ft, solver_parameters={"ksp_type": "preonly", "pc_type": "jacobi"})

print(ft.dat.data.max())
```
I get an error
```
...
  File "/home/karna/sources/firedrake/firedrake/src/tsfc/tsfc/fem.py", line 423, in translate_spatialcoordinate
    terminal = ctx.coordinate(terminal.ufl_domain())
  File "/home/karna/sources/firedrake/firedrake/src/tsfc/tsfc/kernel_interface/common.py", line 37, in coordinate
    return self.domain_coordinate[domain]
KeyError: Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), -1)
```

**Comment by wence-** [comment]
Does it help if you say `Constant(1.0, domain=mesh)`? You might also need the `fix-facet-avg-round-two` branch of tsfc.

**Comment by tkarna** [comment]
Thanks. Yes, defining the domain in the constant works. And I do need the new branch.

**Comment by tkarna** [comment]
Here's a less trivial test.
```
from firedrake import *

mesh = UnitSquareMesh(10, 10, quadrilateral=False)

Vt = FunctionSpace(mesh, 'DGT', 1)
ft = Function(Vt, name='f_trace')

x, y = SpatialCoordinate(mesh)
source = 2*x

test = TestFunction(Vt)
trial = TrialFunction(Vt)
a = test*trial*ds + avg(test)*avg(trial)*dS
l = facet_avg(source)*test*ds + avg(facet_avg(source))*avg(test)*dS
solve(a == l, ft)

# reference solution
ft_ref = Function(Vt, name='ref_sol')
Vt0 = FunctionSpace(mesh, 'DGT', 0)
ft_ref_p0 = Function(Vt0, name='ref_sol')
ft_ref_p0.interpolate(source)
l_ref = ft_ref_p0*test*ds + avg(ft_ref_p0)*avg(test)*dS
solve(a == l_ref, ft_ref)

err = max(abs(ft_ref.dat.data - ft.dat.data))
print(err)
```

**Comment by tkarna** [comment]
Works in 3D as well
```
from firedrake import *

mesh2d = UnitSquareMesh(10, 10, quadrilateral=False)
mesh = ExtrudedMesh(mesh2d, 10, 0.1)

Vt = FunctionSpace(mesh, 'DGT', 1)
ft = Function(Vt, name='f_trace')

x, y, z = SpatialCoordinate(mesh)
source = 2*x + z

test = TestFunction(Vt)
trial = TrialFunction(Vt)
a = test*trial*(ds_v + ds_t + ds_b) + avg(test)*avg(trial)*(dS_v + dS_h)
l = facet_avg(source)*test*(ds_v + ds_t + ds_b) + avg(facet_avg(source))*avg(test)*(dS_v + dS_h)
solve(a == l, ft)

# reference solution
ft_ref = Function(Vt, name='ref_sol')
Vt0 = FunctionSpace(mesh, 'DGT', 0)
ft_ref_p0 = Function(Vt0, name='ref_sol')
ft_ref_p0.interpolate(source)
l_ref = ft_ref_p0*test*(ds_v + ds_t + ds_b) + avg(ft_ref_p0)*avg(test)*(dS_v + dS_h)
solve(a == l_ref, ft_ref)

err = max(abs(ft_ref.dat.data - ft.dat.data))
print(err)
```

**Comment by wence-** [comment]
Thanks, fixed in tsfc and tests added.
