### ISSUE TITLE
installation issue on ubuntu 16.04

### ISSUE THREAD

**Issue by erik-stormy** [firedrakeproject/firedrake#1382]
I tried to install firedrake multiple times on lenovo with ubuntu 16.04. This time I typed:

`python3 firedrake-install --minimal-petsc --disable-ssh`

Shortly before end was output on the terminal:

```
_Successfully cloned repository libsupermesh.
Checking out branch master
Successfully checked out branch master
Installing petsc4py/
Installing COFFEE/
Installing ufl/
Installing fiat/
Installing FInAT/
Installing tsfc/
Installing PyOP2/
Traceback (most recent call last):
  File "firedrake-install", line 1176, in <module>
    install(p+"/")
  File "firedrake-install", line 640, in install
    run_pip_install(["-e", package])
  File "firedrake-install", line 600, in run_pip_install
    check_call(pipinstall + pipargs)
  File "firedrake-install", line 438, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=env).decode())
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/honza/te/firedrake/bin/python', '-m', 'pip', 'install', '--no-binary', 'mpi4py', '--no-deps', '-vvv', '-e', 'PyOP2/']' returned non-zero exit status 1


Install log saved in /home/honza/te/firedrake-install.log

In firedrake-install.log I found (I copy what I think is the problem):


In file included from /home/honza/te/firedrake/lib/python3.5/site-packages/petsc/include/petscbag.h:4:0,
                     from /home/honza/te/firedrake/lib/python3.5/site-packages/petsc/include/petsc.h:5,
                     from pyop2/sparsity.c:595:
    /home/honza/te/firedrake/lib/python3.5/site-packages/petsc/include/petscsys.h:134:19: **fatal error: mpi.h: No such file or directory**
    compilation terminated.
    /home/honza/te/firedrake/lib/python3.5/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/honza/te/firedrake/src/PyOP2/pyop2/sparsity.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    error: command 'gcc' failed with exit status 1
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-7yvrn81m'
Command "/home/honza/te/firedrake/bin/python -c "import setuptools, tokenize;__file__='/home/honza/te/firedrake/src/PyOP2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/honza/te/firedrake/src/PyOP2/
Exception information:
Traceback (most recent call last):
  File "/home/honza/te/firedrake/lib/python3.5/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/home/honza/te/firedrake/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "/home/honza/te/firedrake/lib/python3.5/site-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/home/honza/te/firedrake/lib/python3.5/site-packages/pip/_internal/req/req_install.py", line 903, in install
    install_options, global_options, prefix=prefix,
  File "/home/honza/te/firedrake/lib/python3.5/site-packages/pip/_internal/req/req_install.py", line 760, in install_editable
    show_stdout=False,
  File "/home/honza/te/firedrake/lib/python3.5/site-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/home/honza/te/firedrake/bin/python -c "import setuptools, tokenize;__file__='/home/honza/te/firedrake/src/PyOP2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/honza/te/firedrake/src/PyOP2/

2019-03-06 21:05:51,362 INFO   

Install log saved in /home/honza/te/firedrake-install.log


I somehow managed to install firedrake on same system but older laptop. Though some test failed. But on lenovo I do not know what went wrong. Thank you for answer.

**Comment by dham** [comment]
OK well the proximate cause of your problem is failure to find `mpi.h`. This might be related to the fact that your c compiler is being called as `gcc` rather than `mpicc`. Can you post `firedrake-install.log` so we can check if it's an issue in your environment?

**Comment by erik-stormy** [comment]
Here is whole log file. I has CC=gcc. Is it what you mean?

[firedrake-install_error.log](https://github.com/firedrakeproject/firedrake/files/2940518/firedrake-install_error.log)

**Comment by erik-stormy** [comment]
I think CC=mpicc before start of installation is the solution. I get through installation without problems and also tried example of Helmholtz equation. I add working log file.
[firedrake-install_OK.log](https://github.com/firedrakeproject/firedrake/files/2948185/firedrake-install_OK.log)

**Comment by wence-** [comment]
Ah, yes, if you say `CC=gcc` we don't override it for you (assuming you know what you want). Given that this now works, I'll go ahead and close.
