### ISSUE TITLE
The ds measure does not accept surface IDs of type numpy.int32

### ISSUE THREAD

**Issue by ctjacobs** [firedrakeproject/firedrake#139]
I'm retrieving the surface IDs of a mesh, and then looping over and using them in the `ds` measure like so:
```
from firedrake import *

mesh = UnitSquareMesh(10,10)
fs = FunctionSpace(mesh, "CG", 1)

test = TestFunction(fs)
trial = TrialFunction(fs)

boundary_markers = set(mesh.exterior_facets.markers)
print boundary_markers
for marker in boundary_markers:
   print inner(test, trial)*ds(marker)
```
This results in the following error message:
```
christian@elevate ~ $ python test_markers.py 
Info : Increasing process stack size (8192 kB < 16 MB)
set([1, 2, 3, 4])
Invalid domain id 1.
Traceback (most recent call last):
  File "test_markers.py", line 12, in <module>
    print inner(test, trial)*ds(marker)
  File "/usr/local/lib/python2.7/dist-packages/ufl/integral.py", line 358, in __rmul__
    error("Invalid domain id %s." % str(self._domain_description))
  File "/usr/local/lib/python2.7/dist-packages/ufl/log.py", line 154, in error
    raise self._exception_type(self._format_raw(*message))
ufl.log.UFLException: Invalid domain id 1.
```
I'm currently casting from type `numpy.int32` to `int` to get round this problem.

**Comment by dham** [comment]
Fixed in https://bitbucket.org/fenics-project/ufl/pull-requests/57/relaxed-int-conditions-on-subdomain_id
