### ISSUE TITLE
Can't start new thread error in loopy (in previously working code)

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#1422]
Dear firedrake developers,

@rstumin and I are working on a solver for some problems in magnetohydrodynamics. It used to work, but since the loopy merge has been giving trouble.

The code is here:
[hartmann.py.gz](https://github.com/firedrakeproject/firedrake/files/3090604/hartmann.py.gz)
(apologies for the `.gz`, the only way github would accept it). We run it like

`mpiexec -n 64 python hartmann.py --nref 6 --baseN 20 --Re 1 --Rem 1 --solver-type vanka_add --time`

This used to work. It now gives the error

```
Traceback (most recent call last):
  File "hartmann.py", line 806, in <module>
    solver.solve()
  File "/home/rstumin/fdrake1/firedrake/src/firedrake/firedrake/variational_solver.py", line 244, in solve
    self.snes.solve(None, work)
  File "PETSc/SNES.pyx", line 555, in petsc4py.PETSc.SNES.solve
  File "libpetsc4py/libpetsc4py.pyx", line 879, in libpetsc4py.MatMultTranspose_Python
  File "/home/rstumin/fdrake1/firedrake/src/firedrake/firedrake/mg/ufl_utils.py", line 311, in multTranspose
    self.restrict(self.ffn, self.cfn)
  File "/home/rstumin/fdrake1/firedrake/src/firedrake/firedrake/mg/embedded.py", line 314, in restrict
    t.restrict(f, c)
  File "/home/rstumin/fdrake1/firedrake/src/firedrake/firedrake/mg/embedded.py", line 277, in restrict
    firedrake.restrict(dgf, dgc)
  File "/home/rstumin/fdrake1/firedrake/src/firedrake/firedrake/mg/interface.py", line 127, in restrict
    node_locations = utils.physical_node_locations(Vf)
  File "/home/rstumin/fdrake1/firedrake/src/firedrake/firedrake/mg/utils.py", line 143, in physical_node_locations
    locations = firedrake.interpolate(firedrake.SpatialCoordinate(mesh), Vc)
  File "/home/rstumin/fdrake1/firedrake/src/firedrake/firedrake/interpolation.py", line 37, in interpolate
    return Interpolator(expr, V, subset=subset, access=access).interpolate()
  File "/home/rstumin/fdrake1/firedrake/src/firedrake/firedrake/interpolation.py", line 57, in __init__
    self.callable = make_interpolator(expr, V, subset, access)
  File "/home/rstumin/fdrake1/firedrake/src/firedrake/firedrake/interpolation.py", line 90, in make_interpolator
    loops.extend(_interpolator(V, f.dat, expr, subset, access))
  File "/home/rstumin/fdrake1/firedrake/src/firedrake/firedrake/interpolation.py", line 140, in _interpolator
    ast, oriented, needs_cell_sizes, coefficients, _ = compile_ufl_kernel(expr, to_pts, coords, coffee=False)
  File "/home/rstumin/fdrake1/firedrake/src/tsfc/tsfc/driver.py", line 349, in compile_expression_at_points
    return builder.construct_kernel(return_arg, impero_c, parameters["precision"], {point_index: 'p'})
  File "/home/rstumin/fdrake1/firedrake/src/tsfc/tsfc/kernel_interface/firedrake_loopy.py", line 170, in construct_kernel
    loopy_kernel = generate_loopy(impero_c, args, precision, "expression_kernel", index_names, self.scalar_type)
  File "/home/rstumin/fdrake1/firedrake/src/tsfc/tsfc/loopy.py", line 110, in generate
    seq_dependencies=True, silenced_warnings=["summing_if_branches_ops"])
  File "/home/rstumin/fdrake1/firedrake/src/loopy/loopy/kernel/creation.py", line 2355, in make_function
    return make_kernel(*args, **kwargs)
  File "/home/rstumin/fdrake1/firedrake/src/loopy/loopy/kernel/creation.py", line 2105, in make_kernel
    "%s: instantiate" % kwargs.get("name", "(unnamed)"))
  File "/home/rstumin/fdrake1/firedrake/lib/python3.7/site-packages/pytools/__init__.py", line 2161, in __init__
    self.late_start_log_thread.start()
  File "/home/rstumin/Python-3.7.1rc1/Lib/threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/home/rstumin/fdrake1/firedrake/src/firedrake/firedrake/mg/utils.py", line 140, in physical_node_locations
    return cache[key]
KeyError: FiniteElement('Discontinuous Lagrange', triangle, 1)
```

I attach the full log file below.

[vanka_add.nref_6_ncore_64_base_20.Re_1.Rem_1.log.gz](https://github.com/firedrakeproject/firedrake/files/3090606/vanka_add.nref_6_ncore_64_base_20.Re_1.Rem_1.log.gz)

We are doing a weak scaling analysis; the code still works on 16, 4 and 1 cores (with correspondingly fewer refinements, vary `nref`).

**Comment by wence-** [comment]
Tagging in @inducer, whose code this is.

It looks like the ProcessLogger is being used to log progress in a background thread (so that users don't get confused if things take too long). 

Plausibly the OS (in conjunction with MPI being awful) is getting in the way of these forks.

How best to proceed to avoid this?

**Comment by wence-** [comment]
@pefarrell does this monkeypatching after import Firedrake do the trick?

```python
from firedrake import *
from pytools import ProcessLogger

ProcessLogger.__init__ = lambda *args, **kwargs: None
ProcessLogger.done = lambda *args, **kwargs: None
```

**Comment by pefarrell** [comment]
@rstumin reports the same error message, i.e. no change.

**Comment by wence-** [comment]
Huh, I would have thought this should have stubbed out the relevant code. At least a trivial test does for me. I will try with the hartman example separately.

**Comment by inducer** [comment]
I think a not-completely-unreasonable fix here would be to simply catch the inability to start a thread and give up on printing the "here's what's taking a while" message. Threads and a lot of things (GPUs, Infiniband, ...) are a bad combination, so maybe I'll try to be more restrictive when enabling this. stdin being a TTY comes to mind as a bad proxy for detecting noninteractive uses. I'll take a look tomorrow, but I'd also be grateful for further ideas.

**Comment by wence-** [comment]
Anecdotally, stubbing out this thread start fixes hangs I see in the Firedrake test suite "some of the time". We don't get an error message, but I suspect that perhaps the forking is breaking something with the MPI (I end up in deadlocks because different processes in the test suite end up at different points).

**Comment by pefarrell** [comment]
Any further thoughts on this? We will revert to a version before the loopy merge if the timescales involved are long.

**Comment by inducer** [comment]
[This](https://gitlab.tiker.net/inducer/pytools/merge_requests/27) is the best I've been able to come up with. I'd be grateful for any comments.

**Comment by inducer** [comment]
I'll merge it and release a new pytools. Let me know if this *doesn't* address your issue.

**Comment by inducer** [comment]
2019.1.1 is out: https://pypi.org/project/pytools/#history

**Comment by wence-** [comment]
@pefarrell does `pip install -U pytools` in the relevant firedrake venv fix the problem you were observing?

**Comment by pefarrell** [comment]
Yes, I confirm this updated version fixes the problem.

(Apologies for the delay, it takes a while to get the runs through on the Sandia supercomputer.)

**Comment by wence-** [comment]
Thanks all!
