### ISSUE TITLE
VectorFunctionSpace fails in complex

### ISSUE THREAD

**Issue by orpembery** [firedrakeproject/firedrake#1427]
VectorFunctionSpace appears to break in complex.

MFE:
```
from firedrake import *
num_cells = 2
mesh = UnitSquareMesh(num_cells,num_cells)
V_DG = VectorFunctionSpace(mesh,"DG",0) # No issues with FunctionSpace
v = Function(V_DG)
plot(v)
```
gives the output:
```
/home/owen/progs/firedrake-complex/firedrake/src/firedrake/firedrake/function.py:498: ComplexWarning: Casting complex values to real discards the imaginary part
  arg = np.array(arg, dtype=float)
Traceback (most recent call last):
  File "/home/owen/progs/firedrake-complex/firedrake/src/firedrake/firedrake/function.py", line 469, in _c_evaluate
    return cache[tolerance]
KeyError: 1e-10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/owen/progs/firedrake-complex/firedrake/src/PyOP2/pyop2/compilation.py", line 247, in get_so
    return ctypes.CDLL(soname)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/owen/progs/firedrake-complex/firedrake/.cache/pyop2/12a15d1e1e7e4b013126222e8988447a.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/owen/progs/firedrake-complex/firedrake/src/PyOP2/pyop2/compilation.py", line 278, in get_so
    stdout=log)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpicc', '-std=c99', '-fPIC', '-Wall', '-march=native', '-O3', '-ffast-math', '-I/home/owen/progs/firedrake-complex/firedrake/src/firedrake/firedrake', '-I/home/owen/progs/firedrake-complex/firedrake/include', '-I/home/owen/progs/firedrake-complex/firedrake/lib/python3.5/site-packages/petsc/include', '-fno-tree-loop-vectorize', '-o', '/home/owen/progs/firedrake-complex/firedrake/.cache/pyop2/12a15d1e1e7e4b013126222e8988447a_p7099.so.tmp', '/home/owen/progs/firedrake-complex/firedrake/.cache/pyop2/12a15d1e1e7e4b013126222e8988447a_p7099.c', '-shared', '-L/home/owen/progs/firedrake-complex/firedrake/lib', '-lspatialindex_c', '-Wl,-rpath,/home/owen/progs/firedrake-complex/firedrake/lib']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tmp.py", line 11, in <module>
    plot(v)
  File "/home/owen/progs/firedrake-complex/firedrake/src/firedrake/firedrake/plot.py", line 254, in plot
    p = plot(function, num_sample_points, axes=axes, plot3d=plot3d, real=True, **kwargs)
  File "/home/owen/progs/firedrake-complex/firedrake/src/firedrake/firedrake/plot.py", line 334, in plot
    vals = np.asarray(function.at(coords, tolerance=1e-10))
  File "/home/owen/progs/firedrake-complex/firedrake/src/firedrake/firedrake/function.py", line 555, in at
    single_eval(points[i:i+1], p_result)
  File "/home/owen/progs/firedrake-complex/firedrake/src/firedrake/firedrake/function.py", line 533, in single_eval
    err = self._c_evaluate(tolerance=tolerance)(self._ctypes,
  File "/home/owen/progs/firedrake-complex/firedrake/src/firedrake/firedrake/function.py", line 471, in _c_evaluate
    result = make_c_evaluate(self, tolerance=tolerance)
  File "/home/owen/progs/firedrake-complex/firedrake/src/firedrake/firedrake/function.py", line 644, in make_c_evaluate
    comm=function.comm)
  File "/home/owen/progs/firedrake-complex/firedrake/src/PyOP2/pyop2/compilation.py", line 442, in load
    dll = compiler.get_so(src, extension)
  File "/home/owen/progs/firedrake-complex/firedrake/src/PyOP2/pyop2/compilation.py", line 323, in get_so
    os.rename(tmpname, soname)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/owen/progs/firedrake-complex/firedrake/src/PyOP2/pyop2/logger.py", line 90, in progress
    yield
  File "/home/owen/progs/firedrake-complex/firedrake/src/PyOP2/pyop2/compilation.py", line 284, in get_so
    Compile errors in %s""" % (e.cmd, e.returncode, logfile, errfile))
pyop2.exceptions.CompilationError: Command "['mpicc', '-std=c99', '-fPIC', '-Wall', '-march=native', '-O3', '-ffast-math', '-I/home/owen/progs/firedrake-complex/firedrake/src/firedrake/firedrake', '-I/home/owen/progs/firedrake-complex/firedrake/include', '-I/home/owen/progs/firedrake-complex/firedrake/lib/python3.5/site-packages/petsc/include', '-fno-tree-loop-vectorize', '-o', '/home/owen/progs/firedrake-complex/firedrake/.cache/pyop2/12a15d1e1e7e4b013126222e8988447a_p7099.so.tmp', '/home/owen/progs/firedrake-complex/firedrake/.cache/pyop2/12a15d1e1e7e4b013126222e8988447a_p7099.c', '-shared', '-L/home/owen/progs/firedrake-complex/firedrake/lib', '-lspatialindex_c', '-Wl,-rpath,/home/owen/progs/firedrake-complex/firedrake/lib']" return error status 1.
Unable to compile code
Compile log in /home/owen/progs/firedrake-complex/firedrake/.cache/pyop2/12a15d1e1e7e4b013126222e8988447a_p7099.log
Compile errors in /home/owen/progs/firedrake-complex/firedrake/.cache/pyop2/12a15d1e1e7e4b013126222e8988447a_p7099.err
```

**Comment by wence-** [comment]
This is an issue that some parts of the firedrake code (for example here the point evaluation) are not complex safe yet.

**Comment by wence-** [comment]
I think this is fixed in the complex merge candidate.
