### ISSUE TITLE
Compilation stack requiring extremely large amounts of memory (>13 GB)

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#1451]
I am trying to convert a FEniCS code to firedrake so that I can investigate some solvers for the problem. However, when I try to run it in firedrake, generating the code for the Jacobian requires over 13 gigabytes of RAM, and the run fails:

```
13:19:45 I: Started /usr/bin/time -v python compilecrash.py
13:19:48 O:   0 SNES Function norm 9.136002049720e+03 
13:24:29 O: W.dim(): 7986
13:24:29 E: /mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/loopy/loopy/check.py:710: LoopyWarning: in kernel wrap_form00_cell_integral_otherwise: maximum recursion depth exceeded in comparison (add 'recursion_error_reached_in_check' to silenced_warnings kernel attribute to disable)
13:24:29 E:   warn_with_kernel(kernel, "recursion_error_reached_in_check", str(e))
13:24:29 E: Traceback (most recent call last):
13:24:29 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/PyOP2/pyop2/caching.py", line 197, in __new__
13:24:29 E:     return cls._cache_lookup(key)
13:24:29 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/PyOP2/pyop2/caching.py", line 205, in _cache_lookup
13:24:29 E:     return cls._cache[key]
13:24:29 E: KeyError: ('2ed3379cda98ec19c12e10be4664772c', <class 'pyop2.base.Set'>, False, False, False, <class 'pyop2.base.Arg'>, Access('INC'), (<class 'pyop2.petsc_base.Mat'>, dtype('float64'), (((6, 6),),)), ((<class 'pyop2.base.Map'>, 4, None), (<class 'pyop2.base.Map'>, 4, None)), True, 0, 0, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Dat'>, dtype('float64'), (<class 'pyop2.petsc_base.DataSet'>, (3,), (<class 'pyop2.base.Set'>,))), ((<class 'pyop2.base.Map'>, 4, None),), False, 0, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Global'>, dtype('float64'), (1,)), None, False, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Global'>, dtype('float64'), (1,)), None, False, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Global'>, dtype('float64'), (1,)), None, False, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Global'>, dtype('float64'), (1,)), None, False, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Global'>, dtype('float64'), (1,)), None, False, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Global'>, dtype('float64'), (1,)), None, False, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Global'>, dtype('float64'), (1,)), None, False, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Global'>, dtype('float64'), (1,)), None, False, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Global'>, dtype('float64'), (1,)), None, False, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Global'>, dtype('float64'), (1,)), None, False, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Global'>, dtype('float64'), (1,)), None, False, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Global'>, dtype('float64'), (1,)), None, False, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Global'>, dtype('float64'), (1,)), None, False, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Global'>, dtype('float64'), (1,)), None, False, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Global'>, dtype('float64'), (1,)), None, False, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Global'>, dtype('float64'), (1,)), None, False, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Dat'>, dtype('float64'), (<class 'pyop2.petsc_base.DataSet'>, (6,), (<class 'pyop2.base.Set'>,))), ((<class 'pyop2.base.Map'>, 4, None),), False, 0, <class 'pyop2.base.Arg'>, Access('READ'), (<class 'pyop2.petsc_base.Global'>, dtype('float64'), (6, 6)), None, False, None, <class 'pyop2.sequential.JITModule'>, 4)
13:24:29 E: 
13:24:29 E: During handling of the above exception, another exception occurred:
13:24:29 E: 
13:24:29 E: Traceback (most recent call last):
13:24:29 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/PyOP2/pyop2/compilation.py", line 263, in get_so
13:24:29 E:     return ctypes.CDLL(soname)
13:24:29 E:   File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
13:24:29 E:     self._handle = _dlopen(self._name, mode)
13:24:29 E: OSError: /mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/.cache/pyop2/63/6708e91ceb03ce6cd6890f44913efa.so: cannot open shared object file: No such file or directory
13:24:29 E: 
13:24:29 E: During handling of the above exception, another exception occurred:
13:24:29 E: 
13:24:29 E: Traceback (most recent call last):
13:24:29 E:   File "PETSc/petscsnes.pxi", line 304, in petsc4py.PETSc.SNES_Jacobian
13:24:29 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/firedrake/firedrake/solving_utils.py", line 295, in form_jacobian
13:24:29 E:     ctx._jac.force_evaluation()
13:24:29 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/firedrake/firedrake/matrix.py", line 138, in force_evaluation
13:24:29 E:     self._M._force_evaluation()
13:24:29 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/PyOP2/pyop2/base.py", line 1454, in _force_evaluation
13:24:29 E:     _trace.evaluate(reads, writes)
13:24:30 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/PyOP2/pyop2/base.py", line 192, in evaluate
13:24:30 E:     comp._run()
13:24:30 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/PyOP2/pyop2/base.py", line 3744, in _run
13:24:30 E:     return self.compute()
13:24:30 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/PyOP2/pyop2/base.py", line 3790, in compute
13:24:30 E:     fun = self._jitmodule
13:24:30 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/PyOP2/pyop2/utils.py", line 62, in __get__
13:24:30 E:     obj.__dict__[self.__name__] = result = self.fget(obj)
13:24:30 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/PyOP2/pyop2/sequential.py", line 207, in _jitmodule
13:24:30 E:     pass_layer_arg=self._pass_layer_arg)
13:24:30 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/PyOP2/pyop2/caching.py", line 199, in __new__
13:24:30 E:     obj = make_obj()
13:24:30 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/PyOP2/pyop2/caching.py", line 189, in make_obj
13:24:30 E:     obj.__init__(*args, **kwargs)
13:24:30 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/PyOP2/pyop2/sequential.py", line 101, in __init__
13:24:30 E:     self.compile()
13:24:30 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/PyOP2/pyop2/sequential.py", line 159, in compile
13:24:30 E:     comm=self.comm)
13:24:30 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/PyOP2/pyop2/compilation.py", line 475, in load
13:24:30 E:     dll = compiler.get_so(code, extension)
13:24:30 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/PyOP2/pyop2/compilation.py", line 293, in get_so
13:24:30 E:     stdout=log)
13:24:30 E:   File "/usr/lib/python3.6/subprocess.py", line 286, in check_call
13:24:30 E:     retcode = call(*popenargs, **kwargs)
13:24:30 E:   File "/usr/lib/python3.6/subprocess.py", line 267, in call
13:24:30 E:     with Popen(*popenargs, **kwargs) as p:
13:24:30 E:   File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
13:24:30 E:     restore_signals, start_new_session)
13:24:30 E:   File "/usr/lib/python3.6/subprocess.py", line 1275, in _execute_child
13:24:30 E:     restore_signals, start_new_session, preexec_fn)
13:24:30 E: OSError: [Errno 12] Cannot allocate memory
13:24:30 E: 
13:24:30 E: The above exception was the direct cause of the following exception:
13:24:30 E: 
13:24:30 E: SystemError: <built-in method insert of list object at 0x7f410d3fc888> returned a result with an error set
13:24:30 E: Exception ignored in: 'petsc4py.PETSc.traceback'
13:24:30 E: SystemError: <built-in method insert of list object at 0x7f410d3fc888> returned a result with an error set
13:24:30 E: Traceback (most recent call last):
13:24:30 E:   File "compilecrash.py", line 157, in <module>
13:24:30 E:     solver.solve()
13:24:30 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/firedrake/firedrake/variational_solver.py", line 267, in solve
13:24:30 E:     solving_utils.check_snes_convergence(self.snes)
13:24:30 E:   File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20190428-mpich/src/firedrake/firedrake/solving_utils.py", line 44, in check_snes_convergence
13:24:30 E:     %s""" % (snes.getIterationNumber(), msg))
13:24:30 E: firedrake.exceptions.ConvergenceError: Nonlinear solve failed to converge after 0 nonlinear iterations.
13:24:30 E: Reason:
13:24:30 E:    Inner linear solve failed to converge after 0 iterations with reason: DIVERGED_PCSETUP_FAILED
13:24:32 E: Command exited with non-zero status 1
13:24:32 E: 	Command being timed: "python compilecrash.py"
13:24:32 E: 	User time (seconds): 281.77
13:24:32 E: 	System time (seconds): 4.24
13:24:32 E: 	Percent of CPU this job got: 99%
13:24:32 E: 	Elapsed (wall clock) time (h:mm:ss or m:ss): 4:46.79
13:24:32 E: 	Average shared text size (kbytes): 0
13:24:32 E: 	Average unshared data size (kbytes): 0
13:24:32 E: 	Average stack size (kbytes): 0
13:24:32 E: 	Average total size (kbytes): 0
13:24:32 E: 	Maximum resident set size (kbytes): 13211760
13:24:32 E: 	Average resident set size (kbytes): 0
13:24:32 E: 	Major (requiring I/O) page faults: 375
13:24:32 E: 	Minor (reclaiming a frame) page faults: 3463704
13:24:32 E: 	Voluntary context switches: 93116
13:24:32 E: 	Involuntary context switches: 1403
13:24:32 E: 	Swaps: 0
13:24:32 E: 	File system inputs: 87624
13:24:32 E: 	File system outputs: 8
13:24:32 E: 	Socket messages sent: 0
13:24:32 E: 	Socket messages received: 0
13:24:32 E: 	Signals delivered: 0
13:24:32 E: 	Page size (bytes): 4096
13:24:32 E: 	Exit status: 1
13:24:32 I: Finished with exitcode 1
```

This is presumably connected to the loopy recursion warning. When I connected to the process using gdb, there were nearly 30000 function calls on the stack, with the pattern `_PyEval_EvalFrameDefault / ?? / ??` repeating over and over. (Presumably this is somewhere in loopy?)

I've tried to cut down the code as best I can, removing any extraneous features. The following does one timestep of a very small 10x10x10 problem.

One other note: if I run on a machine with more RAM, it does eventually compile, and it works.

```

#!/usr/bin/env python
import numpy as np
from firedrake import *

np.set_printoptions(precision=2, suppress=False)
dx = dx(degree=2)
ds = ds(degree=2)

A = 80.0
N = 5
base = BoxMesh(N, N, N, A, A, A)
mh = MeshHierarchy(base, 1)
mesh = mh[-1]

#----------DATA---------------
gam = Constant(0.2)
gtw = Constant(0.1)
ell = Constant(0.75)

phi0 = Constant(0.0)
phi1 = Constant(0.01)
phi2 = Constant(0.01)
phi3 = Constant(0.01)

nu0 = Constant(0.01)
nu1 = Constant(0.01)
nu2 = Constant(0.01)
nu3 = Constant(0.01)

eps0 = Constant(2.0*ell/pi*(2.0*gam-gtw))
eps1 = Constant(2.0*ell/pi*gtw)
eps2 = Constant(2.0*ell/pi*gtw)
eps3 = Constant(2.0*ell/pi*gtw)

omega0 = Constant(2.0*(2.0*gam-gtw)/(ell*pi))
omega1 = Constant(2.0*gtw/(ell*pi))
omega2 = Constant(2.0*gtw/(ell*pi))
omega3 = Constant(2.0*gtw/(ell*pi))

rho = Constant(1000.0)

c11 = Constant(166.0)
c12 = Constant(136.0)
c44 = Constant(131.0)

L1=np.array([[c11,c12,c12,0,0,0],
              [c12,c11,c12,0,0,0],
              [c12,c12,c11,0,0,0],
              [0,0,0,2.0*c44,0,0],
              [0,0,0,0,2.0*c44,0],
              [0,0,0,0,0,2.0*c44]])


alpha = Constant(0.9406)
beta = Constant(1.1302)

Logalpha = Constant(np.log(0.9406))
Logbeta = Constant(np.log(1.1302))

# Function space
W = VectorFunctionSpace(mesh, "CG", 1, dim=6)
print("W.dim(): %s" % W.dim())

#Boundary conditions
bc2 = DirichletBC(W.sub(2), Constant(0.0), 5)
bc3 = DirichletBC(W.sub(0), Constant(0.0), [1, 2])
bc4 = DirichletBC(W.sub(1), Constant(0.0), [3, 4])

bcs = [bc2, bc3, bc4]

#Normal and identity tensor
n = FacetNormal(mesh)
I = Identity(mesh.geometric_dimension())

#Time and timestep
dt = Constant(0.001)
t_end = float(2*dt)

# Test function
(u_1, u_2, u_3, et1_, et2_, et3_) = split(TestFunction(W))
u_ = as_vector([u_1, u_2, u_3])

# Current unknown
w = Function(W)
(u1, u2, u3, et1, et2, et3) = split(w)
u = as_vector([u1, u2, u3])
et0 = 1.0 - et1 - et2 - et3

#previous time step
w0 = Function(W)
(u01, u02, u03, et1p, et2p, et3p) = split(w0)
u0 = as_vector([u01, u02, u03])
et0p = 1.0 - et1p - et2p - et3p

# Voigt notation
def voigt(E):
    e=[E[0,0],E[1,1],E[2,2],sqrt(2)*E[0,1],sqrt(2)*E[0,2],sqrt(2)*E[1,2]]
    f=np.array(e)
    return f

Ff = I + grad(u)
invFt=as_matrix([[exp(Logalpha*(-et2 - et3) - Logbeta*et1), 0, 0],
    [0, exp(Logalpha*(-et1 - et3) - Logbeta*et2), 0],
    [0, 0, exp(Logalpha*(-et1 - et2) - Logbeta*et3)]])

Fe = Ff*invFt
CemI = Fe.T*Fe - I
He = 0.5*(CemI - 0.5*CemI*CemI + (CemI*CemI*CemI)/3.0)
e = as_vector(voigt(He))
L = Constant(L1)
FB = 0.5*inner(e,L*e) + et0*phi0 + et1*phi1 + et2*phi2 + et3*phi3
FI = eps0*inner(grad(et0),grad(et0)) + omega0*et0*(1.0-et0) +eps1*inner(grad(et1),grad(et1)) + omega1*et1*(1.0-et1) + eps2*inner(grad(et2),grad(et2)) + omega2*et2*(1.0-et2) + eps3*inner(grad(et3),grad(et3)) + omega3*et3*(1.0-et3)

F = FB + FI
Diss = 0.5*(nu0*(et0-et0p)*(et0-et0p) + nu1*(et1-et1p)*(et1-et1p) + nu2*(et2-et2p)*(et2-et2p) + nu3*(et3-et3p)*(et3-et3p))/dt
Pi = (F + Diss)*dx

pen0 = conditional(lt(et0, 0.0), 0.5*rho*et0*et0, Constant(0.0))
pen1 = conditional(lt(et1, 0.0), 0.5*rho*et1*et1, Constant(0.0))
pen2 = conditional(lt(et2, 0.0), 0.5*rho*et2*et2, Constant(0.0))
pen3 = conditional(lt(et3, 0.0), 0.5*rho*et3*et3, Constant(0.0))

pen = (pen0 + pen1 + pen2 + pen3)*dx

Rc = Constant(20.0)
rhotwo = Constant(1000.0)
x = SpatialCoordinate(mesh)
posz = Constant(20.0)
gap = sqrt((-x[0]-u[0])*(-x[0]-u[0])+(-x[1]-u[1])*(-x[1]-u[1])+(posz-x[2]-u[2])*(posz-x[2]-u[2])) - Rc

penpot = conditional(lt(gap, 0.0), 0.5*rhotwo*gap*gap, Constant(0.0))
contact = penpot*ds(6)

#Derivatives
R = derivative(Pi + pen + contact, w)
J = derivative(R, w)

problem = NonlinearVariationalProblem(R, w, bcs=bcs, J=J)
lu = {"mat_type": "baij",
      "snes_type": "newtonls",
      "snes_monitor": None,
      "snes_max_it": 13,
      "snes_linesearch_type": "basic",
      "ksp_type": "preonly",
      "pc_type": "lu",
      "pc_factor_mat_solver_type": "mumps"}
sp = lu
solver  = NonlinearVariationalSolver(problem, solver_parameters=sp)

# Time-stepping
t = float(dt)

ii = 0
while t < t_end:
    posz.assign(float(Rc + A - 0.5*t))

    solver.solve()
    ii = ii + 1

    # Move to next time step
    w0.assign(w)
    t += float(dt)
    if t > t_end:
      dt.assign(t_end - t +float(dt))
      t = t_end
```

**Comment by wence-** [comment]
@inducer, any ideas? Just trying to generate device code for the kernel for the Jacobian (not even the mesh loop as well) is tremendously expensive. There are only 12 inames (each in separate domains), but nearly 16000 temporaries and instructions.

Pickled kernel file is attached.
[big-kernel.pickle.gz](https://github.com/firedrakeproject/firedrake/files/3276644/big-kernel.pickle.gz)

**Comment by inducer** [comment]
I've reproduced this, however I've hit another snag on the way: I get a segfault due to (it seems) stack exhaustion in `check_variable_access_ordered`, which is a separate issue. (https://gitlab.tiker.net/inducer/loopy/issues/177)

I then made a [widget](https://gitlab.tiker.net/inducer/pytools/merge_requests/29/diffs) to account for the amount of memory the GC knows about starting from various roots, which gives me
```
program mem usage: [MB] 133.553593
codegen_result mem usage: [MB] 129.608624
```
Those numbers (if they were the entire story) would IMO be reasonable. Unfortunately, there seems to be some more memory hanging around that the GC does *not* know as being referred to by those two objects. We'll continue to poke around.

cc @kaushikcfd

**Comment by inducer** [comment]
[tracemalloc](https://docs.python.org/3/library/tracemalloc.html) is probably my next best idea.

**Comment by inducer** [comment]
@kaushikcfd reports trying [pympler](https://pythonhosted.org/Pympler/) with similar results.

Tracemalloc for [this driver](https://gist.github.com/inducer/507f478d28246d6980de3c9d14a16992) also doesn't seem to see what's actually performing these allocations:

```
[ Top 10 differences ]
/home/andreask_work/src/pytools/pytools/__init__.py:257: size=8889 KiB (-17.3 MiB), count=15825 (-31530), average=575 B
/home/andreask_work/src/islpy/islpy/_isl.py:75: size=6689 KiB (+6689 KiB), count=102162 (+102143), average=67 B
/home/andreask_work/src/pymbolic/pymbolic/mapper/__init__.py:435: size=9490 KiB (-5993 KiB), count=155396 (-98146), average=63 B
/home/andreask_work/src/pymbolic/pymbolic/primitives.py:656: size=5122 KiB (+5121 KiB), count=131122 (+131106), average=40 B
/home/andreask_work/src/loopy/loopy/target/c/codegen/expression.py:164: size=3981 KiB (+3981 KiB), count=72784 (+72784), average=56 B
/home/andreask_work/src/islpy/islpy/_isl.py:154: size=3830 KiB (+3829 KiB), count=54469 (+54454), average=72 B
/home/andreask_work/src/pymbolic/pymbolic/primitives.py:537: size=11.0 MiB (+3453 KiB), count=323731 (+99284), average=36 B
/home/andreask_work/src/pymbolic/pymbolic/mapper/__init__.py:370: size=4752 KiB (-3188 KiB), count=86897 (-58299), average=56 B
/home/andreask_work/src/loopy/loopy/symbolic.py:964: size=7670 KiB (-2679 KiB), count=109046 (-38092), average=72 B
/home/andreask_work/src/islpy/islpy/__init__.py:366: size=2607 KiB (+2607 KiB), count=37002 (+37002), average=72 B
```

Maybe isl is leaking?

**Comment by inducer** [comment]
Hilarious observation: When run under Massif (Valgrind's heap debugger), the combined process only allocates ~600MB.

**Comment by inducer** [comment]
So I think I got to the bottom of it, for the most part, and it boils down to a variant of [this issue](https://gitlab.tiker.net/inducer/loopy/issues/90), where the core problem is that the "scheduler" in Loopy is a bit too dumb for its own good. For each statement, it does the following:

* Make a (modified)copy of the current program order ("schedule")
* Make a (modified) copy of the set of statements yet-to-be scheduled
* Make a (modified) copy of the set of statements already scheduled.

A list of 16000 entries takes about 128K on my Python interpreter. On average, these lists are half as long throughout the scheduling process, so 64K. 16,000 * 64K is a GB, give or take. With a factor of two for overhead, that sufficiently explains the memory consumption.

The solution (IMO) is the same I pushed for in the bug I referenced: Rather than schedule each statement individually, we should detect chunks of straight-line code and schedule that as one unit. That was on my radar to do anyway, so my main question here is how urgently this needs to get fixed from your perspective.

Btw, the reason (AFAICT) for the odd results on Massif is that the Python runtime under Massif is apparently better at returning memory to the OS than the OS `malloc` itself.

Also, thanks for the report!

**Comment by wence-** [comment]
Speeding up scheduling (and reducing memory usage) would be good. I don't know what @pefarrell 's timescales are, but anyone else trying some of these hyperelastic models (or similar complex things) will also likely run into these problems.

I also note that (right now at least) we provide seq-dependency on all instructions in the kernel (partly to avoid scheduling taking too long), so to me for these problems, scheduling feels like it ought to be "free": we've already done it!

**Comment by pefarrell** [comment]
Hi. Can I ping this? Is there any hope of identifying the problem in loopy?

**Comment by pefarrell** [comment]
@wence- Is it possible to go back to COFFEE with master firedrake/tsfc, to see if this fixes it?

**Comment by wence-** [comment]
Edit https://github.com/firedrakeproject/firedrake/blob/ba4e18e91bd991b899e5b817cc97fc3e4d234857/firedrake/tsfc_interface.py#L147

To say coffee=True

**Comment by pefarrell** [comment]
OK. With that, the compilation only takes ~1.5GB of RAM. I'll stick with COFFEE until @inducer figures out what's going on. Is there a way that COFFEE could be made accessible to user code without changing the firedrake source?

**Comment by dham** [comment]
I'm not amazingly keen to expose coffee more as it's scheduled to be dropped soon. This is a workaround for a bug, I'm not convinced we should be changing our API for that.

**Comment by pefarrell** [comment]
I would propose that COFFEE not be dropped until this is fixed.

**Comment by pefarrell** [comment]
Do @inducer or @kaushikcfd have any thoughts on whether this is reparable?

**Comment by wence-** [comment]
This problem now runs in a reasonable amount of time. Hopefully more speed improvements will be coming.

**Comment by pefarrell** [comment]
Wonderful, thanks to @inducer and @kaushikcfd for all your hard work!
