### ISSUE TITLE
Unable to solve linear system assembled using MixedElement

### ISSUE THREAD

**Issue by jrmaddison** [firedrakeproject/firedrake#1455]
Illustrated via

```
from firedrake import *

mesh = UnitSquareMesh(10, 10)
space = FunctionSpace(mesh, "Lagrange", 1)
vspace = FunctionSpace(mesh, space.ufl_element() * space.ufl_element())
test, trial = TestFunction(vspace), TrialFunction(vspace)

M = assemble(inner(test, trial) * dx)
solver = LinearSolver(M, solver_parameters={"ksp_type": "preonly",
                                            "pc_type": "lu"})

b = assemble(inner(test, Constant((0, 0))) * dx)

x = Function(vspace, name="x")

solver.solve(x, b)
```

which leads to the error

```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    solver.solve(x, b)
  File "[...]/firedrake/src/firedrake/firedrake/linear_solver.py", line 158, in solve
    self.ksp.solve(rhs, solution)
  File "PETSc/KSP.pyx", line 388, in petsc4py.PETSc.KSP.solve
petsc4py.PETSc.Error: error code 56
[0] KSPSolve() line 725 in /tmp/pip-req-build-2z25_0hh/src/ksp/ksp/interface/itfunc.c
[0] KSPSetUp() line 391 in /tmp/pip-req-build-2z25_0hh/src/ksp/ksp/interface/itfunc.c
[0] PCSetUp() line 932 in /tmp/pip-req-build-2z25_0hh/src/ksp/pc/interface/precon.c
[0] PCSetUp_LU() line 88 in /tmp/pip-req-build-2z25_0hh/src/ksp/pc/impls/factor/lu/lu.c
[0] MatGetOrdering() line 250 in /tmp/pip-req-build-2z25_0hh/src/mat/order/sorder.c
[0] MatGetOrdering_ND() line 17 in /tmp/pip-req-build-2z25_0hh/src/mat/order/spnd.c
[0] No support for this operation for this object type
[0] Cannot get rows for matrix type nest
```

Also appears if the `vspace` definition is replaced with

```
vspace = space * space
```

**Comment by pefarrell** [comment]
Add `mat_type="aij"` to your assembly of `M`.

**Comment by jrmaddison** [comment]
User error
