### ISSUE TITLE
Complex branch not building

### ISSUE THREAD

**Issue by dacreman** [firedrakeproject/firedrake#1496]
Currently the complex branch is not building due to two problems: 

1. Failure when installing loopy dependencies. Fixed in master by https://github.com/firedrakeproject/firedrake/commit/00e289ec39920b97146eb8f0355bfc3b59282213 

1. Failure building libsupermesh. Fixed in master by https://github.com/firedrakeproject/firedrake/commit/9a981d2cc6c70d9b6ea524432e5275963782c83f 

Making equivalent changes to firedrake-install from the complex branch enables the build to complete but committing these changes would surely merge conflicts in future. The two commits cannot be directly applied to firedrake-install as they are dependent on other changes. Is there a way to fix firedrake-install on the complex branch without messing things up in future?

**Comment by dacreman** [comment]
Having built the complex branch it won't import:
```
>>> from firedrake import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../complex/firedrake/src/firedrake/firedrake/__init__.py", line 59, in <module>
    from firedrake.mg.mesh import *
  File ".../complex/firedrake/src/firedrake/firedrake/mg/__init__.py", line 2, in <module>
    from .interface import *         # noqa: F401
  File ".../complex/firedrake/src/firedrake/firedrake/mg/interface.py", line 5, in <module>
    from . import kernels
  File ".../complex/firedrake/src/firedrake/firedrake/mg/kernels.py", line 30, in <module>
    from firedrake.pointquery_utils import dX_norm_square, X_isub_dX, init_X, inside_check, is_affine
  File ".../complex/firedrake/src/firedrake/firedrake/pointquery_utils.py", line 7, in <module>
    from pyop2.sequential import generate_cell_wrapper
ImportError: cannot import name 'generate_cell_wrapper'
>>> 
```

This was also fixed by https://github.com/firedrakeproject/firedrake/commit/00e289ec39920b97146eb8f0355bfc3b59282213

**Comment by sv2518** [comment]
This should be fixed now?
