### ISSUE TITLE
wrong integration on quad/hex mesh with TensorProductQuadratureRule

### ISSUE THREAD

**Issue by JaroslavHron** [firedrakeproject/firedrake#1505]
This example integrates constant on a unit square (quad mesh) with dx and dx(rule=TensorProductQuadratureRule)

```
import firedrake as fd
import FIAT, finat

A = 1.0
NN = 1
mesh = fd.UnitSquareMesh(1, 1, quadrilateral=True)

fiat_rule = FIAT.quadrature.GaussLobattoLegendreQuadratureLineRule(FIAT.ufc_simplex(1), 2)
print(fiat_rule.get_points(), fiat_rule.get_weights())

points1= finat.point_set.PointSet(fiat_rule.get_points())
weights1= fiat_rule.get_weights()

rule1D= finat.quadrature.QuadratureRule(points1, weights1)
rule2D= finat.quadrature.TensorProductQuadratureRule([rule1D, rule1D])

print(rule2D.point_set.points, rule2D.weight_expression)

dx1 = fd.dx(degree=1)
dx2 = fd.dx(rule=rule2D)

V=fd.FunctionSpace(mesh,"CG",1)
u=fd.interpolate(fd.Constant(1.0),V)

int1=fd.assemble( u * dx1 )
int2=fd.assemble( u * dx2 )

print("integral={0}, using tensor product rule={1}".format(int1, int2))
```
however the result of TensorProductQuadratureRule is wrong, the output:
```
[[0.]
 [1.]] [0.5 0.5]
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]] Product(Indexed(Literal(array([0.5, 0.5])), (Index(1),)), Indexed(Literal(array([0.5, 0.5])), (Index(1),)))
UFL:WARNING Applying str() to a metadata value of type TensorProductQuadratureRule, don't know if this is safe.
UFL:WARNING Applying str() to a metadata value of type TensorProductQuadratureRule, don't know if this is safe.
integral=1.0, using tensor product rule=0.5
```
Doing the same for 3D unit cube with hex mesh gives 0.25

**Comment by wence-** [comment]
Is it also wrong in 1D?

**Comment by JaroslavHron** [comment]
No.
- on `UnitIntervalMesh` both `dx` integrals give correct answer

- on `UnitSquareMesh` the `ds` over the boundary gives correct result
  (i.e. `ds1 = fd.ds(degree=1); ds2 = fd.ds(rule=rule1D)`)

However in 3D, 
```
rule1D= finat.quadrature.QuadratureRule(points1, weights1)
rule2D= finat.quadrature.TensorProductQuadratureRule([rule1D, rule1D])
rule3D= finat.quadrature.TensorProductQuadratureRule([rule2D, rule1D])

dx=fd.dx(rule=rule3D)
```
the answer of `fd.assemble( u * dx)` is 0.25,
while the test with `ds=fd.ds_t(rule=rule2D)` ends with following error message
```
[[0.]
 [1.]] [0.5 0.5]
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]] Product(Product(Indexed(Literal(array([0.5, 0.5])), (Index(15),)), Indexed(Literal(array([0.5, 0.5])), (Index(15),))), Indexed(Literal(array([0.5, 0.5])), (Index(15),)))
UFL:WARNING Applying str() to a metadata value of type TensorProductQuadratureRule, don't know if this is safe.
UFL:WARNING Applying str() to a metadata value of type TensorProductQuadratureRule, don't know if this is safe.
Traceback (most recent call last):
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/pyop2/master/givym53suvpy5gl4/lib/python3.6/site-packages/pyop2/caching.py", line 197, in __new__
    return cls._cache_lookup(key)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/firedrake/master/2n4p5kfe2odwi33z/lib/python3.6/site-packages/firedrake/tsfc_interface.py", line 59, in _cache_lookup
    return cls._cache.get(key) or cls._read_from_disk(key, comm)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/firedrake/master/2n4p5kfe2odwi33z/lib/python3.6/site-packages/firedrake/tsfc_interface.py", line 80, in _read_from_disk
    raise KeyError("Object with key %s not found" % key)
KeyError: 'Object with key 2d6be543f44c623ea66373c2565bfc1b not found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_quadrature.py", line 35, in <module>
    int2=fd.assemble( u * ds2 )
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/firedrake/master/2n4p5kfe2odwi33z/lib/python3.6/site-packages/firedrake/assemble.py", line 105, in assemble
    loops = tuple(loops)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/firedrake/master/2n4p5kfe2odwi33z/lib/python3.6/site-packages/firedrake/assemble.py", line 228, in _assemble
    kernels = tsfc_interface.compile_form(f, "form", parameters=form_compiler_parameters, inverse=inverse)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/firedrake/master/2n4p5kfe2odwi33z/lib/python3.6/site-packages/firedrake/tsfc_interface.py", line 218, in compile_form
    number_map, interface, coffee).kernels
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/pyop2/master/givym53suvpy5gl4/lib/python3.6/site-packages/pyop2/caching.py", line 199, in __new__
    obj = make_obj()
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/pyop2/master/givym53suvpy5gl4/lib/python3.6/site-packages/pyop2/caching.py", line 189, in make_obj
    obj.__init__(*args, **kwargs)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/firedrake/master/2n4p5kfe2odwi33z/lib/python3.6/site-packages/firedrake/tsfc_interface.py", line 127, in __init__
    tree = tsfc_compile_form(form, prefix=name, parameters=parameters, interface=interface, coffee=coffee)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/driver.py", line 63, in compile_form
    kernel = compile_integral(integral_data, fd, prefix, parameters, interface=interface, coffee=coffee)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/driver.py", line 197, in compile_integral
    **config)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/fem.py", line 645, in compile_ufl
    result = map_expr_dags(context.translator, expressions)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/ufl/master/uizdu4yfx2olyuay/lib/python3.6/site-packages/ufl/corealg/map_dag.py", line 84, in map_expr_dags
    r = handlers[v._ufl_typecode_](v)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/ufl_utils.py", line 144, in _modified_terminal
    return self.modified_terminal(o)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/fem.py", line 303, in modified_terminal
    return translate(mt.terminal, mt, self.context)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/python/3.6.5/zyqt6nqtkvpdnmtc/lib/python3.6/functools.py", line 803, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/fem.py", line 430, in translate_spatialcoordinate
    return ctx.translator(expr)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/ufl/master/uizdu4yfx2olyuay/lib/python3.6/site-packages/ufl/corealg/multifunction.py", line 100, in __call__
    return self._handlers[o._ufl_typecode_](o, *args)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/ufl_utils.py", line 144, in _modified_terminal
    return self.modified_terminal(o)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/fem.py", line 303, in modified_terminal
    return translate(mt.terminal, mt, self.context)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/python/3.6.5/zyqt6nqtkvpdnmtc/lib/python3.6/functools.py", line 803, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/fem.py", line 581, in translate_coefficient
    finat_dict = ctx.basis_evaluation(element, mt, entity_id)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/fem.py", line 228, in basis_evaluation
    coordinate_mapping=CoordinateMapping(mt, self))
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/finat/master/wxosvdf2xluiseeo/lib/python3.6/site-packages/finat/tensorfiniteelement.py", line 91, in basis_evaluation
    return self._tensorise(scalar_evaluation(order, ps, entity, coordinate_mapping=coordinate_mapping))
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/finat/master/wxosvdf2xluiseeo/lib/python3.6/site-packages/finat/tensor_product.py", line 128, in basis_evaluation
    ps_factors = factor_point_set(self.cell, entity_dim, ps)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/finat/master/wxosvdf2xluiseeo/lib/python3.6/site-packages/finat/tensor_product.py", line 210, in factor_point_set
    for ps, dim in zip(point_set.factors, point_dims))
AssertionError
```

**Comment by wence-** [comment]
Aha, I see your issue, for slightly detailed reasons, each of the 1D rules needs to be a separate object (so that the indices used to contract over change).

If you do this:

```python
def make_1d():
    fiat_rule = FIAT.quadrature.GaussLobattoLegendreQuadratureLineRule(FIAT.ufc_simplex(1), 2)
    points1= finat.point_set.PointSet(fiat_rule.get_points())
    weights1= fiat_rule.get_weights()

    rule1D= finat.quadrature.QuadratureRule(points1, weights1)
    return rule1D

rule2D= finat.quadrature.TensorProductQuadratureRule([make_1d(), make_1d()])
```
then it's all nice.

**Comment by JaroslavHron** [comment]
I see - yes that works, thanks.

**Comment by JaroslavHron** [comment]
1) `rule2D= finat.quadrature.TensorProductQuadratureRule([make_1d(), make_1d()])` works fine
2) `rule3D= finat.quadrature.TensorProductQuadratureRule([make_1d(), make_1d(), make_1d()])` fails with simmilar error message like above
3) `rule3D= finat.quadrature.TensorProductQuadratureRule([rule2D, rule1D()])` on extruded mesh works with correct answer in this test

Is 3. the correct way and 2. is supposed to fail?
In 3D for the `ds` integration does it need new object for rule2D if this one is used inside rule3D?
Just to make sure I am not missing some detail.

**Comment by wence-** [comment]
you need to match the number of quadrature tensor product factors to the number of factors in the cell. On an extruded mesh, you have a quad x interval, so I think you want:

`TPQR([rule2D, rule1D])`

where
`rule2D = TPQR([rule1D, rule1D])`

For `ds` you need to provide a quadrature rule on the surface element (so a 2D one of appropriate type)

**Comment by JaroslavHron** [comment]
Thanks.

**Comment by pefarrell** [comment]
Can I suggest that an assertion be added in the `TensorProductQuadratureRule` constructor to catch similar issues in the future? This is rather subtle.

**Comment by rckirby** [comment]
Would it be possible for the constructor to search for duplicates and replace, or is an assertion with a message how to fix the problem better?
