### ISSUE TITLE
problem with face integration on extruded hex mesh with TensorProductQuadratureRule

### ISSUE THREAD

**Issue by JaroslavHron** [firedrakeproject/firedrake#1506]
When trying to use own `TensorProductQuadratureRule` for the face integrals on extruded hex mesh, the `ds_v` integrals work but the top/bottom `ds_t`, `ds_b` fail

MWE
```
import firedrake as fd
import FIAT, finat

mesh = fd.UnitSquareMesh(1, 1, quadrilateral=True)
mesh = fd.ExtrudedMesh(mesh, 1)

def rule1D():
    points = finat.point_set.PointSet([[0.0], [1.0]])
    weights = [0.5, 0.5]
    return(finat.quadrature.QuadratureRule(points, weights))

rule2D= finat.quadrature.TensorProductQuadratureRule([rule1D(), rule1D()])
rule3D= finat.quadrature.TensorProductQuadratureRule([rule2D, rule1D()])

V=fd.FunctionSpace(mesh,"CG",1)
u=fd.interpolate(fd.Constant(1.0),V)

ds = fd.ds_t(degree=1)
I=fd.assemble( u*ds )
print("integral={0}".format(I))

ds = fd.ds_t(rule=rule2D)
I=fd.assemble( u*ds )
print("using tensor product rule={}".format(I))
```

the resulting output with the error message:
```
integral=1.0
UFL:WARNING Applying str() to a metadata value of type TensorProductQuadratureRule, don't know if this is safe.
UFL:WARNING Applying str() to a metadata value of type TensorProductQuadratureRule, don't know if this is safe.
Traceback (most recent call last):
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/pyop2/master/givym53suvpy5gl4/lib/python3.6/site-packages/pyop2/caching.py", line 197, in __new__
    return cls._cache_lookup(key)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/firedrake/master/2n4p5kfe2odwi33z/lib/python3.6/site-packages/firedrake/tsfc_interface.py", line 59, in _cache_lookup
    return cls._cache.get(key) or cls._read_from_disk(key, comm)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/firedrake/master/2n4p5kfe2odwi33z/lib/python3.6/site-packages/firedrake/tsfc_interface.py", line 80, in _read_from_disk
    raise KeyError("Object with key %s not found" % key)
KeyError: 'Object with key 8aad001053ba89a2d5f0339e6009e203 not found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_quadrature.py", line 23, in <module>
    I=fd.assemble( u*ds )
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/firedrake/master/2n4p5kfe2odwi33z/lib/python3.6/site-packages/firedrake/assemble.py", line 105, in assemble
    loops = tuple(loops)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/firedrake/master/2n4p5kfe2odwi33z/lib/python3.6/site-packages/firedrake/assemble.py", line 228, in _assemble
    kernels = tsfc_interface.compile_form(f, "form", parameters=form_compiler_parameters, inverse=inverse)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/firedrake/master/2n4p5kfe2odwi33z/lib/python3.6/site-packages/firedrake/tsfc_interface.py", line 218, in compile_form
    number_map, interface, coffee).kernels
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/pyop2/master/givym53suvpy5gl4/lib/python3.6/site-packages/pyop2/caching.py", line 199, in __new__
    obj = make_obj()
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/pyop2/master/givym53suvpy5gl4/lib/python3.6/site-packages/pyop2/caching.py", line 189, in make_obj
    obj.__init__(*args, **kwargs)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/firedrake/master/2n4p5kfe2odwi33z/lib/python3.6/site-packages/firedrake/tsfc_interface.py", line 127, in __init__
    tree = tsfc_compile_form(form, prefix=name, parameters=parameters, interface=interface, coffee=coffee)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/driver.py", line 63, in compile_form
    kernel = compile_integral(integral_data, fd, prefix, parameters, interface=interface, coffee=coffee)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/driver.py", line 197, in compile_integral
    **config)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/fem.py", line 645, in compile_ufl
    result = map_expr_dags(context.translator, expressions)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/ufl/master/uizdu4yfx2olyuay/lib/python3.6/site-packages/ufl/corealg/map_dag.py", line 84, in map_expr_dags
    r = handlers[v._ufl_typecode_](v)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/ufl_utils.py", line 144, in _modified_terminal
    return self.modified_terminal(o)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/fem.py", line 303, in modified_terminal
    return translate(mt.terminal, mt, self.context)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/python/3.6.5/zyqt6nqtkvpdnmtc/lib/python3.6/functools.py", line 803, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/fem.py", line 430, in translate_spatialcoordinate
    return ctx.translator(expr)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/ufl/master/uizdu4yfx2olyuay/lib/python3.6/site-packages/ufl/corealg/multifunction.py", line 100, in __call__
    return self._handlers[o._ufl_typecode_](o, *args)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/ufl_utils.py", line 144, in _modified_terminal
    return self.modified_terminal(o)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/fem.py", line 303, in modified_terminal
    return translate(mt.terminal, mt, self.context)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/python/3.6.5/zyqt6nqtkvpdnmtc/lib/python3.6/functools.py", line 803, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/fem.py", line 581, in translate_coefficient
    finat_dict = ctx.basis_evaluation(element, mt, entity_id)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/tsfc/master/twsgewcy6t65qwdg/lib/python3.6/site-packages/tsfc/fem.py", line 228, in basis_evaluation
    coordinate_mapping=CoordinateMapping(mt, self))
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/finat/master/wxosvdf2xluiseeo/lib/python3.6/site-packages/finat/tensorfiniteelement.py", line 91, in basis_evaluation
    return self._tensorise(scalar_evaluation(order, ps, entity, coordinate_mapping=coordinate_mapping))
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/finat/master/wxosvdf2xluiseeo/lib/python3.6/site-packages/finat/tensor_product.py", line 128, in basis_evaluation
    ps_factors = factor_point_set(self.cell, entity_dim, ps)
  File "/usr/local/pkg/Installs/linux-ubuntu16.04-x86_64-gcc8.3.0/finat/master/wxosvdf2xluiseeo/lib/python3.6/site-packages/finat/tensor_product.py", line 210, in factor_point_set
    for ps, dim in zip(point_set.factors, point_dims))
AssertionError
```

**Comment by JaroslavHron** [comment]
Thanks, that works.

We are solving some phase transition problem with penalty terms.
The nodal quadrature with CG elements makes the penalty work better since the corresponding mass matrix is then diagonal (we could use some mass lumping, but this way seems easier to apply)
