### ISSUE TITLE
Fieldsplit when using geometric multigrid with a python PC, error in Newton step other than the first

### ISSUE THREAD

**Issue by tlroy** [firedrakeproject/firedrake#1527]
This issue arises when using a `fieldsplit` preconditioner where the sub solver is a custom preconditioner using `PCBase` and the solver within is geometric multigrid (`mg`). The error does not happen in the first Newton step. Here is a simple example of just two Poisson problems (linear but we solve it with Newton):
```
from firedrake import *

N = 32
nref = 1
base = UnitSquareMesh(N, N, quadrilateral=True)
mh = MeshHierarchy(base, nref)
mesh = mh[-1]

V = FunctionSpace(mesh, "CG", 2)
W = V*V
u = Function(W)
u1,u2 = split(u)
v1,v2 = TestFunctions(W)
x = SpatialCoordinate(mesh)
f = Function(V)
f.interpolate(sin(x[0]*pi)*sin(2*x[1]*pi))
L = f*v1*dx +  f*v2*dx
bcs = [DirichletBC(W.sub(0), Constant(2.0), (1,)), DirichletBC(W.sub(1), Constant(2.0), (1,))]
a = inner(grad(u1),grad(v1))*dx + inner(grad(u2),grad(v2))*dx
F = a - L

fieldsplit_mg= {
       "snes_type": "newtonls",
       "snes_monitor": None,
       "snes_converged_reason": None,
       "ksp_type": "gmres",
       "ksp_monitor": None,
       "ksp_converged_reason": None,
       "pc_type": "fieldsplit",
       "pc_fieldsplit_type": "additive",
       "fieldsplit_0_ksp_type": "preonly",
       "fieldsplit_0_pc_type": "mg",
       "fieldsplit_1_ksp_type": "preonly",
       "fieldsplit_1_pc_type": "mg",
         }
fieldsplit_mg_python= {
       "snes_type": "newtonls",
       "snes_monitor": None,
       "snes_converged_reason": None,
       "ksp_type": "gmres",
       "ksp_monitor": None,
       "ksp_converged_reason": None,
       "pc_type": "fieldsplit",
       "pc_fieldsplit_type": "additive",
       "fieldsplit_0_ksp_type": "preonly",
       "fieldsplit_0_pc_type": "python",
       "fieldsplit_0_pc_python_type": "firedrake.AssembledPC",
       "fieldsplit_0_assembled_pc_type": "mg", 
       "fieldsplit_1_ksp_type": "preonly",
       "fieldsplit_1_pc_type": "mg",
         }

#sp = fieldsplit_mg
sp = fieldsplit_mg_python
solve(F == 0, u, bcs=bcs, solver_parameters=sp)
```
Using `fieldsplit_mg` works fine. Using ` fieldsplit_mg_python`, we get the following error at every GMRES iteration of the second Newton step:
```
Traceback (most recent call last):
  File "PETSc/petscksp.pxi", line 269, in petsc4py.PETSc.KSP_ComputeOps
  File "/scratch/roy/firedrake/src/firedrake/firedrake/solving_utils.py", line 317, in compute_operators
    assert J.handle == ctx._jac.petscmat.handle
AssertionError

The above exception was the direct cause of the following exception:

SystemError: <built-in method insert of list object at 0x7f8ff1e42c88> returned a result with an error set
Exception ignored in: 'petsc4py.PETSc.traceback'
SystemError: <built-in method insert of list object at 0x7f8ff1e42c88> returned a result with an error set
```
This does not seem to affect the convergence here, but in actual nonlinear problems it really ruins it.

**Comment by salazardetroya** [comment]
@tlroy I am having the same problem. Did you figure out a solution?

**Comment by tlroy** [comment]
@salazardetroya Good to see you found a solution. Unfortunately, the fix given by @pefarrell for #1573 does not work in this case.

**Comment by wence-** [comment]
I suspect this is because the the two subspaces are the same, and we end up sharing the DM that is used to communicate information. If I make this problem use `V*Q` rather than `V*V` where `Q != V` then the error disappears.

I think to fix this needs, unfortunately, a bigger redesign of the DM stuff.
