### ISSUE TITLE
Cannot use ExtrudedMeshHierarchy and MG for DG(0) problem

### ISSUE THREAD

**Issue by tlroy** [firedrakeproject/firedrake#1530]
Consider a hierarchy of 3D quadrilateral meshes:
```
from firedrake import *
N = 10
nref = 1
meshbase = UnitSquareMesh(N, N, quadrilateral = True)
mhbase = MeshHierarchy(meshbase, nref)
mh = ExtrudedMeshHierarchy(mhbase, height = 1, base_layer = N)
mesh = mh[-1]
```
There is no issue when solving the following CG(1) Poisson problem with multigrid:
```
V = FunctionSpace(mesh, "CG", 1)
bc = DirichletBC(V, Constant(0), [1, 2])
x,y,z = mesh.coordinates
f = interpolate(10*exp(-((x - 0.5)**2 \
    + (y - 0.5)**2) / 0.02), V)
g = interpolate(sin(5*x), V)

u = TrialFunction(V)
v = TestFunction(V)
a = inner(grad(u), grad(v))*dx
L = f*v*dx + g*v*ds_v

u = Function(V)
solve(a == L, u, bc, solver_parameters = {"pc_type": "mg"})
```
We instead consider a DG(0) discretization (Finite Volume) for the same problem:
```
V = FunctionSpace(mesh, "DG", 0)
bc = DirichletBC(V, Constant(0), [1, 2], method = "geometric")
x,y,z = mesh.coordinates
f = interpolate(10*exp(-((x - 0.5)**2 \
    + (y - 0.5)**2) / 0.02), V)
g = interpolate(sin(5*x), V)
x_func = interpolate(x, V)
y_func = interpolate(y, V)
z_func = interpolate(z, V)
Delta_h = sqrt(jump(x_func)**2 + jump(y_func)**2  + jump(z_func)**2)

u = TrialFunction(V)
v = TestFunction(V)
a = jump(u)/Delta_h*jump(v)*(dS_v + dS_h)
L = f*v*dx + g*v*(ds_v)

u = Function(V)
solve(a == L, u, bc, solver_parameters =  {"pc_type": "mg"})
```
Something breaks during the mg solve. The run fails with the following error:
```
Traceback (most recent call last):
  File "/scratch/roy/bin/firedrake/src/firedrake/firedrake/mg/utils.py", line 107, in coarse_cell_to_fine_node_map
    return cache[key]
KeyError: (((0, 0), (), (), (), (), (), (), (), ()), ((0, 1), (), (), (), ()), ((1, 0), (), (), (), (), (), (), (), ()), ((1, 1), (), (), (), ()), ((2, 0), (), ()), ((2, 1), (0,)), 0, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PETSc/petscdmshell.pxi", line 222, in petsc4py.PETSc.DMSHELL_Coarsen
  File "/scratch/roy/bin/firedrake/src/firedrake/firedrake/dmhooks.py", line 468, in coarsen
    cctx = coarsen(ctx, coarsen)
  File "/usr/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/scratch/roy/bin/firedrake/src/firedrake/firedrake/mg/ufl_utils.py", line 264, in coarsen_snescontext
    problem = self(context._problem, self, coefficient_mapping=coefficient_mapping)
  File "/usr/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/scratch/roy/bin/firedrake/src/firedrake/firedrake/mg/ufl_utils.py", line 215, in coarsen_nlvp
    coefficient_mapping[c] = self(c, self, coefficient_mapping=coefficient_mapping)
  File "/usr/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/scratch/roy/bin/firedrake/src/firedrake/firedrake/mg/ufl_utils.py", line 183, in coarsen_function
    inject(expr, new)
  File "/scratch/roy/bin/firedrake/src/firedrake/firedrake/mg/interface.py", line 218, in inject
    coarse_cell_to_fine_nodes = utils.coarse_cell_to_fine_node_map(Vc, Vf)
  File "/scratch/roy/bin/firedrake/src/firedrake/firedrake/mg/utils.py", line 113, in coarse_cell_to_fine_node_map
    raise ValueError("Coarse and fine meshes must have same number of layers")
ValueError: Coarse and fine meshes must have same number of layers

The above exception was the direct cause of the following exception:

SystemError: <built-in method insert of list object at 0x7f5e5f28f908> returned a result with an error set
Exception ignored in: 'petsc4py.PETSc.traceback'
SystemError: <built-in method insert of list object at 0x7f5e5f28f908> returned a result with an error set
```

**Comment by pefarrell** [comment]
Hi Thomas,

It seems we fixed prolongation & restriction for extruded meshes with variable layers, but not injection.

Take a look at `firedrake/mg/utils.py:113`. It asserts that the number of layers should be the same for both meshes. This should be generalised to the case where the number of layers between them is an integer, as is done above in `utils.py:78` and in `fine_to_coarse_nodes` in `firedrake/cython/mgimpl.pyx`.

**Comment by wence-** [comment]
You can simplify your initial test case to:
```
from firedrake import *
N = 10
nref = 1
meshbase = UnitSquareMesh(N, N, quadrilateral = True)
mhbase = MeshHierarchy(meshbase, nref)
mh = ExtrudedMeshHierarchy(mhbase, height = 1, base_layer = N)
mesh = mh[-1]

V = FunctionSpace(mesh, "DQ", 0)

Vc = FunctionSpace(mh[0], "DG", 0)

f = Function(V)
c = Function(Vc)

inject(f, c)
```

**Comment by tlroy** [comment]
Thanks both. I'll try to fix injection.

**Comment by tlroy** [comment]
Patrick and I had a first attempt at modifying `mg/utils.py` to allow multiple layers. The branch is `extruded-variable`. It looks like we are doing something sensible. However, only the values in the base layer seem to be injected in the coarse function. We can modify @wence-'s test case to observe that it is indeed using only the bottom layer:

```
from firedrake import *
N = 1
nref = 1
meshbase = UnitIntervalMesh(N)
mhbase = MeshHierarchy(meshbase, nref)
mh = ExtrudedMeshHierarchy(mhbase, height = 1, base_layer = N, refinement_ratio = 2)
mesh = mh[-1]

V = FunctionSpace(mesh, "DG", 0)

Vc = FunctionSpace(mh[0], "DG", 0)

x = mesh.coordinates
f = Function(V).interpolate(Constant(5))
c = Function(Vc)
inject(f, c)
print(c.dat.data)

f = Function(V).interpolate(conditional(gt(x[1],0.5),5,0))
c = Function(Vc)
inject(f, c)
print(c.dat.data)

f = Function(V).interpolate(conditional(lt(x[1],0.5),5,0))
c = Function(Vc)
inject(f, c)
print(c.dat.data)
```
The correct value should be `5.`, but this prints out, `2.5`, `0.`, and `2.5`.
