### ISSUE TITLE
Fieldsplit, geometric multigrid and PC python

### ISSUE THREAD

**Issue by salazardetroya** [firedrakeproject/firedrake#1573]
This issue is the same than #1527 . I am opening a new one because I've got an additional problem. I am trying to apply multigrid to solve the Hdiv block in the last example in https://www.firedrakeproject.org/demos/saddle_point_systems.py.html with the new PCPatch functionality. The code is as follows:

```python
from firedrake import *


for n in [2, 4, 6]:
    # Create the base mesh
    distribution_parameters={"overlap_type": (DistributedMeshOverlapType.VERTEX, 1)}
    mesh = UnitSquareMesh(2 ** n, 2 ** n, distribution_parameters=distribution_parameters)

    # Make the hierarchy of meshes
    mh = MeshHierarchy(mesh, 1, distribution_parameters=distribution_parameters)
    mesh = mh[-1]

    Sigma = FunctionSpace(mesh, "RT", 1)
    V = FunctionSpace(mesh, "DG", 0)
    W = Sigma * V

    sigma, u = TrialFunctions(W)
    tau, v = TestFunctions(W)

    f = Function(V)

    import numpy as np
    fvector = f.vector()
    fvector.set_local(np.random.uniform(size=fvector.local_size()))

    a = dot(sigma, tau)*dx + div(tau)*u*dx + div(sigma)*v*dx
    L = -f*v*dx
    w = Function(W)


    def riesz(W):
        sigma, u = TrialFunctions(W)
        tau, v = TestFunctions(W)

        return (inner(sigma, tau) + inner(div(sigma), div(tau)) + u*v)*dx


    parameters = {
        "mat_type" : 'nest',
        "ksp_type": "gmres",
        "ksp_max_it": 200,
        "ksp_converged_reason": None,
        "ksp_rtol": 1e-8,
        "pc_type": "fieldsplit",
        "pc_fieldsplit_type": "additive",

        "fieldsplit_0_" : {
               "ksp_type": "cg",
               "pc_type": "mg",
               "pc_mg_type": "full",
               "mg_levels_ksp_type": "richardson",
               "mg_levels_ksp_norm_type": "unpreconditioned",
               "mg_levels_ksp_monitor_true_residual": None,
               "mg_levels_ksp_richardson_scale": 1.0/3.0,
               "mg_levels_ksp_max_it": 1,
               "mg_levels_ksp_convergence_test": "skip",
               "mg_levels_pc_type": "python",
               "mg_levels_pc_python_type": "firedrake.PatchPC",
               "mg_levels_patch_pc_patch_save_operators": True,
               "mg_levels_patch_pc_patch_partition_of_unity": False,
               "mg_levels_patch_pc_patch_construct_type": "star",
               "mg_levels_patch_pc_patch_construct_dim": 0,
               "mg_levels_patch_pc_patch_sub_mat_type": "seqdense",
               "mg_levels_patch_sub_ksp_type": "preonly",
               "mg_levels_patch_sub_pc_type": "lu",
               "mg_coarse_pc_type": "python",
               "mg_coarse_pc_python_type": "firedrake.AssembledPC",
               "mg_coarse_assembled_pc_type": "lu",
               "mg_coarse_assembled_pc_factor_mat_solver_type": "mumps"
               },
        "fieldsplit_1_ksp_type": "preonly",
        "fieldsplit_1_pc_type": "ilu",
    }

    solve(a==L, w, Jp=riesz(W), solver_parameters=parameters)
    print(w.function_space().mesh().num_cells())
```

When I have just one refinement in MeshHierarchy, I get the same problem than #1527 and the program keeps running. When I have more than one, I obtain this error:

```
SystemError: <built-in method insert of list object at 0x7f504876d808> returned a result with an error set
Exception ignored in: 'petsc4py.PETSc.traceback'
SystemError: <built-in method insert of list object at 0x7f504876d808> returned a result with an error set
Traceback (most recent call last):
  File "PETSc/petscksp.pxi", line 269, in petsc4py.PETSc.KSP_ComputeOps
  File "/home/firedrake/firedrake/src/firedrake/firedrake/solving_utils.py", line 353, in compute_operators
    assert P.handle == ctx._pjac.petscmat.handle
AssertionError

The above exception was the direct cause of the following exception:

SystemError: <built-in method insert of list object at 0x7f504876d808> returned a result with an error set
Exception ignored in: 'petsc4py.PETSc.traceback'
SystemError: <built-in method insert of list object at 0x7f504876d808> returned a result with an error set
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or see https://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
[0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
[0]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run 
[0]PETSC ERROR: to get more information on the crash.
application called MPI_Abort(MPI_COMM_WORLD, 50152059) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=50152059
:
system msg for write_line failure : Bad file descriptor
```

and the program crashes. Any clue? Thanks.

**Comment by pefarrell** [comment]
I think this is because of an API bug in PETSc (at some point in the multigrid <-> DM code it only lets the user pass the Jacobian, not a matrix to build a preconditioner).

Workaround: use `AuxiliaryOperatorPC` as your outermost PC; you'll need to subclass it in your code with the form for the Riesz map. See https://www.firedrakeproject.org/demos/geometric_multigrid.py.html for an example. Then apply your current pc options as `aux_pc_...`.

**Comment by salazardetroya** [comment]
Thanks. That worked really well. This linear solver now converges in 7 iterations regardless of the mesh size:

```python
from firedrake import *


for n in [2, 4, 6]:
    # Create the base mesh
    distribution_parameters={"overlap_type": (DistributedMeshOverlapType.VERTEX, 1)}
    mesh = UnitSquareMesh(2 ** n, 2 ** n, distribution_parameters=distribution_parameters)

    # Make the hierarchy of meshes
    mh = MeshHierarchy(mesh, 2, distribution_parameters=distribution_parameters)
    mesh = mh[-1]

    Sigma = FunctionSpace(mesh, "RT", 1)
    V = FunctionSpace(mesh, "DG", 0)
    W = Sigma * V

    sigma, u = TrialFunctions(W)
    tau, v = TestFunctions(W)

    f = Function(V)

    import numpy as np
    fvector = f.vector()
    fvector.set_local(np.random.uniform(size=fvector.local_size()))

    a = dot(sigma, tau)*dx + div(tau)*u*dx + div(sigma)*v*dx
    L = -f*v*dx
    w = Function(W)


    class Riez(AuxiliaryOperatorPC):

        def form(self, pc, test, trial):
            sigma, u = split(trial)
            tau, v = split(test)
            bcs = None
            return ((inner(sigma, tau) + inner(div(sigma), div(tau)) + u*v)*dx, bcs)


    parameters = {
        "mat_type" : 'nest',
        "ksp_type": "gmres",
        "ksp_max_it": 200,
        "ksp_converged_reason": None,
        "ksp_rtol": 1e-8,
        "pc_type" : "python",
        "pc_python_type" : "__main__.Riez",
        "aux_pc_type": "fieldsplit",
        "aux_pc_fieldsplit_type": "additive",

        "aux_fieldsplit_0_" : {
               "ksp_type": "cg",
               "ksp_rtol": 1e-3,
               "ksp_converged_reason": None,
               "pc_type": "mg",
               "pc_mg_type": "full",
               "mg_levels_ksp_type": "richardson",
               "mg_levels_ksp_norm_type": "unpreconditioned",
               "mg_levels_ksp_richardson_scale": 1.0/3.0,
               "mg_levels_ksp_max_it": 1,
               "mg_levels_ksp_convergence_test": "skip",
               "mg_levels_pc_type": "python",
               "mg_levels_pc_python_type": "firedrake.PatchPC",
               "mg_levels_patch_pc_patch_save_operators": True,
               "mg_levels_patch_pc_patch_partition_of_unity": False,
               "mg_levels_patch_pc_patch_construct_type": "star",
               "mg_levels_patch_pc_patch_construct_dim": 0,
               "mg_levels_patch_pc_patch_sub_mat_type": "seqdense",
               "mg_levels_patch_sub_ksp_type": "preonly",
               "mg_levels_patch_sub_pc_type": "lu",
               "mg_coarse_pc_type": "python",
               "mg_coarse_pc_python_type": "firedrake.AssembledPC",
               "mg_coarse_assembled_pc_type": "lu",
               "mg_coarse_assembled_pc_factor_mat_solver_type": "mumps"
               },
        "aux_fieldsplit_1_ksp_type": "preonly",
        "aux_fieldsplit_1_pc_type": "ilu",
    }

    solve(a==L, w, solver_parameters=parameters)
    print(w.function_space().mesh().num_cells())


```
