### ISSUE TITLE
firedrake-install returns non-zero exit when installing dependencies

### ISSUE THREAD

**Issue by mikewallis** [firedrakeproject/firedrake#1615]
Trying to install firedrake and getting:

Installing loopy/
/exports/csce/eddie/eng/groups/aegean/firedrake/Traceback (most recent call last):
  File "firedrake-install", line 1372, in <module>
    install("loopy/")
  File "firedrake-install", line 727, in install
    run_pip_install(["-e", package])
  File "firedrake-install", line 684, in run_pip_install
    check_call(pipinstall + pipargs)
  File "firedrake-install", line 526, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/exports/applications/apps/community/roslin/python/3.6.8/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/exports/applications/apps/community/roslin/python/3.6.8/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/exports/csce/eddie/eng/groups/aegean/firedrake/firedrake/bin/python', '-m', 'pip', 'install', '--no-binary', 'mpi4py,randomgen,islpy', '-vvv', '-e', 'loopy/']' returned non-zero exit status 2.

It looks like it's failing on loopy, but it might be pytools instead; from firedrake-install.log:
    writing manifest file 'loo.py.egg-info/SOURCES.txt'
  Source in ./loopy has version 2019.1, which satisfies requirement loo.py==2019.1 from file:///exports/csce/eddie/eng/groups/aegean/firedrake/firedrake/src/loopy
  Removed loo.py==2019.1 from file:///exports/csce/eddie/eng/groups/aegean/firedrake/firedrake/src/loopy from build tracker '/tmp/pip-req-tracker-qyfs2yr5'
1 location(s) to search for versions of pytools:
* https://pypi.org/simple/pytools/
Fetching project page and analyzing links: https://pypi.org/simple/pytools/
Getting page https://pypi.org/simple/pytools/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/pytools/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pytools/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/43/42/310be754fb4c55d835bf6ba6804c0678f0f314b8b059b639a130adb35c7e/pytools-1.tar.gz#sha256=f83841e1e227311235477a569d880bd49771aeac67301348c608cc5b7ecd4bee (from https://pypi.org/simple/pytools/), version: 1
[....lots of pytools versions...]
  Found link https://files.pythonhosted.org/packages/66/c7/88a4f8b6f0f78d0115ec3320861a0cc1f6daa3b67e97c3c2842c33f9c089/pytools-2020.1.tar.gz#sha256=c132d17855584ad61c6e00f3ff11146499755944afc400cce9eae0ecf03d04a6 (from https://pypi.org/simple/pytools/), version: 2020.1
Given no hashes to check 7 links for project 'pytools': discarding no candidates
Using version 2020.1 (newest of versions: 2018.4, 2018.5, 2018.5.1, 2018.5.2, 2019.1, 2019.1.1, 2020.1)
Using cached wheel link: file:///exports/eddie3_homes_local/aangelou/.cache/pip/wheels/60/16/37/8d95f823f16087004624d5e15fc9417d016ca3e3fdb5295190/pytools-2020.1-py2.py3-none-any.whl
Processing /exports/eddie3_homes_local/aangelou/.cache/pip/wheels/60/16/37/8d95f823f16087004624d5e15fc9417d016ca3e3fdb5295190/pytools-2020.1-py2.py3-none-any.whl
Cleaning up...
Removed build tracker: '/tmp/pip-req-tracker-qyfs2yr5'
ERROR: Exception:
Traceback (most recent call last):
  File "/exports/csce/eddie/eng/groups/aegean/firedrake/firedrake/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/exports/csce/eddie/eng/groups/aegean/firedrake/firedrake/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/exports/csce/eddie/eng/groups/aegean/firedrake/firedrake/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/exports/csce/eddie/eng/groups/aegean/firedrake/firedrake/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/exports/csce/eddie/eng/groups/aegean/firedrake/firedrake/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/exports/csce/eddie/eng/groups/aegean/firedrake/firedrake/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    hashes=hashes,
  File "/exports/csce/eddie/eng/groups/aegean/firedrake/firedrake/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 278, in unpack_url
    return unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/exports/csce/eddie/eng/groups/aegean/firedrake/firedrake/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 251, in unpack_file_url
    unpack_file(from_path, location, content_type)
  File "/exports/csce/eddie/eng/groups/aegean/firedrake/firedrake/lib/python3.6/site-packages/pip/_internal/utils/unpacking.py", line 252, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/exports/csce/eddie/eng/groups/aegean/firedrake/firedrake/lib/python3.6/site-packages/pip/_internal/utils/unpacking.py", line 114, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/exports/applications/apps/community/roslin/python/3.6.8/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/exports/applications/apps/community/roslin/python/3.6.8/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

whole log attached.

Any ideas, anybody? 
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4249741/firedrake-install.log)

**Comment by dham** [comment]
Hi Mike,

pytools is a dependency of loopy, so the failure is in the pytools install which is inside the loopy install, which explains why you see what you see on the command line and in the log.

The error appears to indicate that the pytools wheel (a wheel is a python binary package) in your computer's wheel cache is corrupt. I'm not sure how that's happened, and its almost certainly unrelated to Firedrake. I think you can remove the broken wheel from your cache with:
```bash
  rm /exports/eddie3_homes_local/aangelou/.cache/pip/wheels/60/16/37/8d95f823f16087004624d5e15fc9417d016ca3e3fdb5295190/pytools-2020.1-py2.py3-none-any.whl
```

If you want to check that that has worked, you can try installing pytools in a throwaway venv:
```bash
python3 -m venv tmpvenv
source tmpvenv/bin/activate
pip install pytools
```

This is also one of the circumstances where you *might* be able to restart the Firedrake install. Once you have established that you can install pytools in a throwaway venv, you can try:
```bash
source firedrake/bin/activate
firedrake-update
```

This *might* cause the rest of the install to complete without you having to sit through PETSc building again, however it's not a very robust process, so you may have to redo the install.

**Comment by mikewallis** [comment]
Hi David,

Thanks *very* much for this. In the end it wasn't just the pytools wheel that was the problem, it was the entire cache, and removing that solved the issue. Wouldn't have thought to look there without your help, and I really appreciate it.

Best, Mike
