### ISSUE TITLE
Error during installation at petsc

### ISSUE THREAD

**Issue by PE22** [firedrakeproject/firedrake#1619]
Hey, whilst installing firedrake I continuously keep encountering an error when it attempts to build PETSC. This is the error I receive:

Installing petsc/
Downloading Eigen from 'https://github.com/eigenteam/eigen-git-mirror/archive/3.3.3.tar.gz' to 'eigen-3.3.3.tgz'
Checking Eigen tarball integrity
Eigen tarball hash valid
Depending on your platform, PETSc may take an hour or more to build!
Traceback (most recent call last):
  File "firedrake-install", line 1348, in <module>
    install("petsc/")
  File "firedrake-install", line 724, in install
    build_and_install_petsc()
  File "firedrake-install", line 832, in build_and_install_petsc
    check_call(["./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + list(petsc_options))
  File "firedrake-install", line 526, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./configure', 'PETSC_DIR=/Users/peterelrick/firedrake/src/petsc', 'PETSC_ARCH=default', '--download-netcdf', '--download-exodusii', '--with-debugging=0', '--with-shared-libraries=1', '--download-mumps', '--download-metis', '--download-ptscotch', '--with-c2html=0', '--download-hypre', '--with-fortran-bindings=0', '--download-hdf5', '--download-superlu_dist', '--with-cxx-dialect=C++11', '--download-pastix', '--with-zlib', '--download-hwloc', '--download-pnetcdf', '--download-scalapack', '--download-suitesparse', '--download-chaco', '--download-ml', '--download-mpich', '--download-eigen=/Users/peterelrick/firedrake/src/eigen-3.3.3.tgz ']' returned non-zero exit status 1.

**Comment by lmccash** [comment]
I found this same error - is there any guidance. I tried to run this both with and without
--minimal-petsc

**Comment by wence-** [comment]
Can you show firedrake/src/petsc/configure.log ?

**Comment by lmccash** [comment]
Hi Lawrence, This is what I was trying to run with associated error: 

(base) Luthaiss-iMac:~ luthaismccash$ rm -rf firedrake
^[[A(base) Luthaiss-iMac:~ luthaismccash$ /usr/local/Cellar/python/3.7.7/bin/python3 firedrake-install --minimal-petsc
Running firedrake-install --minimal-petsc
Installing command line tools...
Installing required packages via homebrew. You can safely ignore warnings that packages are already installed
Creating firedrake venv in '/Users/luthaismccash/firedrake'.
Configuration saved to /Users/luthaismccash/firedrake/.configuration.json
Cloning firedrake
 
Failed to clone firedrake using ssh, falling back to https.
Successfully cloned repository firedrake.
Checking out branch master
Successfully checked out branch master
Creating firedrake-update script.
Cloning the dependencies of firedrake
Cloning ufl
 
Failed to clone ufl using ssh, falling back to https.
Successfully cloned repository ufl.
Checking out branch master
Successfully checked out branch master
Cloning fiat
 
Failed to clone fiat using ssh, falling back to https.
Successfully cloned repository fiat.
Checking out branch master
Successfully checked out branch master
Cloning FInAT
 
Failed to clone FInAT using ssh, falling back to https.
Successfully cloned repository FInAT.
Checking out branch master
Successfully checked out branch master
Cloning tsfc
 
Failed to clone tsfc using ssh, falling back to https.
Successfully cloned repository tsfc.
Checking out branch master
Successfully checked out branch master
Cloning PyOP2
 
Failed to clone PyOP2 using ssh, falling back to https.
Successfully cloned repository PyOP2.
Checking out branch master
Successfully checked out branch master
Cloning pyadjoint
 
Failed to clone pyadjoint using ssh, falling back to https.
Successfully cloned repository pyadjoint.
Checking out branch master
Successfully checked out branch master
Cloning the dependencies of PyOP2
Cloning petsc
 
Failed to clone petsc using ssh, falling back to https.
Successfully cloned repository petsc.
Checking out branch firedrake
Successfully checked out branch firedrake
Cloning petsc4py
 
Failed to clone petsc4py using ssh, falling back to https.
Successfully cloned repository petsc4py.
Checking out branch firedrake
Successfully checked out branch firedrake
Cloning COFFEE
 
Failed to clone COFFEE using ssh, falling back to https.
Successfully cloned repository COFFEE.
Checking out branch master
Successfully checked out branch master
Cloning loopy
 
Failed to clone loopy using ssh, falling back to https.
Successfully cloned repository loopy.
Checking out branch firedrake
Successfully checked out branch firedrake
Installing petsc/
Downloading Eigen from 'https://github.com/eigenteam/eigen-git-mirror/archive/3.3.3.tar.gz' to 'eigen-3.3.3.tgz'
Checking Eigen tarball integrity
Eigen tarball hash valid
Depending on your platform, PETSc may take an hour or more to build!
Traceback (most recent call last):
  File "firedrake-install", line 1374, in <module>
    install("petsc/")
  File "firedrake-install", line 730, in install
    build_and_install_petsc()
  File "firedrake-install", line 838, in build_and_install_petsc
    check_call(["python3", "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + list(petsc_options))
  File "firedrake-install", line 532, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python3', './configure', 'PETSC_DIR=/Users/luthaismccash/firedrake/src/petsc', 'PETSC_ARCH=default', '--with-shared-libraries=1', '--download-mpich', '--download-hdf5=https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.bz2', '--download-ptscotch', '--with-debugging=0', '--download-hypre', '--download-eigen=/Users/luthaismccash/firedrake/src/eigen-3.3.3.tgz ', '--download-superlu_dist', '--download-scalapack', '--with-c2html=0', '--with-cxx-dialect=C++11', '--download-chaco', '--download-mumps', '--with-fortran-bindings=0']' returned non-zero exit status 1.
 
 
Install log saved in /Users/luthaismccash/firedrake-install.log

**Comment by wence-** [comment]
Ok, can you now please upload the file firedrake/src/petsc/configure.log that will contain information about the error

**Comment by lmccash** [comment]
[configure.log](https://github.com/firedrakeproject/firedrake/files/4603306/configure.log)

Hi Lawrence, I have now attached the log - sorry I misunderstood your earlier email.

**Comment by wence-** [comment]
It looks like your gfortran doesnt work right:

What does `brew doctor` say?

**Comment by lmccash** [comment]
Brew installations seem to be working fine

**Comment by lmccash** [comment]
Hi Lawrence, running brew doctor gives: 

(base) Luthaiss-iMac:~ luthaismccash$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8-config
  /Applications/anaconda3/bin/llvm-config
  /Applications/anaconda3/bin/icu-config
  /Applications/anaconda3/bin/krb5-config
  /Applications/anaconda3/bin/freetype-config
  /Applications/anaconda3/bin/xslt-config
  /Applications/anaconda3/bin/libpng16-config
  /Applications/anaconda3/bin/python3.7-config
  /Applications/anaconda3/bin/libpng-config
  /Applications/anaconda3/bin/xml2-config
  /Applications/anaconda3/bin/python3.7m-config
  /Applications/anaconda3/bin/gsl-config
  /Applications/anaconda3/bin/python3-config
  /Applications/anaconda3/bin/curl-config
  /Applications/anaconda3/bin/ncursesw6-config
  /Applications/anaconda3/bin/pcre-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/lib/docker/cli-plugins

**Comment by lmccash** [comment]
Hi Lawrence, have you any suggestions on how this can be fixed.

**Comment by wence-** [comment]
Let's confirm that gfortran is the problem. Can you create a file `hello.f90`
```f90
program main
write(*,*)'Hello, World!'
end program
```

Then attempt to compile and then run it (where the `$` indicates the prompt [don't type that bit]):

```
$ gfortran -o hello hello.f90
$ ./hello
```

I see:

```
Hello, World!
```

**Comment by lmccash** [comment]
Thanks Lawrence - still having issues. I've emailed you

**Comment by wence-** [comment]
Hi @lmccash, although it's plausibly slower to get things working this way, can we do it on the issue. That way the solution and debugging process is visible to everyone.

**Comment by lmccash** [comment]
Hi Lawrence, no problem, See attached. Forgive me if I've misunderstood what you meant, but this seems to be a no-goer 

![Snip20200512_3](https://user-images.githubusercontent.com/61108368/81661585-3d8bbe00-9434-11ea-94eb-b0579b6ec23c.png)

**Comment by wence-** [comment]
Ah, the three lines starting with `program main` are to be the _contents_ of the file `hello.f90`!

**Comment by lmccash** [comment]
Hi Lawrence, thanks. I have stored first 3 in file, and aimed to execute using the terminal. Output attached thanks. 

![Snip20200512_8](https://user-images.githubusercontent.com/61108368/81663313-7f1d6880-9436-11ea-9f6c-2336065d0f1b.png)

**Comment by wence-** [comment]
The three lines need to be on separate lines.

**Comment by lmccash** [comment]
the are - in the file anyway. see attached 

![Snip20200512_9](https://user-images.githubusercontent.com/61108368/81664940-f99ab800-9437-11ea-9e28-90c469aecffc.png)

**Comment by wence-** [comment]
can you say `cat hello.f90` ?

**Comment by lmccash** [comment]
it doesn't do anything - I mean, it throws up no errors nor does it give any output

**Comment by wence-** [comment]
So that is very surprising to me, because clearly a file `hello.f90` exists (otherwise you wouldn't have been able to generate that gfortran error).

**Comment by lmccash** [comment]
![Snip20200512_10](https://user-images.githubusercontent.com/61108368/81667708-82ffb980-943b-11ea-916c-c4fb1ad0289e.png)

Unless I'm just not understanding what you mean? This is why I suggested a zoom / TeamViewer exercise in email.

**Comment by wence-** [comment]
What we're attempting to do is figure out what is broken with gfortran. To that end, we want to make a tiny example fortran program, compile it, and see what happens.

So, let's say you're in some directory (let us call it FOO, but it does not matter). In that directory, we want to create a file `hello.f90` containing the following three lines:

```fortran
program main
write(*, *)'Hello, World!'
end program
```

Now we'll confirm that the file exists and has the contents we want, we'll do so by concatenating the file to the screen with `cat`.

```bash
$ cat hello.f90
# Should print the following output
program main
write(*, *)'Hello, World!'
end program
```

Now we want to compile the file with `gfortran`
```bash
$ gfortran -o hello hello.f90
```

If this runs _successfully_ there will be _no output_. We'll then run the binary:

```bash
$ ./hello
# This should print the following
Hello, World!
```

Can you show the output of the steps for you?

**Comment by lmccash** [comment]
Hi @wence- this is weird. 

1. Running with cat displays no output?
2. competing with gfortran gives an output but its not right (everything should be on different lines no?) 
3. the binary tells me the file cannot be found. 

Please see attached screenshot and advise? Would something like Zoom help here?  

![Snip20200513_1](https://user-images.githubusercontent.com/61108368/81800457-c83eec80-950a-11ea-89d0-1bd744e2ac7a.png)

**Comment by lmccash** [comment]
@wence- any ideas here?

**Comment by wence-** [comment]
Not many, what does `od -b hello.f90` say? Somehow it looks like the initial file creation went haywire.

**Comment by lmccash** [comment]
Hi Lawrence, I've reattempted this, and obtain the following output: 

![Snip20200518_6](https://user-images.githubusercontent.com/61108368/82234133-e781b380-9928-11ea-8924-1297358f396a.png)

**Comment by wence-** [comment]
OK, so now this is promising, it tells us more information about what we suspected (namely that gfortran does not work correctly). What do `gfortran --version` and `which gfortran` say?

What also does `brew info gcc` say?

**Comment by lmccash** [comment]
@wence- please see attached

![Snip20200518_7](https://user-images.githubusercontent.com/61108368/82234967-06cd1080-992a-11ea-96c7-d89f6fe3b10a.png)

**Comment by wence-** [comment]
OK, so you have a conda-based installation of gfortran getting in the way. Can you remove it? Either by removing all of the conda-based stuff from your `PATH` or uninstalling it.

**Comment by lmccash** [comment]
@wence- I have tried this and now tried to reinstall firedrake. It still fails, but attached is a screenshot of the gfortran, it's version, and gcc. See also error log attached

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4645419/firedrake-install.log)
![Snip20200518_9](https://user-images.githubusercontent.com/61108368/82237705-f9b22080-992d-11ea-87b6-55c7dd25b506.png)

**Comment by lmccash** [comment]
@wence- does this help / give you any further info to help me here? I think that the error is at the same place, but is not the gfortran compiler

**Comment by lmccash** [comment]
@wence- does this help / give you any further info to help me here? I think that the error is at the same place, but is not the gfortran compiler

**Comment by dham** [comment]
I can't see anything above which indicates that you have resolved the issue with your fortran compiler. Does the hello world test at https://github.com/firedrakeproject/firedrake/issues/1619#issuecomment-630278062 now work? Can you show us what you get?

The install log you post above seems to have a lot of references to the Anaconda gfortran in it, so I am not particularly sure that your environment is clear of anaconda-induced confusion.

Assuming the hello world test is now passing, please provide the configure log from the failed PETSc build.

**Comment by lmccash** [comment]
Hello @wence- @dham 

![Snip20200603_17](https://user-images.githubusercontent.com/61108368/83646724-f369a880-a5ab-11ea-9192-cfb9ab83cf74.png)
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4723862/firedrake-install.log)

Please see attached screenshot (where the install breaks) and also attached install-log. All variables relating to gfortran are now the system version, and Hello World works. There are lots of other environment variables that are still linked to Anaconda, but want to know if you can suggest anything short of removing anaconda completely, or if you've another suggestion here?

**Comment by wence-** [comment]
This looks like you're using the macos provided python. This doesn't ship with ssl certificates. Can you `brew install python` and then run firedrake-install with `/usr/local/bin/python3 firedrake-install`

**Comment by lmccash** [comment]
@wence- Thank for that, I've tried and achieve the following: 

![Snip20200604_18](https://user-images.githubusercontent.com/61108368/83737112-7e997b80-a64a-11ea-9954-e8ee3db7c6d9.png)

**Comment by lmccash** [comment]
@dham @wence- see also the install log and the pets config logs attached.

Thanks, 
L

[configure.log](https://github.com/firedrakeproject/firedrake/files/4730336/configure.log)
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4730337/firedrake-install.log)

**Comment by lmccash** [comment]
@dham @wence- can you advise please?

**Comment by wence-** [comment]
Did you check if that url was accessible?
`https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.bz2`

e.g. `wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.bz2`

**Comment by lmccash** [comment]
@wence- @dham Please see attached logs. Also, 

* The URL is definitely accessible - downloading the hdf5 tarball works both via `<curl -O>` and `<wget>`. Also, it can be unpacked via `<tar xjf>` without problem. Nevertheless the same step fails during the petsc build (see attached logs).
* Trying `<brew install hdf5>` does not result in a hdf5 installation that can be located during the petsc build.
* Is it possible to build petsc manually, and then point the the firedrake installation script to the completed petsc build? If so, are there any specific configuration options needed by firedrake?

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4774335/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/4774336/configure.log)

**Comment by lmccash** [comment]
any suggestions @wence-

**Comment by wence-** [comment]
> Is it possible to build petsc manually, and then point the the firedrake installation script to the completed petsc build? If so, are there any specific configuration options needed by firedrake?

Yes. you build and then set PETSC_DIR and PETSC_ARCH and use `firedrake-install --honour-petsc-dir`. You need to get PETSc from https://github.com/firedrakeproject/petsc and running `firedrake-install --show-petsc-configure-options` shows you what install options to use.

**Comment by lmccash** [comment]
@wence-  I'll give that a go and update you

**Comment by sv2518** [comment]
Did this work @lmccash?

**Comment by JanBurzack** [comment]
> Hi Lawrence, This is what I was trying to run with associated error:
> 
> (base) Luthaiss-iMac:~ luthaismccash$ rm -rf firedrake ^[[A(base) Luthaiss-iMac:~ luthaismccash$ /usr/local/Cellar/python/3.7.7/bin/python3 firedrake-install --minimal-petsc Running firedrake-install --minimal-petsc Installing command line tools... Installing required packages via homebrew. You can safely ignore warnings that packages are already installed Creating firedrake venv in '/Users/luthaismccash/firedrake'. Configuration saved to /Users/luthaismccash/firedrake/.configuration.json Cloning firedrake
> 
> Failed to clone firedrake using ssh, falling back to https. Successfully cloned repository firedrake. Checking out branch master Successfully checked out branch master Creating firedrake-update script. Cloning the dependencies of firedrake Cloning ufl
> 
> Failed to clone ufl using ssh, falling back to https. Successfully cloned repository ufl. Checking out branch master Successfully checked out branch master Cloning fiat
> 
> Failed to clone fiat using ssh, falling back to https. Successfully cloned repository fiat. Checking out branch master Successfully checked out branch master Cloning FInAT
> 
> Failed to clone FInAT using ssh, falling back to https. Successfully cloned repository FInAT. Checking out branch master Successfully checked out branch master Cloning tsfc
> 
> Failed to clone tsfc using ssh, falling back to https. Successfully cloned repository tsfc. Checking out branch master Successfully checked out branch master Cloning PyOP2
> 
> Failed to clone PyOP2 using ssh, falling back to https. Successfully cloned repository PyOP2. Checking out branch master Successfully checked out branch master Cloning pyadjoint
> 
> Failed to clone pyadjoint using ssh, falling back to https. Successfully cloned repository pyadjoint. Checking out branch master Successfully checked out branch master Cloning the dependencies of PyOP2 Cloning petsc
> 
> Failed to clone petsc using ssh, falling back to https. Successfully cloned repository petsc. Checking out branch firedrake Successfully checked out branch firedrake Cloning petsc4py
> 
> Failed to clone petsc4py using ssh, falling back to https. Successfully cloned repository petsc4py. Checking out branch firedrake Successfully checked out branch firedrake Cloning COFFEE
> 
> Failed to clone COFFEE using ssh, falling back to https. Successfully cloned repository COFFEE. Checking out branch master Successfully checked out branch master Cloning loopy
> 
> Failed to clone loopy using ssh, falling back to https. Successfully cloned repository loopy. Checking out branch firedrake Successfully checked out branch firedrake Installing petsc/ Downloading Eigen from 'https://github.com/eigenteam/eigen-git-mirror/archive/3.3.3.tar.gz' to 'eigen-3.3.3.tgz' Checking Eigen tarball integrity Eigen tarball hash valid Depending on your platform, PETSc may take an hour or more to build! Traceback (most recent call last): File "firedrake-install", line 1374, in install("petsc/") File "firedrake-install", line 730, in install build_and_install_petsc() File "firedrake-install", line 838, in build_and_install_petsc check_call(["python3", "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + list(petsc_options)) File "firedrake-install", line 532, in check_call log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode()) File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output **kwargs).stdout File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run output=stdout, stderr=stderr) subprocess.CalledProcessError: Command '['python3', './configure', 'PETSC_DIR=/Users/luthaismccash/firedrake/src/petsc', 'PETSC_ARCH=default', '--with-shared-libraries=1', '--download-mpich', '--download-hdf5=https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.bz2', '--download-ptscotch', '--with-debugging=0', '--download-hypre', '--download-eigen=/Users/luthaismccash/firedrake/src/eigen-3.3.3.tgz ', '--download-superlu_dist', '--download-scalapack', '--with-c2html=0', '--with-cxx-dialect=C++11', '--download-chaco', '--download-mumps', '--with-fortran-bindings=0']' returned non-zero exit status 1.
> 
> Install log saved in /Users/luthaismccash/firedrake-install.log

Hello everyone, I am having the same kind of issue with this, could you please tell me how to fix it?
Jan Burzack

**Comment by connorjward** [comment]
Please can you create a new GitHub discussion providing the `firedrake-install` and `firedrake/src/petsc/configure.log` files.

**Comment by JanBurzack** [comment]
Hello Connor,
I have opened the discussion here:
https://github.com/firedrakeproject/firedrake/discussions/4034
Please help! Thanks!
P.S. the files are attached, if you cannot download them from the website.
Jan
