### ISSUE TITLE
OpenCascade on Mac -- update build system

### ISSUE THREAD

**Issue by rckirby** [firedrakeproject/firedrake#1637]
The version of opencascade on homebrew is now sufficiently modern that pythonocc can use it.  Consequently, I was able to use `OpenCascadeMeshHierarchy` on my Mojave Mac by doing the following.

1.) Install opencascade from homebrew
2.) Clone pythonocc-core from GitHub and follow their cmake/make/make install instructions.  I did this within my firedrake virtual environment.  I didn't need any special options/instructions, but I did use make -j 8 to speed things up a bit (is there a way to query a reasonable number and set this in the build system?)
3.) I needed to make sure that gmsh was callable from the command line.  Perhaps having the install script try to invoke gmsh and then either adding /Applications/Gmsh.app/Contents/MacOS/ to the path or creating a symlink to /Applications/Gmsh.app/Contents/MacOS/gmsh in <firedrake-dir>/bin if needed should work.

If this works generally, the build system can be updated so that firedrake-install --opencascade works on Mac as well as Ubuntu.

**Comment by JDBetteridge** [comment]
@rckirby can you update on how you're currently installing opencascade et al.?

**Comment by rckirby** [comment]
Currently, brew install gives the lastest opencascade -- 7.6.3.  `brew info` doesn't seem to show that older versions are available.

That's later than the required version for the main branch of `pythonocc-core`.  I cloned the main branch of that repo.

`cmake` didn't work OOTB on that.  First, one needs to `brew install swig rapidjson` to get some dependencies that our firedrake installer hadn't already done.

Then, I did cmake in my build directory with options:
cmake -DCMAKE_CXX_FLAGS=-I\ /opt/homebrew/include/rapidjson;/opt/homebrew/include ..

and it claimed to pass on the `make/make install`, but `pythonocc-core/tests/run_tests.py` fails with import issues:
```
Traceback (most recent call last):
  File "/Users/robert_kirby/Code/firedrake/src/pythonocc-core/test/run_tests.py", line 22, in <module>
    import core_wrapper_features_unittest
  File "/Users/robert_kirby/Code/firedrake/src/pythonocc-core/test/core_wrapper_features_unittest.py", line 38, in <module>
    from OCC.Core.BRepBndLib import brepbndlib_Add
ImportError: cannot import name 'brepbndlib_Add' from 'OCC.Core.BRepBndLib' (/Users/robert_kirby/Code/firedrake/lib/python3.10/site-packages/OCC/Core/BRepBndLib.py)
```

So either there is `pythoncc-core` issue or I am mis-configuring/mis-building it.  

If we can clear up the `pythonocc-core` issue, then updating `firedrake-install` should be simple (adding `rapidjson` and `swig` to the `brew` dependencies, removing the logic to fail on Mac, and then cloning a different version of `pythonocc-core`.

**Comment by rckirby** [comment]
This looks like it *might* be a swig/name-mangling issue?

**Comment by connorjward** [comment]
Closing as this is very out-of-date.
