### ISSUE TITLE
Installed firedrake-install with --doi <zenodo> but fails when run make alltest

### ISSUE THREAD

**Issue by msarrafj** [firedrakeproject/firedrake#1655]
Hi Firedrake users/developers,

I am able to successfully install _latest_ version of Firedrake and run make alltest successfully. 
Now I need to install a Zenodo-archived release:
`python3 firedrake-install --doi 10.5281/zenodo.2635069`
or 
`python3 firedrake-install --doi 10.5281/zenodo.2564747`
etc,.
installation seems to complete successfully but when I run `make alltest` or my .py code, I get this error.
```
(firedrake) $ python linear_Epsh.py 
Traceback (most recent call last):
  File "linear_Epsh.py", line 1, in <module>
    from firedrake import *
  File "/home/sarraf/App/firedrake/src/firedrake/firedrake/__init__.py", line 8, in <module>
    elif "PETSC_DIR" not in os.environ and config["options"]["honour_petsc_dir"]:
TypeError: 'NoneType' object is not subscriptable
```
I would appreciate your help.

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4471504/firedrake-install.log)
[makeAlltest_output.txt](https://github.com/firedrakeproject/firedrake/files/4471508/makeAlltest_output.txt)

**Comment by wence-** [comment]
Hmm. This is because between then and now we moved the location of the configuration file that `firedrake-install` creates. If you

```
cp /home/sarraf/App/firedrake/.configuration.json /home/sarraf/App/firedrake/src/firedrake/firedrake_configuration/configuration.json
```

I think things might work.

**Comment by wence-** [comment]
Did you manage to get this working?

**Comment by JDBetteridge** [comment]
Closing due to inactivity (see [policy](https://github.com/firedrakeproject/firedrake/wiki/Closing-Installation-Issues) for more info)
