### ISSUE TITLE
How difficult is it to implement tensor products of zany elements?

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#1656]
I'm interested in using Bogner-Fox-Schmit on quads, the tensor product of Hermite elements.
Unfortunately it fails deep inside FInAT with an assertion about basis evaluation in the physically-mapped case. I wanted to ask for @rckirby's opinion about how difficult this is to implement. Is it a maths problem (it is not known how to do it), or a coding problem (it is known how to do it, but no one needed it before)? If the latter, do you have any comments on how it might be implemented, and how difficult it is?

As a useful aside, I attach a script to apply the method of manufactured solutions to a biharmonic-type problem, adapted from https://zenodo.org/record/3381901 . The code converges correctly if `quad=False` on line 14. 

```
from firedrake import *

L2_errors = []

def delta(u):
    return div(grad(u))

def dds(u, *n):
    for s in n:
        u = dot(grad(u), s)
    return u

for N in [8, 16, 32]:
    quad = False # change to True to use tensor product Hermite elements
    if quad:
        base = UnitIntervalMesh(N)
        mesh = ExtrudedMesh(base, N)

        baseele = FiniteElement("Hermite", interval, 3)
        ele = TensorProductElement(baseele, baseele)
    else:
        mesh = UnitSquareMesh(N, N, diagonal="crossed")
        ele = FiniteElement("Argyris", mesh.ufl_cell(), 5)

    V = FunctionSpace(mesh, ele)
    x, y = SpatialCoordinate(mesh)

    uex = Constant(100) * (x*(1-x)*y*(1-y))**2

    f = delta(delta(uex))

    n = FacetNormal(mesh)
    h = Constant(1/N)
    beta1 = Constant(40)
    beta2 = Constant(40)

    nu = Constant(1)

    u = Function(V)
    v = TestFunction(V)

    F = (
          inner(delta(u), delta(v))*dx
        + inner(dds(delta(u), n), v)*ds
        + inner(u, dds(delta(v), n))*ds
        + beta1/h**2 * inner(u, v)*ds
        - inner(delta(u), dds(v, n))*ds
        - inner(dds(u, n), delta(v))*ds
        + beta2/h * inner(dds(u, n), dds(v, n))*ds
        - inner(f, v)*dx
        )

    sp = {"snes_type": "newtonls",
          "snes_linesearch_type": "basic",
          "snes_lag_jacobian": -2,
          "snes_lag_preconditioner": -2,
          "snes_monitor": None,
          "ksp_type": "preonly",
          "snes_max_it": 2,
          "snes_convergence_test": "skip",
          "pc_type": "lu",
          "pc_factor_mat_solver_type": "umfpack",
          "snes_rtol": 1e-16,
          "snes_atol": 1e-25}

    solve(F == 0, u, solver_parameters=sp)
    err = errornorm(uex, u, "L2")
    L2_errors.append(err)

import numpy
print("L2 errors: ", L2_errors)
L2_errors = numpy.array(L2_errors)
convergence = numpy.log2(L2_errors[:-1] / L2_errors[1:])
print("Convergence orders: ", convergence)
```

The code fails if I try to set `quad=True` with
```
python tphermite.py 
Traceback (most recent call last):
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/firedrake/firedrake/functionspacedata.py", line 51, in cached
    return cache[key]
KeyError: ((((0, 0), (0, 1, 4, 5), (2, 3, 6, 7), (8, 9, 12, 13), (10, 11, 14, 15)), ((0, 1), (), ()), ((1, 0), (), ()), ((1, 1), ())), 'cell')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tphermite.py", line 25, in <module>
    V = FunctionSpace(mesh, ele)
  File "</mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/lib/python3.6/site-packages/decorator.py:decorator-gen-37>", line 2, in FunctionSpace
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/PyOP2/pyop2/profiling.py", line 60, in wrapper
    return f(*args, **kwargs)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/firedrake/firedrake/functionspace.py", line 141, in FunctionSpace
    new = impl.FunctionSpace(topology, element, name=name, real_tensorproduct=real_tensorproduct)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/firedrake/firedrake/functionspaceimpl.py", line 279, in __init__
    sdata = get_shared_data(mesh, finat_element, real_tensorproduct=real_tensorproduct)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/firedrake/firedrake/functionspacedata.py", line 561, in get_shared_data
    return FunctionSpaceData(mesh, finat_element, real_tensorproduct=real_tensorproduct)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/firedrake/firedrake/functionspacedata.py", line 417, in __init__
    self.cell_boundary_masks = get_boundary_masks(mesh, (edofs_key, "cell"), finat_element)
  File "</mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/lib/python3.6/site-packages/decorator.py:decorator-gen-33>", line 2, in get_boundary_masks
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/firedrake/firedrake/functionspacedata.py", line 53, in cached
    result = f(mesh, key, *args, **kwargs)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/firedrake/firedrake/functionspacedata.py", line 221, in get_boundary_masks
    esd = finat_element.entity_support_dofs()
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/FInAT/finat/finiteelementbase.py", line 85, in entity_support_dofs
    return self._entity_support_dofs
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/tsfc/gem/utils.py", line 19, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/FInAT/finat/tensor_product.py", line 52, in _entity_support_dofs
    return productise(self.factors, methodcaller("entity_support_dofs"))
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/FInAT/finat/tensor_product.py", line 180, in productise
    for fe, d in zip(factors, dim)]
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/FInAT/finat/tensor_product.py", line 180, in <listcomp>
    for fe, d in zip(factors, dim)]
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/FInAT/finat/finiteelementbase.py", line 85, in entity_support_dofs
    return self._entity_support_dofs
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/tsfc/gem/utils.py", line 19, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/FInAT/finat/finiteelementbase.py", line 65, in _entity_support_dofs
    vals, = self.basis_evaluation(0, quad.point_set, entity=(entity_dim, f)).values()
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/FInAT/finat/physically_mapped.py", line 109, in basis_evaluation
    assert coordinate_mapping is not None
AssertionError
```

**Comment by rckirby** [comment]
At least tensor products and zany elements (requiring coordinate mapping) are not made to inter-operate.  There may be a problem that FInAT doesn't define the tensor product of derivative nodes as well, but I couldn't say for sure.  It is possible (I didn't write this bit) that zero thought was put in because if one is doing zany elements they must be on triangles.  It might be profitable to strike out the assertion and see whether/where the code fails following.

**Comment by rckirby** [comment]
Here is an issue, but we should be able to solve it if there is nothing else:  The "problem" in the reference mapping is in the gradient, which crosses the boundary of the two one-d elements.  So it would be a pain to programmatically figure out what the mapping for the BFS quad ought to be from the DOF information and coordinate mappings of the individual one-d cells.

But there is nothing to stop you from subclassing the TPE to let basis evaluation work as one would image but make the `basis_transformation` abstract/not implemented and force someone to intervene to provide that mapping.

Of course, this supposes that a tensor product of two lines gets enough of the right information to build the Jacobian (say) for the quad.  This has to be the case *somewhere* in Firedrake, I'm just not sure whether it's apparent at the point of the physical mapping interface.

**Comment by pefarrell** [comment]
A remark for anyone attempting to implement this in the future: commenting out a few assertions, the tensor product of Hermite elements works on uniform tensor product grids. However, we couldn't get it to work on directly-constructed quads.
