### ISSUE TITLE
firedrake-update failed when updating the git repository

### ISSUE THREAD

**Issue by erizmr** [firedrakeproject/firedrake#1734]
Hi, I met a problem when execute ```firedrake-update```. It failed when updating the git repository.
Would you mind giving some suggestions? Thanks.
```
Updating the git repository for COFFEE
Updating the git repository for loopy
Updating the git repository for ufl
Updating the git repository for fiat
Updating the git repository for FInAT
Updating the git repository for tsfc
Updating the git repository for PyOP2
Updating the git repository for pyadjoint
Updating the git repository for thetis
Traceback (most recent call last):
  File "../bin/firedrake-update", line 1475, in <module>
    git_update(p, deps.get(p, None))
  File "../bin/firedrake-update", line 666, in git_update
    git_sha = check_output(["git", "rev-parse", "HEAD"])
  File "../bin/firedrake-update", line 542, in check_output
    return subprocess.check_output(args, stderr=subprocess.STDOUT, env=os.environ).decode()
  File "/home/mz618/anaconda3/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/home/mz618/anaconda3/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.
```

**Comment by djanekovic** [comment]
Hi @erizmr, can you post output of `git rev-parse HEAD` from thetis repo?

**Comment by erizmr** [comment]
I found the problem that my local thetis is not installed from the master branch. The problem is fixed after switching to master branch.
Thanks!

**Comment by dham** [comment]
For future reference, you don't need to be on master for `firedrake-update` to work, but your current branch needs to be pushed to some remote somewhere so that `git pull` works. Of course you should always have your work pushed to a remote, so this is a feature, not a bug ;)
