### ISSUE TITLE
Installation failure on mac os Catalina during petsc build

### ISSUE THREAD

**Issue by thehalfspace** [firedrakeproject/firedrake#1755]
Hi,

Apologies for yet another mac installation failure issue. I'm trying to install firedrake on mac os catalina. The petsc build gives error. I'm doing a minimal petsc install on my macbook pro.

Here are the details:
```
Successfully cloned repository loopy.
Checking out branch firedrake
Successfully checked out branch firedrake
Updating submodules.
Successfully updated submodules.
Installing petsc/
Downloading Eigen from 'https://github.com/eigenteam/eigen-git-mirror/archive/3.3.3.tar.gz' to 'eigen-3.3.3.tgz'
Checking Eigen tarball integrity
Eigen tarball hash valid
Depending on your platform, PETSc may take an hour or more to build!
Traceback (most recent call last):
  File "firedrake-install", line 1393, in <module>
    install("petsc/")
  File "firedrake-install", line 732, in install
    build_and_install_petsc()
  File "firedrake-install", line 838, in build_and_install_petsc
    check_call(["python3", "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + list(petsc_options))
  File "firedrake-install", line 532, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python3', './configure', 'PETSC_DIR=/Users/prithvithakur/firedrake_scripts/firedrake/src/petsc', 'PETSC_ARCH=default', '--download-hypre', '--download-superlu_dist', '--download-scalapack', '--download-mumps', '--download-hdf5=https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.bz2', '--with-cxx-dialect=C++11', '--download-eigen=/Users/prithvithakur/firedrake_scripts/firedrake/src/eigen-3.3.3.tgz ', '--download-chaco', '--with-shared-libraries=1', '--with-debugging=0', '--with-fortran-bindings=0', '--download-ptscotch', '--download-mpich', '--with-c2html=0']' returned non-zero exit status 1.


Install log saved in /Users/prithvithakur/firedrake_scripts/firedrake-install.log
```

The log files are attached:

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4825588/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/4825592/configure.log)

Any input on how to resolve this is appreciated. 
Thanks.

**Comment by thehalfspace** [comment]
Additional info that might be relevant (looking at other similar issues):

```
$ gfortran --version
GNU Fortran (Homebrew GCC 9.3.0_1) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
$ which gfortran
/usr/local/bin/gfortran
```

```
$ ls -l /usr/local/lib/gcc/9/libgfortran*
-r--r--r--  1 prithvithakur  staff   3123476 Jun 19 11:47 /usr/local/lib/gcc/9/libgfortran.5.dylib
-r--r--r--  1 prithvithakur  staff  12648392 Jun 19 11:46 /usr/local/lib/gcc/9/libgfortran.a
lrwxr-xr-x  1 prithvithakur  staff        19 Jun 19 11:46 /usr/local/lib/gcc/9/libgfortran.dylib -> libgfortran.5.dylib
-r--r--r--  1 prithvithakur  staff       198 Jun 19 11:46 /usr/local/lib/gcc/9/libgfortran.spec
```

```
$ ls -l /usr/local/lib/gcc/6/libgfortran*
-r--r--r--  1 prithvithakur  admin  1582540 Jun 19 13:26 /usr/local/lib/gcc/6/libgfortran.3.dylib
-r--r--r--  1 prithvithakur  admin  7661656 Jun 19 13:24 /usr/local/lib/gcc/6/libgfortran.a
lrwxr-xr-x  1 prithvithakur  admin       19 Jun 19 13:24 /usr/local/lib/gcc/6/libgfortran.dylib -> libgfortran.3.dylib
-r--r--r--  1 prithvithakur  admin      198 Jun 19 13:24 /usr/local/lib/gcc/6/libgfortran.spec
```

```
$ ~/firedrake_scripts/firedrake/src/petsc/default/bin/mpicc -show
gcc -fstack-protector -fno-stack-check -Qunused-arguments -g -O3 -Wl,-flat_namespace -Wl,-commons,use_dylibs -I/Users/prithvithakur/firedrake_scripts/firedrake/src/petsc/default/include -L/Users/prithvithakur/firedrake_scripts/firedrake/src/petsc/default/lib -lmpi -lpmpi
```

```
$ otool -L /Users/prithvithakur/firedrake_scripts/firedrake/src/petsc/default/lib/libmpich*
/Users/prithvithakur/firedrake_scripts/firedrake/src/petsc/default/lib/libmpich.dylib:
	/Users/prithvithakur/firedrake_scripts/firedrake/src/petsc/default/lib/libmpi.12.dylib (compatibility version 14.0.0, current version 14.8.0)
	/Users/prithvithakur/firedrake_scripts/firedrake/src/petsc/default/lib/libpmpi.12.dylib (compatibility version 14.0.0, current version 14.8.0)
	@rpath/libxml2.2.dylib (compatibility version 12.0.0, current version 12.10.0)
	/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libgfortran.4.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/usr/local/lib/gcc/9/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
/Users/prithvithakur/firedrake_scripts/firedrake/src/petsc/default/lib/libmpichcxx.dylib:
	/Users/prithvithakur/firedrake_scripts/firedrake/src/petsc/default/lib/libmpicxx.12.dylib (compatibility version 14.0.0, current version 14.8.0)
	/Users/prithvithakur/firedrake_scripts/firedrake/src/petsc/default/lib/libmpi.12.dylib (compatibility version 14.0.0, current version 14.8.0)
	/Users/prithvithakur/firedrake_scripts/firedrake/src/petsc/default/lib/libpmpi.12.dylib (compatibility version 14.0.0, current version 14.8.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	@rpath/libxml2.2.dylib (compatibility version 12.0.0, current version 12.10.0)
	/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
/Users/prithvithakur/firedrake_scripts/firedrake/src/petsc/default/lib/libmpichf90.dylib:
	/Users/prithvithakur/firedrake_scripts/firedrake/src/petsc/default/lib/libmpifort.12.dylib (compatibility version 14.0.0, current version 14.8.0)
	/Users/prithvithakur/firedrake_scripts/firedrake/src/petsc/default/lib/libmpi.12.dylib (compatibility version 14.0.0, current version 14.8.0)
	/Users/prithvithakur/firedrake_scripts/firedrake/src/petsc/default/lib/libpmpi.12.dylib (compatibility version 14.0.0, current version 14.8.0)
	@rpath/libxml2.2.dylib (compatibility version 12.0.0, current version 12.10.0)
	/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libgfortran.4.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/usr/local/lib/gcc/9/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by wence-** [comment]
Thanks, my suspicion is that conda is putting a libgfortran.4.dylib somewhere in the link line. Can you expunge the conda parts of your `PATH` and use homebrew python3?

**Comment by thehalfspace** [comment]
Thanks! That worked :)

Running tests now, it takes time but it should be good to go!

For future reference: I did `brew info python` to find out the location of homebrew python. I use that python to install firedrake, something like this: `/usr/local/Cellar/python/3.7/python3 firedrake-install --minimal-petsc`
