### ISSUE TITLE
Installing Firedrake on CentOS 7.7

### ISSUE THREAD

**Issue by rado9012** [firedrakeproject/firedrake#1787]
Hello,

I am having some issues installing firedrake on CentOS 7.7, and would appreciate any help. I followed some of the previous questions people have asked. So used 

curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install

env -u PYTHONPATH python3 firedrake-install --no-package-manager

for the installation. I get the following error

Downloading Eigen from 'https://github.com/eigenteam/eigen-git-mirror/archive/3.3.3.tar.gz' to 'eigen-3.3.3.tgz'
Checking Eigen tarball integrity
Eigen tarball hash valid
Depending on your platform, PETSc may take an hour or more to build!
Traceback (most recent call last):
  File "firedrake-install", line 1395, in <module>
    install("petsc/")
  File "firedrake-install", line 734, in install
    build_and_install_petsc()
  File "firedrake-install", line 840, in build_and_install_petsc
    check_call(["python3", "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + list(petsc_options))
  File "firedrake-install", line 534, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python3', './configure', 'PETSC_DIR=/home/rvuchkov/firedrake/src/petsc', 'PETSC_ARCH=default', '--download-pastix', '--with-cxx-dialect=C++11', '--with-debugging=0', '--download-pnetcdf', '--download-scalapack', '--with-fortran-bindings=0', '--download-netcdf', '--download-hwloc', '--download-ptscotch', '--download-hdf5=https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.bz2', '--with-shared-libraries=1', '--download-hypre', '--download-ml', '--download-superlu_dist', '--download-chaco', '--download-mumps', '--with-zlib', '--with-c2html=0', '--download-eigen=/home/rvuchkov/firedrake/src/eigen-3.3.3.tgz ', '--download-metis', '--download-suitesparse', '--download-mpich']' returned non-zero exit status 1.
Install log saved in /home/rvuchkov/firedrake-install.log

I am attaching the log file as well. Thank you so much for looking into this.
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4950161/firedrake-install.log)

**Comment by dham** [comment]
Well the proximate cause of the error is:
```
In file included from /usr/include/sys/wait.h:30:0,
                 from common.h:130,
                 from common_string.c:57:
/usr/include/signal.h:156:1: error: unknown type name ‘siginfo_t’
 extern void psiginfo (const siginfo_t *__pinfo, const char *__s);
 ^
make[2]: *** [common_string.o] Error 1
```

Which is occurring when PETSc tries to build lib scotch. I googled the error message, which threw up this discussion: https://github.com/geommer/yabar/issues/18 with a possible fix, however I suspect that the root cause of your problem is that you're using a 2015 Gcc. At least your python was built with that compiler so I presume that's the one you're using.

**Comment by fcannini** [comment]
Hi there.
I'm using intel icc 2020.2 and I can confirm that the workaround suggested in geommer/yabar#18 works for scotch, using `PETSC_CONFIGURE_OPTIONS="--CFLAGS='-D_POSIX_C_SOURCE=199309L'"`. However, it barfs later on building islpy:

```
isl/imath/gmp_compat.c: In function ‘impz_export’:
isl/imath/gmp_compat.c:691:3: error: unknown type name ‘ssize_t’
    ssize_t word_offset;
```

Even more puzzling is that if you activate the venv `pip install --no-binary :all: islpy` works just fine.

**Comment by JDBetteridge** [comment]
Closing due to inactivity (see [policy](https://github.com/firedrakeproject/firedrake/wiki/Closing-Installation-Issues) for more info)
