### ISSUE TITLE
Support VertexOnlyMesh in 1D mesh

### ISSUE THREAD

**Issue by ReubenHill** [firedrakeproject/firedrake#1792]
At present creating a VertexOnlyMesh within an interval mesh causes a `NotImplementedError`. If this is removed then, 

> with `test.py` containing
> ```python
> from firedrake import *
> m = UnitIntervalMesh(1)
> vertices = [(0.,), (0.1,), (0.9,), (1.0,)]
> vm = VertexOnlyMesh(m, vertices)
> ```
> I get
> ```
> Traceback (most recent call last):
>   File "test.py", line 4, in <module>
>     vm = VertexOnlyMesh(m, vertices)
>   File "/Users/rwh10/firedrake/src/firedrake/firedrake/mesh.py", line 1733, in VertexOnlyMesh
>     swarm = _pic_swarm_in_plex(mesh.topology._plex, vertexcoords, fields=[("parentcellnum", 1, IntType)])
>   File "/Users/rwh10/firedrake/src/firedrake/firedrake/mesh.py", line 1846, in _pic_swarm_in_plex
>     swarm.setPointCoordinates(coords, redundant=False, mode=PETSc.InsertMode.INSERT_VALUES)
>   File "PETSc/DMSwarm.pyx", line 200, in petsc4py.PETSc.DMSwarm.setPointCoordinates
> petsc4py.PETSc.Error: error code 63
> [0] DMSwarmSetPointCoordinates() line 305 in /Users/rwh10/firedrake/src/petsc/src/dm/impls/swarm/swarmpic.c
> [0] DMLocatePoints() line 6550 in /Users/rwh10/firedrake/src/petsc/src/dm/interface/dm.c
> [0] DMLocatePoints_Plex() line 738 in /Users/rwh10/firedrake/src/petsc/src/dm/impls/plex/plexgeometry.c
> [0] DMPlexLocatePoint_Internal() line 460 in /Users/rwh10/firedrake/src/petsc/src/dm/impls/plex/plexgeometry.c
> [0] Argument out of range
> [0] No point location for cell 0 with type segment
> ```

_Originally posted by @ReubenHill in https://github.com/firedrakeproject/firedrake/pull/1638#discussion_r444823687_

Suggested solution:

> OK, so if you wanted to support this you could implement `DMPlexLocatePoint_Simplex_1D_Internal` and hook it up in `DMPlexLocatePoint_Internal`

_Originally posted by @wence- in https://github.com/firedrakeproject/firedrake/pull/1638#discussion_r444825512_

**Comment by ReubenHill** [comment]
Resolved by #2175
