### ISSUE TITLE
Problem to run a simple 3D elastic beam

### ISSUE THREAD

**Issue by Rlahuerta** [firedrakeproject/firedrake#1824]
Hi

I am trying to run a simple example in Firedrake, and I am getting an error related to the space function definition problem and with 'cell_node_map' function.

Here is the test example:

```python
import firedrake as fd
import ufl as ufl

from mpi4py import MPI
from petsc4py import PETSc

import pandas as pd
import numpy as np

elsize = 0.25

dim_x = 5.
dim_y = 1.
dim_z = 1.

nx = int(dim_x / elsize)
ny = int(dim_y / elsize)
nz = int(dim_z / elsize)

msh = fd.RectangleMesh(nx, ny, dim_x, dim_y, quadrilateral=True, comm=MPI.COMM_WORLD)
mesh = fd.ExtrudedMesh(msh, layers=nz, layer_height=dim_z / nz, extrusion_type='uniform')

dim = mesh.geometric_dimension()

E = 1.0e9
nu = 0.0
mu = E / (2.0 * (1.0 + nu))
lmbda = E * nu / ((1.0 + nu) * (1.0 - 2.0 * nu))

x = fd.SpatialCoordinate(mesh)
ufl_x = mesh.coordinates

dti = 0.001

sd_bc = fd.SubDomainData(fd.And(ufl_x[0] >= 0., ufl_x[0] <= dti))
# sd_bc = fd.op2.Subset(mesh.cell_set, sd_bc.indices)

sd_ld = fd.SubDomainData(fd.And(ufl_x[0] >= dim_x - dti, ufl_x[0] <= dim_x))
# sd_ld = fd.op2.Subset(mesh.cell_set, sd_ld.indices)

def epsilon(v):
    return ufl.sym(ufl.grad(v))

def sigma(v):
    return lmbda * ufl.tr(epsilon(v)) * ufl.Identity(dim) + 2.0 * mu * epsilon(v)

fun_spc = fd.VectorFunctionSpace(mesh, "CG", 1)

u_fun = fd.Function(fun_spc, name='displacement')
u_fun.assign(0.)

u_trl = ufl.TrialFunction(fun_spc)
u_tst = ufl.TestFunction(fun_spc)

tr = ufl.as_vector((0., 0., -100000.))
br = ufl.as_vector((0., 0., -0.0001))

a = ufl.inner(sigma(u_trl), epsilon(u_tst)) * fd.dx
# L = ufl.inner(tr, u_tst) * fd.ds(subdomain_data=sd_ld)
L = ufl.inner(br, u_tst) * fd.dx

noslip = fd.DirichletBC(fun_spc, fd.Constant((0., 0., 0.)), sd_bc)

fd.solve(a == L, u_fun, bcs=[noslip], solver_parameters={"ksp_monitor": None})

outfile = fd.File("output.pvd")
outfile.write(u_fun)
```

**Comment by dham** [comment]
Could you post the error please?

**Comment by dham** [comment]
OK, one problem here is that you are importing ufl. Don't do that. Instead use the ufl names defined inside the Firedrake module. The reason for this is that Firedrake sometimes subclasses or wraps ufl objects to add its own functionality.

**Comment by Rlahuerta** [comment]
Yes, sure!

The first error:

``
Traceback (most recent call last):
  File "frk_hexa_test.py", line 97, in <module>
    fd.solve(a == L, u_fun, bcs=[noslip], solver_parameters={"ksp_monitor": None})
  File "/home/ironman/firedrake/src/firedrake/firedrake/adjoint/solving.py", line 50, in wrapper
    output = solve(*args, **kwargs)
  File "/home/ironman/firedrake/src/firedrake/firedrake/solving.py", line 127, in solve
    _solve_varproblem(*args, **kwargs)
  File "/home/ironman/firedrake/src/firedrake/firedrake/solving.py", line 149, in _solve_varproblem
    solver = vs.LinearVariationalSolver(problem, solver_parameters=solver_parameters,
  File "/home/ironman/firedrake/src/firedrake/firedrake/variational_solver.py", line 347, in __init__
    super(LinearVariationalSolver, self).__init__(*args, **kwargs)
  File "/home/ironman/firedrake/src/pyadjoint/pyadjoint/tape.py", line 46, in wrapper
    return function(*args, **kwargs)
  File "/home/ironman/firedrake/src/firedrake/firedrake/adjoint/variational_solver.py", line 27, in wrapper
    init(self, problem, *args, **kwargs)
  File "/home/ironman/firedrake/src/firedrake/firedrake/variational_solver.py", line 185, in __init__
    ctx = solving_utils._SNESContext(problem,
  File "/home/ironman/firedrake/src/firedrake/firedrake/solving_utils.py", line 138, in __init__
    tensor=self._F,
  File "/home/ironman/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/ironman/firedrake/src/firedrake/firedrake/solving_utils.py", line 449, in _F
    return function.Function(self.F.arguments()[0].function_space())
AttributeError: 'Argument' object has no attribute 'function_space'
``

Later, when I modified the source code from ``self.F.arguments()[0].function_space()`` to ``self.F.arguments()[0].ufl_function_space()``


``
PyDev console: using IPython 7.17.0
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Traceback (most recent call last):
  File "/home/incor-fenics/firedrake/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-f8a4b26f8bf4>", line 1, in <module>
    runfile('/home/incor-fenics/Dropbox/PostDoc/InCor/FenicsRun/V03/frk_hexa_test.py', wdir='/home/incor-fenics/Dropbox/PostDoc/InCor/FenicsRun/V03')
  File "/home/incor-fenics/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/202.6948.78/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/incor-fenics/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/202.6948.78/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/incor-fenics/Dropbox/PostDoc/InCor/FenicsRun/V03/frk_hexa_test.py", line 97, in <module>
    fd.solve(a == L, u_fun, bcs=[noslip], solver_parameters={"ksp_monitor": None})
  File "/home/incor-fenics/firedrake/src/firedrake/firedrake/adjoint/solving.py", line 50, in wrapper
    output = solve(*args, **kwargs)
  File "/home/incor-fenics/firedrake/src/firedrake/firedrake/solving.py", line 127, in solve
    _solve_varproblem(*args, **kwargs)
  File "/home/incor-fenics/firedrake/src/firedrake/firedrake/solving.py", line 149, in _solve_varproblem
    solver = vs.LinearVariationalSolver(problem, solver_parameters=solver_parameters,
  File "/home/incor-fenics/firedrake/src/firedrake/firedrake/variational_solver.py", line 347, in __init__
    super(LinearVariationalSolver, self).__init__(*args, **kwargs)
  File "/home/incor-fenics/firedrake/src/pyadjoint/pyadjoint/tape.py", line 46, in wrapper
    return function(*args, **kwargs)
  File "/home/incor-fenics/firedrake/src/firedrake/firedrake/adjoint/variational_solver.py", line 27, in wrapper
    init(self, problem, *args, **kwargs)
  File "/home/incor-fenics/firedrake/src/firedrake/firedrake/variational_solver.py", line 198, in __init__
    elif ctx.is_mixed:
  File "/home/incor-fenics/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/incor-fenics/firedrake/src/firedrake/firedrake/solving_utils.py", line 423, in is_mixed
    return self._jac.block_shape != (1, 1)
  File "/home/incor-fenics/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/incor-fenics/firedrake/src/firedrake/firedrake/solving_utils.py", line 405, in _jac
    return allocate_matrix(self.J,
  File "/home/incor-fenics/firedrake/src/firedrake/firedrake/assemble.py", line 140, in allocate_matrix
    _, _, result = get_matrix(expr, mat_type, sub_mat_type,
  File "/home/incor-fenics/firedrake/src/firedrake/firedrake/assemble.py", line 259, in get_matrix
    map_pairs, iteration_regions = zip(*(((get_map(test), get_map(trial)),
  File "/home/incor-fenics/firedrake/src/firedrake/firedrake/assemble.py", line 259, in <genexpr>
    map_pairs, iteration_regions = zip(*(((get_map(test), get_map(trial)),
AttributeError: 'Argument' object has no attribute 'cell_node_map'
``

**Comment by dham** [comment]
That first error is a result of importing ufl. You are getting plain ufl arguments instead of Firedrake wrapped ones.

**Comment by Rlahuerta** [comment]
Thanks! I change the code as you advise, and It is showing a diferent error.

``
Thanks! I change the code as you advise, and It is showing a diferent error.

``
# -*- coding: utf-8 -*-
import firedrake as fd
# import ufl as ufl

from mpi4py import MPI
from petsc4py import PETSc

import numpy as np


elsize = 0.25

dim_x = 5.
dim_y = 1.
dim_z = 1.

nx = int(dim_x / elsize)
ny = int(dim_y / elsize)
nz = int(dim_z / elsize)

msh = fd.RectangleMesh(nx, ny, dim_x, dim_y, quadrilateral=True, comm=MPI.COMM_WORLD)
mesh = fd.ExtrudedMesh(msh, layers=nz, layer_height=dim_z / nz, extrusion_type='uniform')

dim = mesh.geometric_dimension()

# Elasticity parameters
E = 1.0e9
nu = 0.0
mu = E / (2.0 * (1.0 + nu))
lmbda = E * nu / ((1.0 + nu) * (1.0 - 2.0 * nu))

x = fd.SpatialCoordinate(mesh)
ufl_x = mesh.coordinates

dti = 0.001

sd_bc = fd.SubDomainData(fd.And(ufl_x[0] >= 0., ufl_x[0] <= dti))
# sd_bc = fd.op2.Subset(mesh.cell_set, sd_bc.indices)

sd_ld = fd.SubDomainData(fd.And(ufl_x[0] >= dim_x - dti, ufl_x[0] <= dim_x))
# sd_ld = fd.op2.Subset(mesh.cell_set, sd_ld.indices)


def epsilon(v):
    return fd.sym(fd.grad(v))

def sigma(v):
    return lmbda * fd.tr(epsilon(v)) * fd.Identity(dim) + 2.0 * mu * epsilon(v)

fun_spc = fd.VectorFunctionSpace(mesh, "CG", 1)


u_fun = fd.Function(fun_spc, name='displacement')
u_fun.assign(0.)

# Define variational problem
u_trl = fd.TrialFunction(fun_spc)
u_tst = fd.TestFunction(fun_spc)

tr = fd.as_vector((0., 0., -100000.))
br = fd.as_vector((0., 0., -0.0001))

a = fd.inner(sigma(u_trl), epsilon(u_tst)) * fd.dx
# L = fd.inner(tr, u_tst) * fd.ds(subdomain_data=sd_ld)
L = fd.inner(br, u_tst) * fd.dx

noslip = fd.DirichletBC(fun_spc, fd.Constant((0., 0., 0.)), sd_bc)

fd.solve(a == L, u_fun, bcs=[noslip], solver_parameters={"ksp_monitor": None})

outfile = fd.File("output.pvd")
outfile.write(u_fun)

``

The error:

``
File "frk_hexa_test.py", line 97, in <module>
    fd.solve(a == L, u_fun, bcs=[noslip], solver_parameters={"ksp_monitor": None})
  File "/home/ironman/firedrake/src/firedrake/firedrake/adjoint/solving.py", line 50, in wrapper
    output = solve(*args, **kwargs)
  File "/home/ironman/firedrake/src/firedrake/firedrake/solving.py", line 127, in solve
    _solve_varproblem(*args, **kwargs)
  File "/home/ironman/firedrake/src/firedrake/firedrake/solving.py", line 155, in _solve_varproblem
    solver.solve()
  File "/home/ironman/firedrake/src/firedrake/firedrake/adjoint/variational_solver.py", line 59, in wrapper
    out = solve(self, **kwargs)
  File "/home/ironman/firedrake/src/firedrake/firedrake/variational_solver.py", line 261, in solve
    dbc.apply(self._problem.u)
  File "<decorator-gen-45>", line 2, in apply
  File "/home/ironman/firedrake/src/PyOP2/pyop2/profiling.py", line 60, in wrapper
    return f(*args, **kwargs)
  File "/home/ironman/firedrake/src/pyadjoint/pyadjoint/tape.py", line 46, in wrapper
    return function(*args, **kwargs)
  File "/home/ironman/firedrake/src/firedrake/firedrake/adjoint/dirichletbc.py", line 30, in wrapper
    return apply(self, *args, **kwargs)
  File "/home/ironman/firedrake/src/firedrake/firedrake/bcs.py", line 423, in apply
    r.assign(self.function_arg, subset=self.node_set)
  File "/home/ironman/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/ironman/firedrake/src/firedrake/firedrake/bcs.py", line 180, in node_set
    return op2.Subset(self._function_space.node_set, self.nodes)
  File "/home/ironman/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/ironman/firedrake/src/firedrake/firedrake/bcs.py", line 170, in nodes
    bcnodes1.append(hermite_stride(self._function_space.boundary_nodes(ss, self.method)))
  File "/home/ironman/firedrake/src/firedrake/firedrake/functionspaceimpl.py", line 514, in boundary_nodes
    return self._shared_data.boundary_nodes(self, sub_domain, method)
  File "/home/ironman/firedrake/src/firedrake/firedrake/functionspacedata.py", line 461, in boundary_nodes
    return get_boundary_nodes(V.mesh(), key, V)
  File "<decorator-gen-38>", line 2, in get_boundary_nodes
  File "/home/ironman/firedrake/src/firedrake/firedrake/functionspacedata.py", line 53, in cached
    result = f(mesh, key, *args, **kwargs)
  File "/home/ironman/firedrake/src/firedrake/firedrake/functionspacedata.py", line 325, in get_boundary_nodes
    indices = dmcommon.boundary_nodes(V, sub_domain, method)
  File "firedrake/cython/dmcommon.pyx", line 927, in firedrake.cython.dmcommon.boundary_nodes
  File "/home/ironman/firedrake/src/firedrake/firedrake/mesh.py", line 182, in subset
    markers = as_tuple(markers, numbers.Integral)
  File "/home/ironman/firedrake/src/PyOP2/pyop2/utils.py", line 86, in as_tuple
    raise TypeError("Items need to be of type %s" % type)
TypeError: Items need to be of type <class 'numbers.Integral'>
``

**Comment by dham** [comment]
This is because you can't use subdomains as boundary markers. You need to use the integer boundary markers from the mesh.

**Comment by dham** [comment]
as an aside, the markdown for code is three backticks, not two. I have to keep editing your posts to make them readable!

**Comment by Rlahuerta** [comment]
Thanks for the quick answer, and sorry for the code markdown error! 

I am looking for the best way to create subdomains to use with DirichletBC. My intension is to use in more complex meshes. Do you have a good example of doing that?

**Comment by wence-** [comment]
The normal way to do this is to get your mesh generator to tag the bits of the boundary with integer labels. These are then read by firedrake, and you can use them as subdomain tags in `DirichletBC`.

**Comment by Rlahuerta** [comment]
I am using HyperMesh to generate very large and complex models based on the Abaqus input deck; if I could generate a function to localize the BCs, I would be able to constraint it.

**Comment by wence-** [comment]
Can hypermesh not mark the boundaries?

**Comment by Rlahuerta** [comment]
> Can hypermesh not mark the boundaries?

Not with the Gmsh input deck, but with Abaqus and Nastran deck, it can be done very well.

I am going to try with meshio.

**Comment by wence-** [comment]
Did you manage to get this working?

**Comment by Rlahuerta** [comment]
Now I am solving this problem using Fenics, but my intention is to try to use Firedrake...

**Comment by wence-** [comment]
OK, thanks, I think the blocker is being able to mark boundaries of the domain in this way. This is possible but we don't have a nice interface for it.

I will close this issue and create something describing the enhancement that would be required.

**Comment by Rlahuerta** [comment]
Thank you!
