### ISSUE TITLE
make alltest SyntaxError after installing firedrake on Mac

### ISSUE THREAD

**Issue by plankering** [firedrakeproject/firedrake#1828]
I am trying to install Firedrake on my macOS Catalina Version 10.15.6 laptop but I get the following error when I run "make alltest" after installation : 

    Building extension modules
  File "setup.py", line 51
    dirs = (sys.prefix, *petsc_dirs)
                        ^
SyntaxError: invalid syntax
    Linting firedrake codebase
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named flake8
make: *** [lint] Error 1

I followed all the prior instructions including installing Homebrew, making sure I had python3, and then install firedrake as instructed on the 'Obtaining Firedrake' of your website. The following is the firedrake-install.log file. Any help would be greatly appreciated. Thank you.

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/5146409/firedrake-install.log)

**Comment by miklos1** [comment]
You are apparently running this with Python 2.7.

Did you forget to activate the virtual env before `make alltest`?

**Comment by plankering** [comment]
oh yes, I did forget the activation step before the make alltest. Thanks for that. Nevertheless, I still get the following error
taking that step into account.

    Building extension modules
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
    Linting firedrake codebase
/Users/romeo/firedrake/bin/python: No module named flake8
make: *** [lint] Error 1

I did the "python3 --version" check and it shows that I have Python 3.8.5 installed. My guess therefore is that, I have both versions installed. How do I modify the "python3 firedrake-install" commend to forcibly run with Python 3? Thanks. 
P.S. A novice here so sorry if the question sounds trivial.

**Comment by miklos1** [comment]
`python3 firedrake-install` will run Python 3, because that's made explicit.  Once you activated the virtual env, even `python` should refer to the Python 3 used in the virtual env.

But it seems mysterious to me, why the virtualenv python fails to find numpy and flake8... they should be installed inside the virtualenv.
- I also notice from the logfile that you have anaconda installed.  We used to have issues with anaconda python in the past, not sure what the current state is...

**Comment by plankering** [comment]
I also suspected a potential issue with anaconda but I have tried deleting all installation files and then installing firedrake (before and after) installing anaconda. Neither worked so I think that may not be the problem. I will continue playing around with the installations and maybe one combination will work. Thank you anyway. Cheers!

**Comment by wence-** [comment]
Maybe fixed by #1885, needs a fresh install with a newly download `firedrake-install` script. Can you confirm?

**Comment by JDBetteridge** [comment]
Closing due to inactivity (see [policy](https://github.com/firedrakeproject/firedrake/wiki/Closing-Installation-Issues) for more info)
