### ISSUE TITLE
Hypre ADS Preconditioner for H(div) problem

### ISSUE THREAD

**Issue by xiaodizhang29** [firedrakeproject/firedrake#1888]
I am writing a  ADS preconditioner for H(div) problem, based on the code for AMS preconditioner. The additional information we need to provide is the discrete curl matrix. But it gives some errors. 

```
/mnt/firedrake/src/fiat/FIAT/check_format_variant.py:9: DeprecationWarning: Variant of Raviart Thomas element will change from point evaluation to integral evaluation. You should project into variant="integral"
  warnings.warn('Variant of ' + element + ' element will change from point evaluation to integral evaluation.'
/mnt/firedrake/src/fiat/FIAT/check_format_variant.py:9: DeprecationWarning: Variant of Nedelec element will change from point evaluation to integral evaluation. You should project into variant="integral"
  warnings.warn('Variant of ' + element + ' element will change from point evaluation to integral evaluation.'
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Error in external library
[0]PETSC ERROR: Error in jac->setup(): error code 12
[0]PETSC ERROR: See https://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
[0]PETSC ERROR: Petsc Development GIT revision: v3.4.2-30292-g4fdc5fe836  GIT Date: 2020-07-13 18:48:19 +0100
[0]PETSC ERROR: ADSTest.py on a default named ubuntu by zxd Tue Oct 27 21:57:34 2020
[0]PETSC ERROR: Configure options PETSC_DIR=/mnt/firedrake/src/petsc PETSC_ARCH=default --with-fortran-bindings=0 --download-ptscotch --with-c2html=0 --download-superlu_dist --download-chaco --with-cxx-dialect=C++11 --download-scalapack --with-debugging=0 --with-cc=/usr/bin/mpicc --download-hdf5=https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.bz2 --with-cxx=/usr/bin/mpicxx --with-shared-libraries=1 --with-fc=/usr/bin/mpif90 --download-mumps --download-eigen="/mnt/firedrake/src/eigen-3.3.3.tgz " --with-mpiexec=/usr/bin/mpiexec --download-hypre
[0]PETSC ERROR: #1 PCSetUp_HYPRE() line 408 in /mnt/firedrake/src/petsc/src/ksp/pc/impls/hypre/hypre.c
[0]PETSC ERROR: #2 PCSetUp() line 959 in /mnt/firedrake/src/petsc/src/ksp/pc/interface/precon.c
[0]PETSC ERROR: #3 PCSetUp() line 959 in /mnt/firedrake/src/petsc/src/ksp/pc/interface/precon.c
[0]PETSC ERROR: #4 KSPSetUp() line 405 in /mnt/firedrake/src/petsc/src/ksp/ksp/interface/itfunc.c
[0]PETSC ERROR: #5 KSPSolve_Private() line 662 in /mnt/firedrake/src/petsc/src/ksp/ksp/interface/itfunc.c
[0]PETSC ERROR: #6 KSPSolve() line 882 in /mnt/firedrake/src/petsc/src/ksp/ksp/interface/itfunc.c
[0]PETSC ERROR: #7 SNESSolve_KSPONLY() line 51 in /mnt/firedrake/src/petsc/src/snes/impls/ksponly/ksponly.c
[0]PETSC ERROR: #8 SNESSolve() line 4515 in /mnt/firedrake/src/petsc/src/snes/interface/snes.c
Traceback (most recent call last):
  File "ADSTest.py", line 41, in <module>
    solver.solve()
  File "/mnt/firedrake/src/firedrake/firedrake/adjoint/variational_solver.py", line 75, in wrapper
    out = solve(self, **kwargs)
  File "/mnt/firedrake/src/firedrake/firedrake/variational_solver.py", line 271, in solve
    self.snes.solve(None, work)
  File "PETSc/SNES.pyx", line 571, in petsc4py.PETSc.SNES.solve
  File "libpetsc4py/libpetsc4py.pyx", line 1298, in libpetsc4py.PCSetUp_Python
  File "/mnt/firedrake/src/firedrake/firedrake/preconditioners/base.py", line 125, in setUp
    super().setUp(pc)
  File "/mnt/firedrake/src/firedrake/firedrake/preconditioners/base.py", line 45, in setUp
    self.initialize(pc)
  File "/home/zxd/Desktop/Firedark/AMS_ADS/hypre_ads.py", line 52, in initialize
    pc.setUp()
  File "PETSc/PC.pyx", line 215, in petsc4py.PETSc.PC.setUp
petsc4py.PETSc.Error: error code 76
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Error in external library
[0]PETSC ERROR: Error in HYPRE_IJVectorDestroy(): error code 12
[0]PETSC ERROR: See https://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
[0]PETSC ERROR: Petsc Development GIT revision: v3.4.2-30292-g4fdc5fe836  GIT Date: 2020-07-13 18:48:19 +0100
[0]PETSC ERROR: ADSTest.py on a default named ubuntu by zxd Tue Oct 27 21:57:34 2020
[0]PETSC ERROR: Configure options PETSC_DIR=/mnt/firedrake/src/petsc PETSC_ARCH=default --with-fortran-bindings=0 --download-ptscotch --with-c2html=0 --download-superlu_dist --download-chaco --with-cxx-dialect=C++11 --download-scalapack --with-debugging=0 --with-cc=/usr/bin/mpicc --download-hdf5=https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.bz2 --with-cxx=/usr/bin/mpicxx --with-shared-libraries=1 --with-fc=/usr/bin/mpif90 --download-mumps --download-eigen="/mnt/firedrake/src/eigen-3.3.3.tgz " --with-mpiexec=/usr/bin/mpiexec --download-hypre
[0]PETSC ERROR: #9 MatDestroy_HYPRE() line 1147 in /mnt/firedrake/src/petsc/src/mat/impls/hypre/mhypre.c
[0]PETSC ERROR: #10 MatDestroy() line 1287 in /mnt/firedrake/src/petsc/src/mat/interface/matrix.c
[0]PETSC ERROR: #11 PCReset_HYPRE() line 454 in /mnt/firedrake/src/petsc/src/ksp/pc/impls/hypre/hypre.c
[0]PETSC ERROR: #12 PCReset() line 76 in /mnt/firedrake/src/petsc/src/ksp/pc/interface/precon.c
[0]PETSC ERROR: #13 PCDestroy() line 108 in /mnt/firedrake/src/petsc/src/ksp/pc/interface/precon.c
[0]PETSC ERROR: #14 PetscObjectDestroy() line 59 in /mnt/firedrake/src/petsc/src/sys/objects/destroy.c
petsc4py.PETSc.Error: error code 76
Exception ignored in: 'petsc4py.PETSc.Object.__dealloc__'
petsc4py.PETSc.Error: error code 76

```
The test code is

```
import numpy
from firedrake import *
from hypre_ads import*
from firedrake.solving_utils import KSPReasons
from firedrake.petsc import PETSc
PETSc.Sys.popErrorHandler()

for n in [3, 4, 5]:
    mesh = UnitCubeMesh(2 ** n, 2 ** n, 2 ** n)
    V = FunctionSpace(mesh, "RT", 1)
    V0 = VectorFunctionSpace(mesh, "DG", 0)

    u = TrialFunction(V)
    v = TestFunction(V)

    a = inner(div(u), div(v))*dx
    L = inner(Constant((0., 0., 0.)), v)*dx

    x, y, z = SpatialCoordinate(mesh)
    B0 = 1
    constant_field = as_vector([-0.5*B0*(y - 0.5), 0.5*B0*(x - 0.5), 0])

    bc = DirichletBC(V, constant_field, (1, 2, 3, 4))

    params = {'ksp_type': 'cg',
              'ksp_itmax': '30',
              'ksp_rtol': '1e-8',
              'ksp_atol': '1e-8',
              "ksp_converged_reason": None,
              "ksp_monitor_true_residual": None,
              'pc_type': 'python',
              'pc_python_type': 'hypre_ads.HypreADS',
              'pc_hypre_ams_zero_beta_poisson': True,
              'ksp_monitor ': None,
              'ksp_view ': None,
              }

    A = Function(V)
    problem = LinearVariationalProblem(a, L, A, bcs=bc)
    solver = LinearVariationalSolver(problem, solver_parameters=params)
    solver.solve()
    print("N = {}, iterations = {}, converged reason = {}".format(
        V.dim(), solver.snes.ksp.getIterationNumber(), 
        KSPReasons[solver.snes.ksp.getConvergedReason()]))
```

And the subfunction is 

```
from firedrake.preconditioners.base import PCBase
from firedrake.petsc import PETSc
from firedrake.functionspace import FunctionSpace
from firedrake.constant import Constant
from firedrake.ufl_expr import TestFunction
from firedrake.interpolation import Interpolator
from firedrake.projection import project
from firedrake.dmhooks import get_function_space
from ufl import grad, curl
import numpy as np


__all__ = ("HypreADS",)


class HypreADS(PCBase):
    def initialize(self, obj):
        A, P = obj.getOperators()
        prefix = obj.getOptionsPrefix()
        V = get_function_space(obj.getDM())
        mesh = V.mesh()

        family = str(V.ufl_element().family())
        degree = V.ufl_element().degree()
        if family != 'Raviart-Thomas' or degree != 1:
            raise ValueError("Hypre ADS requires lowest order RT elements! (not %s of degree %d)" % (family, degree))

        P1 = FunctionSpace(mesh, "Lagrange", 1)
        NC1 = FunctionSpace(mesh, "N1curl", 1)
        # DiscreteGradient
        G = Interpolator(grad(TestFunction(P1)), NC1).callable().handle
        # DiscreteCurl
        C = Interpolator(curl(TestFunction(NC1)), V).callable().handle

        pc = PETSc.PC().create(comm=obj.comm)
        pc.incrementTabLevel(1, parent=obj)
        pc.setOptionsPrefix(prefix + "hypre_ads_")
        pc.setOperators(A, P)

        pc.setType('hypre')
        pc.setHYPREType('ads')
        pc.setHYPREDiscreteGradient(G)
        pc.setHYPREDiscreteCurl(C)
        zero_beta = PETSc.Options(prefix).getBool("pc_hypre_ads_zero_beta_poisson", default=False)
        if zero_beta:
            pc.setHYPRESetBetaPoissonMatrix(None)
        pc.setCoordinates(np.reshape(mesh.coordinates.dat.data_ro, (-1,mesh.geometric_dimension())))

        pc.setUp()
        self.pc = pc

    def apply(self, pc, x, y):
        self.pc.apply(x, y)

    def applyTranspose(self, pc, x, y):
        self.pc.applyTranspose(x, y)

    def view(self, pc, viewer=None):
        super(HypreADS, self).view(pc, viewer)
        if hasattr(self, "pc"):
            viewer.printfASCII("PC to apply inverse\n")
            self.pc.view(viewer)

    def update(self, pc):
        self.pc.setUp()
```

Could you tell me how to deal with this error? Thanks for any input!

Best wishes
xiaodi

**Comment by wence-** [comment]
I think `'pc_hypre_ams_zero_beta_poisson': True,` should be `'pc_hypre_ads_zero_beta_poisson': True,`

That might help. It seems that Hypre is complaining in the setup, I guess because you're only solving `(div(u), div(v))_L2` so the problem is singular, but you didn't tell it that this was the case.

**Comment by xiaodizhang29** [comment]
Thank you for your advise. You are right! The ADS solver in hypre also requires \beta >0, i.e. the zero-order term must exist.

![image](https://user-images.githubusercontent.com/43510798/97385102-fde65f00-190b-11eb-8450-51a20e0199b3.png)

After a little modification, my codes present satisfactory results.

---------------------------------------------------------------------
N = 120, iterations = 6, converged reason = CONVERGED_ATOL
N = 864, iterations = 7, converged reason = CONVERGED_ATOL
N = 6528, iterations = 9, converged reason = CONVERGED_ATOL
N = 50688, iterations = 11, converged reason = CONVERGED_ATOL
N = 399360, iterations = 13, converged reason = CONVERGED_ATOL
---------------------------------------------------------------------

**Comment by xiaodizhang29** [comment]
What a pity! I can't generalizate to higher-order elements. The obstacle for is that a petsc4py wrapper is missing to use the corresponding interface, as in Feature hypre ams [#1854](https://github.com/firedrakeproject/firedrake/pull/1854). There is an additional method to resolve it. We can implemente the AMS and ADS solver rather than call the hypre. But it's too much trouble.

**Comment by pefarrell** [comment]
Adding wrappers to petsc4py is pretty straightforward. You don't really need to know Cython, so long as you can programme in a monkey-see-monkey-do fashion. Clone the source and `git grep <a_similar_function_that_is_wrapped>`.

**Comment by wence-** [comment]
@xiaodizhang29 given that this now works, do you mind preparing a pull request that adds the `ADS` preconditioner to firedrake? We can then look at adding the necessary petsc4py extensions to support higher-order versions.

**Comment by xiaodizhang29** [comment]
OK, it's my pleasure. I will create a merge request until next week.

**Comment by florian98765** [comment]
> Adding wrappers to petsc4py is pretty straightforward. You don't really need to know Cython, so long as you can programme in a monkey-see-monkey-do fashion. Clone the source and `git grep <a_similar_function_that_is_wrapped>`.

Dear Patrick, how can i recompile petsc / petsc4py when firedrake was installed using ```firedrake-install```?

I would also like to try the higher order interface for the AMS solver. Please let me know if you already have a working version.
best wishes
Florian

**Comment by wence-** [comment]
In the activated venv do `pip install -U --no-deps src/petsc4py`

**Comment by xiaodizhang29** [comment]
#1893
