### ISSUE TITLE
Installation Error: RuntimeError & pip._internal.exceptions.InstallationError when building MATPLOTLIB

### ISSUE THREAD

**Issue by AwesomemixTang** [firedrakeproject/firedrake#1911]
Hi,
My system is McaOs Catalina 10.15 
Running the command python3 firedrake-install, and I got the following log.file
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/5522177/firedrake-install.log)
In particular:
I got the following error When build matplotlib :

BUILDING` MATPLOTLIB
      matplotlib: yes [3.3.2]
          python: yes [3.9.0 (default, Oct 27 2020, 14:15:17)  [Clang 12.0.0
                      (clang-1200.0.32.21)]]
        platform: yes [darwin]
     sample_data: yes [installing]
           tests: no  [skipping due to configuration]
          macosx: yes [installing]

    running egg_info
    creating /private/var/folders/zr/w3h72j9n6yv66m19zlmk46q40000gn/T/pip-pip-egg-info-2iaeatv3/matplotlib.egg-info
    writing /private/var/folders/zr/w3h72j9n6yv66m19zlmk46q40000gn/T/pip-pip-egg-info-2iaeatv3/matplotlib.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/zr/w3h72j9n6yv66m19zlmk46q40000gn/T/pip-pip-egg-info-2iaeatv3/matplotlib.egg-info/dependency_links.txt
    writing namespace_packages to /private/var/folders/zr/w3h72j9n6yv66m19zlmk46q40000gn/T/pip-pip-egg-info-2iaeatv3/matplotlib.egg-info/namespace_packages.txt
    writing requirements to /private/var/folders/zr/w3h72j9n6yv66m19zlmk46q40000gn/T/pip-pip-egg-info-2iaeatv3/matplotlib.egg-info/requires.txt
    writing top-level names to /private/var/folders/zr/w3h72j9n6yv66m19zlmk46q40000gn/T/pip-pip-egg-info-2iaeatv3/matplotlib.egg-info/top_level.txt
    writing manifest file '/private/var/folders/zr/w3h72j9n6yv66m19zlmk46q40000gn/T/pip-pip-egg-info-2iaeatv3/matplotlib.egg-info/SOURCES.txt'
    init_dgelsd failed init
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zr/w3h72j9n6yv66m19zlmk46q40000gn/T/pip-install-f2sog2f0/matplotlib/setup.py", line 242, in <module>
        setup(  # Finally, pass this all along to distutils to do the heavy lifting.
      File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 298, in run
        self.find_sources()
      File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 305, in find_sources
        mm.run()
      File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 536, in run
        self.add_defaults()
      File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 572, in add_defaults
        sdist.add_defaults(self)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/private/var/folders/zr/w3h72j9n6yv66m19zlmk46q40000gn/T/pip-install-f2sog2f0/matplotlib/setup.py", line 88, in finalize_options
        self.distribution.ext_modules[:] = [
      File "/private/var/folders/zr/w3h72j9n6yv66m19zlmk46q40000gn/T/pip-install-f2sog2f0/matplotlib/setup.py", line 91, in <listcomp>
        for ext in package.get_extensions()
      File "/private/var/folders/zr/w3h72j9n6yv66m19zlmk46q40000gn/T/pip-install-f2sog2f0/matplotlib/setupext.py", line 345, in get_extensions
        add_numpy_flags(ext)
      File "/private/var/folders/zr/w3h72j9n6yv66m19zlmk46q40000gn/T/pip-install-f2sog2f0/matplotlib/setupext.py", line 469, in add_numpy_flags
        import numpy as np
      File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
        raise RuntimeError(msg)
    RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
    RankWarning: Polyfit may be poorly conditioned

`ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 323, in run
    requirement_set = resolver.resolve(
  File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 530, in _generate_metadata
    return generate_metadata_legacy(
  File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 70, in generate_metadata
    call_subprocess(
  File "/Users/oscartwb/firedrake/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Removed matplotlib from https://files.pythonhosted.org/packages/2b/4c/fe4b36325795524f35d39edc390c89584e9a901df9e615df6f5effddaa0e/matplotlib-3.3.2.tar.gz#sha256=3d2edbf59367f03cd9daf42939ca06383a7d7803e3993eb5ff1bee8e8a3fbb6b (from -r firedrake/requirements-ext.txt (line 6)) from build tracker '/private/var/folders/zr/w3h72j9n6yv66m19zlmk46q40000gn/T/pip-req-tracker-ql7ixgsp'
Removed build tracker: '/private/var/folders/zr/w3h72j9n6yv66m19zlmk46q40000gn/T/pip-req-tracker-ql7ixgsp'

2020-11-10 21:27:23,538 INFO   
Install log saved in /Users/oscartwb/firedrake-install.log

How do I fix the problem?
  #Thanks

**Comment by danshapero** [comment]
It looks like you're installing with python-3.9, which is unfortunately not supported yet by both Firedrake and several other packages. For example, Firedrake depends on VTK, which doesn't ship binary wheels for python-3.9 yet. You can make homebrew downgrade to python-3.8 by running these commands:

```
brew unlink python@3.9
brew install python@3.8
brew link python@3.8
```

Let us know if that helps and we can close the issue. There have been some other problems installing on Catalina lately which have hopefully been taken care of. But in any case please don't hesitate to raise another issue or ask in the Firedrake [slack channel](https://firedrakeproject.org/contact.html) if you encounter other problems.
