### ISSUE TITLE
Firedrake get's stuck in first call to assemble

### ISSUE THREAD

**Issue by florianwechsung** [firedrakeproject/firedrake#1932]
Hi all, 

I've been trying to run some larger simulation on the TACC Frontera and the NYU Greene HPC systems.
When going past a few hundred cores, the first call to `assemble` scales unexpectedly poorly: for more than 8 nodes, it suddenly get's stuck for around 30 extra seconds. The next call to assemble does not exhibit this problem and scales nicely.

|                | 1 Node | 2 Nodes | 4 Nodes | 8 Nodes | 9 Nodes | 10 Nodes | 14 Nodes |
| --- | --- | --- | --- | --- | --- | --- | --- |
| First assemble |   54.7 | 27.0    |    13.7 | 7.61 | 36.2 | 35.8     |     34.8 |
| Second assemble |   20.7 | 10.4    |     5.5 | 2.89 | 2.6 |2.4      |      1.7 |

The problem has 32894427 dofs, so even on 14 Nodes x 48 cores, we have around 50k dofs per core. The numbers above are on NYU Greene. I see the same effect on TACC Frontera, but at a different (higher) node count.

Both installations are compiled with Intel Compilers, but linked to different MPI implementations (intel mpi on Frontera, mvapich on Greene). 

The problem is just assemble of a Stokes system, using CG3 x DG0 elements on a regular tet mesh:

```
from mpi4py import MPI
comm = MPI.COMM_WORLD
from petsc4py import PETSc
PETSc.Sys.popErrorHandler()
PETSc.Log.begin()
from firedrake import *

import argparse

import logging

parser = argparse.ArgumentParser(add_help=False)
parser.add_argument("--nref", type=int, default=1)
parser.add_argument("--N", type=int, default=10)
parser.add_argument("--overlap", dest="overlap", default=False, action="store_true")
args, _ = parser.parse_known_args()

nref = args.nref
N = args.N

PETSc.Sys.Print("before mesh hierarchy")

baseMesh = BoxMesh(N, N, N, 4, 4, 4)
mh = MeshHierarchy(baseMesh, nref, reorder=True)
PETSc.Sys.Print("after mesh hierarchy")
mesh = mh[-1]

V = VectorFunctionSpace(mesh, "CG", 3)
Q = FunctionSpace(mesh, "DG", 0)

PETSc.Sys.Print("Finished FunctionSpaces")
Z = V * Q
size = Z.mesh().mpi_comm().size
PETSc.Sys.Print("dim(Z) = %i (%i per core) " % ( Z.dim(), Z.dim()/size))
PETSc.Sys.Print("dim(V) = %i (%i per core) " % ( V.dim(), V.dim()/size))
PETSc.Sys.Print("dim(Q) = %i (%i per core) " % ( Q.dim(), Q.dim()/size))

z = Function(Z)
u, p = TrialFunctions(Z)
v, q = TestFunctions(Z)
bcs = [DirichletBC(Z.sub(0), 0, "on_boundary")]

F = inner(2*sym(grad(u)), grad(v))*dx
F += - p * div(v) * dx - div(u) * q * dx
a = lhs(F)
l = rhs(F)
from time import time
PETSc.Log.begin()
PETSc.Sys.Print("Start assembly 1")
t1 = time()
assemble(a, bcs=bcs)
t2 = time()
PETSc.Sys.Print("Start assembly 2")
assemble(a, bcs=bcs)
t3 = time()
PETSc.Sys.Print("Time for first  assembly:", t2-t1)
PETSc.Sys.Print("Time for second assembly:", t3-t2)
PETSc.Log.view()
```

I call the script twice in the job submission, to make sure caching of the compiled kernels is not an issue. I also set the PYOP2_CACHE_DIR to /tmp/ to make sure filesystem access is not the crux.
I have also attached the log file for the run on 9 nodes and on 8 nodes, that contains the output of `-log_view`.
[minimal_356398_Nodes_8_BaseN_18_NREF_2_second.txt](https://github.com/firedrakeproject/firedrake/files/5653971/minimal_356398_Nodes_8_BaseN_18_NREF_2_second.txt)
[minimal_356421_Nodes_9_BaseN_18_NREF_2_second.txt](https://github.com/firedrakeproject/firedrake/files/5653972/minimal_356421_Nodes_9_BaseN_18_NREF_2_second.txt)

**Comment by wence-** [comment]
It looks to be all (mostly) in `MatAssemblyEnd`? Can you try running with `-matstash_legacy` ?

**Comment by wence-** [comment]
Also run with `PYOP2_LOG_LEVEL=DEBUG` and `set_log_level(DEBUG)` to see potentially more debugging output.

**Comment by ksagiyam** [comment]
Just noticed that, at least on process 0, 9-nodes run uses twice as much memory for LG map as 8-nodes run:
`IS L to G Mapping    43             27      7565040     0` ( 8 nodes)
`IS L to G Mapping    43             27     14510488     0` (9 nodes)

**Comment by florianwechsung** [comment]
I just ran with `-matstash_legacy`. Still works fine on 8 nodes. On 9 nodes, it fails with this error message:
```
[261]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[261]PETSC ERROR: Petsc has generated inconsistent data
[261]PETSC ERROR: Unused space detected in matrix: 76533 X 76533, 20886 unneeded
[261]PETSC ERROR: See https://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
[261]PETSC ERROR: Petsc Development GIT revision: v3.4.2-33053-ge85aaad7c1  GIT Date: 2020-10-09 10:20:17 +0100
[261]PETSC ERROR: Unknown Name on a intel named cs067.nyu.cluster by fw18 Mon Dec  7 12:37:10 2020
[261]PETSC ERROR: Configure options PETSC_DIR=/tmp/bin/petsc PETSC_ARCH=intel CFLAGS="-xCORE-AVX512 -O2 -g" CXXFLAGS="-xCORE-AVX512 -O2 -g" FFLAGS="-xCORE-AVX512 -O2 -g" --download-blacs --download-chaco --download-hypre --download-metis --download-mumps --download-parmetis --download-plapack --download-ptscotch=1 --download-scalapack --download-spai --download-suitesparse --download-superlu --download-superlu_dist --with-blacs=1 --with-blaslapack-dir=/share/apps/intel/19.1.2/compilers_and_libraries/linux/mkl/ --with-chaco=1 --with-cxx-dialect=C++11 --with-debugging=no --with-hdf5=1 --download-hdf5=https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.4/src/hdf5-1.10.4.tar.bz2 --with-hypre=1 --with-make-np=8 --with-metis=1 --with-mpi-dir=/share/apps/mvapich2/2.3.4/intel/ --with-mpi=1 --with-mumps=1 --with-packages-build-dir=/tmp/petsc-firedrake/intel --with-parmetis=1 --with-plapack=1 --with-precision=double --with-python-exec=python3 --with-python=1 --with-scalapack=1 --with-scalar-type=real --with-shared-libraries=1 --with-spai=1 --with-suitesparse=1 --with-superlu=1 --with-superlu_dist=1 --with-x=0 --with-pic --with-logging=1 --download-eigen=3.3.3.tar.gz
[261]PETSC ERROR: #1 MatAssemblyEnd_SeqAIJ() line 1181 in /tmp/bin/petsc/src/mat/impls/aij/seq/aij.c
[261]PETSC ERROR: #2 MatAssemblyEnd() line 5444 in /tmp/bin/petsc/src/mat/interface/matrix.c
[261]PETSC ERROR: #3 MatAssemblyEnd_MPIAIJ() line 854 in /tmp/bin/petsc/src/mat/impls/aij/mpi/mpiaij.c
[261]PETSC ERROR: #4 MatAssemblyEnd() line 5440 in /tmp/bin/petsc/src/mat/interface/matrix.c
Traceback (most recent call last):
  File "minimal.py", line 51, in <module>
    assemble(a, bcs=bcs)
  File "/tmp/bin/firedrake/src/firedrake/firedrake/adjoint/assembly.py", line 18, in wrapper
    output = assemble(*args, **kwargs)
  File "/tmp/bin/firedrake/src/firedrake/firedrake/assemble.py", line 100, in assemble
    for l in loops:
  File "/tmp/bin/firedrake/src/firedrake/firedrake/assemble.py", line 707, in _assemble
    tensor, zeros, result = get_matrix(expr, mat_type, sub_mat_type,
  File "/tmp/bin/firedrake/src/firedrake/firedrake/assemble.py", line 280, in get_matrix
    tensor = matrix.Matrix(expr, bcs, mat_type, sparsity, ScalarType,
  File "/tmp/bin/firedrake/src/firedrake/firedrake/matrix.py", line 99, in __init__
    self.M = op2.Mat(*args, mat_type=mat_type, **kwargs)
  File "/tmp/bin/firedrake/src/PyOP2/pyop2/petsc_base.py", line 603, in __init__
    self._init()
  File "/tmp/bin/firedrake/src/PyOP2/pyop2/petsc_base.py", line 626, in _init
    self._init_monolithic()
  File "/tmp/bin/firedrake/src/PyOP2/pyop2/petsc_base.py", line 693, in _init_monolithic
    mat.assemble()
  File "PETSc/Mat.pyx", line 1048, in petsc4py.PETSc.Mat.assemble
petsc4py.PETSc.Error: error code 77
[cli_261]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 261
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 358221.2 ON cs062-ib0 CANCELLED AT 2020-12-07T12:37:28 ***
srun: error: cs062-ib0: tasks 0-2,4-29,31-47: Killed
srun: Terminating job step 358221.2
srun: error: cs062-ib0: tasks 3,30: Killed
srun: error: cs067-ib0: tasks 244-245,247,252-253,256,258-263,265-267,271-272,277-278: Killed
srun: error: cs067-ib0: tasks 240-243,246,248-251,254-255,257,264,268-270,273-276,279-287: Killed
srun: error: cs068-ib0: tasks 288-335: Killed
srun: error: cs065-ib0: tasks 144-191: Killed
srun: error: cs064-ib0: tasks 96-143: Killed
srun: error: cs066-ib0: tasks 192-239: Killed
srun: error: cs070-ib0: tasks 384-431: Killed
srun: error: cs069-ib0: tasks 336-383: Killed
srun: error: cs063-ib0: tasks 48-95: Killed
```
Now running with more PYOP2 logging.

**Comment by florianwechsung** [comment]
No particularly interesting data from PYOP2 logging, just that it found a compilation comm.
@ksagiyam What would be a good check to see if the LG Map is constructed correctly? I added 
```
from mpi4py import MPI
lgv = V.local_to_global_map([])
s = lgv.size
s = comm.allreduce(s, op=MPI.MAX)
PETSc.Sys.Print("LG V Size:", s)
lgq = Q.local_to_global_map([])
s = lgq.size
s = comm.allreduce(s, op=MPI.MAX)
PETSc.Sys.Print("LG Q Size:", s)
```
But don't see a blowup in size as I go from 8 to 9 nodes.

In other news, I have submitted a few more jobs on 9 nodes with `-matstash_legacy`: some crash with the message above, some run through fine but with the extra 30 seconds spend in the first assembly, and then oddly freeze in the log view output...

**Comment by wence-** [comment]
Can you add `from firedrake.petsc import PETSc` and then `PETSc.Sys.popErrorHandler()` at the top of your script?

**Comment by florianwechsung** [comment]
I'm currently doing 
```
from mpi4py import MPI
comm = MPI.COMM_WORLD
from petsc4py import PETSc
PETSc.Sys.popErrorHandler()
PETSc.Log.begin()
from firedrake import *
```
Is that what you mean, or should I change the order here?

**Comment by wence-** [comment]
If petsc is imported before firedrake, then we dont pass it the commandline args i think. 

But something like that. I was wondering if somehow our matrix preallocation is off.

**Comment by florianwechsung** [comment]
Ah, so `-matstash_legacy` was probably not passed before. Let me rerun then.

**Comment by florianwechsung** [comment]
Mh, made sure options are passed now, but same result: either crashes or 30 extra seconds.
In the case of crash, I still only get the error message above... my script starts with 
```
from firedrake import *
from firedrake.petsc import PETSc
PETSc.Sys.popErrorHandler()
```

Compiling with debugging now, maybe that gives some insight.

**Comment by ksagiyam** [comment]
`-mat_view ::ascii_info` prints how many `malloc`s have been used during assembly, but the output will be huge if you run with many processes.

**Comment by JDBetteridge** [comment]
I have tried to reproduce this issue on [Isambard](https://gw4-isambard.github.io/docs/), but was not able to:
|                 | 1 Node | 2 Nodes | 4 Nodes | 8 Nodes | 9 Nodes | 10 Nodes | 14 Nodes | 16 Nodes |
| --------------- | ------ | ------- | ------- | ------- | ------- | -------- | -------- | -------- |
| First assemble  | 82.41  | 41.33   | 20.48   | 10.54   | 9.17    | 8.69     | 6.46     | 5.94     |
| Second assemble | 29.79  | 15.45   |  8.18   |  4.24   | 3.77    | 3.53     | 2.63     | 2.27     |

This was run on 48 of the 64 available cores per node to more closely reproduce your setup.

I did have an issue running on 14 and 16 cores where the task just hangs and times out, but resubmitting the jobs, everything worked fine.

One thing I have done to avoid filesystem contention is install Firedrake to a directory in `/tmp` then tarballed the whole installation and I un-tarball it back to `/tmp` every job at the start of my script.

This Firedrake was installed at commit `c5bad4ac`, if you want a reference.

I'm happy to share any other details of my setup and any logs/scripts that might be useful.
[8_384_aprun.txt](https://github.com/firedrakeproject/firedrake/files/5675731/8_384_aprun.txt)
[8_nodes.err.txt](https://github.com/firedrakeproject/firedrake/files/5675737/8_nodes.err.txt)
[8_nodes.out.txt](https://github.com/firedrakeproject/firedrake/files/5675738/8_nodes.out.txt)

[9_432_aprun.txt](https://github.com/firedrakeproject/firedrake/files/5675732/9_432_aprun.txt)
[9_nodes.err.txt](https://github.com/firedrakeproject/firedrake/files/5675740/9_nodes.err.txt)
[9_nodes.out.txt](https://github.com/firedrakeproject/firedrake/files/5675741/9_nodes.out.txt)

**Comment by JDBetteridge** [comment]
Assemble has been heavily refactored since this problem arose, and the issue has seen no activity for 2-years, so I'm closing. Feel free to open a new issue if the problem is still occuring
