### ISSUE TITLE
Build issue with ARM hardware

### ISSUE THREAD

**Issue by fcannini** [firedrakeproject/firedrake#1965]
Hi there.

I'm having problems building firedrake on a Cavium Thunder X2 running centos 7.7.

I've managed to narrow down to the symengine library not being available on PyPI.
Tried to build it, but cmake barfs saying that cython version is too old, even though it is the latest available.

```
 Found link https://files.pythonhosted.org/packages/c7/21/1b6af2da049e41b7c91eec00f7fbbb9f0099eae9440f20b4be3cd5b41373/symengine-0.6.1.tar.gz#sha256=8c647ace43e4214c4452bc06de06eb2cf2d1abbcc4c1faa7c13ad7741be1
c1ce (from https://pypi.org/simple/symengine/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,<4), version: 0.6.1
Given no hashes to check 7 links for project 'symengine': discarding no candidates
Collecting symengine
  Created temporary directory: /tmp/pip-unpack-u8oj01me
  Looking up "https://files.pythonhosted.org/packages/c7/21/1b6af2da049e41b7c91eec00f7fbbb9f0099eae9440f20b4be3cd5b41373/symengine-0.6.1.tar.gz" in the cache
  Current age based on date: 4132981
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 4132981
  Using cached symengine-0.6.1.tar.gz (721 kB)
  Added symengine from https://files.pythonhosted.org/packages/c7/21/1b6af2da049e41b7c91eec00f7fbbb9f0099eae9440f20b4be3cd5b41373/symengine-0.6.1.tar.gz#sha256=8c647ace43e4214c4452bc06de06eb2cf2d1abbcc4c1faa7c13ad7741be1c1ce to build tracker '/tmp/pip-req-tracker-ydkmkhlj'
    Running setup.py (path:/tmp/pip-install-7rp88e4d/symengine_943058817d394bb696401abd87844437/setup.py) egg_info for package symengine
    Created temporary directory: /tmp/pip-pip-egg-info-ayvo5lgm
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-ayvo5lgm/symengine.egg-info
    writing /tmp/pip-pip-egg-info-ayvo5lgm/symengine.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-ayvo5lgm/symengine.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-ayvo5lgm/symengine.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-ayvo5lgm/symengine.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-ayvo5lgm/symengine.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.hpp' under directory 'symengine'
    warning: no files found matching '*.in' under directory 'cmake'
    writing manifest file '/tmp/pip-pip-egg-info-ayvo5lgm/symengine.egg-info/SOURCES.txt'
  Source in /tmp/pip-install-7rp88e4d/symengine_943058817d394bb696401abd87844437 has version 0.6.1, which satisfies requirement symengine from https://files.pythonhosted.org/packages/c7/21/1b6af2da049e41b7c91eec00f7fbbb9f0099eae9440f20b4be3cd5b41373/symengine-0.6.1.tar.gz#sha256=8c647ace43e4214c4452bc06de06eb2cf2d1abbcc4c1faa7c13ad7741be1c1ce
  Removed symengine from https://files.pythonhosted.org/packages/c7/21/1b6af2da049e41b7c91eec00f7fbbb9f0099eae9440f20b4be3cd5b41373/symengine-0.6.1.tar.gz#sha256=8c647ace43e4214c4452bc06de06eb2cf2d1abbcc4c1faa7c13ad7741be1c1ce from build tracker '/tmp/pip-req-tracker-ydkmkhlj'
Created temporary directory: /tmp/pip-unpack-fb66q1bx
Skipping wheel build for symengine, due to binaries being disabled for it.
Installing collected packages: symengine
  Created temporary directory: /tmp/pip-record-9o_87w3g
    Running setup.py install for symengine: started
    Running command /home/user/softwares/firedrake/arm/gcc-9.2.0/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7rp88e4d/symengine_943058817d394bb696401abd87844437/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7rp88e4d/symengine_943058817d394bb696401abd87844437/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9o_87w3g/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/softwares/firedrake/arm/gcc-9.2.0/include/site/python3.6/symengine
    running install
    running build
    running build_ext
    Re-run cmake no build system arguments
    -- The C compiler identification is GNU 9.2.0
    -- The CXX compiler identification is GNU 9.2.0
    -- Check for working C compiler: /opt/spack/opt/spack/linux-centos7-thunderx2/gcc-8.3.0/gcc-9.2.0-z27yfcjijawmyvugvtm2s5szmyu363m2/bin/gcc
    -- Check for working C compiler: /opt/spack/opt/spack/linux-centos7-thunderx2/gcc-8.3.0/gcc-9.2.0-z27yfcjijawmyvugvtm2s5szmyu363m2/bin/gcc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /opt/spack/opt/spack/linux-centos7-thunderx2/gcc-8.3.0/gcc-9.2.0-z27yfcjijawmyvugvtm2s5szmyu363m2/bin/g++
    -- Check for working CXX compiler: /opt/spack/opt/spack/linux-centos7-thunderx2/gcc-8.3.0/gcc-9.2.0-z27yfcjijawmyvugvtm2s5szmyu363m2/bin/g++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    SymEngine_DIR : /opt/spack/opt/spack/linux-centos7-thunderx2/gcc-9.2.0/symengine-0.6.0-3mixkavsjsdfgrwynridvympplioklgl/lib/cmake/symengine
    SymEngine Version : 0.6.0
    -- Python include path: /opt/spack/opt/spack/linux-centos7-thunderx2/gcc-9.2.0/python-3.6.8-fucqk4xf5x2tlargbkis56jowbhcia3f/include/python3.6m
    -- Python version: 3.6
    -- Python install path: /home/user/softwares/firedrake/arm/gcc-9.2.0/lib/python3.6/site-packages
    -- Found PYTHON: /opt/spack/opt/spack/linux-centos7-thunderx2/gcc-9.2.0/python-3.6.8-fucqk4xf5x2tlargbkis56jowbhcia3f/lib/libpython3.6m.so
    -- Found CYTHON: cython
    CMake Error at cmake/FindCython.cmake:39 (MESSAGE):
      Your Cython version is too old.  Please upgrade Cython.
    Call Stack (most recent call first):
      CMakeLists.txt:17 (find_package)


    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-_lgxsex6/symengine_9f93cc5a62a944b9bfedb44130c20471/build/lib.linux-aarch64-3.6/CMakeFiles/CMakeOutput.log".
    error: error calling cmake
    Running setup.py install for symengine: finished with status 'error'
ERROR: Command errored out with exit status 1: /home/user/softwares/firedrake/arm/gcc-9.2.0/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_lgxsex6/symengine_9f93cc5a62a944b9bfedb44130c20471/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_lgxsex6/symengine_9f93cc5a62a944b9bfedb44130c20471/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kaxwg031/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/softwares/firedrake/arm/gcc-9.2.0/include/site/python3.6/symengine Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/user/softwares/firedrake/arm/gcc-9.2.0/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 826, in install
    req_description=str(self.req),
  File "/home/user/softwares/firedrake/arm/gcc-9.2.0/lib/python3.6/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/softwares/firedrake/arm/gcc-9.2.0/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/home/user/softwares/firedrake/arm/gcc-9.2.0/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/home/user/softwares/firedrake/arm/gcc-9.2.0/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 400, in run
    pycompile=options.compile,
  File "/home/user/softwares/firedrake/arm/gcc-9.2.0/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 88, in install_given_reqs
    pycompile=pycompile,
  File "/home/user/softwares/firedrake/arm/gcc-9.2.0/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 830, in install
    six.reraise(*exc.parent)
  File "/home/user/softwares/firedrake/arm/gcc-9.2.0/lib/python3.6/site-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/home/user/softwares/firedrake/arm/gcc-9.2.0/lib/python3.6/site-packages/pip/_internal/operations/install/legacy.py", line 76, in install
    cwd=unpacked_source_directory,
  File "/home/user/softwares/firedrake/arm/gcc-9.2.0/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 293, in runner
    spinner=spinner,
  File "/home/user/softwares/firedrake/arm/gcc-9.2.0/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 258, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /home/user/softwares/firedrake/arm/gcc-9.2.0/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_lgxsex6/symengine_9f93cc5a62a944b9bfedb44130c20471/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_lgxsex6/symengine_9f93cc5a62a944b9bfedb44130c20471/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kaxwg031/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/softwares/firedrake/arm/gcc-9.2.0/include/site/python3.6/symengine Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-svsuzcwp'
```

Any ideas to what might be the cause are most welcome.
TIA.

**Comment by JDBetteridge** [comment]
Hi @fcannini, we had similar issues getting up and running on Isambard. You may need to try using a more up to date CMake to build symengine. I managed to build a symengine wheel for Python3.8 with an upgraded CMake, so hopefully this fixes the issue for you too. Report back if you have any further issues.

**Comment by fcannini** [comment]
@JDBetteridge Thanks for the tip. Do you know the exact cmake version used on isambard?

**Comment by JDBetteridge** [comment]
It was CMake 3.18.0, which was the latest at the time (I ended up having to build it myself)

**Comment by fcannini** [comment]
Thanks. I'll try this one and report back.

**Comment by fcannini** [comment]
Tried cmake 3.18.0 and 3.19.3,  still the same error but with a twist:

```
 CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.

      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.


    CMake Deprecation Warning at /opt/spack/opt/spack/linux-centos7-thunderx2/gcc-9.2.0/symengine-0.6.0-3mixkavsjsdfgrwynridvympplioklgl/lib/cmake/symengine/SymEngineConfig.cmake:34 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.

      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    Call Stack (most recent call first):
      CMakeLists.txt:5 (find_package)
```
It seems to me that `firedrake-install` is purging `$PATH` before beginning, therefore not finding the newer cmake (which is at the first element of `$PATH`).

**Comment by JDBetteridge** [comment]
The install script _shouldn't_ be overwriting the `PATH` variable, it is possible the the path to CMake has been hard baked into some config file. It looks like you're using the spack package manager, is that how you installed CMake?

**Comment by fcannini** [comment]
@JDBetteridge  Sorry for the delay, notifications by email were disabled somehow :/

Yes, that's how I installed cmake, then loaded its module, which in turn prepended a directory to `$PATH`.

**Comment by fcannini** [comment]
Tried again with the latest `firedrake-install` in master, now the error is different:
```
ERROR: Could not find a version that satisfies the requirement vtk==9.0.1
ERROR: No matching distribution found for vtk==9.0.1
```

**Comment by JDBetteridge** [comment]
No worries, perhaps I should @fcannini, hopefully that will notify you!

We actually have our own VTK wheels as they tend to lag behind the latest python versions, unfortunately the one I built on Isambard was for Python 3.8 (and you appear to be using Python 3.6). If you can get a Python 3.8 installed I can just upload the wheel somewhere. Or if you want to build your own wheel, it's not too complicated, it just takes a bit of time. If you copy the resultant `.whl` file (in the dist directory) it only has to be done once:

```bash
#!/bin/bash
git clone https://gitlab.kitware.com/vtk/vtk.git
cd vtk
git checkout tags/v9.0.1 -b v9.0.1
cd ..

mkdir vtk_build
cd vtk_build
cmake -GNinja -DVTK_WHEEL_BUILD=ON -DVTK_PYTHON_VERSION=3 -DVTK_WRAP_PYTHON=ON ../vtk
ninja

#cmake -G"Unix Makefiles" -DVTK_WHEEL_BUILD=ON -DVTK_PYTHON_VERSION=3 -DVTK_WRAP_PYTHON=ON ../vtk
#make

python setup.py bdist_wheel
```
If you don't have Ninja available you can try the commented out lines, which uses make instead.

Then you can install that wheel into the Firedrake virtual env you have already made and run `firedrake-update`.
Or if you're installing from scratch you can use `firedrake-install --pip-install=/path/to/your/vtk.whl`

**Comment by fcannini** [comment]
Tried installing from scratch and this happened:
`ERROR: vtk-9.0.1-cp38-cp38-linux_aarch64.whl is not a supported wheel on this platform.`

Mind you that it's using a fairly recent pip: 20.2

**Comment by JDBetteridge** [comment]
I think we need to fix what Python version we are trying to solve the problem for. In your first message you were using Python 3.6 (I deduced this from the back trace). In your latest message you built the wheel for Python 3.8.

It should be the case that VTK builds a wheel for whatever Python (3) is on the `PATH`, this may just be a case of changing the module you are loading, or the Python you are installing. I would recommend Python 3.8 over Python 3.6.

**Comment by JDBetteridge** [comment]
Closing due to inactivity (see [policy](https://github.com/firedrakeproject/firedrake/wiki/Closing-Installation-Issues) for more info)
