### ISSUE TITLE
Firedrake Installation failed at PETSc on mac Catalina 

### ISSUE THREAD

**Issue by rajbrohit** [firedrakeproject/firedrake#1967]
Hi,

I am installing Firedrake. I guess there is python conflict because of which it is repeatedly failing at the following PETSc installation step.

Details:

```
Successfully updated submodules.
Installing petsc/
Downloading Eigen from 'https://github.com/eigenteam/eigen-git-mirror/archive/3.3.3.tar.gz' to 'eigen-3.3.3.tgz'
Checking Eigen tarball integrity
Eigen tarball hash valid
Depending on your platform, PETSc may take an hour or more to build!
Traceback (most recent call last):
File "firedrake-install", line 1555, in <module>
install("petsc/")
File "firedrake-install", line 834, in install
build_and_install_petsc()
File "firedrake-install", line 960, in build_and_install_petsc
check_call([python, "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + list(petsc_options))
File "firedrake-install", line 615, in check_call
log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/brohit/FireDrake/firedrake/bin/python', './configure', 'PETSC_DIR=/Users/brohit/FireDrake/firedrake/src/petsc', 'PETSC_ARCH=default', '--with-shared-libraries=1', '--with-c2html=0', '--with-fortran-bindings=0', '--with-zlib', '--download-suitesparse', '--download-scalapack', '--download-hdf5', '--with-blaslapack-dir=/usr/local/opt/openblas', '--download-hwloc', '--download-ml', '--download-ptscotch', '--download-pastix', '--download-eigen=/Users/brohit/FireDrake/firedrake/src/eigen-3.3.3.tgz ', '--CFLAGS=-I/usr/local/opt/openblas/include -Wno-implicit-function-declaration', '--download-hwloc-configure-arguments=--disable-opencl', '--download-chaco', '--with-debugging=0', '--LDFLAGS=-Wl,-rpath,/usr/local/opt/openblas/lib -L/usr/local/opt/openblas/lib', '--download-hypre', '--download-metis', '--download-netcdf', '--download-pnetcdf', '--download-superlu_dist', '--with-cxx-dialect=C++11', '--download-mpich', '--download-mumps', '--download-mpich-configure-arguments=--disable-opencl']' returned non-zero exit status 1.


Install log saved in /Users/brohit/FireDrake/firedrake-install.log
```

The installation log file is attached below.
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/5889774/firedrake-install.log)

Thanks

**Comment by danshapero** [comment]
The log says that the install script failed to fetch the NetCDF library from both GitHub and from a mirror that the PETSc developers maintain. I'm able to download it from both locations on my machine. This could be a silly suggestion, but is it possible your internet connection cut out while the script was running? If that's the case, I'd check your connection, retry, and hope for the best.

**Comment by rajbrohit** [comment]
@danshapero : Thanks a lot. 

I first deleted the directory where the virtual environment was created, made a new directory and installed Firedrake in it. 
It worked! 

Thanks for the help again.

**Comment by danshapero** [comment]
No worries! Good luck and feel free to post issues here or ask in [slack](https://firedrakeproject.org/contact.html) if you encounter more trouble.
