### ISSUE TITLE
Complex types getting into real mode PyOP2 Kernels (can't create a "Real" interpolator)

### ISSUE THREAD

**Issue by ReubenHill** [firedrakeproject/firedrake#2095]
This issue is relevant post-merge of #2059. 

The following script (I call `real_fail.py`) fails when trying to create an interpolator in real-mode firedrake.

```python
from firedrake import *

m = UnitSquareMesh(2, 2)
vm = VertexOnlyMesh(m, [[0.1, 0.2], [0.9, 0.8]])
V = FunctionSpace(m, "Real", 0)
W = FunctionSpace(vm, "DG", 0)
A = Interpolator(TestFunction(V), W)
```

giving the log

```
/Users/rwh10/firedrake/src/firedrake/firedrake/parloops.py:129: LoopyWarning: 'lang_version' was not passed to make_function(). To avoid this warning, pass lang_version=(2018, 2) in this invocation. (Or say 'from loopy.version import LOOPY_USE_LANGUAGE_VERSION_2018_2' in the global scope of the calling frame.)
  knl = loopy.make_function(kernel_domains, instructions, kargs, seq_dependencies=True,
Traceback (most recent call last):
  File "real_fail.py", line 7, in <module>
    A = Interpolator(TestFunction(V), W)
  File "/Users/rwh10/firedrake/src/firedrake/firedrake/interpolation.py", line 80, in __init__
    self.callable, arguments = make_interpolator(expr, V, subset, access)
  File "/Users/rwh10/firedrake/src/firedrake/firedrake/interpolation.py", line 213, in make_interpolator
    loops.extend(_interpolator(V, tensor, expr, subset, arguments, access))
  File "<decorator-gen-19>", line 2, in _interpolator
  File "/Users/rwh10/firedrake/src/firedrake/firedrake/utils.py", line 73, in wrapper
    return f(*args, **kwargs)
  File "/Users/rwh10/firedrake/src/firedrake/firedrake/interpolation.py", line 294, in _interpolator
    kernel = op2.Kernel(ast, name, requires_zeroed_output_arguments=True)
  File "/Users/rwh10/firedrake/src/PyOP2/pyop2/caching.py", line 178, in __new__
    key = cls._cache_key(*args, **kwargs)
  File "<decorator-gen-14>", line 2, in _cache_key
  File "/Users/rwh10/firedrake/src/PyOP2/pyop2/utils.py", line 133, in wrapper
    return f(*args, **kwargs)
  File "/Users/rwh10/firedrake/src/PyOP2/pyop2/base.py", line 3337, in _cache_key
    code.update_persistent_hash(key_hash, LoopyKeyBuilder())
  File "/Users/rwh10/firedrake/src/loopy/loopy/tools.py", line 46, in update_persistent_hash
    key_builder.rec(key_hash, getattr(obj, field_name))
  File "/Users/rwh10/firedrake/lib/python3.8/site-packages/pytools/persistent_dict.py", line 239, in rec
    method(inner_key_hash, key)
  File "/Users/rwh10/firedrake/src/loopy/loopy/tools.py", line 86, in update_for_dict
    unordered_hash(
  File "/Users/rwh10/firedrake/lib/python3.8/site-packages/pytools/__init__.py", line 2679, in unordered_hash
    for i in iterable:
  File "/Users/rwh10/firedrake/src/loopy/loopy/tools.py", line 88, in <genexpr>
    (self.rec(self.new_hash(), (k, v)).digest()
  File "/Users/rwh10/firedrake/lib/python3.8/site-packages/pytools/persistent_dict.py", line 239, in rec
    method(inner_key_hash, key)
  File "/Users/rwh10/firedrake/lib/python3.8/site-packages/pytools/persistent_dict.py", line 292, in update_for_tuple
    self.rec(key_hash, obj_i)
  File "/Users/rwh10/firedrake/lib/python3.8/site-packages/pytools/persistent_dict.py", line 221, in rec
    method(inner_key_hash, self)
  File "/Users/rwh10/firedrake/src/loopy/loopy/tools.py", line 46, in update_persistent_hash
    key_builder.rec(key_hash, getattr(obj, field_name))
  File "/Users/rwh10/firedrake/lib/python3.8/site-packages/pytools/persistent_dict.py", line 221, in rec
    method(inner_key_hash, self)
  File "/Users/rwh10/firedrake/src/loopy/loopy/tools.py", line 46, in update_persistent_hash
    key_builder.rec(key_hash, getattr(obj, field_name))
  File "/Users/rwh10/firedrake/lib/python3.8/site-packages/pytools/persistent_dict.py", line 239, in rec
    method(inner_key_hash, key)
  File "/Users/rwh10/firedrake/src/loopy/loopy/tools.py", line 86, in update_for_dict
    unordered_hash(
  File "/Users/rwh10/firedrake/lib/python3.8/site-packages/pytools/__init__.py", line 2679, in unordered_hash
    for i in iterable:
  File "/Users/rwh10/firedrake/src/loopy/loopy/tools.py", line 88, in <genexpr>
    (self.rec(self.new_hash(), (k, v)).digest()
  File "/Users/rwh10/firedrake/lib/python3.8/site-packages/pytools/persistent_dict.py", line 239, in rec
    method(inner_key_hash, key)
  File "/Users/rwh10/firedrake/lib/python3.8/site-packages/pytools/persistent_dict.py", line 292, in update_for_tuple
    self.rec(key_hash, obj_i)
  File "/Users/rwh10/firedrake/lib/python3.8/site-packages/pytools/persistent_dict.py", line 221, in rec
    method(inner_key_hash, self)
  File "/Users/rwh10/firedrake/src/loopy/loopy/kernel/data.py", line 812, in update_persistent_hash
    key_builder.rec(key_hash, initializer)
  File "/Users/rwh10/firedrake/lib/python3.8/site-packages/pytools/persistent_dict.py", line 239, in rec
    method(inner_key_hash, key)
  File "/Users/rwh10/firedrake/lib/python3.8/site-packages/pytools/persistent_dict.py", line 292, in update_for_tuple
    self.rec(key_hash, obj_i)
  File "/Users/rwh10/firedrake/lib/python3.8/site-packages/pytools/persistent_dict.py", line 239, in rec
    method(inner_key_hash, key)
  File "/Users/rwh10/firedrake/lib/python3.8/site-packages/pytools/persistent_dict.py", line 292, in update_for_tuple
    self.rec(key_hash, obj_i)
  File "/Users/rwh10/firedrake/lib/python3.8/site-packages/pytools/persistent_dict.py", line 243, in rec
    raise TypeError("unsupported type for persistent hash keying: %s"
TypeError: unsupported type for persistent hash keying: <class 'complex'>
```

Replacing the line `A = Interpolator(TestFunction(V), W)` with `w_v = interpolate(Function(V), W)` passes happily enough and tests in #2059 confirm that we get the correct values on `w_v`.

This issue with `TypeError: unsupported type for persistent hash keying: <class 'complex'>` has cropped up on other branches. I therefore do not think this is because of an implementation issue in #2059 but reveals some underlying problem: When attempting to interpolate from RTCF and RTCE with FInAT dual evaluation using #1743  one gets the same error. 

I presume that there's a small mistake left over from the complex sprint somewhere.

**Comment by sv2518** [comment]
Without having done any debugging it would think this looks like a loopy issue. We are using their hashing functionality as you can see in the log in this bit:
> File "/Users/rwh10/firedrake/src/PyOP2/pyop2/base.py", line 3337, in _cache_key
>     code.update_persistent_hash(key_hash, LoopyKeyBuilder())

**Comment by ReubenHill** [comment]
@kaushikcfd any thought on this?

**Comment by ReubenHill** [comment]
TODO - look at the loopy kernel before it gets passed to pyop2
