### ISSUE TITLE
Extruded Mesh SubDomain

### ISSUE THREAD

**Issue by medinaeder** [firedrakeproject/firedrake#2104]
SubDomainData does not work on extruded meshes. 

I haven't done much digging around. I will update the post if I manage to find the solution. 

The following code yields the message a SubsetIndexOutOfBounds Error.  It works on a rectangular mesh. 
```
from firedrake import *
L = 7
t = 2
nx = 25
ny = 8
base = IntervalMesh(nx, L)

mesh = ExtrudedMesh(base, ny, layer_height=t/ny, extrusion_type='uniform')
#mesh = RectangleMesh(nx,ny, L, t)
x = SpatialCoordinate(mesh)

#c = lt(abs(x[0]-3.5), 1.0)

sd = SubDomainData(x[0]<3.5)
V = FunctionSpace(mesh, "CG", 1)
u = Function(V)
v = TestFunction(V)
du = TrialFunction(V)
a = inner(du, v)*dx
l = 20*v*dx(subdomain_data = sd)

solve(a==l, u) 
File("temp/results.pvd").write(u)
```

```
/home/e/Software/firedrake/firedrake/src/firedrake/firedrake/extrusion_utils.py:117: LoopyWarning: 'lang_version' was not passed to make_function(). To avoid this warning, pass lang_version=(2018, 2) in this invocation. (Or say 'from loopy.version import LOOPY_USE_LANGUAGE_VERSION_2018_2' in the global scope of the calling frame.)
  ast = lp.make_function(domains, instructions, data, name=name, target=lp.CTarget(),
Traceback (most recent call last):
  File "subds.py", line 14, in <module>
    sd = SubDomainData(x[0]<3.5)
  File "/home/e/Software/firedrake/firedrake/src/firedrake/firedrake/mesh.py", line 2139, in SubDomainData
    return op2.Subset(m.cell_set, indices)
  File "<decorator-gen-3>", line 2, in __init__
  File "/home/e/Software/firedrake/firedrake/src/PyOP2/pyop2/utils.py", line 133, in wrapper
    return f(*args, **kwargs)
  File "/home/e/Software/firedrake/firedrake/src/PyOP2/pyop2/base.py", line 716, in __init__
    raise SubsetIndexOutOfBounds(
pyop2.exceptions.SubsetIndexOutOfBounds: Out of bounds indices in Subset construction: [0, 95) not [0, 25)

```

**Comment by wence-** [comment]
You'll only be able to select a subset of columns this way. Is that what you want? If so, the easiest way to do that is to build your mesh and apply markers to the cells. Then you can just do `dx(2)` (say).

Otherwise you have to do this:

```
mesh = ExtrudedMesh(...)
base = mesh._base_mesh
x = SpatialCoordinate(base)
subset = SubdomainData(x[0] < 3.5)
indices = subset.indices

sd = op2.Subset(mesh.cell_set, indices)

...*dx(subdomain_data=sd)
```

Note that this support for subdomain_data is very incomplete so I advocate marking your mesh directly.
