### ISSUE TITLE
Install on mac

### ISSUE THREAD

**Issue by bensworth** [firedrakeproject/firedrake#2109]
I'm trying to install Firedrake on a mac; I had some Petsc issues a few months back and put it aside and tried again today, but was still not successful. Conda is off, brew is on and working, Python 3.9.4 installed through Pip. I made it through pestsc, but got stuck on libsupermesh:

```
Failed to clone libsupermesh using ssh, falling back to https.
Successfully cloned repository libsupermesh.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Traceback (most recent call last):
  File "/Users/southworth/Software/firedrake-install", line 1611, in <module>
    build_and_install_libsupermesh()
  File "/Users/southworth/Software/firedrake-install", line 1064, in build_and_install_libsupermesh
    check_call(["make"])
  File "/Users/southworth/Software/firedrake-install", line 523, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
```
Unfortunately, I accidentally reran the install script, and it overwrote my output log.

1. Suggestions on what is going on here?
2. Is it possible to pick up where the install stopped to try and "fix" the install? Petsc and the rest of the packages took 3 hours to complete, but when I try to run it again with verbose to see what went wrong here, I get the error
```
Specified venv '/Users/southworth/Software/firedrake' already exists
Can't install into existing venv '/Users/southworth/Software/firedrake'
```
Would rather not have to rerun through the Petsc install every time I try to fix this..

UPDATE: I renamed my install script firedrake-update, sourced the environment, and ran update. Oddly enough, when running update, it printed:
```
Installing libsupermesh
Updating the git repository for libsupermesh
No need to rebuild libsupermesh
```
Unfortunately, the installation still failed and it appears to be due to libsupermesh:
```
Cleaning firedrake
Installing firedrake/
Traceback (most recent call last):
  File "/Users/southworth/Software/firedrake/src/../bin/firedrake-update", line 1770, in <module>
    install(p+"/")
  File "/Users/southworth/Software/firedrake/src/../bin/firedrake-update", line 859, in install
    run_pip_install(["-e", package])
  File "/Users/southworth/Software/firedrake/src/../bin/firedrake-update", line 788, in run_pip_install
    check_call(pipinstall + pipargs)
  File "/Users/southworth/Software/firedrake/src/../bin/firedrake-update", line 523, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/southworth/Software/firedrake/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,islpy,numpy,scipy', '--no-deps', '-vvv', '-e', 'firedrake/']' returned non-zero exit status 1.
```
And the install log says:
```
    /Users/southworth/Software/firedrake/src/petsc/default/bin/mpicc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -L/Users/southworth/Software/firedrake/src/petsc/default/lib -I/Users/southworth/Software/firedrake/src/petsc/default/include -I/Users/southworth/Software/firedrake/lib/python3.9/site-packages/numpy/core/include -I/Users/southworth/Software/firedrake/lib/python3.9/site-packages/petsc4py/include -I/Users/southworth/Software/firedrake/src/petsc/include -I/Users/southworth/Software/firedrake/src/petsc/default/include -I/Users/southworth/Software/firedrake/include -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c firedrake/cython/supermeshimpl.c -o build/temp.macosx-10.15-x86_64-3.9/firedrake/cython/supermeshimpl.o
    In file included from /Users/southworth/Software/firedrake/lib/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1944,
                     from /Users/southworth/Software/firedrake/lib/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /Users/southworth/Software/firedrake/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from firedrake/cython/supermeshimpl.c:612:
    /Users/southworth/Software/firedrake/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
       17 | #warning "Using deprecated NumPy API, disable it with " \
          |  ^~~~~~~
    firedrake/cython/supermeshimpl.c:635:10: fatal error: libsupermesh-c.h: No such file or directory
      635 | #include "libsupermesh-c.h"
          |          ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command '/Users/southworth/Software/firedrake/src/petsc/default/bin/mpicc' failed with exit code 1
ERROR: Command errored out with exit status 1: /Users/southworth/Software/firedrake/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/southworth/Software/firedrake/src/firedrake/setup.py'"'"'; __file__='"'"'/Users/southworth/Software/firedrake/src/firedrake/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/Users/southworth/Software/firedrake/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/Users/southworth/Software/firedrake/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/Users/southworth/Software/firedrake/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 393, in run
    installed = install_given_reqs(
  File "/Users/southworth/Software/firedrake/lib/python3.9/site-packages/pip/_internal/req/__init__.py", line 77, in install_given_reqs
    requirement.install(
  File "/Users/southworth/Software/firedrake/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 777, in install
    install_editable_legacy(
  File "/Users/southworth/Software/firedrake/lib/python3.9/site-packages/pip/_internal/operations/install/editable_legacy.py", line 44, in install_editable
    call_subprocess(
  File "/Users/southworth/Software/firedrake/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 244, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /Users/southworth/Software/firedrake/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/southworth/Software/firedrake/src/firedrake/setup.py'"'"'; __file__='"'"'/Users/southworth/Software/firedrake/src/firedrake/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by danshapero** [comment]
Can you upload your configure.log and make.log from the failed PETSc installation? There are instructions for how to find those files [here](https://firedrakeproject.org/download.html#debugging-install-problems).

**Comment by wence-** [comment]
> 2\. Is it possible to pick up where the install stopped to try and "fix" the install? Petsc and the rest of the packages took 3 hours to complete, but when I try to run it again with verbose to see what went wrong here, I get the error

Depending on when things finish, doing what you did (run `firedrake-update`) can work. I tend to build PETSc separately and then use `firedrake-install --honour-petsc-dir` (use `firedrake-install --show-petsc-configure-options` to see how we build PETSc).

The issue with libsupermesh not being built is because our tracking of if things need updating is very incomplete. You can fake `firedrake-update` into figuring things out by:
```
cd firedrake/src/libsupermesh
git reset --hard HEAD~
firedrake-update
```

I imagine that this will fail, but hopefully we will see some useful output from the `firedrake-update.log` that failed.

**Comment by bensworth** [comment]
Thanks guys; I did the libsupermesh reset. Attached are the three log files. I also tried to go in and build it manually. The error seems to be in compiling libsupermesh:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/sys/_pthread/_pthread_types.h:34:1: error: C++ style comments are not allowed in ISO C90
   34 | // pthread opaque structures
      | ^

```
Looks like cmake is using ISO C90 flags to compile libsupermesh, but some of the mac SDK package is not compatible? Is there a way around this?

[firedrake-update.log](https://github.com/firedrakeproject/firedrake/files/6656793/firedrake-update.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/6656796/configure.log)
[make.log](https://github.com/firedrakeproject/firedrake/files/6656797/make.log)

**Comment by bensworth** [comment]
Okay, libsupermesh was sort of fixed by changing the C-standard in the CMakeLists (currently a PR here https://bitbucket.org/libsupermesh/libsupermesh/pull-requests/7). It compiles anyways. I now make it to the hypothetically final step of installing firedrake and fail there. Attached are the logs; it seems related to petsc and libsupermesh:
```
    firedrake/cython/supermeshimpl.c:635:10: fatal error: libsupermesh-c.h: No such file or directory
      635 | #include "libsupermesh-c.h"
          |          ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command '/Users/southworth/Software/firedrake/src/petsc/default/bin/mpicc' failed with exit code 1
```
That file does exist in `src/libsupermesh/include/libsupermesh-c.h`, so something is not linking correctly.

[configure.log](https://github.com/firedrakeproject/firedrake/files/6657036/configure.log)
[firedrake-update.log](https://github.com/firedrakeproject/firedrake/files/6657037/firedrake-update.log)
[make.log](https://github.com/firedrakeproject/firedrake/files/6657038/make.log)

**Comment by wence-** [comment]
@bensworth if I interpret things correctly, you did manage to fix this?

**Comment by bensworth** [comment]
Yes, the issue was libsupermesh not compiling with the C90 ISO using my compiler, and the flag is hardcoded into their build script. Be changing this flag in the libsupermesh Cmakelists and modifying the firedrake build script so that it doesn't reset my changes to the libsupermesh repo, the build went fine and seems to run.
