### ISSUE TITLE
"no-package-manager" is not hono[u]red

### ISSUE THREAD

**Issue by VictorEijkhout** [firedrakeproject/firedrake#2319]
```
Running firedrake-install --no-package-manager --honour-pythonpath --honour-petsc-dir
Traceback (most recent call last):
  File "firedrake-install", line 1438, in <module>
    check_call(["brew", "--version"])
  File "firedrake-install", line 543, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'brew'
```

**Comment by dham** [comment]
On Mac we have a hard dependency on Homebrew, though I concede that this error could be clearer. What passing `--no-package-manager` will do on Mac is tell brew not to install packages.

**Comment by VictorEijkhout** [comment]
Ok, installed brew and now I'm getting pretty far in. Let's consider this closed.
