### ISSUE TITLE
h5py installation issue

### ISSUE THREAD

**Issue by VictorEijkhout** [firedrakeproject/firedrake#2321]
```
Installing h5py/
Traceback (most recent call last):
  File "firedrake-install", line 1668, in <module>
    build_and_install_h5py()
  File "firedrake-install", line 1079, in build_and_install_h5py
    install("h5py/")
  File "firedrake-install", line 896, in install
    run_pip_install(["--no-build-isolation", package])
  File "firedrake-install", line 831, in run_pip_install
    check_call(pipinstall + pipargs)
  File "firedrake-install", line 543, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/eijkhout/Installation/firedrake/firedrake/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,islpy,numpy', '-vvv', '--no-build-isolation', 'h5py/']' returned non-zero exit status 1.
```

The log ends in:

```
  running build_ext
  Loading library to get version: libhdf5.dylib
  error: Unable to load dependency HDF5, make sure HDF5 is installed properly
  error: dlopen(libhdf5.dylib, 6): image not found
  Building wheel for h5py (pyproject.toml): finished with status 'error'
  ERROR: Failed building wheel for h5py
Failed to build h5py
ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "/Users/eijkhout/Installation/firedrake/firedrake/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/eijkhout/Installation/firedrake/firedrake/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/Users/eijkhout/Installation/firedrake/firedrake/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 374, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for h5py, which is required to install pyproject.toml-based projects
Removed build tracker: '/private/var/folders/zw/l0plykjn5gjfb1c7w37qztth0000gn/T/pip-req-tracker-hu3hojgu'
```

Whole log attached for good measure.
[firelog.zip](https://github.com/firedrakeproject/firedrake/files/7942705/firelog.zip)

**Comment by wence-** [comment]
I see you built with `--honour-petsc-dir`. Our autodetection of the HDF5 library is not great. At present our solution to compiled libraries that are not "basic" is "PETSc compiled them for us, so we can find them in $PETSC_DIR/$PETSC_ARCH/...". My guess here is that your PETSc was not built with `--download-hdf5` (you might have used `--with-hdf5` but I think our sniffing is not good enough).

If you have an HDF5 lying around and want to use it, run `HDF5_DIR=/path/to/hdf5 firedrake-install` (such that `/path/to/hdf5/lib` contains `libhdf5` and /path/to/hdf5/include` contains the headers).

@JDBetteridge our errors could be much better here!

Longer term we want a more robust solution building on package managers, but a combination of funding and lack of anything being perfect has meant that to date we have this somewhat bespoke solution.

**Comment by JDBetteridge** [comment]
I think Koki implemented some of the new HDF5 detection stuff:
https://github.com/firedrakeproject/firedrake/blob/master/scripts/firedrake-install#L655

To get a successful install I think you need to set `PETSC_CONFIGURE_OPTIONS="--with-hdf5-dir=$HDF5_DIR"`, even if you have built your own PETSc.

However, I agree this is confusing and the error message needs to be improved (amongst other things that need to be cleaned up in the install script!).

**Comment by wence-** [comment]
> To get a successful install I think you need to set `PETSC_CONFIGURE_OPTIONS="--with-hdf5-dir=$HDF5_DIR"`, even if you have built your own PETSc.

That's not how I read the code. That function `get_petsc_options` is never called with `--honour-petsc-dir` provided.

But HDF5 is found to link h5py against here:

https://github.com/firedrakeproject/firedrake/blob/1fafb01f15f817bece2cbabddd1367b2db7bc151/scripts/firedrake-install#L1068

**Comment by JDBetteridge** [comment]
You're quite correct, the block of code has been moved since the last time I was running the install script against a prebuilt HDF5. Setting HDF5_DIR makes more sense anyway.

We should document this on the install page.

**Comment by wence-** [comment]
```
-- Check for working Fortran compiler: /Users/eijkhout/Installation/petsc/petsc-3.16.1/macx-clang-hdf5-debug/bin/mpif90
-- Check for working Fortran compiler: /Users/eijkhout/Installation/petsc/petsc-3.16.1/macx-clang-hdf5-debug/bin/mpif90 - broken
CMake Error at /opt/local/share/cmake-3.22/Modules/CMakeTestFortranCompiler.cmake:61 (message):
  The Fortran compiler

    "/Users/eijkhout/Installation/petsc/petsc-3.16.1/macx-clang-hdf5-debug/bin/mpif90"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/eijkhout/Installation/firedrake/firedrake/src/libsupermesh/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/opt/local/bin/gmake -f Makefile cmTC_c1d9a/fast && gmake[1]: Entering directory '/Users/eijkhout/Installation/firedrake/firedrake/src/libsupermesh/build/CMakeFiles/CMakeTmp'
    /opt/local/bin/gmake  -f CMakeFiles/cmTC_c1d9a.dir/build.make CMakeFiles/cmTC_c1d9a.dir/build
    gmake[2]: Entering directory '/Users/eijkhout/Installation/firedrake/firedrake/src/libsupermesh/build/CMakeFiles/CMakeTmp'
    Building Fortran object CMakeFiles/cmTC_c1d9a.dir/testFortranCompiler.f.o
    /Users/eijkhout/Installation/petsc/petsc-3.16.1/macx-clang-hdf5-debug/bin/mpif90   -fallow-argument-mismatch  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -mmacosx-version-min=11.6 -c /Users/eijkhout/Installation/firedrake/firedrake/src/libsupermesh/build/CMakeFiles/CMakeTmp/testFortranCompiler.f -o CMakeFiles/cmTC_c1d9a.dir/testFortranCompiler.f.o
    gfortran: error: unrecognized command line option '-fallow-argument-mismatch'; did you mean '-Wno-argument-mismatch'?
    gmake[2]: *** [CMakeFiles/cmTC_c1d9a.dir/build.make:78: CMakeFiles/cmTC_c1d9a.dir/testFortranCompiler.f.o] Error 1
    gmake[2]: Leaving directory '/Users/eijkhout/Installation/firedrake/firedrake/src/libsupermesh/build/CMakeFiles/CMakeTmp'
    gmake[1]: *** [Makefile:127: cmTC_c1d9a/fast] Error 2
    gmake[1]: Leaving directory '/Users/eijkhout/Installation/firedrake/firedrake/src/libsupermesh/build/CMakeFiles/CMakeTmp'
    
```

On MacOS, we probably assume that homebrew is providing gfortran (and so it's probably gfortran 10 or 11) which barfs building when building old fortran libraries (like the mpif90 module bindings) that have argument mismatches. So we send in `-fallow-argument-mismatch` in the libsupermesh build. But your fortran compiler doesn't like that.

The relevant part of the `CMakeLists.txt` in libsupermesh does:
```
  if(CMAKE_Fortran_COMPILER_ID MATCHES "GNU")
    set(CMAKE_Fortran_FLAGS "-ffree-line-length-none -pipe -std=f2008")
    if(CMAKE_Fortran_COMPILER_VERSION VERSION_GREATER_EQUAL "10")
      set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -fallow-argument-mismatch")
    endif()
```
So it's meant to only add the flag for gfortran versions that have it. But I have to say that cmake is a closed book to me.

What does `gfortran --version` say along with 

```
/Users/eijkhout/Installation/petsc/petsc-3.16.1/macx-clang-hdf5-debug/bin/mpif90 -show
/Users/eijkhout/Installation/petsc/petsc-3.16.1/macx-clang-hdf5-debug/bin/mpif90 --version
```

**Comment by VictorEijkhout** [comment]
> /Users/eijkhout/Installation/petsc/petsc-3.16.1/macx-clang-hdf5-debug/bin/mpif90 -show
> /Users/eijkhout/Installation/petsc/petsc-3.16.1/macx-clang-hdf5-debug/bin/mpif90 --version

```
[eijkhout/Software/firedrake 1069] /Users/eijkhout/Installation/petsc/petsc-3.16.1/macx-clang-hdf5-debug/bin/mpif90 -show
gfortran-mp-8 -m64 -fPIC -g -O0 -Wl,-flat_namespace -Wl,-commons,use_dylibs -I/Users/eijkhout/Installation/petsc/petsc-3.16.1/macx-clang-hdf5-debug/include -I/Users/eijkhout/Installation/petsc/petsc-3.16.1/macx-clang-hdf5-debug/include -L/Users/eijkhout/Installation/petsc/petsc-3.16.1/macx-clang-hdf5-debug/lib -lmpifort -lmpi -lpmpi


[eijkhout/Software/firedrake 1071] /Users/eijkhout/Installation/petsc/petsc-3.16.1/macx-clang-hdf5-debug/bin/mpif90 --version
GNU Fortran (MacPorts gcc8 8.5.0_1) 8.5.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I'll spare you having to unpack the log file:

```
    Run Build Command(s):/opt/local/bin/gmake -f Makefile cmTC_67c2c/fast && gmake[1]: Entering directory '/Users/eijkhout/Installation/firedrake/firedrake/src/libsupermesh/build/CMakeFiles/CMakeTmp'
    /opt/local/bin/gmake  -f CMakeFiles/cmTC_67c2c.dir/build.make CMakeFiles/cmTC_67c2c.dir/build    gmake[2]: Entering directory '/Users/eijkhout/Installation/firedrake/firedrake/src/libsupermesh/build/CMakeFiles/CMakeTmp'
    Building Fortran object CMakeFiles/cmTC_67c2c.dir/testFortranCompiler.f.o
    /Users/eijkhout/Installation/petsc/petsc-3.16.1/macx-clang-hdf5-debug/bin/mpif90   -fallow-argument-mismatch  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -mmacosx-version-min=11.6 -c /Users/eijkhout/Installation/firedrake/firedrake/src/libsupermesh/build/CMakeFiles/CMakeTmp/testFortranCompiler.f -o CMakeFiles/cmTC_67c2c.dir/testFortranCompiler.f.o
    gfortran-mp-8: error: unrecognized command line option '-fallow-argument-mismatch'; did you mean '-Wno-argument-mismatch'?
```

Is my `gfortran` older or newer than the one from homebrew?

**Comment by wence-** [comment]
Pretty sure 8.5.0 is less than 10. So what I don't understand is why cmake is determining the opposite.

My cmake-fu is pretty weak, so I actually don't even know how to printf debug this.

**Comment by VictorEijkhout** [comment]
Didn't you write the cmake script?

I'm getting ever more confirmed in my decision to stick with ordinary good old Make....

**Comment by VictorEijkhout** [comment]
And I get one line further every day....

Actually, I'm now on a Linux box.

```
  error: command '/home1/apps/intel19/impi19_0/petsc/3.16/clx/bin/mpicc' failed: No such file or directory: '/home1/apps/intel19/impi19_0/petsc/3.16/clx/bin/mpicc'
```

That's because PETSc only creates an `mpicc` in that location if it uses its own downloaded mpich. If you use an external MPI it doesn't. But I see that you have the `--mpicc` and such flags for that.

Anyway:

```
Building wheels for collected packages: petsc4py
  Created temporary directory: /tmp/pip-wheel-_v29ulny
  Building wheel for petsc4py (setup.py): started
  Destination directory: /tmp/pip-wheel-_v29ulny
  Running command /work2/00434/eijkhout/firedrake/firedrake/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home1/apps/intel19/impi19_0/petsc/3.16/src/binding/pets
c4py/setup.py'"'"'; __file__='"'"'/home1/apps/intel19/impi19_0/petsc/3.16/src/binding/petsc4py/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else
 io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pi
p-wheel-_v29ulny
  running bdist_wheel
  running build
  running build_src
  running build_py
  creating build/lib.linux-x86_64-3.7
  error: could not create 'build/lib.linux-x86_64-3.7': Permission denied
```

Where are you creating this `build` directory? How can I make sure that  nothing gets built outside my account? So I'd prefer it if you didnt' write in `/tmp` even.

**Comment by wence-** [comment]
>  Where are you creating this build directory? How can I make sure that nothing gets built outside my account? So I'd prefer it if you didnt' write in /tmp even.

This appears to be a recent change to how pip/setuptools installs packages (previously it would copy them into a temporary directory), now it builds "in-place". But of course you don't have permissions to build in-place in the PETSc source tree (because that's a central package). This is #2314 which I think @JDBetteridge was working on.

To additionally avoid never writing to /tmp, I think you're going to have to set `TMPDIR` to a scratch directory in $HOME (make sure it exists, otherwise python falls back to /tmp).

Thanks for your patience, we're in a phase where a bunch of package updates that we have been relying on providing particular behaviour have changed, and we haven't had time to adapt yet.

**Comment by VictorEijkhout** [comment]
```
2022-01-28 13:03:17,529 DEBUG  *** Current environment (output of 'env') ***
2022-01-28 13:03:17,529 DEBUG  Running command 'env'
2022-01-28 13:03:17,533 DEBUG  TMPDIR=/work/00434/eijkhout/firedrake/build-git
HDF5_DIR=/opt/apps/intel19/impi19_0/phdf5/1.10.4/x86_64
```


but still:

```
Created temporary directory: /work2/00434/eijkhout/firedrake/build-git/pip-unpack-a11y1map
Building wheels for collected packages: petsc4py
  Created temporary directory: /work2/00434/eijkhout/firedrake/build-git/pip-wheel-8ic3wv0k
  Building wheel for petsc4py (setup.py): started
  Destination directory: /work2/00434/eijkhout/firedrake/build-git/pip-wheel-8ic3wv0k
  Running command /work2/00434/eijkhout/firedrake/firedrake/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home1/apps/intel19/impi19_0/petsc/3.16/src/binding/pets
c4py/setup.py'"'"'; __file__='"'"'/home1/apps/intel19/impi19_0/petsc/3.16/src/binding/petsc4py/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else
 io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /work2/
00434/eijkhout/firedrake/build-git/pip-wheel-8ic3wv0k
  running bdist_wheel
  running build
  running build_src
  running build_py
  creating build/lib.linux-x86_64-3.7
  error: could not create 'build/lib.linux-x86_64-3.7': Permission denied
```

**Comment by wence-** [comment]
Thanks. I think you need a fix from us/setuptools. Previously, if you said `pip install /local/directory`, setuptools would copy to a temporary location and build there. They changed that behaviour recently to _no longer_ copy. 

This naturally assumes that the directory you are trying to install from is writeable by you, which is not the case here.

What we need to do is do that copy step manually to then be able to install. This needs someone to write some code. 

An alternative is to switch up the pip “build backend” that petsc4py uses to one that supports the copying but I don’t know how feasible that is. Python packaging is in rather a state of flux at the moment and I don’t think best practices have been pinned down again yet.

A workaround for now might be `firedrake-install —pip-install ‘pip<21.3’ …` which puts a version of pip in the venv that is old enough. But this is an untested idea.

**Comment by VictorEijkhout** [comment]
Hm. I definitely do not use pip explicitly.

Anyway, is that `pip<21.3` literal sytax? (Minus the smart quotes in your suggestion.) The installed doesn't take it.

**Comment by VictorEijkhout** [comment]
Oh, and 

```
firedrake-install: error: unrecognized arguments: —-pip-install pip<21.3
```

sounds like the whole `--pip-install` option is unknown.

Oh crap. Your suggested option had not only smart quotes but also some unicode type of dash. Might be a good idea to turn that stuff off.

**Comment by wence-** [comment]
> Oh crap. Your suggested option had not only smart quotes but also some unicode type of dash. Might be a good idea to turn that stuff off.

Sorry, phone. Thought I had, but clearly not.

**Comment by VictorEijkhout** [comment]
Anyway, that syntax is apparently accepted, but it doesn't solve the problem.

**Comment by VictorEijkhout** [comment]
Ok, I built a petsc in my own account that includes hdf5 and now the installation actually works. But I shouldn't have to do that. I'm on a cluster where I should use as much as possible the installed system software.

**Comment by VictorEijkhout** [comment]
But even with the activate script I still get

```
ImportError: libhdf5.so.103: cannot open shared object file: No such file or directory
```

which is not the hdf5 that's in petsc:

```
(firedrake) [c206-008 firedrake:7] ls $PETSC_DIR/$PETSC_ARCH/lib
libhdf5.a               libhdf5.so@            libsundials_nvecparallel.a
libhdf5_hl.a            libhdf5.so.200@        libsundials_nvecparallel.la*
libhdf5_hl.la*          libhdf5.so.200.1.0*    libsundials_nvecserial.a
libhdf5_hl.so@          libpetsc.so@           libsundials_nvecserial.la*
libhdf5_hl.so.200@      libpetsc.so.3.16@      petsc/
libhdf5_hl.so.200.0.1*  libpetsc.so.3.16.3*    petsc4py/
libhdf5.la*             libsundials_cvode.a    petsc4py-3.16.3-py3.7.egg-info/
libhdf5.settings        libsundials_cvode.la*  pkgconfig/
(firedrake) [c206-008 firedrake:8] echo !$
echo $PETSC_DIR/$PETSC_ARCH/lib
/work/00434/eijkhout/petsc/petsc-3.16.3/clx-intel-firedrake/lib
```

I think this is the hdf5 that's built into my python.

**Comment by wence-** [comment]
> But I shouldn't have to do that. I'm on a cluster where I should use as much as possible the installed system software.

FWIW, we consider PETSc to be a moving target dependency (rather than something you should rely on the cluster to provide). Not least because we're often not compatible with a release version. However, I agree that it should be easier to build PETSc using system-installed versions of dependent packages.

**Comment by wence-** [comment]
> But even with the activate script I still get
> 
> ```
> ImportError: libhdf5.so.103: cannot open shared object file: No such file or directory
> ```
> 
> which is not the hdf5 that's in petsc:
> 
> ```
> (firedrake) [c206-008 firedrake:7] ls $PETSC_DIR/$PETSC_ARCH/lib
> libhdf5.a               libhdf5.so@            libsundials_nvecparallel.a
> libhdf5_hl.a            libhdf5.so.200@        libsundials_nvecparallel.la*
> libhdf5_hl.la*          libhdf5.so.200.1.0*    libsundials_nvecserial.a
> libhdf5_hl.so@          libpetsc.so@           libsundials_nvecserial.la*
> libhdf5_hl.so.200@      libpetsc.so.3.16@      petsc/
> libhdf5_hl.so.200.0.1*  libpetsc.so.3.16.3*    petsc4py/
> libhdf5.la*             libsundials_cvode.a    petsc4py-3.16.3-py3.7.egg-info/
> libhdf5.settings        libsundials_cvode.la*  pkgconfig/
> (firedrake) [c206-008 firedrake:8] echo !$
> echo $PETSC_DIR/$PETSC_ARCH/lib
> /work/00434/eijkhout/petsc/petsc-3.16.3/clx-intel-firedrake/lib
> ```
> 
> I think this is the hdf5 that's built into my python.

What is `h5py.*.so` linked against (it will live somewhere like `/path/to/firedrake/lib/site-packages/python-3.7/h5py/`) ? Did you still have `HDF5_DIR` defined in your environment when running `firedrake-install`?

I don't know why your python is built with hdf5 support  (I thought python itself didn't care about it).

**Comment by JDBetteridge** [comment]
Closing due to inactivity (see [policy](https://github.com/firedrakeproject/firedrake/wiki/Closing-Installation-Issues) for more info)
