### ISSUE TITLE
Error with Point Evaluation and VertexOnlyMesh

### ISSUE THREAD

**Issue by vabhi6** [firedrakeproject/firedrake#2359]
I am having trouble extracting my results at certain points on my mesh. I understand that there are 2 methods to do this (i) at() function and (ii) VertexOnlyMesh. Both dont work for me. However, the code runs without error and gives proper results until the solve() command.

Here is a minimal example of trying both methods out: 
```
from firedrake import *

from firedrake.mesh import VertexOnlyMesh

import numpy as np

mesh = UnitSquareMesh(10, 10)
V = FunctionSpace(mesh, "CG", 1)
v = TestFunction(V)
u = TrialFunction(V)

a = inner(grad(u), grad(v)) * dx
L = Constant(0) * v * dx

bc1 = DirichletBC(V, 0.0, 1)
bc2 = DirichletBC(V, 1.0, 2)

sol = Function(V)
problem1 = LinearVariationalProblem(a, L, sol, bcs=[bc1, bc2], constant_jacobian=True)
solver1 = LinearVariationalSolver(problem1, solver_parameters={"ksp_type": "cg", "pc_type": "jacobi"})
solver1.solve()
print(sol.dat.data_ro)

vm=0
pe=1
#Test VertexOnlyMesh Generation
num_points = 25
δs = np.linspace(0.0, 1.0, num_points + 1)
X, Y = np.meshgrid(δs, δs)
xs = np.vstack((X.flatten(), Y.flatten())).T
if vm:
    
    point_cloud = VertexOnlyMesh(mesh, xs)

#Test Point Evaluation of Function
if pe:
    crd=[0.5256,0.5051]
    print(sol.at(crd))
```
For the VertexOnlyMesh case (vm=1), I get the following error:
```
Traceback (most recent call last):
  File "debugresults.py", line 38, in <module>
    print(sol.at(crd))
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/.nfs/home/6/venketea/firedrake/firedrake/src/firedrake/firedrake/function.py", line 651, in at
    raise PointNotInDomainError(self.function_space().mesh(), points[i].reshape(-1))
firedrake.function.PointNotInDomainError: domain <Mesh #1> does not contain point [0.5256 0.5051]
```

For the Point Evaluation case (pe=1), I get this error:
```
Traceback (most recent call last):
  File "debugresults.py", line 38, in <module>
    print(sol.at(crd))
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/.nfs/home/6/venketea/firedrake/firedrake/src/firedrake/firedrake/function.py", line 651, in at
    raise PointNotInDomainError(self.function_space().mesh(), points[i].reshape(-1))
firedrake.function.PointNotInDomainError: domain <Mesh #1> does not contain point [0.5256 0.5051]


```

**Comment by vabhi6** [comment]
I ran a code that @ReubenHill has provided in another issue #2224 
```
from firedrake import *
m = UnitSquareMesh(10,10)
coords = [[0.5, 0.5], [0.9, 0.9]]
print(f'Rank {COMM_WORLD.rank}, coord {coords[0]} in cell {m.locate_cell(coords[0])}, coord {coords[1]} in cell {m.locate_cell(coords[1])}')
```
It looks like the locate_cell is not able to locate the cells that these coordinates belong to. Please find below the output:
```
Rank 0, coord [0.5, 0.5] in cell None, coord [0.9, 0.9] in cell None
Rank 1, coord [0.5, 0.5] in cell None, coord [0.9, 0.9] in cell None
Rank 2, coord [0.5, 0.5] in cell None, coord [0.9, 0.9] in cell None
```
Is it possible that there is some firedrake installation problem
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/8128507/firedrake-install.log)

**Comment by wence-** [comment]
Something does seem fishy. Does this at least work:
```python
from firedrake import UnitTriangleMesh
mesh = UnitTriangleMesh()
print(mesh.locate_cell([1/3, 1/3]))
```

?

**Comment by vabhi6** [comment]
The pytest on locate_cell in the regression folder also fails. The output from the pytest is attached here.
[locate_cell.txt](https://github.com/firedrakeproject/firedrake/files/8134606/locate_cell.txt)

**Comment by vabhi6** [comment]
1D evaluation of at() doesnt fail.

**Comment by ksagiyam** [comment]
I have no idea. Lawrence's 2D example is supposed to output `0`.
Maybe you can try in the terminal `export PYOP2_DEBUG=1`, which turns off compiler optimisation, run the 2D example again, and see if anything changes.

**Comment by vabhi6** [comment]
> I have no idea. Lawrence's 2D example is supposed to output `0`. Maybe you can try in the terminal `export PYOP2_DEBUG=1`, which turns off compiler optimisation, run the 2D example again, and see if anything changes.

@ksagiyam Nothing changes. I do not get any additional output also.

**Comment by ksagiyam** [comment]
I made a branch just to get more information. With the firedrake venv activated, could you do 
```
cd /.nfs/home/6/venketea/firedrake/firedrake/src/firedrake
git fetch origin
git checkout ksagiyam/debug_locate_cell
```
, run the above 2D example, and post the output?

**Comment by vabhi6** [comment]
@ksagiyam : The output of the git chekout code is below
```
remote: Enumerating objects: 199, done.
remote: Counting objects: 100% (199/199), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 199 (delta 125), reused 170 (delta 108), pack-reused 0
Receiving objects: 100% (199/199), 90.44 KiB | 0 bytes/s, done.
Resolving deltas: 100% (125/125), completed with 36 local objects.
From https://github.com/firedrakeproject/firedrake
   2217841..d973eac  master     -> origin/master
   28153f7..2c5579b  JDBetteridge/obtain_petsc_features_at_install -> origin/JDBetteridge/obtain_petsc_features_at_install
 * [new branch]      JDBetteridge/purge_distutils -> origin/JDBetteridge/purge_distutils
 * [new branch]      check-loopy-merge -> origin/check-loopy-merge
 * [new branch]      connorjward/test-ufl-group-integrals -> origin/connorjward/test-ufl-group-integrals
 + 23f752a...66ac1f2 jwallwork23/metric-based -> origin/jwallwork23/metric-based  (forced update)
 * [new branch]      ksagiyam/debug_locate_cell -> origin/ksagiyam/debug_locate_cell
 + 46a1084...2e4eda3 ksagiyam/io_hdf5_xdmf -> origin/ksagiyam/io_hdf5_xdmf  (forced update)
 * [new branch]      ksagiyam/only_use_enabled_components -> origin/ksagiyam/only_use_enabled_components
   024f3f4..c31573b  pbrubeck/fdm-element -> origin/pbrubeck/fdm-element
   fdec821..29c1e17  pbrubeck/fdm-redist-mg -> origin/pbrubeck/fdm-redist-mg
   ad2c350..4166408  smaclachlan/ocmh_fixes -> origin/smaclachlan/ocmh_fixes
   fa1577a..7a9574e  smaclachlan/update_opencascade -> origin/smaclachlan/update_opencascade
 * [new branch]      sv/fix-slate-test -> origin/sv/fix-slate-test
 * [new branch]      sv/test-loopy-upstream -> origin/sv/test-loopy-upstream
 * [new branch]      vectorisation-sprint -> origin/vectorisation-sprint
 * [new tag]         Firedrake_20220223.0 -> Firedrake_20220223.0
 * [new tag]         Firedrake_20220223.1 -> Firedrake_20220223.1
Branch ksagiyam/debug_locate_cell set up to track remote branch ksagiyam/debug_locate_cell from origin.
```
Next, I ran the code:
```
from firedrake import UnitTriangleMesh
mesh = UnitTriangleMesh()
cell,X=mesh.locate_cell_and_reference_coordinate([1/3, 1/3])
print(X)
```
and got this output:
```
Traceback (most recent call last):
  File "testtri.py", line 2, in <module>
    mesh = UnitTriangleMesh()
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/.nfs/home/6/venketea/firedrake/firedrake/src/firedrake/firedrake/utility_meshes.py", line 328, in UnitTriangleMesh
    return mesh.Mesh(plex, reorder=False)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/.nfs/home/6/venketea/firedrake/firedrake/src/firedrake/firedrake/mesh.py", line 1856, in Mesh
    distribution_parameters=distribution_parameters)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/.nfs/home/6/venketea/firedrake/firedrake/src/firedrake/firedrake/mesh.py", line 720, in __init__
    plex.distributeSetDefault(False)
AttributeError: 'petsc4py.PETSc.DMPlex' object has no attribute 'distributeSetDefault'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
```
Before I ran the checkout code, I never received an error for ```mesh=UnitTriangleMesh()```

**Comment by ksagiyam** [comment]
It indicates that your firedrake (and PETSc) is not up-to-date. You can update it by running `firedrake-update` on the terminal with firedrake venv active. This will take some time as it will update PETSc.

**Comment by vabhi6** [comment]
@ksagiyam : I had asked my IT support staff to update firedrake in my directory, last week. He had done that and I could also see that some of the changes in the scripts (such as mesh.py) were incorporated in the update. Could you tell me what I should look for to confirm if the update was unsuccessful?

**Comment by ksagiyam** [comment]
To see if the update was successful or not, you can run some tests. Assuming that you are at `src/firedrake`, you can do:
```
pytest tests
```
to run all tests (, which takes a few hours) or:
```
pytest tests/multigrid
```
to only run multigrid tests, say. You can check `src/firedrake/tests` folder to see what tests are available; see also `pytest` documentation (https://docs.pytest.org/en/6.2.x/contents.html).

We updated our PETSc fork 7 days ago, so if you used system PETSc with `--honour-petsc-dir` flag when installing Firedrake, that PETSc needs to be updated manually, and, if you let firedrake install PETSc, `firedrake-update` will automatically update PETSc. Your `firedrake-install.log` indicates that you let firedrake install PETSc. (Note that `distributeSetDefault()` method which your `petsc4py` cannot find was added very recently.)

**Comment by vabhi6** [comment]
@ksagiyam: I am running firedrake-update now and will let you know what is happening

**Comment by vabhi6** [comment]
@ksagiyam I tried the firedrake-update which failed. So I tried 
````
module load gnu/9.3.0 openmpi/4.0.4_gnu9.3
cd ~/firedrake
rm -rf firedrake
curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
(Update the firedrake-install script)
python firedrake-install --with-blas="download" --no-package-manager --minimal-petsc --disable-ssh --mpicc mpicc --mpicxx mpicxx --mpif90 mpif90 --mpiexec mpiexec
```
I get this output:
```
File "firedrake-install", line 1321
    "-L" + os.path.join(*get_petsc_dir(), "lib"),
SyntaxError: only named arguments may follow *expression
```

**Comment by vabhi6** [comment]
> @ksagiyam I tried the firedrake-update which failed. So I tried
> 
> ```
> module load gnu/9.3.0 openmpi/4.0.4_gnu9.3
> cd ~/firedrake
> rm -rf firedrake
> curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
> (Update the firedrake-install script)
> python firedrake-install --with-blas="download" --no-package-manager --minimal-petsc --disable-ssh --mpicc mpicc --mpicxx mpicxx --mpif90 mpif90 --mpiexec mpiexec
> ```
> 
> I get this output:
> 
> ```
> File "firedrake-install", line 1321
>     "-L" + os.path.join(*get_petsc_dir(), "lib"),
> SyntaxError: only named arguments may follow *expression
> ```

I have successfully reverted back to the firedrake installation that was current as of Feb 22nd. I am however not able to run firedrake-update

**Comment by wence-** [comment]
@vabhi6 what is your python version?

@JDBetteridge is this a python 3.8ism?

**Comment by vabhi6** [comment]
> 

@wence- Python 3.8

**Comment by JDBetteridge** [comment]
There shouldn't be any issue for Python 3.8, I have just tried locally with my build of 3.8.12:

```
$ /opt/python/v3.8.12/bin/python3
Python 3.8.12 (tags/v3.8.12:07119dd38c, Nov 24 2021, 15:25:08) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> 
>>> def one_two():
...     return "one", "two"
... 
>>> "-L" + os.path.join(*one_two(), "three")
'-Lone/two/three'
>>> 
```

Things seem to work. I think such functionality has been available since [3.5](https://docs.python.org/3/whatsnew/3.5.html#pep-448-additional-unpacking-generalizations). Let me know if this example fails and we can investigate

**Comment by vabhi6** [comment]
@ksagiyam , @wence- I believe that the problem with the failing pointwise evaluation api could arise if we install firedrake with ```minimal-petsc```. I have one installation with ```minimal-petsc``` that fails with the tests but another one without it that passes.

**Comment by vabhi6** [comment]
> @ksagiyam I tried the firedrake-update which failed. So I tried
> 
> ```
> module load gnu/9.3.0 openmpi/4.0.4_gnu9.3
> cd ~/firedrake
> rm -rf firedrake
> curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
> (Update the firedrake-install script)
> python firedrake-install --with-blas="download" --no-package-manager --minimal-petsc --disable-ssh --mpicc mpicc --mpicxx mpicxx --mpif90 mpif90 --mpiexec mpiexec
> ```
> 
> I get this output:
> 
> ```
> File "firedrake-install", line 1321
>     "-L" + os.path.join(*get_petsc_dir(), "lib"),
> SyntaxError: only named arguments may follow *expression
> ```

Kindly ignore this. It was a mistake on my part
