### ISSUE TITLE
IndexError when using $\R$ space with more then one other space.

### ISSUE THREAD

**Issue by lrtfm** [firedrakeproject/firedrake#2396]
The following code will fail in the latest version of Firedrake.
```
$ cat r_fail.py
#!/usr/bin/env python
# coding: utf-8

# A failing example with $R$

from firedrake import *
from firedrake.petsc import PETSc
import numpy as np

mesh = RectangleMesh(10, 10, 1, 1)

U = VectorFunctionSpace(mesh, 'CG', 2)
Q = FunctionSpace(mesh, 'CG', 1)
R = FunctionSpace(mesh, 'R', 0)
V = MixedFunctionSpace([U, Q, R])

eps = 1e-8

w_, p_, l_water_ = TrialFunctions(V)
v_, q_, m_water_ = TestFunctions(V)

f = as_vector([0, -9.8])

A = 2*inner(sym(grad(w_)), sym(grad(v_)))*dx \
    - inner(p_, div(v_))*dx \
    + inner(div(w_), q_)*dx \
    + eps*inner(p_, q_)*dx
A += dot(w_, f)*m_water_*dx - l_water_*v_[1]*dx
L = dot(f, v_)*dx(domain=mesh)

bc = DirichletBC(V.sub(0), 0., 'on_boundary')

sol = Function(V)
# If we solve homogeneous problem, i.e. L=0, everything is ok
# stokes_problem = LinearVariationalProblem(A, 0, sol, bcs=bc)
stokes_problem = LinearVariationalProblem(A, L, sol, bcs=bc)
stokes_solver = LinearVariationalSolver(stokes_problem, options_prefix='stokes')
stokes_solver.solve()

```
The output information:
```
Traceback (most recent call last):
  File "r_fail.py", line 38, in <module>
    stokes_solver.solve()
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/zzyang/workspace/firedrake-gcc/firedrake-mini-petsc/src/firedrake/firedrake/adjoint/variational_solver.py", line 90, in wrapper
    out = solve(self, **kwargs)
  File "/home/zzyang/workspace/firedrake-gcc/firedrake-mini-petsc/src/firedrake/firedrake/variational_solver.py", line 278, in solve
    self.snes.solve(None, work)
  File "PETSc/SNES.pyx", line 590, in petsc4py.PETSc.SNES.solve
  File "libpetsc4py/libpetsc4py.pyx", line 1548, in libpetsc4py.PCSetUp_Python
  File "/home/zzyang/workspace/firedrake-gcc/firedrake-mini-petsc/src/firedrake/firedrake/preconditioners/base.py", line 125, in setUp
    super().setUp(pc)
  File "/home/zzyang/workspace/firedrake-gcc/firedrake-mini-petsc/src/firedrake/firedrake/preconditioners/base.py", line 45, in setUp
    self.initialize(pc)
  File "/home/zzyang/workspace/firedrake-gcc/firedrake-mini-petsc/src/firedrake/firedrake/preconditioners/assembled.py", line 60, in initialize
    self._assemble_P()
  File "/home/zzyang/workspace/firedrake-gcc/firedrake-mini-petsc/src/firedrake/firedrake/assemble.py", line 394, in assemble
    self._apply_bc(bc)
  File "/home/zzyang/workspace/firedrake-gcc/firedrake-mini-petsc/src/firedrake/firedrake/assemble.py", line 634, in _apply_bc
    self._apply_bcs_mat_real_block(op2tensor, index, j, component, bc.node_set)
  File "/home/zzyang/workspace/firedrake-gcc/firedrake-mini-petsc/src/firedrake/firedrake/assemble.py", line 650, in _apply_bcs_mat_real_block
    dat = op2tensor[i, j].handle.getPythonContext().dat
  File "/home/zzyang/workspace/firedrake-gcc/firedrake-mini-petsc/src/PyOP2/pyop2/types/mat.py", line 819, in __getitem__
    return self.blocks[i][j]
IndexError: list index out of range
```

**Comment by connorjward** [comment]
@ksagiyam this seems related to https://github.com/firedrakeproject/firedrake/commit/d5cb6270cb2af943fa40ae8469ff2ff3c135f0e3.

**Comment by ksagiyam** [comment]
Direct fix would be:
```
bc = DirichletBC(V.sub(0), as_vector([0., 0.]), 'on_boundary')
```
as `V.sub(0)` is a vector function space, but I'd like to double check our implementations around `bc.reconstruct()`.

**Comment by ksagiyam** [comment]
https://github.com/firedrakeproject/firedrake/pull/2398 will hopefully fix your problem. Thanks.
