### ISSUE TITLE
Problem Nonlinear Solver and MixedFunctionSpace

### ISSUE THREAD

**Issue by zhyxue0** [firedrakeproject/firedrake#2410]
I try to solve this nonlinear problem with MixedFunctionSpace
<img src="https://latex.codecogs.com/svg.image?\int_{\Omega}&space;u&space;v&space;dx&space;&plus;&space;\int_{\Omega}&space;\boldsymbol{q}&space;\cdot&space;\boldsymbol{\phi}&space;dx&space;&plus;&space;\int_{\Omega}&space;(u&space;)^{3}&space;v&space;dx&space;=&space;0" title="https://latex.codecogs.com/svg.image?\int_{\Omega} u v dx + \int_{\Omega} \boldsymbol{q} \cdot \boldsymbol{\phi} dx + \int_{\Omega} (u )^{3} v dx = 0" />

```python
from firedrake import *

mesh = UnitSquareMesh(1, 1)
V0 = FunctionSpace(mesh, "DG", 1)
V1 = VectorFunctionSpace(mesh, "DG", 1)

W = MixedFunctionSpace([V0, V1])

v, phi = TestFunctions(W)
w = Function(W)


F = inner(w.sub(0),v)*dx + dot(w.sub(1),phi)*dx + pow(w.sub(0),3)*v*dx


F_problem_w = NonlinearVariationalProblem(F, w)
F_solver_w = NonlinearVariationalSolver(F_problem_w)
F_solver_w.solve()
```

```shell
Traceback (most recent call last):
  File "/home/Code/firedrake_code/Test_1.py", line 16, in <module>
    F_problem_w = NonlinearVariationalProblem(F, w)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/src/pyadjoint/pyadjoint/tape.py", line 46, in wrapper
    return function(*args, **kwargs)
  File "/home/firedrake/src/firedrake/firedrake/adjoint/variational_solver.py", line 16, in wrapper
    init(self, *args, **kwargs)
  File "/home/firedrake/src/firedrake/firedrake/variational_solver.py", line 80, in __init__
    self.J = J or ufl_expr.derivative(F, u)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/src/firedrake/firedrake/ufl_expr.py", line 152, in derivative
    raise ValueError("Taking derivative of form wrt u, but form contains coefficients from u.split()."
ValueError: Taking derivative of form wrt u, but form contains coefficients from u.split().
You probably meant to write split(u) when defining your form.

```

I change the code like this, but still error

```python
from firedrake import *

mesh = UnitSquareMesh(1, 1)
V0 = FunctionSpace(mesh, "DG", 1)
V1 = VectorFunctionSpace(mesh, "DG", 1)

W = MixedFunctionSpace([V0, V1])

v, phi = TestFunctions(W)
u = Function(V0)
q = Function(V1)

F = u*v*dx + dot(q,phi)*dx + pow(u,3)*v*dx

w_solution = Function(W)
F_problem_w = NonlinearVariationalProblem(F, w_solution)
F_solver_w = NonlinearVariationalSolver(F_problem_w)
F_solver_w.solve()
```

```shell
UFL:ERROR Expecting bilinear form.
Traceback (most recent call last):
  File "/home/Code/firedrake_code/Test_1.py", line 17, in <module>
    F_problem_w = NonlinearVariationalProblem(F, w_solution)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/src/pyadjoint/pyadjoint/tape.py", line 46, in wrapper
    return function(*args, **kwargs)
  File "/home/firedrake/src/firedrake/firedrake/adjoint/variational_solver.py", line 27, in wrapper
    self._ad_adj_F = adjoint(dFdu)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/src/firedrake/firedrake/ufl_expr.py", line 252, in adjoint
    return ufl.adjoint(form, reordered_arguments)
  File "/home/firedrake/src/ufl/ufl/formoperators.py", line 135, in adjoint
    return compute_form_adjoint(form, reordered_arguments)
  File "/home/firedrake/src/ufl/ufl/algorithms/formtransformations.py", line 465, in compute_form_adjoint
    error("Expecting bilinear form.")
  File "/home/firedrake/src/ufl/ufl/log.py", line 158, in error
    raise self._exception_type(self._format_raw(*message))
ufl.log.UFLException: Expecting bilinear form.
```
How to solve it ?

**Comment by wence-** [comment]
You should write 

```
w = Function(W)
u, q = split(w)
```

and then continue with the first approach. 

This is a slight subtlety in UFL/Firedrake:

`w.sub(0)` numerically shares data with `w`, but symbolically "forgets" where it came from. So now when the NLVS says `derivative(F, w)` it can't find any reference to `w`. If instead you say `split(w)` the pieces you get are still symbolically related to `w`. 

That is what the first error message is trying to hint at.

**Comment by zhyxue0** [comment]
> You should write
> 
> ```
> w = Function(W)
> u, q = split(w)
> ```
> 
> and then continue with the first approach.
> 
> This is a slight subtlety in UFL/Firedrake:
> 
> `w.sub(0)` numerically shares data with `w`, but symbolically "forgets" where it came from. So now when the NLVS says `derivative(F, w)` it can't find any reference to `w`. If instead you say `split(w)` the pieces you get are still symbolically related to `w`.
> 
> That is what the first error message is trying to hint at.

thanks
