### ISSUE TITLE
Matrix-free does not work for interior facet integrals

### ISSUE THREAD

**Issue by zhyxue0** [firedrakeproject/firedrake#2428]
Since the matrix obtained by LDG  mehod is sparse, I try to use the Matrix-free method to improve the efficiency of the solver and save memory, but it does not work for the interior facet integrals part.

**Code:**
```python
from firedrake import *
import math

Nx = 40
Pk = 0
CFL = 0.01
T = 0.2
Lx = 2*math.pi
Hx = Lx/Nx

mesh = IntervalMesh(Nx, Lx)

V = FunctionSpace(mesh, "DG", Pk)
MixedSpace = V * V
u_trial, q_trial = TrialFunctions(MixedSpace)
v, w = TestFunctions(MixedSpace)

x, = SpatialCoordinate(mesh)

# dt 
dt = CFL * Hx
N_step = math.ceil(T/dt)
dt = T / N_step
dtc = Constant(dt)

t = 0.0
tc = Constant(t)

# Initial value 
u = Function(V)
u = project(sin(x),MixedSpace.sub(0))

# Boundary term
u_bd = Function(V)
u_bd =  project(exp(-tc)*sin(x),MixedSpace.sub(0))


Lap = ( -q_trial*v.dx(0) *dx + q_trial("+")*(v("-") - v("+") )*dS + q_trial*v*ds(2) - q_trial*v*ds(1) )
Qu = ( -u_trial*w.dx(0) *dx + u_trial("-")*(w("-") - w("+") )*dS )


a = u_trial*v*dx - dtc* Lap + q_trial*w*dx - Qu
L = u*v*dx + u_bd*w*ds(2) - u_bd*w*ds(1)


# Matrix-Free
solver_parameters ={"mat_type": "matfree"}
w_solution = Function(MixedSpace)
problem = LinearVariationalProblem(a,L, w_solution)
solver= LinearVariationalSolver(problem, solver_parameters = solver_parameters)

Step = 0
for Step in range(N_step):

    tc.assign(t+dt)

    solver.solve()
    u.assign(w_solution.sub(0))    

    t += dt
    print("t = ", t)


tc.assign(t)
u_exact = project(exp(-tc)*sin(x), MixedSpace.sub(0))
L2_error = norms.errornorm(  u_exact, u, norm_type = "L2")
print("L2 error:", L2_error)
```

**Error:**
```shell
Traceback (most recent call last):
  File "/home/firedrake/src/PyOP2/pyop2/caching.py", line 205, in __new__
    return cls._cache_lookup(key)
  File "/home/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 71, in _cache_lookup
    return cls._cache.get((key, commkey)) or cls._read_from_disk(key, comm)
  File "/home/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 92, in _read_from_disk
    raise KeyError(f"Object with key {key} not found")
KeyError: 'Object with key c98e6578d6cc7e70424ed97e3cbf14b2 not found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Code/firedrake_code/MatrixFree/Test_MatrixFree.py", line 57, in <module>
    solver.solve()
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/src/firedrake/firedrake/adjoint/variational_solver.py", line 90, in wrapper
    out = solve(self, **kwargs)
  File "/home/firedrake/src/firedrake/firedrake/variational_solver.py", line 278, in solve
    self.snes.solve(None, work)
  File "PETSc/SNES.pyx", line 590, in petsc4py.PETSc.SNES.solve
  File "libpetsc4py/libpetsc4py.pyx", line 1176, in libpetsc4py.MatGetDiagonal_Python
  File "/home/firedrake/src/firedrake/firedrake/matrix_free/operators.py", line 180, in getDiagonal
    self._assemble_diagonal()
  File "/home/firedrake/src/firedrake/firedrake/assemble.py", line 388, in assemble
    for parloop in self.parloops:
  File "/home/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/firedrake/src/firedrake/firedrake/assemble.py", line 444, in parloops
    for lknl, gknl in zip(self.local_kernels, self.global_kernels))
  File "/home/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/firedrake/src/firedrake/firedrake/assemble.py", line 421, in local_kernels
    return tsfc_interface.compile_form(self._form, "form", diagonal=self.diagonal,
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 236, in compile_form
    kinfos = TSFCKernel(f, prefix, parameters,
  File "/home/firedrake/src/PyOP2/pyop2/caching.py", line 207, in __new__
    obj = make_obj()
  File "/home/firedrake/src/PyOP2/pyop2/caching.py", line 197, in make_obj
    obj.__init__(*args, **kwargs)
  File "/home/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 138, in __init__
    tree = tsfc_compile_form(form, prefix=name, parameters=parameters,
  File "/home/firedrake/src/tsfc/tsfc/driver.py", line 71, in compile_form
    kernel = compile_integral(integral_data, fd, prefix, parameters, interface=interface, coffee=coffee, diagonal=diagonal)
  File "/home/firedrake/src/tsfc/tsfc/driver.py", line 103, in compile_integral
    raise NotImplementedError("Sorry, we can't assemble the diagonal of a form for interior facet integrals")
NotImplementedError: Sorry, we can't assemble the diagonal of a form for interior facet integrals
```

**Comment by dham** [comment]
This is correct. It's a known limitation and the error message tells you that we just can't do this.

However, for a 1D problem (even for a 2D problem unless it's really, really big) you are very unlikely to beat the default sparse direct solver that we call. Before even attempting to use a different solver, you should build a flame graph and establish whether the solver is really the problem https://firedrakeproject.org/optimising.html#automatic-flame-graph-generation-with-petsc
