### ISSUE TITLE
VertexOnlyMesh not supported for periodic meshes

### ISSUE THREAD

**Issue by rubyturner** [firedrakeproject/firedrake#2429]
Here is an example:

```
from firedrake import *

m = PeriodicUnitSquareMesh(30, 30)
vm = VertexOnlyMesh(m, [[0.5, 0.5]])

 ```
which returns the following error:

<pre>Traceback (most recent call last):
  File &quot;vertexerror.py&quot;, line 4, in &lt;module&gt;
    vm = VertexOnlyMesh(m, [[0.5, 0.5]])
  File &quot;PETSc/Log.pyx&quot;, line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File &quot;PETSc/Log.pyx&quot;, line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File &quot;/home/ruby/firedrake/src/firedrake/firedrake/mesh.py&quot;, line 2106, in VertexOnlyMesh
    raise NotImplementedError(&quot;Meshes made from coordinate fields are not yet supported&quot;)
NotImplementedError: Meshes made from coordinate fields are not yet supported
</pre>

**Comment by dham** [comment]
OK, I have a draft solution to this in #2437. I think it works so please try the `periodic_vertexonlymesh` branch of firedrake and see if that works for you. With the venv active:
```
cd $VIRTUAL_ENV/src/firedrake
git checkout periodic_vertexonlymesh
```

**Comment by rubyturner** [comment]
I am running into an issue when importing firedrake -- I get the following error:

```
Traceback (most recent call last):
  File "adjoint.py", line 4, in <module>
    from firedrake import *
  File "/home/ruby/firedrake/src/firedrake/firedrake/__init__.py", line 72, in <module>
    from firedrake.assemble import *
  File "/home/ruby/firedrake/src/firedrake/firedrake/assemble.py", line 15, in <module>
    from firedrake import (assemble_expressions, extrusion_utils as eutils, matrix, parameters, solving,
  File "/home/ruby/firedrake/src/firedrake/firedrake/assemble_expressions.py", line 209, in <module>
    class Assign(object):
  File "/home/ruby/firedrake/src/firedrake/firedrake/assemble_expressions.py", line 290, in Assign
    def args(self):
  File "/home/ruby/firedrake/src/firedrake/firedrake/utils.py", line 64, in known_pyop2_safe
    from firedrake.parameters import parameters
  File "/home/ruby/firedrake/src/firedrake/firedrake/parameters.py", line 3, in <module>
    from pyop2.configuration import configuration, target as pyop2_target
ImportError: cannot import name 'target' from 'pyop2.configuration' (/home/ruby/firedrake/src/PyOP2/pyop2/configuration.py)

```

**Comment by ReubenHill** [comment]
For reference see also https://github.com/firedrakeproject/firedrake/issues/1791 and https://github.com/firedrakeproject/firedrake/issues/2185.

David's PR is doing the "Quick" solution suggested in #2185.

**Comment by ksagiyam** [comment]
Regarding the error you are getting, your Firedrake and surrounding packages seem old; run `firedrake-update` before using David's branch.
