### ISSUE TITLE
"CalledProcessError" when installing PETSc

### ISSUE THREAD

**Issue by sz9518** [firedrakeproject/firedrake#2442]
[](url
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/8693187/firedrake-install.log)
)

I always meet a calledprocesserror when installing firedrake after wait for a long time in the step of installing PETSc, can anyone help me with this?

Depending on your platform, PETSc may take an hour or more to build!
Installing pip dependencies for COFFEE
Traceback (most recent call last):
  File "/Users/shuchanzhou/firedrake-install", line 1758, in <module>
    pip_requirements(p, compiler_env)
  File "/Users/shuchanzhou/firedrake-install", line 895, in pip_requirements
    run_pip_install(["--no-deps", "-r", "%s/requirements.txt" % package])
  File "/Users/shuchanzhou/firedrake-install", line 864, in run_pip_install
    check_call(pipinstall + pipargs)
  File "/Users/shuchanzhou/firedrake-install", line 543, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/shuchanzhou/firedrake/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,islpy,numpy', '-vvv', '--no-deps', '-r', 'COFFEE/requirements.txt']' returned non-zero exit status 1.

**Comment by danshapero** [comment]
I just hit the same error yesterday and found a workaround. You can still activate the virtual environment even though the install didn't complete successfully. So what you'll do is:

```shell
. </path/to/firedrake venv>/bin/activate
pip install packaging==20.5
firedrake-update
```

The call to `firedrake-update` at the end will complete the installation. Let us know if this works, an actual fix will be pushed in the meantime.

**Comment by sz9518** [comment]
> 
[firedrake-update.log](https://github.com/firedrakeproject/firedrake/files/8693484/firedrake-update.log)

Thank you and I can activate the virtual environment. and when I entered "firedrake-update", a callprocesserror happened again. I cannot actually use firedrake right now even I can activate the virtual environment. I have attached the "firedrake-update.log".


Installing pip dependencies for COFFEE
Traceback (most recent call last):
  File "/Users/shuchanzhou/firedrake/src/../bin/firedrake-update", line 1877, in <module>
    pip_requirements(p, compiler_env)
  File "/Users/shuchanzhou/firedrake/src/../bin/firedrake-update", line 895, in pip_requirements
    run_pip_install(["--no-deps", "-r", "%s/requirements.txt" % package])
  File "/Users/shuchanzhou/firedrake/src/../bin/firedrake-update", line 864, in run_pip_install
    check_call(pipinstall + pipargs)
  File "/Users/shuchanzhou/firedrake/src/../bin/firedrake-update", line 543, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/shuchanzhou/firedrake/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,islpy,numpy', '-vvv', '--no-deps', '-r', 'COFFEE/requirements.txt']' returned non-zero exit status 1.

**Comment by danshapero** [comment]
Can you activate the virtual environment, then do
```pip show packaging```
and then copy/paste the output? Just trying to see if it installed correctly.

**Comment by sz9518** [comment]
> Can you activate the virtual environment, then do
> `pip show packaging`
> and then copy/paste the output? Just trying to see if it installed correctly.

after I enter "pip show packaging" I just got a warning said : "WARNING: Package(s) not found: packaging", maybe I should enter something else?

**Comment by danshapero** [comment]
Ah ok I wonder if you might have switched the order by mistake, can you do `pip install packaging==20.5` and, if that works, try `firedrake-update` again?

**Comment by sz9518** [comment]
> Ah ok I wonder if you might have switched the order by mistake, can you do `pip install packaging==20.5` and, if that works, try `firedrake-update` again?

Now it is finished! Thank you very much!
