### ISSUE TITLE
CheckpointFile cannot save VertexOnlyMesh

### ISSUE THREAD

**Issue by dham** [firedrakeproject/firedrake#2452]
MFE:
```python3
from firedrake import *

mesh = UnitIntervalMesh(2)
vm = VertexOnlyMesh(mesh, [[0.55]])

with CheckpointFile("foo.h5", "w") as outfile:
    outfile.save_mesh(vm)
```

Output is:
```console
(firedrake2) dham@IC-D46G33P392 firedrake % python test_checkpoint_vertex_only_mesh.py
Traceback (most recent call last):
  File "/Users/dham/src/firedrake2/src/firedrake/test_checkpoint_vertex_only_mesh.py", line 7, in <module>
    outfile.save_mesh(vm)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/Users/dham/src/firedrake2/src/firedrake/firedrake/checkpointing.py", line 600, in save_mesh
    self._save_mesh_topology(tmesh)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/Users/dham/src/firedrake2/src/firedrake/firedrake/checkpointing.py", line 635, in _save_mesh_topology
    topology_dm.topologyView(viewer=self.viewer)
AttributeError: 'petsc4py.PETSc.DMSwarm' object has no attribute 'topologyView'
```

**Comment by ksagiyam** [comment]
I think we can implement `DMView()` and `DMLoad()` for `DMSwarm`s reusing existing infrastructure.

The most straightforward implementation would probably put vertices also in ghost cells; why do we remove vertices in the ghost cells? Maybe we had this discussion long time ago, but, if swarm points ever contributed to some interior facet integral, we would need to have swarm points in the ghost cells. Would it currently break something if we had ghost swarm points? @ReubenHill

**Comment by wence-** [comment]
You can't integrate over a mesh and use a function on a vertexonlymesh, and vertexonlymeshes have no connectivity, so all integrals over them decouple. So "interior facet integrals" doesn't make sense.

**Comment by ksagiyam** [comment]
I meant interior facets of the base mesh; what I vaguely had in mind is some charged particle represented by a function on a vertexonlymesh influencing some interior facet integral in a coupling problem.
I don't know what the next step is with VertexOnlyMesh, but just wondered if it really bothers to have vertices also in ghost cells, as it is probably more natural.

**Comment by ReubenHill** [comment]
I don't recall the exact reasoning for removing vertices from ghost cells, but you'll find a whole bunch of parallel tests in `firedrake/tests/vertexonly` will fail if you don't do it. It's possible that my reasoning about how you're supposed to use firedrake in parallel when writing those tests was incorrect of course!

**Comment by dham** [comment]
I *think* the reason we remove vertices from ghost cells is to ensure uniqueness. As discussed elsewhere, we plan to move to a different uniqueness strategy under which there can be particles in ghost cells (due to the voting algorithm).

**Comment by ReubenHill** [comment]
@ksagiyam I would suggest delaying the depreciation of `DumbCheckpoint` until this is fixed - functions on `VertexOnlyMesh` can't be saved in a CheckpointFile but can be saved in a `DumbCheckpoint`:
```python
from firedrake import *
m = UnitSquareMesh(32, 32)
vm = VertexOnlyMesh(m, [[0.2,0.3],[0.5,0.56]])
V = FunctionSpace(vm, "DG", 0)
f = Function(V)
chk = DumbCheckpoint("dump", mode=FILE_CREATE)
chk.store(f) # This line works
with CheckpointFile("example.h5", 'w') as afile:
    afile.save_function(f) # This line fails
```

**Comment by ksagiyam** [comment]
Yes. I think that makes sense.

**Comment by ReubenHill** [comment]
@ksagiyam I can put vertex only mesh cells back in ghost cells, since uniqueness doesn't depend on that any more. What needs to happen to fix this? I presume I need to make sure the PETScSF is correctly set up? Running David's originally failing code now gives the output
```
Traceback (most recent call last):
  File "/Users/rwh10/firedrake/src/firedrake/failing_checkpoint.py", line 7, in <module>
    outfile.save_mesh(vm)
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/Users/rwh10/firedrake/src/firedrake/firedrake/checkpointing.py", line 615, in save_mesh
    self._save_mesh_topology(tmesh)
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/Users/rwh10/firedrake/src/firedrake/firedrake/checkpointing.py", line 660, in _save_mesh_topology
    distribution_name = tmesh._distribution_name
AttributeError: 'VertexOnlyMeshTopology' object has no attribute '_distribution_name'
Exception ignored in: <function CheckpointFile.__del__ at 0x11f011510>
Traceback (most recent call last):
  File "/Users/rwh10/firedrake/src/firedrake/firedrake/checkpointing.py", line 538, in __del__
TypeError: 'NoneType' object is not callable
```
