### ISSUE TITLE
pybind11 cause firedrake-install to fail

### ISSUE THREAD

**Issue by albert-oliver** [firedrakeproject/firedrake#2497]
Following the steps from the webpage, `firedrake-install` gives the following error:
```
Installing loopy/
Traceback (most recent call last):
  File "/home/aoliver/.local/opt/Firedrake2/firedrake-install", line 1771, in <module>
    install("loopy/")
  File "/home/aoliver/.local/opt/Firedrake2/firedrake-install", line 937, in install
    run_pip_install(["-e", package])
  File "/home/aoliver/.local/opt/Firedrake2/firedrake-install", line 866, in run_pip_install
    check_call(pipinstall + pipargs)
  File "/home/aoliver/.local/opt/Firedrake2/firedrake-install", line 543, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/aoliver/.local/opt/Firedrake2/firedrake/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,islpy,numpy', '-vvv', '-e', 'loopy/']' returned non-zero exit status 1.


Install log saved in /home/aoliver/.local/opt/Firedrake2/firedrake-install.log
```
Inspecting the `firedrake-install.log` file, I've found what has turned up to be the root of the error:
```
  src/wrapper/wrap_isl.cpp: In function ‘void pybind11_init__isl(pybind11::module_&)’:
  src/wrapper/wrap_isl.cpp:18:61: error: no matching function for call to ‘pybind11::exception<isl::error>::exception(pybind11::module_&, const char [6], NULL)’
     18 |   static py::exception<isl::error> ISLError(m, "Error", NULL);
        |                                                             ^
  In file included from src/wrapper/wrap_helpers.hpp:6,
                   from src/wrapper/wrap_isl.hpp:1,
                   from src/wrapper/wrap_isl.cpp:1:
```
My system is a Ubuntu and the compiler version is 
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

$ x86_64-linux-gnu-gcc --version
x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I had installed previously `firedrake` in this same machine, so I have compared the two `firedrake-install.log` files, and I've seen that the version of `pybind11` was different. Hence, I've tried to pin the pybind11 package at the same version as the successful build. With this version I've been able to install `firedrake`.

Just for the record, this is the diff between the two files:
```
$ diff firedrake-install firedrake-install_OK
1701c1701
<     run_pip_install(["pybind11"])
---
>     run_pip_install(["pybind11==2.9.2"])
```

So, binding the `pybind11` package to the version `2.9.2` has worked for me.
I haven't filled a pull request because I don't know if the problem is general or is something specific with my system.

PS: I have tried it in another system, and it has shown the same behaviour. System specification:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bookworm/sid
Release:        unstable
Codename:       sid

$ x86_64-linux-gnu-gcc --version
x86_64-linux-gnu-gcc (Debian 11.3.0-4) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by albert-oliver** [comment]
Sorry, I've just seen that there's already a pull-request (#2496) for this issue... Sorry for the inconveniences.
