### ISSUE TITLE
New assign() implementation does not work with Real space in mixed spaces

### ISSUE THREAD

**Issue by miguelcoolchips** [firedrakeproject/firedrake#2654]
The following code:
```python
import firedrake as fd

mesh = fd.UnitSquareMesh(10, 10)
V = fd.FunctionSpace(mesh, "CG", 1)
R = fd.FunctionSpace(mesh, "R", 0)
W = V * R

up = fd.Function(W)
up2 = fd.Function(W)

up.assign(up2)
```
fails with
```
Traceback (most recent call last):
  File "/Users/miguel/repos/firedrake-latest/src/firedrake/test_real.py", line 15, in <module>
    up += up2
  File "/Users/miguel/repos/firedrake-latest/src/firedrake/firedrake/adjoint/function.py", line 153, in wrapper
    func = __iadd__(self, other, **kwargs)
  File "/Users/miguel/repos/firedrake-latest/src/firedrake/firedrake/function.py", line 400, in __iadd__
    IAddAssigner(self, expr).assign()
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/Users/miguel/repos/firedrake-latest/src/firedrake/firedrake/assign.py", line 165, in assign
    self._assign_single_dat(assignee_dat, func_dats)
  File "/Users/miguel/repos/firedrake-latest/src/firedrake/firedrake/assign.py", line 229, in _assign_single_dat
    assignee_dat.data_with_halos[self._indices] += self._compute_rvalue(function_dats)
AttributeError: 'Global' object has no attribute 'data_with_halos'
```
It looks like it is because `Real` spaces are not considered as components of a function space: https://github.com/firedrakeproject/firedrake/blob/master/firedrake/assign.py#L163

**Comment by connorjward** [comment]
Thanks for flagging this. I will get on it.
