### ISSUE TITLE
Installation failure on  Linux

### ISSUE THREAD

**Issue by zhyxue0** [firedrakeproject/firedrake#2665]
Hi everyone! 
After I failed to update firedrake, I deleted firedrake and reinstalled, but it reported an error:
```shell
Running firedrake-install
Checking for presence of package build-essential...
  installed.
Checking for presence of package autoconf...
  installed.
Checking for presence of package automake...
  installed.
Checking for presence of package bison...
  installed.
Checking for presence of package flex...
  installed.
Checking for presence of package cmake...
  installed.
Checking for presence of package gfortran...
  installed.
Checking for presence of package git...
  installed.
Checking for presence of package libtool...
  installed.
Checking for presence of package python3-dev...
  installed.
Checking for presence of package python3-pip...
  installed.
Checking for presence of package python3-tk...
  installed.
Checking for presence of package python3-venv...
  installed.
Checking for presence of package zlib1g-dev...
  installed.
Checking for presence of package libboost-dev...
  installed.
Checking for presence of package libopenblas-dev...
  installed.
Creating firedrake venv in '/home/user_0/firedrake'.
BLAS config is {}
Configuration saved to /home/user_0/firedrake/.configuration.json
Cloning firedrake

Failed to clone firedrake using ssh, falling back to https.

Failed to clone firedrake branch master.
Traceback (most recent call last):
  File "firedrake-install", line 874, in git_clone
    check_call(["git", "clone", "-q", "--recursive", git_url(plain_url, "ssh")])
  File "firedrake-install", line 653, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'clone', '-q', '--recursive', 'git@github.com:firedrakeproject/firedrake.git']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "firedrake-install", line 1794, in <module>
    git_clone("git+https://github.com/firedrakeproject/firedrake.git")
  File "firedrake-install", line 880, in git_clone
    check_call(["git", "clone", "-q", "--recursive", git_url(plain_url, "https")])
  File "firedrake-install", line 653, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'clone', '-q', '--recursive', 'https://github.com/firedrakeproject/firedrake.git']' returned non-zero exit status 128.


Install log saved in /home/user_0/firedrake-install.log

```

And here is the firedrake-install.log 
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10148680/firedrake-install.log)

**Comment by danshapero** [comment]
Here's the important part in the install log:

```
2022-12-04 21:38:53,891 WARNING Failed to clone firedrake using ssh, falling back to https.
2022-12-04 21:38:53,891 DEBUG  Running command 'git clone -q --recursive https://github.com/firedrakeproject/firedrake.git'
2022-12-04 21:56:56,905 DEBUG  error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

I'm guessing that maybe your internet connection was unstable or cut out briefly in the middle of cloning Firedrake. Can you delete the directory and try again?

**Comment by zhyxue0** [comment]
Thanks, I tried it, and the network is indeed unstable. Is there a way to install it offline?

> Here's the important part in the install log:
> 
> ```
> 2022-12-04 21:38:53,891 WARNING Failed to clone firedrake using ssh, falling back to https.
> 2022-12-04 21:38:53,891 DEBUG  Running command 'git clone -q --recursive https://github.com/firedrakeproject/firedrake.git'
> 2022-12-04 21:56:56,905 DEBUG  error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
> fatal: the remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed
> ```
> 
> I'm guessing that maybe your internet connection was unstable or cut out briefly in the middle of cloning Firedrake. Can you delete the directory and try again?

Thanks, I tried it, and the workstation‘s internet connection is indeed unstable. Is there any other way to install?

**Comment by connorjward** [comment]
@zhyxue0 is this still an issue or can it be closed?

**Comment by JDBetteridge** [comment]
Closing this issue, see [policy](https://github.com/firedrakeproject/firedrake/wiki/Closing-Installation-Issues).
