### ISSUE TITLE
MPI communicator exhaustion when creating too many meshes

### ISSUE THREAD

**Issue by jrmaddison** [firedrakeproject/firedrake#2669]
The following example

```
from firedrake import *

import gc
import sys

i = 0

while True:
    i += 1

    mesh = UnitIntervalMesh(10)
    del mesh
    gc.collect()

    sys.stdout.write(f"{i:d}\n")
    sys.stdout.flush()
```

eventually leads to an error (here when run on 2 processes)

```
[...]
680
680
Traceback (most recent call last):
  File "[...]/firedrake/test.py", line 11, in <module>
Traceback (most recent call last):
  File "[...]/firedrake/test.py", line 11, in <module>
    mesh = UnitIntervalMesh(10)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
    mesh = UnitIntervalMesh(10)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "[...]/firedrake/firedrake/src/firedrake/firedrake/utility_meshes.py", line 170, in UnitIntervalMesh
    return IntervalMesh(
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "[...]/firedrake/firedrake/src/firedrake/firedrake/utility_meshes.py", line 170, in UnitIntervalMesh
  File "[...]/firedrake/firedrake/src/firedrake/firedrake/utility_meshes.py", line 116, in IntervalMesh
    return IntervalMesh(
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
    plex = mesh.plex_from_cell_list(
  File "[...]/firedrake/firedrake/src/firedrake/firedrake/mesh.py", line 391, in plex_from_cell_list
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
    plex = PETSc.DMPlex().createFromCellList(dim, cells, coords, comm=icomm)
  File "[...]/firedrake/firedrake/src/firedrake/firedrake/utility_meshes.py", line 116, in IntervalMesh
  File "PETSc/DMPlex.pyx", line 49, in petsc4py.PETSc.DMPlex.createFromCellList
    plex = mesh.plex_from_cell_list(
  File "[...]/firedrake/firedrake/src/firedrake/firedrake/mesh.py", line 399, in plex_from_cell_list
petsc4py.PETSc.Error: error code 98
[0] DMPlexCreateFromCellListPetsc() at [...]/firedrake/firedrake/src/petsc/src/dm/impls/plex/plexcreate.c:4829
[0] DMSetType() at [...]/firedrake/firedrake/src/petsc/src/dm/interface/dm.c:3896
[0] DMCreate_Plex() at [...]/firedrake/firedrake/src/petsc/src/dm/impls/plex/plexcreate.c:4325
[0] PetscPartitionerCreate() at [...]/firedrake/firedrake/src/petsc/src/dm/partitioner/interface/partitioner.c:383
[0] PetscPartitionerSetType() at [...]/firedrake/firedrake/src/petsc/src/dm/partitioner/interface/partitioner.c:44
[0] PetscPartitionerCreate_PTScotch() at [...]/firedrake/firedrake/src/petsc/src/dm/partitioner/impls/ptscotch/partptscotch.c:327
[0] General MPI error
[0] MPI error 672744975 Other MPI error, error stack:
                internal_Comm_dup(85)...............: MPI_Comm_dup(comm=0xc40053ec, newcomm=0x55bf69238950) failed
                MPIR_Comm_dup_with_info_impl(724)...: 
                MPII_Comm_copy(833).................: 
                MPIR_Get_contextid_sparse_group(591): Too many communicators (0/2048 free on this process; ignore_id=0)
    plex = PETSc.DMPlex().createFromCellList(dim,
  File "PETSc/DMPlex.pyx", line 49, in petsc4py.PETSc.DMPlex.createFromCellList
application called MPI_Abort(PYOP2_COMM_WORLD, 1) - process 0
```

**Comment by JDBetteridge** [comment]
Thanks for the example. This is a flaw with the current implementation of `PETSc.garbage_cleanup()` in that it isn't called automatically. If you insert a call to `PETSc.garbage_cleanup()`  after `gc.collect()` does it fix the issue?

Currently Firedrake calls the cleanup routine after every solve, but perhaps we need to call it elsewhere. Could you explain a little more how this case arises in your code?

**Comment by jrmaddison** [comment]
No, unfortunately that does not fix the issue. I encountered this when trying to trace the deadlock in #2668.

The updated test

```
from firedrake import *

import petsc4py.PETSc as PETSc

import gc
import sys

i = 0

while True:
    i += 1

    mesh = UnitIntervalMesh(10)
    del mesh
    gc.collect()
    PETSc.garbage_cleanup()

    PETSc.garbage_view()
    sys.stdout.write(f"{i:d}\n")
    for j in range(PETSc.COMM_WORLD.size):
        if j == PETSc.COMM_WORLD.rank:
            sys.stdout.flush()
        PETSc.COMM_WORLD.barrier()
```

raises the same error, but shows

```
PETSc garbage on PETSC_COMM_WORLD
Rank 0:: Total entries: 0
Rank 1:: Total entries: 0
680
680
```

**Comment by JDBetteridge** [comment]
A [bad commit](https://github.com/firedrakeproject/firedrake/pull/2666) was recently reverted, if you update Firedrake, are you still seeing this issue?

There are still a few rough edges as a result of the PETSc update and communicator refactor, which I'm patching up in [this](https://github.com/firedrakeproject/firedrake/pull/2674) branch.

**Comment by connorjward** [comment]
Can this be closed? I ran the latest MFE to `i = 1000` without error. The [linked (and merged) PyOP2 PR](https://github.com/OP2/PyOP2/pull/692) may well have fixed this.

**Comment by jrmaddison** [comment]
Running the latter script with two processes on a recent Firedrake build:

```
2036
2036
PETSc garbage on PETSC_COMM_WORLD
Rank 0:: Total entries: 0
Rank 1:: Total entries: 0
2037
2037
Traceback (most recent call last):
  File "/home/maddison/build/tlm_adjoint/tlm_adjoint/test.py", line 16, in <module>
Traceback (most recent call last):
  File "/home/maddison/build/tlm_adjoint/tlm_adjoint/test.py", line 16, in <module>
    PETSc.garbage_cleanup()
  File "petsc4py/PETSc/cyclicgc.pxi", line 57, in petsc4py.PETSc.garbage_cleanup
    PETSc.garbage_cleanup()
  File "petsc4py/PETSc/cyclicgc.pxi", line 57, in petsc4py.PETSc.garbage_cleanup
  File "petsc4py/PETSc/PETSc.pyx", line 79, in petsc4py.PETSc.CHKERR
  File "petsc4py/PETSc/PETSc.pyx", line 79, in petsc4py.PETSc.CHKERR
petsc4py.PETSc.Error: error code 98
[0] PetscGarbageCleanup() at /home/maddison/firedrake/firedrake/src/petsc/src/sys/objects/garbage.c:209
[0] PetscCommDuplicate() at /home/maddison/firedrake/firedrake/src/petsc/src/sys/objects/tagm.c:220
[0] General MPI error
[0] MPI error 941706511 Other MPI error, error stack:
                internal_Comm_dup(85)...............: MPI_Comm_dup(MPI_COMM_WORLD, newcomm=0x7ffc4c7c8f8c) failed
                MPIR_Comm_dup_impl(661).............: 
                MPII_Comm_dup(871)..................: 
                MPII_Comm_copy(913).................: 
                MPIR_Get_contextid_sparse_group(591): Too many communicators (0/2048 free on this process; ignore_id=0)
petsc4py.PETSc.Error: error code 98
[1] PetscGarbageCleanup() at /home/maddison/firedrake/firedrake/src/petsc/src/sys/objects/garbage.c:209
[1] PetscCommDuplicate() at /home/maddison/firedrake/firedrake/src/petsc/src/sys/objects/tagm.c:220
[1] General MPI error
[1] MPI error 2182415 Other MPI error, error stack:
                internal_Comm_dup(85)...............: MPI_Comm_dup(MPI_COMM_WORLD, newcomm=0x7ffcf1c8e1ac) failed
                MPIR_Comm_dup_impl(661).............: 
                MPII_Comm_dup(871)..................: 
                MPII_Comm_copy(913).................: 
                MPIR_Get_contextid_sparse_group(591): Too many communicators (0/2048 free on this process; ignore_id=0)
application called MPI_Abort(PYOP2_COMM_WORLD, 1) - process 0
application called MPI_Abort(PYOP2_COMM_WORLD, 1) - process 1
```

**Comment by jrmaddison** [comment]
Looks like it's leaking `DMPlex` objects.

```
from firedrake import *

import petsc4py.PETSc as PETSc

import gc
import sys

i = 0

while True:
    i += 1

    mesh = UnitIntervalMesh(10)
    plex = mesh._topology_dm
    del mesh
    # plex.destroy()  # Uncommenting fixes the issue

    sys.stdout.write(f"{i:d}\n")
    for j in range(PETSc.COMM_WORLD.size):
        if j == PETSc.COMM_WORLD.rank:
            sys.stdout.flush()
        PETSc.COMM_WORLD.barrier()
```

**Comment by wence-** [comment]
I think you need the `garbage_cleanup` call?

**Comment by jrmaddison** [comment]
The error message in the previous included the garbage_cleanup` call.

**Comment by connorjward** [comment]
What happens with `PETSc.garbage_cleanup(mesh._comm)`? The default communicator is COMM_WORLD which is not where we stash all our objects (we use the internal PyOP2 comm).

**Comment by connorjward** [comment]
Does this mean that we can close this issue? The unintuitive behaviour of `garbage_cleanup` (needing to pass a private comm) is already recorded as an issue [here](https://github.com/firedrakeproject/firedrake/issues/3075).

**Comment by JDBetteridge** [comment]
I have created a public interface to PETSc.garbage_cleanup().

It accepts a Firedrake object and checks for a `_comm` attribute, alternatively a comm can be passes and the routine checks for a pyop2 "innercomm". Then `PETSc.garbage_cleanup()` is called on the internal comm.

Some things need to be kept in mind:
- It's really easy to exhaust comms, just don't hold a reference in a loop and create a million objects. However, if you are creating a Firedrake object and not holding a reference I'd suggest something is amiss.
- If you create your own comms, you're responsible for cleaning up after yourself. This is not a Firedrake issue as much as it is an [mpi4py policy](https://github.com/mpi4py/mpi4py/pull/29#discussion_r593384270). Granted, not having a public interface to clean up routines was a mistake, which is hopefully now addressed.
- I don't really want to add garbage_cleanup calls all over the place "just in case". In parallel, this can be an expensive call. If you aren't calling solve PETSc garbage doesn't get cleaned up and allocated memory and comms will persist, unless you perform the clean up manually.
- There will be improvements in the future, for instance addressing issue [#702](https://github.com/OP2/PyOP2/issues/702). However, this will not happen any time soon. It's not ideal.

Feel free to try out the branch and suggest improvements for your use case.

**Comment by jrmaddison** [comment]
> Does this mean that we can close this issue?

Yes, can be closed.
