### ISSUE TITLE
class 'ufl.tensors.ListTensor‘ Error

### ISSUE THREAD

**Issue by zhyxue0** [firedrakeproject/firedrake#2673]
Hi, everyone!  After I installed the latest firedrake, my previous code didn't work anymore (the last version was installed in October).
The error message is about ufl.tensors.ListTensor.

Here is my code
```python
from firedrake import *
import numpy as np
Nx = 2
degree = 2

mesh = UnitSquareMesh(Nx, Nx, quadrilateral=False)
x, y  = SpatialCoordinate(mesh)

n = FacetNormal(mesh)
Orientation = Function(VectorFunctionSpace(mesh, "DG", 0))
Orientation.assign(as_vector([1.0, 1.0]))
```

and the Error:
```shell
Traceback (most recent call last):
  File "/home/Code/firedrake_code/Test.py", line 11, in <module>
    Orientation.assign(as_vector([1.0, 1.0]))
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/src/firedrake/firedrake/adjoint/function.py", line 135, in wrapper
    ret = assign(self, other, *args, **kwargs)
  File "/home/firedrake/src/firedrake/firedrake/function.py", line 400, in assign
    Assigner(self, expr, subset).assign()
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/src/firedrake/firedrake/assign.py", line 171, in assign
    *(f.dat.split for f in self._functions)):
  File "/home/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/firedrake/src/firedrake/firedrake/assign.py", line 188, in _functions
    return tuple(c for (c, _) in self._weighted_coefficients
  File "/home/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/firedrake/src/firedrake/firedrake/assign.py", line 218, in _weighted_coefficients
    return map_expr_dag(self._coefficient_collector, self._expression)
  File "/home/firedrake/src/ufl/ufl/corealg/map_dag.py", line 36, in map_expr_dag
    result, = map_expr_dags(function, [expression], compress=compress,
  File "/home/firedrake/src/ufl/ufl/corealg/map_dag.py", line 99, in map_expr_dags
    r = handlers[v._ufl_typecode_](v, *[vcache[u] for u in v.ufl_operands])
  File "/home/firedrake/src/firedrake/firedrake/assign.py", line 93, in expr
    raise NotImplementedError(f"Handler not defined for {type(o)}")
NotImplementedError: Handler not defined for <class 'ufl.tensors.ListTensor'>
```

**Comment by connorjward** [comment]
You can get this to work by using `Constant([1.0, 1.0])` instead of `as_vector([1.0, 1.0])`.
