### ISSUE TITLE
Firedrake tests hang after gc_fix

### ISSUE THREAD

**Issue by ksagiyam** [firedrakeproject/firedrake#2693]
Related (or identical?) to https://github.com/firedrakeproject/firedrake/issues/2669.

`tests/output/test_io_solve.py` (and probably others) hangs in parallel.

Using 2 processes, I get the following backtrace:

rank 0: 
```
(gdb) bt
#0  poll_active_fboxes (cell=0x7fffffffcb70)
    at ./src/mpid/ch3/channels/nemesis/include/mpid_nem_fbox.h:53
#1  0x00007ffff3eda7c5 in MPID_nem_mpich_blocking_recv (completions=6535, 
    in_fbox=<synthetic pointer>, cell=0x7fffffffcb70)
    at ./src/mpid/ch3/channels/nemesis/include/mpid_nem_inline.h:942
#2  MPIDI_CH3I_Progress (progress_state=progress_state@entry=0x7fffffffcc34, 
    is_blocking=is_blocking@entry=1)
    at src/mpid/ch3/channels/nemesis/src/ch3_progress.c:360
#3  0x00007ffff3e15657 in MPIR_Wait_state (request_ptr=0x2970170, 
    status=<optimized out>, state=0x7fffffffcc34)
    at src/mpi/request/request_impl.c:837
#4  0x00007ffff3e1573e in MPIR_Wait_impl (
    request_ptr=request_ptr@entry=0x2970170, status=status@entry=0x1)
    at src/mpi/request/request_impl.c:860
#5  0x00007ffff3dcc9f6 in MPID_Wait (status=0x1, request_ptr=0x2970170)
    at ./src/mpid/ch3/include/mpidpost.h:272
#6  MPIC_Wait (request_ptr=0x2970170, errflag=errflag@entry=0x7fffffffcf88)
    at src/mpi/coll/helper_fns.c:63
#7  0x00007ffff3dcda1a in MPIC_Sendrecv (sendbuf=0x7fffffffcfdc, sendcount=33, 
    sendtype=sendtype@entry=1275069445, dest=dest@entry=0, 
    sendtag=sendtag@entry=14, recvbuf=recvbuf@entry=0x1852784, recvcount=32, 
    recvtype=1275069445, source=0, recvtag=14, 
    comm_ptr=0x7ffff4293f40 <MPIR_Comm_builtin>, status=0x7fffffffcca0, 
    errflag=0x7fffffffcf88) at src/mpi/coll/helper_fns.c:328
#8  0x00007ffff3d3f205 in MPIR_Allreduce_intra_reduce_scatter_allgather (
    sendbuf=sendbuf@entry=0xffffffffffffffff, 
    recvbuf=recvbuf@entry=0x7fffffffcfdc, count=count@entry=65, 
    datatype=datatype@entry=1275069445, op=op@entry=1476395014, 
    comm_ptr=comm_ptr@entry=0x7ffff4293f40 <MPIR_Comm_builtin>, 
    errflag=0x7fffffffcf88)
    at src/mpi/coll/allreduce/allreduce_intra_reduce_scatter_allgather.c:184
#9  0x00007ffff3dc05d2 in MPIR_Allreduce_allcomm_auto (
    sendbuf=sendbuf@entry=0xffffffffffffffff, 
    recvbuf=recvbuf@entry=0x7fffffffcfdc, count=count@entry=65, 
    datatype=datatype@entry=1275069445, op=1476395014, 
    comm_ptr=0x7ffff4293f40 <MPIR_Comm_builtin>, errflag=0x7fffffffcf88)
    at src/mpi/coll/mpir_coll.c:4527
#10 0x00007ffff3dc0787 in MPIR_Allreduce_impl (
    sendbuf=sendbuf@entry=0xffffffffffffffff, recvbuf=0x7fffffffcfdc, 
    count=count@entry=65, datatype=datatype@entry=1275069445, 
    op=op@entry=1476395014, 
    comm_ptr=comm_ptr@entry=0x7ffff4293f40 <MPIR_Comm_builtin>, 
    errflag=0x7fffffffcf88) at src/mpi/coll/mpir_coll.c:4580
#11 0x00007ffff3ddc48a in MPIR_Get_contextid_sparse_group (
    comm_ptr=comm_ptr@entry=0x7ffff4293f40 <MPIR_Comm_builtin>, 
    group_ptr=group_ptr@entry=0x0, tag=268435455, 
    context_id=context_id@entry=0x7fffffffd134, ignore_id=ignore_id@entry=0)
    at src/mpi/comm/contextid.c:474
#12 0x00007ffff3ddcff7 in MPIR_Get_contextid_sparse (
    comm_ptr=comm_ptr@entry=0x7ffff4293f40 <MPIR_Comm_builtin>, 
    context_id=context_id@entry=0x7fffffffd134, ignore_id=ignore_id@entry=0)
    at src/mpi/comm/contextid.c:289
#13 0x00007ffff3dda05d in MPII_Comm_copy (
    comm_ptr=comm_ptr@entry=0x7ffff4293f40 <MPIR_Comm_builtin>, size=2, 
    info=info@entry=0x0, outcomm_ptr=outcomm_ptr@entry=0x7fffffffd1b0)
    at src/mpi/comm/commutil.c:831
#14 0x00007ffff3dd187c in MPIR_Comm_dup_with_info_impl (
    comm_ptr=comm_ptr@entry=0x7ffff4293f40 <MPIR_Comm_builtin>, 
    info=info@entry=0x0, newcomm_ptr=newcomm_ptr@entry=0x7fffffffd1b0)
    at src/mpi/comm/comm_impl.c:723
#15 0x00007ffff3dd196a in MPIR_Comm_dup_impl (
    comm_ptr=comm_ptr@entry=0x7ffff4293f40 <MPIR_Comm_builtin>, 
    newcomm_ptr=newcomm_ptr@entry=0x7fffffffd1b0)
    at src/mpi/comm/comm_impl.c:699
#16 0x00007ffff3cbb942 in internal_Comm_dup (newcomm=0x7fffffffd66c, 
    comm=1140850688) at src/binding/c/comm/comm_dup.c:68
#17 PMPI_Comm_dup (comm=comm@entry=1140850688, 
    newcomm=newcomm@entry=0x7fffffffd66c) at src/binding/c/comm/comm_dup.c:162
#18 0x00007ffff43e7bff in PetscCommDuplicate (
    comm_in=comm_in@entry=1140850688, comm_out=comm_out@entry=0x7fffffffd66c, 
    first_tag=first_tag@entry=0x0)
    at /home/ksagiyam/ecse/petsc/src/sys/objects/tagm.c:217
#19 0x00007ffff44251e1 in PetscGarbageCleanup (comm=<optimized out>, 
    comm@entry=1140850688)
    at /home/ksagiyam/ecse/petsc/src/sys/objects/garbage.c:199
#20 0x00007ffff5f677c5 in __pyx_pf_8petsc4py_5PETSc_garbage_cleanup (
    __pyx_v_comm=<optimized out>, __pyx_self=<optimized out>)
    at src/petsc4py.PETSc.c:89474
#21 __pyx_pw_8petsc4py_5PETSc_1garbage_cleanup (__pyx_self=<optimized out>, 
    __pyx_args=<optimized out>, __pyx_kwds=<optimized out>)
    at src/petsc4py.PETSc.c:23858
#22 0x00000000004fb478 in PyCFunction_Call ()
#23 0x00007ffff5ef7753 in __Pyx_PyObject_Call (func=0x7fffe8797f90, 
    arg=0x7ffff7f89040, kw=0x0) at src/petsc4py.PETSc.c:408431
#24 0x00007ffff602d6c7 in __Pyx_PyObject_CallNoArg (func=0x7fffe8797f90)
    at src/petsc4py.PETSc.c:408480
#25 0x00007ffff60359b1 in __pyx_pf_8petsc4py_5PETSc_6_pre_finalize (
    __pyx_self=<optimized out>) at src/petsc4py.PETSc.c:363100
#26 __pyx_pw_8petsc4py_5PETSc_7_pre_finalize (__pyx_self=<optimized out>, 
    __pyx_args=<optimized out>, __pyx_kwds=<optimized out>)
    at src/petsc4py.PETSc.c:35383
#27 0x00000000005ec478 in ?? ()
#28 0x000000000063b970 in ?? ()
#29 0x00000000006156ba in Py_FinalizeEx ()
#30 0x00000000005e8519 in Py_RunMain ()
#31 0x00000000005e8319 in Py_BytesMain ()
#32 0x00007ffff6bf0c87 in __libc_start_main (main=0x4f64a0 <main>, argc=2, 
    argv=0x7fffffffde38, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffde28)
    at ../csu/libc-start.c:310
#33 0x00000000005e822a in _start ()
```
rank 1:
```
(gdb) bt
#0  0x00007ffff3ed6108 in poll_active_fboxes (cell=0x7fffffff9270)
    at ./src/mpid/ch3/channels/nemesis/include/mpid_nem_fbox.h:33
#1  0x00007ffff3eda7c5 in MPID_nem_mpich_blocking_recv (completions=4958, 
    in_fbox=<synthetic pointer>, cell=0x7fffffff9270)
    at ./src/mpid/ch3/channels/nemesis/include/mpid_nem_inline.h:942
#2  MPIDI_CH3I_Progress (progress_state=progress_state@entry=0x7fffffff9334, 
    is_blocking=is_blocking@entry=1)
    at src/mpid/ch3/channels/nemesis/src/ch3_progress.c:360
#3  0x00007ffff3e15657 in MPIR_Wait_state (
    request_ptr=0x7ffff429e080 <MPIR_Request_direct+6240>, 
    status=<optimized out>, state=0x7fffffff9334)
    at src/mpi/request/request_impl.c:837
#4  0x00007ffff3e1573e in MPIR_Wait_impl (
    request_ptr=request_ptr@entry=0x7ffff429e080 <MPIR_Request_direct+6240>, 
    status=status@entry=0x1) at src/mpi/request/request_impl.c:860
#5  0x00007ffff3dcc9f6 in MPID_Wait (status=0x1, 
    request_ptr=0x7ffff429e080 <MPIR_Request_direct+6240>)
    at ./src/mpid/ch3/include/mpidpost.h:272
#6  MPIC_Wait (request_ptr=0x7ffff429e080 <MPIR_Request_direct+6240>, 
    errflag=errflag@entry=0x7fffffff9688) at src/mpi/coll/helper_fns.c:63
#7  0x00007ffff3dcda1a in MPIC_Sendrecv (sendbuf=0x7fffffff9760, sendcount=32, 
    sendtype=sendtype@entry=1275069445, dest=dest@entry=1, 
    sendtag=sendtag@entry=14, recvbuf=recvbuf@entry=0x427f4b0, recvcount=33, 
    recvtype=1275069445, source=1, recvtag=14, 
    comm_ptr=0x7ffff4293240 <MPIR_Comm_direct+3328>, status=0x7fffffff93a0, 
    errflag=0x7fffffff9688) at src/mpi/coll/helper_fns.c:328
#8  0x00007ffff3d3f205 in MPIR_Allreduce_intra_reduce_scatter_allgather (
    sendbuf=sendbuf@entry=0xffffffffffffffff, 
    recvbuf=recvbuf@entry=0x7fffffff96dc, count=count@entry=65, 
    datatype=datatype@entry=1275069445, op=op@entry=1476395014, 
    comm_ptr=comm_ptr@entry=0x7ffff4293240 <MPIR_Comm_direct+3328>, 
    errflag=0x7fffffff9688)
    at src/mpi/coll/allreduce/allreduce_intra_reduce_scatter_allgather.c:184
#9  0x00007ffff3dc05d2 in MPIR_Allreduce_allcomm_auto (
    sendbuf=sendbuf@entry=0xffffffffffffffff, 
    recvbuf=recvbuf@entry=0x7fffffff96dc, count=count@entry=65, 
    datatype=datatype@entry=1275069445, op=1476395014, 
    comm_ptr=0x7ffff4293240 <MPIR_Comm_direct+3328>, errflag=0x7fffffff9688)
    at src/mpi/coll/mpir_coll.c:4527
#10 0x00007ffff3dc0787 in MPIR_Allreduce_impl (
    sendbuf=sendbuf@entry=0xffffffffffffffff, recvbuf=0x7fffffff96dc, 
    count=count@entry=65, datatype=datatype@entry=1275069445, 
    op=op@entry=1476395014, 
    comm_ptr=comm_ptr@entry=0x7ffff4293240 <MPIR_Comm_direct+3328>, 
    errflag=0x7fffffff9688) at src/mpi/coll/mpir_coll.c:4580
#11 0x00007ffff3ddc48a in MPIR_Get_contextid_sparse_group (
    comm_ptr=comm_ptr@entry=0x7ffff4293240 <MPIR_Comm_direct+3328>, 
    group_ptr=group_ptr@entry=0x0, tag=268435455, 
    context_id=context_id@entry=0x7fffffff9834, ignore_id=ignore_id@entry=0)
    at src/mpi/comm/contextid.c:474
#12 0x00007ffff3ddcff7 in MPIR_Get_contextid_sparse (
    comm_ptr=comm_ptr@entry=0x7ffff4293240 <MPIR_Comm_direct+3328>, 
    context_id=context_id@entry=0x7fffffff9834, ignore_id=ignore_id@entry=0)
    at src/mpi/comm/contextid.c:289
#13 0x00007ffff3dda05d in MPII_Comm_copy (
    comm_ptr=comm_ptr@entry=0x7ffff4293240 <MPIR_Comm_direct+3328>, size=2, 
    info=info@entry=0x0, outcomm_ptr=outcomm_ptr@entry=0x7fffffff98b0)
    at src/mpi/comm/commutil.c:831
#14 0x00007ffff3dd187c in MPIR_Comm_dup_with_info_impl (
    comm_ptr=comm_ptr@entry=0x7ffff4293240 <MPIR_Comm_direct+3328>, 
    info=info@entry=0x0, newcomm_ptr=newcomm_ptr@entry=0x7fffffff98b0)
    at src/mpi/comm/comm_impl.c:723
#15 0x00007ffff3dd196a in MPIR_Comm_dup_impl (
    comm_ptr=comm_ptr@entry=0x7ffff4293240 <MPIR_Comm_direct+3328>, 
    newcomm_ptr=newcomm_ptr@entry=0x7fffffff98b0)
    at src/mpi/comm/comm_impl.c:699
#16 0x00007ffff3cbb942 in internal_Comm_dup (newcomm=0x7fffce165c60, 
    comm=-2080374780) at src/binding/c/comm/comm_dup.c:68
#17 PMPI_Comm_dup (comm=-2080374780, newcomm=newcomm@entry=0x7fffce165c60)
    at src/binding/c/comm/comm_dup.c:162
#18 0x00007fffe5081333 in __pyx_pf_6mpi4py_3MPI_4Comm_18Dup (
    __pyx_v_info=<optimized out>, __pyx_v_self=0x7fffe5388f90)
    at src/mpi4py.MPI.c:110039
#19 __pyx_pw_6mpi4py_3MPI_4Comm_19Dup (__pyx_v_self=0x7fffe5388f90, 
    __pyx_args=<optimized out>, __pyx_kwds=<optimized out>)
    at src/mpi4py.MPI.c:44409
#20 0x00000000005d256c in ?? ()
#21 0x0000000000556ea9 in _PyEval_EvalFrameDefault ()
#22 0x00000000004fa54a in _PyFunction_Vectorcall ()
#23 0x0000000000556bc6 in _PyEval_EvalFrameDefault ()
#24 0x00000000004fa54a in _PyFunction_Vectorcall ()
#25 0x000000000055ac2a in _PyEval_EvalFrameDefault ()
#26 0x0000000000555f6a in _PyEval_EvalCodeWithName ()
#27 0x00000000004fa5dd in _PyFunction_Vectorcall ()
#28 0x00000000004fb80b in PyVectorcall_Call ()
#29 0x00000000005587d2 in _PyEval_EvalFrameDefault ()
#30 0x0000000000555f6a in _PyEval_EvalCodeWithName ()
#31 0x00000000004faf5b in _PyObject_Call_Prepend ()
#32 0x0000000000534777 in ?? ()
#33 0x000000000053225e in ?? ()
#34 0x00000000004f9e19 in _PyObject_MakeTpCall ()
#35 0x000000000055a9c7 in _PyEval_EvalFrameDefault ()
#36 0x00000000004fa54a in _PyFunction_Vectorcall ()
#37 0x00000000005ced51 in ?? ()
#38 0x0000000000556bc6 in _PyEval_EvalFrameDefault ()
#39 0x000000000055613f in _PyEval_EvalCodeWithName ()
#40 0x00000000004fa5dd in _PyFunction_Vectorcall ()
#41 0x0000000000557802 in _PyEval_EvalFrameDefault ()
#42 0x0000000000555bc0 in _PyEval_EvalCodeWithName ()
#43 0x00000000004fa5dd in _PyFunction_Vectorcall ()
#44 0x0000000000556bc6 in _PyEval_EvalFrameDefault ()
#45 0x00000000004fa54a in _PyFunction_Vectorcall ()
#46 0x000000000055ac2a in _PyEval_EvalFrameDefault ()
#47 0x00000000004fa54a in _PyFunction_Vectorcall ()
#48 0x00000000004fa2ad in ?? ()
#49 0x00000000004fa131 in PyObject_CallFunctionObjArgs ()
#50 0x0000000000437be8 in _PyObject_GenericGetAttrWithDict ()
#51 0x0000000000556f89 in _PyEval_EvalFrameDefault ()
#52 0x00000000004fa54a in _PyFunction_Vectorcall ()
#53 0x000000000055ac2a in _PyEval_EvalFrameDefault ()
#54 0x00000000004fa54a in _PyFunction_Vectorcall ()
#55 0x00000000004fa2ad in ?? ()
#56 0x00000000004fa131 in PyObject_CallFunctionObjArgs ()
#57 0x0000000000437be8 in _PyObject_GenericGetAttrWithDict ()
#58 0x0000000000556f89 in _PyEval_EvalFrameDefault ()
#59 0x00000000005ec36b in ?? ()
(continues...)
```

`gc.disable()` works around this issue.

If I check out the following commits right before gc_fix, the issue disappears:

- 424d9c4c17ea8081151657a9ee9d97310de954b6 (Firedrake) with minor version change in `checkpointing.py` (`dm_plex_view_hdf5_storage_version:` `2.0.0`->`2.1.0`) due to PETSc update.
- 7a3c68f9d4ab287dac229aff9af8aaa679afa149 (PyOP2).

Checking out `JDBetteridge/additional_wrong_comms` did not help.

@JDBetteridge

**Comment by JDBetteridge** [comment]
Is this still the case?

If so does [this branch of PyOP2](https://github.com/OP2/PyOP2/pull/692) fix things?

**Comment by JDBetteridge** [comment]
@ksagiyam can you try to reproduce this deadlock?
