### ISSUE TITLE
Failure to generate code for nested EnrichedElement

### ISSUE THREAD

**Issue by pbrubeck** [firedrakeproject/firedrake#2713]
I want to assemble a linear form with `ufl.FacetElement(NCE_k)` but code generation struggles when the element is expressed as a nested `finat.EnrichedElement`. 

Here's the minimal failing example, where I do the decomposition of the restricted element (`e0`) by hand as a nested ErichedElement (`e1`) and single EnrichedElement (`e2`):
```
from firedrake import *

degree = 2
mesh = ExtrudedMesh(UnitSquareMesh(1, 1, quadrilateral=True), 1)
cell = mesh.ufl_cell()
e0 = FacetElement(FiniteElement("NCE", degree=degree, cell=cell))

sub_cells = cell.sub_cells()
Qc_elt = FiniteElement("Q", sub_cells[0], degree)
Qd_elt = FiniteElement("RTCE", sub_cells[0], degree)
Id_elt = FiniteElement("DG", sub_cells[1], degree - 1)
Ic_elt = FiniteElement("CG", sub_cells[1], degree)

elems = [HCurl(TensorProductElement(FacetElement(Qc_elt), Id_elt, cell=cell)),
         HCurl(TensorProductElement(Qd_elt, FacetElement(Ic_elt), cell=cell)),
         HCurl(TensorProductElement(FacetElement(Qd_elt), InteriorElement(Ic_elt), cell=cell))
        ]

e1 = EnrichedElement(EnrichedElement(elems[0], elems[1]), elems[2])

e2 = EnrichedElement(*elems)

for element in (e0, e1, e2):
    V = FunctionSpace(mesh, element)
    u = Function(V)
    v = TestFunction(V)
    print(V.ufl_element())
    try:
        assemble(inner(u, v)*dx)
        print("success")
    except AssertionError:
        print("fail")
```
The output is:
```
<<HCurlElement(TensorProductElement(FiniteElement('Q', quadrilateral, 2), FiniteElement('Discontinuous Lagrange', interval, 1), TensorProductCell(quadrilateral, interval))) + HCurlElement(TensorProductElement(FiniteElement('RTCE', quadrilateral, 2), FiniteElement('Lagrange', interval, 2), TensorProductCell(quadrilateral, interval)))>>|_{facet}
fail

<<HCurlElement(TensorProductElement(RestrictedElement(FiniteElement('Q', quadrilateral, 2), 'facet'), FiniteElement('Discontinuous Lagrange', interval, 1), TensorProductCell(quadrilateral, interval))) + HCurlElement(TensorProductElement(FiniteElement('RTCE', quadrilateral, 2), RestrictedElement(FiniteElement('Lagrange', interval, 2), 'facet'), TensorProductCell(quadrilateral, interval)))> + HCurlElement(TensorProductElement(RestrictedElement(FiniteElement('RTCE', quadrilateral, 2), 'facet'), RestrictedElement(FiniteElement('Lagrange', interval, 2), 'interior'), TensorProductCell(quadrilateral, interval)))>
fail

<HCurlElement(TensorProductElement(RestrictedElement(FiniteElement('Q', quadrilateral, 2), 'facet'), FiniteElement('Discontinuous Lagrange', interval, 1), TensorProductCell(quadrilateral, interval))) + HCurlElement(TensorProductElement(FiniteElement('RTCE', quadrilateral, 2), RestrictedElement(FiniteElement('Lagrange', interval, 2), 'facet'), TensorProductCell(quadrilateral, interval))) + HCurlElement(TensorProductElement(RestrictedElement(FiniteElement('RTCE', quadrilateral, 2), 'facet'), RestrictedElement(FiniteElement('Lagrange', interval, 2), 'interior'), TensorProductCell(quadrilateral, interval)))>
success
```
And the Traceback of the AssertionError is:
```
Traceback (most recent call last):
  File "/home/pbrubeck/git/dphil_thesis/static_condensation/snippets/bug_facet_NCE.py", line 28, in <module>
    assemble(inner(u, v)*dx)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/firedrake/firedrake/adjoint/assembly.py", line 19, in wrapper
    output = assemble(*args, **kwargs)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/firedrake/firedrake/assemble.py", line 102, in assemble
    return _assemble_form(expr, *args, **kwargs)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/firedrake/firedrake/assemble.py", line 291, in _assemble_form
    return assembler.assemble()
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/firedrake/firedrake/assemble.py", line 427, in assemble
    self.execute_parloops()
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/firedrake/firedrake/assemble.py", line 565, in execute_parloops
    for parloop in self.parloops:
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/firedrake/firedrake/assemble.py", line 486, in parloops
    for lknl, gknl in zip(self.local_kernels, self.global_kernels))
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/firedrake/firedrake/assemble.py", line 463, in local_kernels
    return tsfc_interface.compile_form(self._form, "form", diagonal=self.diagonal,
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/firedrake/firedrake/tsfc_interface.py", line 233, in compile_form
    kinfos = TSFCKernel(f, prefix, parameters,
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/PyOP2/pyop2/caching.py", line 207, in __new__
    obj = make_obj()
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/PyOP2/pyop2/caching.py", line 197, in make_obj
    obj.__init__(*args, **kwargs)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/firedrake/firedrake/tsfc_interface.py", line 136, in __init__
    tree = tsfc_compile_form(form, prefix=name, parameters=parameters,
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/tsfc/tsfc/driver.py", line 72, in compile_form
    kernel = compile_integral(integral_data, fd, prefix, parameters, interface=interface, coffee=coffee, diagonal=diagonal, log=log)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/tsfc/tsfc/driver.py", line 143, in compile_integral
    integrand_exprs = builder.compile_integrand(integrand, params, ctx)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/tsfc/tsfc/kernel_interface/common.py", line 155, in compile_integrand
    expressions = fem.compile_ufl(integrand,
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/tsfc/tsfc/fem.py", line 718, in compile_ufl
    result = map_expr_dags(context.translator, expressions)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/ufl/ufl/corealg/map_dag.py", line 97, in map_expr_dags
    r = handlers[v._ufl_typecode_](v)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/tsfc/tsfc/ufl_utils.py", line 152, in _modified_terminal
    return self.modified_terminal(o)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/tsfc/tsfc/fem.py", line 367, in modified_terminal
    return translate(mt.terminal, mt, self.context)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/tsfc/tsfc/fem.py", line 676, in translate_coefficient
    for var, expr in unconcatenate([(vec_beta, table_qi)], ctx.index_cache):
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/tsfc/gem/unconcatenate.py", line 242, in unconcatenate
    return _unconcatenate(cache, pairs)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/tsfc/gem/unconcatenate.py", line 222, in _unconcatenate
    return _unconcatenate(cache, split_pairs)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/tsfc/gem/unconcatenate.py", line 181, in _unconcatenate
    concat_group = find_group([e for v, e in pairs])
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/tsfc/gem/unconcatenate.py", line 103, in find_group
    assert i in free_indices
AssertionError
```

**Comment by wence-** [comment]
Fixed by finat/finat#105.
