### ISSUE TITLE
PETSc handle error when using operator preconditioning with a mesh hierarchy

### ISSUE THREAD

**Issue by JHopeCollins** [firedrakeproject/firedrake#2722]
I'm trying to precondition a solver with another operator using the `Jp` argument to `solve`. However, when I try to apply a multigrid scheme to this secondary operator I run into an assertion error where it seems that PETSc handles are getting mixed up. I've made a failing example based on first example in the geometric multigrid tutorial:

```
import firedrake as fd

mg = True

if mg is True:                                                                                   
    base_mesh = fd.UnitSquareMesh(8, 8)
    mesh = fd.MeshHierarchy(base_mesh, 4)[-1]  # breaks
else:
    mesh = fd.UnitSquareMesh(128, 128)  # works

x, y = fd.SpatialCoordinate(mesh)

V = fd.FunctionSpace(mesh, "CG", 1)

u = fd.TrialFunction(V)
v = fd.TestFunction(V)

bcs = fd.DirichletBC(V, fd.zero(), (1, 2, 3, 4))

f = -0.5*fd.pi*fd.pi*(4*fd.cos(fd.pi*x) - 5*fd.cos(fd.pi*x*0.5) + 2)*fd.sin(fd.pi*y)
L = fd.inner(f, v)*fd.dx

a = fd.dot(fd.grad(u), fd.grad(v))*fd.dx
aP = fd.Constant(0.5)*a

parameters = {
    'ksp_type': 'cg',
    'pc_type': 'mg',
}

w = fd.Function(V)
fd.solve(a == L, w, Jp=aP, bcs=bcs, solver_parameters=parameters)
```

When `mg = False` then this script works (even with the `pc_type: mg` option). When `mg = True` the call to `solve` fails with the following output:

```
Traceback (most recent call last):
  File "mg_operator_preconditioning.py", line 32, in <module>
    fd.solve(a == L, w, Jp=aP, bcs=bcs, solver_parameters=parameters)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/jhc/icl_ra/firedrake/src/firedrake/firedrake/adjoint/solving.py", line 53, in wrapper
    output = solve(*args, **kwargs)
  File "/home/jhc/icl_ra/firedrake/src/firedrake/firedrake/solving.py", line 130, in solve
    _solve_varproblem(*args, **kwargs)
  File "/home/jhc/icl_ra/firedrake/src/firedrake/firedrake/solving.py", line 162, in _solve_varproblem
    solver.solve()
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/jhc/icl_ra/firedrake/src/firedrake/firedrake/adjoint/variational_solver.py", line 90, in wrapper
    out = solve(self, **kwargs)
  File "/home/jhc/icl_ra/firedrake/src/firedrake/firedrake/variational_solver.py", line 279, in solve
    self.snes.solve(None, work)
  File "PETSc/SNES.pyx", line 590, in petsc4py.PETSc.SNES.solve
  File "PETSc/petscksp.pxi", line 276, in petsc4py.PETSc.KSP_ComputeOps
  File "/home/jhc/icl_ra/firedrake/src/firedrake/firedrake/solving_utils.py", line 498, in compute_operators
    assert P.handle == ctx._pjac.petscmat.handle
AssertionError
```

Have I missed something with setting up this problem, or is this a bug?

**Comment by pefarrell** [comment]
I vaguely recall there's some conceptual problem in one of the interfaces of PETSc that meant this breaks. A more robust way to build preconditioners on auxiliary operators is to use `firedrake.AuxiliaryOperatorPC`, instead of passing it in as `Jp=...` to the solver.

**Comment by JHopeCollins** [comment]
Ok. That's a shame, I was hoping I could use `Jp` for some quick prototyping. I am looking at `AuxiliaryOperatorPC` right now as an alternative, good to know I'm on the right track.
Thanks

**Comment by wence-** [comment]
Yeah, there is no `DMCreateMatrices`, only `DMCreateMatrix`, so if you have a multigrid hierarchy like this, the interface in PETSc has no way to give you separate coarse grid operators and preconditioning operators. In any case, as @pefarrell says, the `AuxiliaryOperatorPC` is more flexible, and not much more effort.
