### ISSUE TITLE
Error FileNotFound occured while installing firedrake

### ISSUE THREAD

**Issue by Komiller** [firedrakeproject/firedrake#2731]
This is my cmd:
C:\Users\mille\AppData\Local\Programs\Python\Python310>python firedrake-install
Running firedrake-install
Traceback (most recent call last):
  C:\Users\mille\AppData\Local\Programs\Python\Python310>python firedrake-install
Running firedrake-install
Traceback (most recent call last):
  File "C:\Users\mille\AppData\Local\Programs\Python\Python310\firedrake-install", line 1524, in <module>
    log.debug(check_output(["env"]))
  File "C:\Users\mille\AppData\Local\Programs\Python\Python310\firedrake-install", line 662, in check_output
    return subprocess.check_output(args, stderr=subprocess.STDOUT, env=os.environ).decode()
  File "C:\Users\mille\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\mille\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\mille\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\mille\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2]
And log file:
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10483693/firedrake-install.log)

**Comment by connorjward** [comment]
Firedrake is not supported on Windows unless you are using WSL. For more information please see the [installation page](http://firedrakeproject.org/download.html) or the WSL [wiki](https://github.com/firedrakeproject/firedrake/wiki/Installing-on-Windows-Subsystem-for-Linux) page.
