### ISSUE TITLE
change in assigning to native vector value functions?

### ISSUE THREAD

**Issue by w3168** [firedrakeproject/firedrake#2739]
Apologies if I have missed a change, but I have been trying to run some scripts on a new firedrake build and (as well as reactivating github actions with the latest firedrake...) it seems like assigning to natively vector valued functions has changed or is broken... My previous firedrake build was from 7th July 2022 so it might be a bit out of date.

here is an mfe: 
from firedrake import *

mesh = UnitSquareMesh(5,5,quadrilateral=True)

V = FunctionSpace(mesh,"RTCE",2)   # raviart tomas with triangles also has a similar problem...
#V = VectorFunctionSpace(mesh,"RTCE",2)  # this runs but I think this causes problems later in the code with having the wrong shape...

f = Function(V)
f.assign(as_vector((0.0,0.0)))

print(f.dat.data) # added to see result on old Firedrake

Traceback (most recent call last):
  File "/home/wis15/thwaites/tests/regression/test_assign_mfe.py", line 10, in <module>
    f.assign(as_vector((0.0,0.0)))
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/wis15/firedrake/src/firedrake/firedrake/adjoint/function.py", line 135, in wrapper
    ret = assign(self, other, *args, **kwargs)
  File "/home/wis15/firedrake/src/firedrake/firedrake/function.py", line 400, in assign
    Assigner(self, expr, subset).assign()
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/wis15/firedrake/src/firedrake/firedrake/assign.py", line 172, in assign
    self._assign_single_dat(assignee_dat, func_dats)
  File "/home/wis15/firedrake/src/firedrake/firedrake/assign.py", line 202, in _assign_single_dat
    assignee_dat.data_with_halos[self._indices] = self._compute_rvalue(function_dats)
ValueError: could not broadcast input array from shape (2,) into shape (840,)

Old firedrake output with FunctionSpace: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
 
 Old firedrake output with VectorFunctionSpace: 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

**Comment by connorjward** [comment]
As @wence- said on Slack:
> assign directly manipulates the dof values, which for vector-valued spaces are scalars

This code works if you use `f.assign(0.0)`.

**Comment by w3168** [comment]
thanks @connorjward for replying

As I mentioned on slack what I really want to do is this - should I close this issue and start another one?: 
from firedrake import *
base_mesh = UnitSquareMesh(10,10)
mesh = ExtrudedMesh(base_mesh,5)
# Set up function spaces
# Nedelec wedge element. Discontinuous in normal component
# continuous in tangential component.
N2_1 = FiniteElement("N2curl", triangle, 1, variant="integral")
CG_2 = FiniteElement("CG", interval, 2)
N2CG = TensorProductElement(N2_1, CG_2)
Ned_horiz = HCurlElement(N2CG)
P2tr = FiniteElement("CG", triangle, 2)
P1dg = FiniteElement("DG", interval, 1)
P2P1 = TensorProductElement(P2tr, P1dg)
Ned_vert = HCurlElement(P2P1)
Ned_wedge = Ned_horiz + Ned_vert
V = FunctionSpace(mesh, Ned_wedge)
W0 = TensorProductElement(P2tr, CG_2)
W = FunctionSpace(mesh, W0)  # pressure space
M = MixedFunctionSpace([V, W])
#V = VectorFunctionSpace(mesh,"RTCE",2)
m = Function(M)
v_, p_ = m.split()  # function: velocity, pressure
v_init = zero(mesh.geometric_dimension())
v_.interpolate(v_init)
Traceback (most recent call last):
  File "/home/wis15/thwaites/tests/regression/test_assign_mfe_3d_vector.py", line 28, in <module>
    v_.interpolate(v_init)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/wis15/firedrake/src/firedrake/firedrake/function.py", line 371, in interpolate
    return interpolation.interpolate(expression, self, subset=subset, ad_block_tag=ad_block_tag)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/wis15/firedrake/src/firedrake/firedrake/interpolation.py", line 61, in interpolate
    return Interpolator(expr, V, subset=subset, access=access).interpolate(ad_block_tag=ad_block_tag)
  File "/home/wis15/firedrake/src/firedrake/firedrake/interpolation.py", line 87, in __init__
    self.callable, arguments = make_interpolator(expr, V, subset, access)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/wis15/firedrake/src/firedrake/firedrake/interpolation.py", line 218, in make_interpolator
    loops.extend(_interpolator(V, tensor, expr, subset, arguments, access))
  File "<decorator-gen-28>", line 2, in _interpolator
  File "/home/wis15/firedrake/src/firedrake/firedrake/utils.py", line 74, in wrapper
    return f(*args, **kwargs)
  File "/home/wis15/firedrake/src/firedrake/firedrake/interpolation.py", line 291, in _interpolator
    kernel = compile_expression(cell_set.comm, expr, to_element, V.ufl_element(),
  File "/home/wis15/firedrake/src/PyOP2/pyop2/caching.py", line 300, in wrapper
    v = func(*args, **kwargs)
  File "/home/wis15/firedrake/src/firedrake/firedrake/interpolation.py", line 406, in compile_expression
    return compile_expression_dual_evaluation(*args, **kwargs)
  File "/home/wis15/firedrake/src/tsfc/tsfc/driver.py", line 257, in compile_expression_dual_evaluation
    evaluation, basis_indices = to_element.dual_evaluation(fn)
  File "/home/wis15/firedrake/src/FInAT/finat/finiteelementbase.py", line 251, in dual_evaluation
    Q, x = self.dual_basis
  File "/home/wis15/firedrake/src/FInAT/finat/finiteelementbase.py", line 231, in dual_basis
    raise NotImplementedError(
NotImplementedError: Dual basis not defined for element EnrichedElement




this has the same error re EnrichedElements
but I guess should be the same as just using RTCE2 in the first example ...
from firedrake import *
mesh = UnitSquareMesh(10,10,quadrilateral=True)
v_ele = FiniteElement("RTCE", mesh.ufl_cell(), 2)
V = FunctionSpace(mesh,v_ele)
#V = VectorFunctionSpace(mesh,"RTCE",2)
f = Function(V)
f.interpolate(as_vector((0.0,0.0)))

**Comment by connorjward** [comment]
Replacing `v_.interpolate(v_init)` with `v_.assign(0.0)` runs without error. Also `v_.dat.dim` returns `(1,)` which means that you are storing a scalar at each node.

**Comment by w3168** [comment]
@connorjward that's great! I'll close the issue - thanks very much for your help
