### ISSUE TITLE
firedrake-update Failed to build fenics-ufl

### ISSUE THREAD

**Issue by b17jps1** [firedrakeproject/firedrake#2789]
Cleaning ufl
Installing ufl/
Traceback (most recent call last):
  File "../bin/firedrake-update", line 2038, in <module>
    install(p+"/")
  File "../bin/firedrake-update", line 1038, in install
    run_pip_install(["-e", package])
  File "../bin/firedrake-update", line 967, in run_pip_install
    check_call(pipinstall + pipargs)
  File "../bin/firedrake-update", line 655, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/apps/spack/x86_64/0.16.1/opt/spack/linux-centos7-skylake/gcc-8.4.0/python-3.8.10-76mywnpzqklwziqcnfjgllnxzh55qxhv/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/apps/spack/x86_64/0.16.1/opt/spack/linux-centos7-skylake/gcc-8.4.0/python-3.8.10-76mywnpzqklwziqcnfjgllnxzh55qxhv/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/data/gpfs/Users/l1057678/firedrake/firedrake/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,islpy,numpy', '--no-deps', '-vvv', '-e', 'ufl/']' returned non-zero exit status 1.

----------
creating '/tmp/pip-modern-metadata-heszll4m/fenics_ufl-2022.3.0.dev0.dist-info'
  adding license file "COPYING" (matched pattern "COPYING")
  adding license file "COPYING.LESSER" (matched pattern "COPYING.LESSER")
  adding license file "AUTHORS" (matched pattern "AUTHORS")
  Preparing editable metadata (pyproject.toml): finished with status 'done'
  Source in ./ufl has version 2022.3.0.dev0, which satisfies requirement fenics-ufl==2022.3.0.dev0 from file:///data/gpfs/Users/l1057678/firedrake/firedrake/src/ufl
  Removed fenics-ufl==2022.3.0.dev0 from file:///data/gpfs/Users/l1057678/firedrake/firedrake/src/ufl from build tracker '/tmp/pip-build-tracker-_u5oq6lg'
Created temporary directory: /tmp/pip-unpack-63yf3t3_
Building wheels for collected packages: fenics-ufl
  Created temporary directory: /tmp/pip-wheel-_dtt8d1j
  Destination directory: /tmp/pip-wheel-_dtt8d1j
  Building editable for fenics-ufl (pyproject.toml): started
  Running command Building editable for fenics-ufl (pyproject.toml)
  usage: _in_process.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: _in_process.py --help [cmd1 cmd2 ...]
     or: _in_process.py --help-commands
     or: _in_process.py cmd --help

  error: invalid command 'editable_wheel'
  error: subprocess-exited-with-error

  × Building editable for fenics-ufl (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /data/gpfs/Users/l1057678/firedrake/firedrake/bin/python /data/gpfs/Users/l1057678/firedrake/firedrake/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_editable /tmp/tmp_53ywgyz
  cwd: /data/gpfs/Users/l1057678/firedrake/firedrake/src/ufl
  Building editable for fenics-ufl (pyproject.toml): finished with status 'error'
  ERROR: Failed building editable for fenics-ufl
Failed to build fenics-ufl
ERROR: Could not build wheels for fenics-ufl, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "/data/gpfs/Users/l1057678/firedrake/firedrake/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/data/gpfs/Users/l1057678/firedrake/firedrake/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/data/gpfs/Users/l1057678/firedrake/firedrake/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 477, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for fenics-ufl, which is required to install pyproject.toml-based projects
Remote version of pip: 23.0.1
Local version of pip:  23.0.1
Was pip installed by pip? True
Removed build tracker: '/tmp/pip-build-tracker-_u5oq6lg'

Any and all assistance will be greatly appreciated!

**Comment by connorjward** [comment]
I think this might be caused by something in the build process being the wrong version but it’s not easy to figure out what. Are you using a custom branch of Firedrake? When did you last install? Etc.

The easiest thing to do is almost definitely a reinstall. Does that work?

**Comment by danshapero** [comment]
All the recent changes to Python packaging / PEPs 517+518 broke editable installs at one point. I think that's now been at least partially fixed for a pure Python package but possibly not for one with extension modules. A possible fix might be to build fenics-ufl normally and not in editable mode.

**Comment by b17jps1** [comment]
Thank you for the feedback, resolution....just use docker and/or singularity.
