### ISSUE TITLE
Install failure on Linux Ubuntu 22.04

### ISSUE THREAD

**Issue by saustinp** [firedrakeproject/firedrake#2803]
Hi,

I am attempting to install Firedrake on my system running Ubuntu 22.04 and Python 3.10.6.

I am following the instructions here and installing into my home directory: https://www.firedrakeproject.org/download.html

The failure occurs when running `python3 firedrake-install`. The traceback is similar to #2794 in the NETCDF install, but I'm not sure that the root cause is:

```
Traceback (most recent call last):
  File "/home/saustin/firedrake-install", line 1856, in <module>
    install("petsc/")
  File "/home/saustin/firedrake-install", line 1022, in install
    build_and_install_petsc()
  File "/home/saustin/firedrake-install", line 1162, in build_and_install_petsc
    check_call([python, "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + petsc_options)
  File "/home/saustin/firedrake-install", line 655, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.10/subprocess.py", line 420, in che
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10913004/firedrake-install.log)
ck_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/saustin/firedrake/bin/python', './configure', 'PETSC_DIR=/home/saustin/firedrake/src/petsc', 'PETSC_ARCH=default', '--download-netcdf', '--download-hwloc', '--download-cmake', '--download-suitesparse', '--download-bison', '--with-zlib', '--with-debugging=0', '--wit
[configure.log](https://github.com/firedrakeproject/firedrake/files/10913001/configure.log)
h-c2html=0', '--download-pnetcdf', '--with-shared-libraries=1', '--download-ml', '--with-fortran-bindings=0', '--download-eigen=/home/saustin/firedrake/src/eigen-3.3.3.tgz ', '--download-hypre', '--download-scalapack', '--download-hdf5', '--download-mpich', '--download-mumps', '--download-chaco', '--download-pastix', '--download-ptscotch', '--download-metis', '--download-superlu_dist']' returned non-zero exit status 1.
```

To troubleshoot, I removed the install folder, re-downloaded the install script, and tried again to the same end. I am attaching both log files here. Any help with this would be much appreciated.

[configure.log](https://github.com/firedrakeproject/firedrake/files/10913017/configure.log)
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10913020/firedrake-install.log)

Thanks!

**Comment by angus-g** [comment]
I think it's the same issue: I've found that on Ubuntu 22.04 I need to install `libcurl4-openssl-dev` and `libxml2-dev`.

**Comment by saustinp** [comment]
Thanks a lot for the advice, and yes it was! Got it all figured out now.
