### ISSUE TITLE
"Failed to clone libsupermesh branch master"

### ISSUE THREAD

**Issue by MaihgrUmosch** [firedrakeproject/firedrake#2832]
The following is the traceback during the attempt to install libsupermesh after running firedrake-install or -update.

`Traceback (most recent call last):
  File "/home/epipremnum/firedrake/src/../bin/firedrake-update", line 876, in git_clone
    check_call(["git", "clone", "-q", "--recursive", git_url(plain_url, "ssh")])
  File "/home/epipremnum/firedrake/src/../bin/firedrake-update", line 655, in check_call
    Traceback (most recent call last):
  File "/home/epipremnum/firedrake/src/../bin/firedrake-update", line 876, in git_clone
    check_call(["git", "clone", "-q", "--recursive", git_url(plain_url, "ssh")])
  File "/home/epipremnum/firedrake/src/../bin/firedrake-update", line 655, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'clone', '-q', '--recursive', 'git@bitbucket.org:libsupermesh/libsupermesh.git']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/epipremnum/firedrake/src/../bin/firedrake-update", line 2014, in <module>
    build_and_install_libsupermesh()
  File "/home/epipremnum/firedrake/src/../bin/firedrake-update", line 1262, in build_and_install_libsupermesh
    git_clone(url)
  File "/home/epipremnum/firedrake/src/../bin/firedrake-update", line 882, in git_clone
    check_call(["git", "clone", "-q", "--recursive", git_url(plain_url, "https")])
  File "/home/epipremnum/firedrake/src/../bin/firedrake-update", line 655, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'clone', '-q', '--recursive', 'https://bitbucket.org/libsupermesh/libsupermesh.git']' returned non-zero exit status 128.log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'clone', '-q', '--recursive', 'git@bitbucket.org:libsupermesh/libsupermesh.git']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/epipremnum/firedrake/src/../bin/firedrake-update", line 2014, in <module>
    build_and_install_libsupermesh()
  File "/home/epipremnum/firedrake/src/../bin/firedrake-update", line 1262, in build_and_install_libsupermesh
    git_clone(url)
  File "/home/epipremnum/firedrake/src/../bin/firedrake-update", line 882, in git_clone
    check_call(["git", "clone", "-q", "--recursive", git_url(plain_url, "https")])
  File "/home/epipremnum/firedrake/src/../bin/firedrake-update", line 655, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'clone', '-q', '--recursive', 'https://bitbucket.org/libsupermesh/libsupermesh.git']' returned non-zero exit status 128.`

**Comment by JDBetteridge** [comment]
Seems like a flakey internet connection, or bitbucket were experiencing issues.

Could you try again to see if the issue is now resolved?

**Comment by MaihgrUmosch** [comment]
Could well have been flakey internet connection, although it seems stable at the moment:

firedrake-update --install thetis
Running /home/epipremnum/Programs/Firedrake/firedrake/bin/firedrake-update --install thetis
Traceback (most recent call last):
  File "/home/epipremnum/Programs/Firedrake/firedrake/bin/firedrake-update", line 1724, in <module>
    run_pip(["install", "-U", "setuptools==59.2.0"])  # Unpin this when numpy will build with latest setuptools
  File "/home/epipremnum/Programs/Firedrake/firedrake/bin/firedrake-update", line 958, in run_pip
    check_call(pip + args)
  File "/home/epipremnum/Programs/Firedrake/firedrake/bin/firedrake-update", line 655, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/epipremnum/Programs/Firedrake/firedrake/bin/python', '-m', 'pip', 'install', '-U', 'setuptools==59.2.0']' returned non-zero exit status 1.


Update log saved in /home/epipremnum/Programs/Firedrake/firedrake/firedrake-update.log
(firedrake) epipremnum@epipremnum-linux:~/Documents/tidal_dam_model/dungeness_contour$ firedrake-update --install thetis
Running /home/epipremnum/Programs/Firedrake/firedrake/bin/firedrake-update --install thetis
Traceback (most recent call last):
  File "/home/~/firedrake/bin/firedrake-update", line 1724, in <module>
    run_pip(["install", "-U", "setuptools==59.2.0"])  # Unpin this when numpy will build with latest setuptools
  File "/home/~/firedrake/bin/firedrake-update", line 958, in run_pip
    check_call(pip + args)
  File "/home/~/firedrake/bin/firedrake-update", line 655, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/~/firedrake/bin/python', '-m', 'pip', 'install', '-U', 'setuptools==59.2.0']' returned non-zero exit status 1.

Kind regards

**Comment by JDBetteridge** [comment]
What do you see if you try running
```
pip install -U setuptools==59.2.0
```
manually in the activated virtual environment?

**Comment by MaihgrUmosch** [comment]
"No module named distutils.cmd"

**Comment by MaihgrUmosch** [comment]
(firedrake) epipremnum@epipremnum-linux:~$ sudo apt install python3-distutils
[sudo] password for epipremnum: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-distutils is already the newest version (3.10.6-1~22.04).
The following packages were automatically installed and are no longer required:
  cryptsetup-run libabsl20200923 libaom0 libavif9 libcbor0.6 libclang1-11 libcmark-gfm-extensions0 libcmark-gfm0 libcmis-0.5-5v5 libcodec2-0.9
  libdav1d4 libflashrom1 libftdi1-2 libfwupdplugin1 libgdal28 libgeos-3.9.0 libglew2.1 libgmsh4 libgraphblas3 libhypre libicu67 libidn11
  libigdgmm11 libjsoncpp24 libkdecorations2private8 libkf5pulseaudioqt2 libllvm11 libllvm12 libmbedcrypto3 libmbedtls12 libmbedx509-0
  libmumps-5.3 libntfs-3g883 liborcus-0.16-0 liborcus-parser-0.16-0 libpdal-base12 libpdal-util12 libperl5.32 libpetsc-real3.14
  libpetsc-real3.14-dev libpetsc3.14-dev-common libpetsc3.14-dev-examples libplacebo72 libpoppler111 libpython3.9 libpython3.9-dev
  libpython3.9-minimal libpython3.9-stdlib libqgis-3d3.10.14 libqgis-analysis3.10.14 libqgis-app3.10.14 libqgis-core3.10.14 libqgis-gui3.10.14
  libqgis-native3.10.14 libqgis-server3.10.14 libqgisgrass7-3.10.14 libqgispython3.10.14 libsuperlu-dist6 libtinyxml2-8 libvpx6 libx264-160
  libx265-192 libxmlb1 linux-headers-5.13.0-30 ltrace perl-modules-5.32 python3-argcomplete python3-argh python3-mistune python3-regex
  python3-retrying python3-simplejson python3-typed-ast python3.9 python3.9-dev python3.9-minimal qml-module-qtwebkit xul-ext-ubufox xwayland
Use 'sudo apt autoremove' to remove them.
0 to upgrade, 0 to newly install, 0 to remove and 6 not to upgrade.
(firedrake) epipremnum@epipremnum-linux:~$ sudo apt install python3.9-distutils
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python3.9-distutils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3.9-distutils' has no installation candidate
(firedrake) epipremnum@epipremnum-linux:~$ SsSsS

**Comment by JDBetteridge** [comment]
It sounds like you have a broken Python install. Perhaps system Python has been updated since you created your original Firedrake installation.

You should be able to establish whether it is a system problem by creating a new empty venv:
```
python -m venv test_environment
source ./test_environment/bin/activate
```

An then trying to run the command above:
```
pip install -U setuptools==59.2.0
```

**Comment by JDBetteridge** [comment]
I forget sometimes that on some OS's `python` is still considered Python2!

If the Python version inside the venv is 3.9.7, what is the version outside the venv?

If it's 3.10 or 3.11 (or any other major version) we don't support updating Firedrake through a major version change, your only option is to reinstall Firedrake from scratch by following the instructions [here](https://firedrakeproject.org/download.html).
