### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by makeabhishek** [firedrakeproject/firedrake#2836]
Hi,
I'm trying to install firedrake in Apple Mac M1 max. But its unsuccessful. I attached the log file comments for the reference. Also the command line error. Any help would be appreciated.
```

Running make install on NETCDF; this may take several minutes
=============================================================================================
TESTING: check from config.libraries(config/BuildSystem/config/libraries.py:168)
TESTING: checkInclude from config.headers(config/BuildSystem/config/headers.py:86)
TESTING: checkInclude from config.headers(config/BuildSystem/config/headers.py:86)
TESTING: checkVersion from config.packages.netcdf(config/BuildSystem/config/package.py:1111)
TESTING: checkSharedLibrary from config.packages.netcdf(config/BuildSystem/config/package.py:1036)
TESTING: consistencyChecks from config.packages.exodusii(config/BuildSystem/config/package.py:1044)
TESTING: alternateConfigureLibrary from config.packages.exodusii(config/BuildSystem/config/package.py:1040)
TESTING: consistencyChecks from config.packages.fblaslapack(config/BuildSystem/config/package.py:1044)
TESTING: alternateConfigureLibrary from config.packages.fblaslapack(config/BuildSystem/config/package.py:1040)
TESTING: consistencyChecks from config.packages.pthread(config/BuildSystem/config/package.py:1044)
TESTING: checkDependencies from config.packages.pthread(config/BuildSystem/config/package.py:938)
TESTING: configureLibrary from config.packages.pthread(config/BuildSystem/config/packages/pthread.py:19)
TESTING: check from config.libraries(config/BuildSystem/config/libraries.py:168)
TESTING: checkInclude from config.headers(config/BuildSystem/config/headers.py:86)
TESTING: checkInclude from config.headers(config/BuildSystem/config/headers.py:86)
TESTING: checkVersion from config.packages.pthread(config/BuildSystem/config/package.py:1111)
TESTING: checkSharedLibrary from config.packages.pthread(config/BuildSystem/config/package.py:1036)
TESTING: consistencyChecks from config.packages.egads(config/BuildSystem/config/package.py:1044)
TESTING: alternateConfigureLibrary from config.packages.egads(config/BuildSystem/config/package.py:1040)
TESTING: consistencyChecks from config.packages.PTScotch(config/BuildSystem/config/package.py:1044)
TESTING: checkDependencies from config.packages.PTScotch(config/BuildSystem/config/package.py:938)
TESTING: configureLibrary from config.packages.PTScotch(config/BuildSystem/config/package.py:964)
=============================================================================================
          Trying to download https://gitlab.inria.fr/scotch/scotch.git for PTSCOTCH
=============================================================================================
=============================================================================================
                      Compiling PTScotch; this may take several minutes
=============================================================================================
=============================================================================================
                      Installing PTScotch; this may take several minutes
=============================================================================================
TESTING: check from config.libraries(config/BuildSystem/config/libraries.py:168)
TESTING: check from config.libraries(config/BuildSystem/config/libraries.py:168)
TESTING: check from config.libraries(config/BuildSystem/config/libraries.py:168)

*********************************************************************************************
           UNABLE to CONFIGURE with GIVEN OPTIONS (see configure.log for details):
---------------------------------------------------------------------------------------------
  Downloaded ptscotch could not be used. Please check install in
  /Users/asaini/Applications/firedrake/src/petsc/default
*********************************************************************************************


2023-03-19 19:07:54,229 DEBUG  Popping path '/Users/asaini/Applications/firedrake/src/petsc'
2023-03-19 19:07:54,229 DEBUG  New path '/Users/asaini/Applications/firedrake/src'
2023-03-19 19:07:54,230 INFO   


```

Command line error.
```
Failed to clone loopy using ssh, falling back to https.
Successfully cloned repository loopy.
Checking out branch main
Successfully checked out branch main
Updating submodules.
Successfully updated submodules.
Installing petsc/
Downloading Eigen from 'https://github.com/eigenteam/eigen-git-mirror/archive/3.3.3.tar.gz' to 'eigen-3.3.3.tgz'
Checking Eigen tarball integrity
Eigen tarball hash valid
Depending on your platform, PETSc may take an hour or more to build!
Traceback (most recent call last):
  File "/Users/asaini/Applications/firedrake-install", line 1860, in <module>
    install("petsc/")
  File "/Users/asaini/Applications/firedrake-install", line 1022, in install
    build_and_install_petsc()
  File "/Users/asaini/Applications/firedrake-install", line 1162, in build_and_install_petsc
    check_call([python, "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + petsc_options)
  File "/Users/asaini/Applications/firedrake-install", line 655, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/asaini/Applications/firedrake/bin/python', './configure', 'PETSC_DIR=/Users/asaini/Applications/firedrake/src/petsc', 'PETSC_ARCH=default', '--download-suitesparse', '--download-hwloc', '--download-hypre', '--download-pnetcdf', '--with-fortran-bindings=0', '--download-metis', '--LDFLAGS=-Wl,-rpath,/opt/homebrew/opt/openblas/lib -L/opt/homebrew/opt/openblas/lib', '--CFLAGS=-I/opt/homebrew/opt/openblas/include -Wno-implicit-function-declaration', '--with-blaslapack-dir=/opt/homebrew/opt/openblas', '--download-bison', '--with-c2html=0', '--download-netcdf', '--download-ml', '--download-ptscotch', '--with-x=0', '--download-mpich-configure-arguments=--disable-opencl', '--download-superlu_dist', '--with-debugging=0', '--download-scalapack', '--with-shared-libraries=1', '--download-hdf5', '--with-zlib', '--download-pastix', '--download-hwloc-configure-arguments=--disable-opencl', '--download-mumps', '--download-mpich', '--download-chaco', '--download-eigen=/Users/asaini/Applications/firedrake/src/eigen-3.3.3.tgz ']' returned non-zero exit status 1.
```

Regards
Abhi

**Comment by connorjward** [comment]
Please can you share the full `firedrake-install.log` and `firedrake/src/petsc/configure.log` files?

**Comment by makeabhishek** [comment]
Here are the files.
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/11024943/firedrake-install.log)

**Comment by connorjward** [comment]
Somehow the `configure.log` file that you shared is empty. Can you check and try again?

**Comment by makeabhishek** [comment]
Sorry for that. Here is the config.log file
[configure.log](https://github.com/firedrakeproject/firedrake/files/11034777/configure.log)

**Comment by connorjward** [comment]
I'm seeing warnings like:
```
ld: warning: object file (/Users/asaini/Applications/firedrake/src/petsc/default/lib/libscotch.a(wgraph_part_st.o)) was built for newer macOS version (11.0) than being linked (10.15)
```
Can you please run `export MACOSX_DEPLOYMENT_TARGET=11.0` before running `firedrake-install` again.

**Comment by makeabhishek** [comment]
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/11043168/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/11043172/configure.log)

I tried to follow the instructions, but still have the issues. Attached are the log files.

**Comment by connorjward** [comment]
You have hit a different issue this time. To resolve it please follow the instructions [here](https://github.com/firedrakeproject/firedrake/issues/2793#issuecomment-1450487399).

Yes it is absolutely possible to install PETSc separately to Firedrake. You have to install PETSc, set `PETSC_DIR` and `PETSC_ARCH` and then pass `--honour-petsc-dir` to `firedrake-install`. However, it is important that you install a Firedrake-specific version of PETSc which has some additional dependencies. To see what flags need passing to PETSc `configure` you should run `python3 firedrake-install --show-petsc-configure-options` (or some very similar sounding flag).

**Comment by makeabhishek** [comment]
[configure.log](https://github.com/firedrakeproject/firedrake/files/11045193/configure.log)
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/11045195/firedrake-install.log)
Now getting follwing error

**Comment by connorjward** [comment]
This is a repeat of the same `MACOSX_DEPLOYMENT_TARGET` issue that you had above. You must have launched a new shell so the exported variable would have been lost.

The second error that you encountered will still need fixing as gmake 4.4.1 will not work. I am not familiar with homebrew but it seems like you are failing here because your homebrew installation is recent and hence has no older gmake versions available to use. Somehow you need to coerce homebrew into installing an older version of gmake. [This webpage](https://cmichel.io/how-to-install-an-old-package-version-with-brew/) may be useful.

**Comment by connorjward** [comment]
In fact, the gmake issue has already been resolved by PETSc. I will update our fork tomorrow which should fix your installation. Similarly, today we merged a fix to the installation script so the environment variable issue should also go away.
