### ISSUE TITLE
adjoint using ROL does not work with Schur complement preconditioner

### ISSUE THREAD

**Issue by xiyuanbao** [firedrakeproject/firedrake#2862]
Hi All,
I am trying to perform adjoint calculation for a stokes problem with Schur complement preconditioner. When I use the default scipy optimizer it works as expected, however when I switch to ROL it gives error.

**Environment:**
CentOS 7, firedrake-notebooks docker, 0.13.0+5269.g1c50c5ad

Here is the code to reproduce the issue:
```python
from firedrake import *
from firedrake_adjoint import *
from firedrake.petsc import PETSc
from mpi4py import MPI
import numpy as np

import ROL

# Quadrature degree:
dx = dx(degree=6)

# Set up geometry
a, b, c = 1.0079, 0.6283, 1.0
nx, ny, nz = 10, int(b/c * 10), 10
mesh2d = RectangleMesh(nx, ny, a, b, quadrilateral=True)  # Rectangular 2D mesh
mesh = ExtrudedMesh(mesh2d, nz)
bottom_id, top_id, left_id, right_id, front_id, back_id = "bottom", "top", 1, 2, 3, 4



# Set up function spaces - currently using the bilinear Q2Q1 element pair:
V = VectorFunctionSpace(mesh, "CG", 2)  # Velocity function space (vector)
W = FunctionSpace(mesh, "CG", 1)  # Pressure function space (scalar)
Q = FunctionSpace(mesh, "CG", 2)  # Temperature function space (scalar)
Z = MixedFunctionSpace([V, W])  # Mixed function space.
# Test functions and functions to hold solutions:
v, w = TestFunctions(Z)
q = TestFunction(Q)
z = Function(Z)  # a field over the mixed function space Z.
u, p = split(z)  # Returns symbolic UFL expression for u and p


# Set up temperature field and initialise:
X = SpatialCoordinate(mesh)
Told, Tnew = Function(Q, name="OldTemp"), Function(Q, name="NewTemp")
pi = 3.141592653589793238
Told.interpolate(0.5*(erf((1-X[2])*4)+erf(-X[2]*4)+1) + 0.2*(cos(pi*X[0]/a)+cos(pi*X[1]/b))*sin(pi*X[2]))

Tnew.assign(Told)

Tref, Tfinal = Function(Q),Function(Q)
Tref.interpolate(0.4*(erf((1-X[2])*4)+erf(-X[2]*4)+1) + 0.1*(cos(pi*X[0]/a)+cos(pi*X[1]/b))*sin(pi*X[2]))

# Temporal discretisation - Using a Crank-Nicholson scheme where theta = 0.5:
Ttheta = 0.5 * Tnew + (1-0.5) * Told





# Stokes Equation Solver Parameters:
stokes_solver_parameters = {
    "mat_type": "matfree",
    "snes_type": "ksponly",
    "ksp_type": "preonly",
    "pc_type": "fieldsplit",
    "pc_fieldsplit_type": "schur",
    "pc_fieldsplit_schur_type": "full",
    "fieldsplit_0": {
        "ksp_type": "cg",
        "ksp_rtol": 1e-5,
        "pc_type": "python",
        "pc_python_type": "firedrake.AssembledPC",
        "assembled_pc_type": "gamg",
        "assembled_pc_gamg_threshold": 0.01,
        "assembled_pc_gamg_square_graph": 100,
    },
    "fieldsplit_1": {
        "ksp_type": "fgmres",
        "ksp_rtol": 1e-4,
        "pc_type": "python",
        "pc_python_type": "firedrake.MassInvPC",
        "Mp_ksp_rtol": 1e-5,
        "Mp_ksp_type": "cg",
        "Mp_pc_type": "sor",
    }
}

# Energy Equation Solver Parameters:
energy_solver_parameters = {
    "mat_type": "aij",
    "snes_type": "ksponly",
    "ksp_type": "gmres",
    "ksp_rtol": 1e-5,
    "pc_type": "sor",
}


# Stokes related constants (note that since these are included in UFL, they are wrapped inside Constant):
Ra = Constant(3e4)  # Rayleigh number
mu = Constant(1.0)  # Viscosity
k = Constant((0, 0, 1))  # Unit vector (in direction opposite to gravity).

# Temperature equation related constants:
delta_t = Constant(1e-6)  # Initial time-step
kappa = Constant(1.0)  # Thermal diffusivity

# Stokes equations in UFL form:
stress = 2 * mu * sym(grad(u))
F_stokes = inner(grad(v), stress) * dx - div(v) * p * dx - (dot(v, k) * Ra * Ttheta) * dx
F_stokes += -w * div(u) * dx  # Continuity equation
# Energy equation in UFL form:
F_energy = q * (Tnew - Told) / delta_t * dx + q * dot(u, grad(Ttheta)) * dx + dot(grad(q), kappa * grad(Ttheta)) * dx

# Set up boundary conditions for Stokes
bcvfb = DirichletBC(Z.sub(0).sub(1), 0, (front_id, back_id))  # Free slip BC on front and back
bcvlr = DirichletBC(Z.sub(0).sub(0), 0, (left_id, right_id))  # Free slip BC on left and right
bcvbt = DirichletBC(Z.sub(0), 0, (bottom_id, top_id))  # Zero slip boundary condition on bottom and top

# Temperature boundary conditions
bctb, bctt = DirichletBC(Q, 1.0, bottom_id), DirichletBC(Q, 0.0, top_id)

# Pressure nullspace
p_nullspace = MixedVectorSpaceBasis(Z, [Z.sub(0), VectorSpaceBasis(constant=True)])

# Generating near_nullspaces for GAMG:
x_rotV = Function(V).interpolate(as_vector((0, X[2], -X[1])))
y_rotV = Function(V).interpolate(as_vector((-X[2], 0, X[0])))
z_rotV = Function(V).interpolate(as_vector((-X[1], X[0], 0)))
nns_x = Function(V).interpolate(Constant([1., 0., 0.]))
nns_y = Function(V).interpolate(Constant([0., 1., 0.]))
nns_z = Function(V).interpolate(Constant([0., 0., 1.]))
V_near_nullspace = VectorSpaceBasis([nns_x, nns_y, nns_z, x_rotV, y_rotV, z_rotV])
V_near_nullspace.orthonormalize()
Z_near_nullspace = MixedVectorSpaceBasis(Z, [V_near_nullspace, Z.sub(1)])


u, p = z.split()  

# Setup problem and solver objects so we can reuse (cache) solver setup
stokes_problem = NonlinearVariationalProblem(F_stokes, z, bcs=[bcvbt, bcvfb, bcvlr])
stokes_solver = NonlinearVariationalSolver(stokes_problem, solver_parameters=stokes_solver_parameters, appctx={"mu": mu}, nullspace=p_nullspace, transpose_nullspace=p_nullspace, near_nullspace=Z_near_nullspace)
energy_problem = NonlinearVariationalProblem(F_energy, Tnew, bcs=[bctb, bctt])
energy_solver = NonlinearVariationalSolver(energy_problem, solver_parameters=energy_solver_parameters)


# Solve Stokes sytem:
stokes_solver.solve()

# Temperature system:
energy_solver.solve()

J = assemble(inner(Tnew - Tref, Tnew - Tref)* dx)

m = Control(Told)

J_hat = ReducedFunctional(J, m)


# #scipy works smoothly
# T_final = minimize(J_hat, method ="L-BFGS-B", tol = 1e-4,
#                            options = {'disp': True, "maxiter":3}, bounds=(0.0, 1.0))

#ROL does not work: MatSolverType mumps does not support matrix type python
problem = MinimizationProblem(J_hat, bounds=(0.0, 1.0))

params_trust = {
    "Step": {
        "Type": "Trust Region",
        "Trust Region": {
            "Initial Radius": 1e-2,#-1,
            'Maximum Radius':1e5,
            "Subproblem Solver": "Truncated CG",
            "Radius Growing Rate": 2.5,
            "Step Acceptance Threshold": 0.05,
            "Radius Shrinking Threshold": 0.05,
            "Radius Growing Threshold": 0.9,
            "Radius Shrinking Rate (Negative rho)": 0.0625,
            "Radius Shrinking Rate (Positive rho)": 0.25,
            "Sufficient Decrease Parameter": 1e-4,
            "Safeguard Size": 1e2,
        },
    },
    "Status Test": {
        "Gradient Tolerance": 1e-18,
        "Step Tolerance": 1e-18,
        "Iteration Limit": 10,
    },
    "General": {
        "Print Verbosity": 1,
        "Secant": {},
    },
}

solver = ROLSolver(problem, params_trust, inner_product="L2")

T_final = solver.solve()


```

Here is the error message:
```
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
Traceback (most recent call last):
  File "precond_ROL_error.py", line 187, in <module>
    T_final = solver.solve()
  File "/home/firedrake/firedrake/src/pyadjoint/pyadjoint/tape.py", line 69, in wrapper
    return function(*args, **kwargs)
  File "/home/firedrake/firedrake/src/pyadjoint/pyadjoint/optimization/rol_solver.py", line 238, in solve
    self.solver.solve()
  File "/home/firedrake/firedrake/src/pyadjoint/pyadjoint/optimization/rol_solver.py", line 27, in hessVec
    hessian_action = self.rf.hessian(v.dat)
  File "/home/firedrake/firedrake/src/pyadjoint/pyadjoint/tape.py", line 69, in wrapper
    return function(*args, **kwargs)
  File "/home/firedrake/firedrake/src/pyadjoint/pyadjoint/reduced_functional.py", line 99, in hessian
    r = compute_hessian(self.functional, self.controls, m_dot, options=options, tape=self.tape)
  File "/home/firedrake/firedrake/src/pyadjoint/pyadjoint/drivers.py", line 63, in compute_hessian
    tape.evaluate_tlm()
  File "/home/firedrake/firedrake/src/pyadjoint/pyadjoint/tape.py", line 198, in evaluate_tlm
    self._blocks[i].evaluate_tlm()
  File "/home/firedrake/firedrake/src/pyadjoint/pyadjoint/tape.py", line 69, in wrapper
    return function(*args, **kwargs)
  File "/home/firedrake/firedrake/src/pyadjoint/pyadjoint/block.py", line 211, in evaluate_tlm
    tlm_output = self.evaluate_tlm_component(inputs,
  File "/home/firedrake/firedrake/src/pyadjoint/dolfin_adjoint_common/blocks/solving.py", line 277, in evaluate_tlm_component
    return self._assemble_and_solve_tlm_eq(
  File "/home/firedrake/firedrake/src/pyadjoint/dolfin_adjoint_common/blocks/solving.py", line 281, in _assemble_and_solve_tlm_eq
    return self._assembled_solve(dFdu, dFdm, dudm, bcs)
  File "/home/firedrake/firedrake/src/pyadjoint/dolfin_adjoint_common/blocks/solving.py", line 461, in _assembled_solve
    self.backend.solve(lhs, func.vector(), rhs, **kwargs)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/firedrake/src/firedrake/firedrake/adjoint/solving.py", line 53, in wrapper
    output = solve(*args, **kwargs)
  File "/home/firedrake/firedrake/src/firedrake/firedrake/solving.py", line 133, in solve
    return _la_solve(*args, **kwargs)
  File "/home/firedrake/firedrake/src/firedrake/firedrake/solving.py", line 244, in _la_solve
    solver.solve(x, b)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/firedrake/src/firedrake/firedrake/linear_solver.py", line 158, in solve
    self.ksp.solve(rhs, solution)
  File "PETSc/KSP.pyx", line 404, in petsc4py.PETSc.KSP.solve
petsc4py.PETSc.Error: error code 92
[2] KSPSolve() at /home/firedrake/firedrake/src/petsc/src/ksp/ksp/interface/itfunc.c:1081
[2] KSPSolve_Private() at /home/firedrake/firedrake/src/petsc/src/ksp/ksp/interface/itfunc.c:835
[2] KSPSetUp() at /home/firedrake/firedrake/src/petsc/src/ksp/ksp/interface/itfunc.c:416
[2] PCSetUp() at /home/firedrake/firedrake/src/petsc/src/ksp/pc/interface/precon.c:991
[2] PCSetUp_LU() at /home/firedrake/firedrake/src/petsc/src/ksp/pc/impls/factor/lu/lu.c:84
[2] MatGetFactor() at /home/firedrake/firedrake/src/petsc/src/mat/interface/matrix.c:4764
[2] See https://petsc.org/release/overview/linear_solve_table/ for possible LU and Cholesky solvers
[2] MatSolverType mumps does not support matrix type python
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2
```

It seems the solver options are not passed to ROL correctly? If I switch to direct solver then ROL still works.

Thank you!

**Comment by xiyuanbao** [comment]
I figured out the solution myself.
To pass the solver parameters, nullspace etc, one can do the following change for the pyadjoint package, bak_solving.py is the original version:
```
$ diff pyadjoint/dolfin_adjoint_common/blocks/solving.py pyadjoint/dolfin_adjoint_common/blocks/bak_solving.py
278c278
<             self.compat.assemble_adjoint_value(dFdu, bcs=bcs, **self.assemble_kwargs), dFdm, dudm, bcs, **self.adj_kwargs)
---
>             self.compat.assemble_adjoint_value(dFdu, bcs=bcs, **self.assemble_kwargs), dFdm, dudm, bcs)
280,281c280,281
<     def _assemble_and_solve_tlm_eq(self, dFdu, dFdm, dudm, bcs, **kwargs):
<         return self._assembled_solve(dFdu, dFdm, dudm, bcs, **kwargs)
---
>     def _assemble_and_solve_tlm_eq(self, dFdu, dFdm, dudm, bcs):
>         return self._assembled_solve(dFdu, dFdm, dudm, bcs)
```

It is a simple fix and maybe someone can open a PR for it? @dham 
I am closing the issue here.
