### ISSUE TITLE
BUG: Periodic utility meshes cannot create mesh hierarchies in parallel

### ISSUE THREAD

**Issue by connorjward** [firedrakeproject/firedrake#2984]
Running the following code in parallel

```py
from firedrake import *

mesh = PeriodicIntervalMesh(3, 1)
mh = MeshHierarchy(mesh, 3)
```

raises the exception

```
(firedrake) [connor@elitebook840 firedrake]$ mpiexec -np 2 python mytest.py 
Traceback (most recent call last):
  File "/home/connor/.local/opt/firedrake/src/firedrake/mytest.py", line 6, in <module>
Traceback (most recent call last):
  File "/home/connor/.local/opt/firedrake/src/firedrake/mytest.py", line 6, in <module>
    mh = MeshHierarchy(mesh, 3)
  File "/home/connor/.local/opt/firedrake/src/firedrake/firedrake/mg/mesh.py", line 109, in MeshHiera
rchy
    mh = MeshHierarchy(mesh, 3)
  File "/home/connor/.local/opt/firedrake/src/firedrake/firedrake/mg/mesh.py", line 109, in MeshHiera
rchy
    raise RuntimeError("Cannot refine parallel overlapped meshes "
RuntimeError: Cannot refine parallel overlapped meshes (make sure the MeshHierarchy is built immediat
ely after the Mesh)
application called MPI_Abort(PYOP2_COMM_WORLD, 1) - process 0
    raise RuntimeError("Cannot refine parallel overlapped meshes "
RuntimeError: Cannot refine parallel overlapped meshes (make sure the MeshHierarchy is built immediat
ely after the Mesh)
application called MPI_Abort(PYOP2_COMM_WORLD, 1) - process 1
```

The same error is observed for other periodic meshes like `PeriodicRectangleMesh`.

This error is happening because we create these periodic meshes by first creating a manifold mesh and then transforming the coordinates. This means we always have code in each `utility_meshes.py` function like ([example](https://github.com/firedrakeproject/firedrake/blob/master/firedrake/utility_meshes.py#L225)):

```py
    coord_fs = VectorFunctionSpace(
        m, FiniteElement("DG", interval, 1, variant="equispaced"), dim=1
    )
    old_coordinates = m.coordinates
    new_coordinates = Function(
        coord_fs, name=mesh._generate_default_mesh_coordinates_name(name)
    )
```

Constructing this `VectorFunctionSpace` calls `mesh.init()` which then means that we cannot construct a mesh hierarchy using the topology.

**Comment by ksagiyam** [comment]
It seems we should make those Firedrake DG coordinates in the callback.

**Comment by connorjward** [comment]
@pefarrell thank you for the code. I think that it would likely be better to pursue a solution with tighter integration with DMPlex.
@wence- this is almost exactly what I had been discussing with @ksagiyam!

**Comment by connorjward** [comment]
This no longer seems to be an issue.
