### ISSUE TITLE
BUG: Not() not implemented/working correctly?

### ISSUE THREAD

**Issue by stephankramer** [firedrakeproject/firedrake#3000]
**Describe the bug**
Whenever I'm trying to use `Not()` in a logical UFL expression it fails in any evaluation (assemble, interpolate, project)  with a not immediately obvious error + backtrace

**Steps to Reproduce**
```
from firedrake import *
mesh = UnitSquareMesh(1,1)
V = FunctionSpace(mesh, "CG", 1)
x,y = SpatialCoordinate(mesh)
interpolate(conditional(Not(x<.1),1,0), V)
```
returns
```Traceback (most recent call last):
  File "/home/skramer/firedrake/src/firedrake/firedrake/interpolation.py", line 117, in interpolate
    assembled_interpolator = self.frozen_assembled_interpolator
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Interpolator' object has no attribute 'frozen_assembled_interpolator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skramer/firedrake/src/PyOP2/pyop2/global_kernel.py", line 314, in __call__
    func = self._func_cache[key]
           ~~~~~~~~~~~~~~~~^^^^^
KeyError: 140335620184848

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skramer/firedrake/src/PyOP2/pyop2/compilation.py", line 335, in get_so
    return ctypes.CDLL(soname)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/skramer/firedrake/.cache/pyop2/78/c87e678f57e3dda6340bcfe2907651.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skramer/tstnot.py", line 5, in <module>
    interpolate(conditional(Not(x<.1),1,0), V)
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/skramer/firedrake/src/firedrake/firedrake/interpolation.py", line 62, in interpolate
    return Interpolator(expr, V, subset=subset, access=access).interpolate(ad_block_tag=ad_block_tag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/skramer/firedrake/src/firedrake/firedrake/adjoint/interpolate.py", line 22, in wrapper
    output = interpolate(interpolator, *function, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/firedrake/firedrake/interpolation.py", line 120, in interpolate
    assembled_interpolator = self.callable()
                             ^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/firedrake/firedrake/interpolation.py", line 232, in callable
    l()
  File "/home/skramer/firedrake/src/PyOP2/pyop2/parloop.py", line 206, in compute
    self()
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/skramer/firedrake/src/PyOP2/pyop2/parloop.py", line 215, in __call__
    self._compute(self.iterset.core_part)
  File "/home/skramer/firedrake/src/PyOP2/pyop2/parloop.py", line 197, in _compute
    self.global_kernel(self.comm, part.offset, part.offset+part.size, *self.arglist)
  File "/home/skramer/firedrake/src/PyOP2/pyop2/global_kernel.py", line 316, in __call__
    func = self.compile(comm)
           ^^^^^^^^^^^^^^^^^^
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/skramer/firedrake/src/PyOP2/pyop2/global_kernel.py", line 387, in compile
    return compilation.load(self, extension, self.name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/PyOP2/pyop2/compilation.py", line 606, in load
    dll = compiler(cppargs, ldargs, cpp=cpp, comm=comm).get_so(code, extension)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/PyOP2/pyop2/compilation.py", line 345, in get_so
    f.write(jitmodule.code_to_compile)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/PyOP2/pyop2/global_kernel.py", line 357, in code_to_compile
    code = lp.generate_code_v2(wrapper)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/codegen/__init__.py", line 626, in generate_code_v2
    cgr = generate_code_for_a_single_kernel(program[func_id],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/codegen/__init__.py", line 417, in generate_code_for_a_single_kernel
    device_code_str = codegen_result.device_code()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/codegen/result.py", line 161, in device_code
    + "\n\n".join(str(dp.ast) for dp in self.device_programs))
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/codegen/result.py", line 161, in <genexpr>
    + "\n\n".join(str(dp.ast) for dp in self.device_programs))
                  ^^^^^^^^^^^
  File "/home/skramer/firedrake/lib/python3.11/site-packages/cgen/__init__.py", line 86, in __str__
    return "\n".join(l.rstrip() for l in self.generate())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/lib/python3.11/site-packages/cgen/__init__.py", line 86, in <genexpr>
    return "\n".join(l.rstrip() for l in self.generate())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/lib/python3.11/site-packages/cgen/__init__.py", line 961, in generate
    for b_line in self.body.generate():
  File "/home/skramer/firedrake/lib/python3.11/site-packages/cgen/__init__.py", line 983, in generate
    for item_line in item.generate():
  File "/home/skramer/firedrake/lib/python3.11/site-packages/cgen/__init__.py", line 672, in generate
    for line in self.body.generate():
  File "/home/skramer/firedrake/lib/python3.11/site-packages/cgen/__init__.py", line 983, in generate
    for item_line in item.generate():
  File "/home/skramer/firedrake/lib/python3.11/site-packages/cgen/__init__.py", line 817, in generate
    yield "%s = %s;" % (self.lvalue, self.rvalue)
                                     ^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/target/c/__init__.py", line 389, in __str__
    return self.to_code_mapper(self.expr, PREC_NONE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/lib/python3.11/site-packages/pymbolic/mapper/__init__.py", line 141, in __call__
    result = method(expr, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/target/c/codegen/expression.py", line 769, in map_sum
    self.join_rec(" + ", expr.children, PREC_SUM),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/target/c/codegen/expression.py", line 611, in join_rec
    return f % tuple(
               ^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/target/c/codegen/expression.py", line 612, in <genexpr>
    self.rec_with_force_parens_around(
  File "/home/skramer/firedrake/src/loopy/loopy/target/c/codegen/expression.py", line 618, in rec_with_force_parens_around
    result = self.rec(expr, enclosing_prec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/lib/python3.11/site-packages/pymbolic/mapper/__init__.py", line 141, in __call__
    result = method(expr, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/target/c/codegen/expression.py", line 692, in map_if
    self.rec(expr.condition, PREC_CALL),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/lib/python3.11/site-packages/pymbolic/mapper/__init__.py", line 141, in __call__
    result = method(expr, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/target/c/codegen/expression.py", line 722, in map_logical_not
    "!" + self.rec(expr.child, PREC_UNARY),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/lib/python3.11/site-packages/pymbolic/mapper/__init__.py", line 154, in __call__
    return self.map_foreign(expr, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/lib/python3.11/site-packages/pymbolic/mapper/__init__.py", line 220, in map_foreign
    return self.map_tuple(expr, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/lib/python3.11/site-packages/pymbolic/mapper/__init__.py", line 202, in map_tuple
    raise NotImplementedError
NotImplementedError
```
Note that if I change the conditional to e.g. `Not(abs(x<.1))` I, seemingly, get a quite different error
```
...
 File "/home/skramer/firedrake/src/PyOP2/pyop2/global_kernel.py", line 357, in code_to_compile
    code = lp.generate_code_v2(wrapper)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/codegen/__init__.py", line 598, in generate_code_v2
    program = preprocess_program(program)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/tools.py", line 949, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/preprocess.py", line 811, in preprocess_program
    program = infer_unknown_types(program, expect_completion=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/type_inference.py", line 1067, in infer_unknown_types
    return clbl_inf_ctx.finish_program(program)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/translation_unit.py", line 622, in finish_program
    old_func_id = history[new_id]
                  ~~~~~~~^^^^^^^^
KeyError: 'abs'
```

**Expected behavior**
I was expecting `Not()` to work. Trying to convert some complicated marking of boundaries from a Fenics code. I can work out the logic based on positive conditionals (flipping some comparisons) but it gets a bit convoluted.

**Comment by connorjward** [comment]
Thanks for reporting this. I think I've found a fix in [TSFC](https://github.com/firedrakeproject/tsfc/pull/296) (and [added a test](https://github.com/firedrakeproject/firedrake/pull/3006) to catch this in Firedrake).

**Comment by stephankramer** [comment]
Thanks Connor. The MFE above indeed now works with your fix. Unfortunately the following variant still errors out, so maybe this is a different bug?
```
from firedrake import *
mesh = UnitSquareMesh(1,1)
V = FunctionSpace(mesh, "CG", 1)
x,y = SpatialCoordinate(mesh)
interpolate(conditional(Not(abs(x)<.1),1,0), V)
```
gives (I did do a firedrake-clean):
```
Traceback (most recent call last):
  File "/home/skramer/firedrake/src/firedrake/firedrake/interpolation.py", line 117, in interpolate
    assembled_interpolator = self.frozen_assembled_interpolator
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Interpolator' object has no attribute 'frozen_assembled_interpolator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skramer/firedrake/src/PyOP2/pyop2/global_kernel.py", line 314, in __call__
    func = self._func_cache[key]
           ~~~~~~~~~~~~~~~~^^^^^
KeyError: 139940937636720

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skramer/firedrake/src/PyOP2/pyop2/compilation.py", line 335, in get_so
    return ctypes.CDLL(soname)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/skramer/firedrake/.cache/pyop2/10/7303fc957a0d37ff3c02afcee5de87.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skramer/firedrake/src/loopy/loopy/tools.py", line 933, in wrapper
    result = transform_cache[cache_key]
             ~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/skramer/firedrake/lib/python3.11/site-packages/pytools/persistent_dict.py", line 583, in __getitem__
    return self.fetch(key, _stacklevel=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/lib/python3.11/site-packages/pytools/persistent_dict.py", line 702, in fetch
    raise NoSuchEntryError(key)
pytools.persistent_dict.NoSuchEntryError: ('preprocess_program', 'preprocess_program', (TranslationUnit(entrypoints=frozenset({'wrap_expression_kernel'}), callables_table=pmap({'MatSetValues': PetscCallable(arg_id_to_descr=None, name='MatSetValues', arg_id_to_dtype=None, name_in_target=None), 'wrap_expression_kernel': CallableKernel(arg_id_to_descr=None, name='wrap_expression_kernel', subkernel=LoopKernel(domains=[BasicSet("[end, start] -> { [n] : start <= n < end }"), BasicSet("{ [i1] : i1 = 0 }"), BasicSet("{ [i3] : 0 <= i3 <= 2 }"), BasicSet("{ [i4] : i4 = 0 }"), BasicSet("{ [i5] : i5 = 0 }"), BasicSet("{ [i0] : 0 <= i0 <= 2 }"), BasicSet("{ [i2] : 0 <= i2 <= 1 }"), BasicSet("{ [i6] : 0 <= i6 <= 2 }"), BasicSet("{ [i7] : i7 = 0 }"), BasicSet("{ [i8] : i8 = 0 }"), BasicSet("{ [i9] : i9 = 0 }"), BasicSet("{ [i10] : 0 <= i10 <= 2 }"), BasicSet("{ [i11] : i11 = 0 }"), BasicSet("{ [i12] : i12 = 0 }"), BasicSet("{ [i13] : 0 <= i13 <= 2 }"), BasicSet("{ [i14] : 0 <= i14 <= 1 }")], instructions=[CallInstruction(expression=Call(Variable('expression_kernel'), (SubArrayRef((Variable('i1'), Variable('i3'), Variable('i4')), Subscript(Variable('t0'), (Variable('i1'), Variable('i3'), Variable('i4')))), SubArrayRef((Variable('i5'), Variable('i0'), Variable('i2')), Subscript(Variable('t1'), (Variable('i5'), Variable('i0'), Variable('i2')))))), groups=frozenset(), priority=0, tags=frozenset(), depends_on_is_final=True, temp_var_types=(Optional(),), depends_on=frozenset({'statement0', 'statement1'}), conflicts_with_groups=frozenset(), predicates=frozenset(), assignees=(SubArrayRef((Variable('i1'), Variable('i3'), Variable('i4')), Subscript(Variable('t0'), (Variable('i1'), Variable('i3'), Variable('i4')))),), id='statement3', within_inames=frozenset({'n'}), within_inames_is_final=True, no_sync_with=frozenset()), Assignment(expression=Subscript(Variable('t0'), (Variable('i8'), Variable('i6'), Variable('i7'))), groups=frozenset(), priority=0, tags=frozenset(), depends_on_is_final=True, depends_on=frozenset({'statement3'}), assignee=Subscript(Variable('dat0'), (Subscript(Variable('map0'), (Variable('n'), Variable('i6'))), Variable('i7'))), conflicts_with_groups=frozenset(), predicates=frozenset(), atomicity=(), id='statement2', within_inames=frozenset({'n', 'i6', 'i7', 'i8'}), within_inames_is_final=True, temp_var_type=Optional(), no_sync_with=frozenset()), Assignment(expression=0, groups=frozenset(), priority=0, tags=frozenset(), depends_on_is_final=True, depends_on=frozenset(), assignee=Subscript(Variable('t0'), (Variable('i9'), Variable('i10'), Variable('i11'))), conflicts_with_groups=frozenset(), predicates=frozenset(), atomicity=(), id='statement1', within_inames=frozenset({'i9', 'i11', 'i10', 'n'}), within_inames_is_final=True, temp_var_type=Optional(), no_sync_with=frozenset()), Assignment(expression=Subscript(Variable('dat1'), (Subscript(Variable('map0'), (Variable('n'), Variable('i13'))), Variable('i14'))), groups=frozenset(), priority=0, tags=frozenset(), depends_on_is_final=True, depends_on=frozenset(), assignee=Subscript(Variable('t1'), (Variable('i12'), Variable('i13'), Variable('i14'))), conflicts_with_groups=frozenset(), predicates=frozenset(), atomicity=(), id='statement0', within_inames=frozenset({'i13', 'i14', 'n', 'i12'}), within_inames_is_final=True, temp_var_type=Optional(), no_sync_with=frozenset())], args=[<start: ValueArg, type: np:dtype('int32')>, <end: ValueArg, type: np:dtype('int32')>, <dat0: type: np:dtype('float64'), shape: (None, 1), dim_tags: (N1:stride:1, N0:stride:1) out aspace: global>, <dat1: type: np:dtype('float64'), shape: (None, 2), dim_tags: (N1:stride:2, N0:stride:1) in aspace: global>, <map0: type: np:dtype('int32'), shape: (None, 3), dim_tags: (N1:stride:3, N0:stride:1) in aspace: global>], assumptions=BasicSet("[end, start] -> {  : 0 <= start <= end }"), temporary_variables={'t0': <t0: type: np:dtype('float64'), shape: (1, 3, 1), dim_tags: (N2:stride:3, N1:stride:1, N0:stride:1) aspace: auto>, 't1': <t1: type: np:dtype('float64'), shape: (1, 3, 2), dim_tags: (N2:stride:6, N1:stride:2, N0:stride:1) aspace: auto>}, inames={'i4': Iname(name='i4', tags=frozenset()), 'i11': Iname(name='i11', tags=frozenset()), 'i3': Iname(name='i3', tags=frozenset()), 'i14': Iname(name='i14', tags=frozenset()), 'n': Iname(name='n', tags=frozenset()), 'i12': Iname(name='i12', tags=frozenset()), 'i2': Iname(name='i2', tags=frozenset()), 'i7': Iname(name='i7', tags=frozenset()), 'i8': Iname(name='i8', tags=frozenset()), 'i1': Iname(name='i1', tags=frozenset()), 'i5': Iname(name='i5', tags=frozenset()), 'i9': Iname(name='i9', tags=frozenset()), 'i10': Iname(name='i10', tags=frozenset()), 'i13': Iname(name='i13', tags=frozenset()), 'i0': Iname(name='i0', tags=frozenset()), 'i6': Iname(name='i6', tags=frozenset())}, substitutions={}, options=Options(enforce_array_accesses_within_bounds=True, return_dict=False, build_options=[], write_wrapper=False, trace_assignments=False, cl_exec_manage_array_events=True, check_dep_resolution=True, insert_gbarriers=False, no_numpy=False, trace_assignment_values=False, edit_code=False, skip_arg_checks=False, write_code=False, allow_terminal_colors=True, disable_global_barriers=False, annotate_inames=False, allow_fp_reordering=True, enforce_variable_access_ordered=True), target=<loopy.target.c.CWithGNULibcTarget object at 0x7f469476e1d0>, tags=frozenset(), state=<KernelState.INITIAL: 0>, name='wrap_expression_kernel', preambles=(), preamble_generators=(_PreambleGen(preamble='#include <complex.h>\n#include <math.h>\n#include <petsc.h>'),), symbol_manglers=[<function symbol_mangler at 0x7f468d9da7a0>], linearization=None, iname_slab_increments=immutables.Map({}), loop_priority=frozenset({('i12', 'i13', 'i14'), ('i7',), ('i9', 'i10', 'i11')}), applied_iname_rewrites=(), index_dtype=np:dtype('int32'), silenced_warnings=[], overridden_get_grid_sizes_for_insn_ids=None), arg_id_to_dtype=None), 'expression_kernel': CallableKernel(arg_id_to_descr=None, name='expression_kernel', subkernel=LoopKernel(domains=[BasicSet("{ [p0] : 0 <= p0 <= 2 }"), BasicSet("{ [i] : 0 <= i <= 2 }")], instructions=[Assignment(expression=0.0, groups=frozenset(), priority=0, tags=frozenset(), depends_on_is_final=True, depends_on=frozenset(), assignee=Variable('t1'), conflicts_with_groups=frozenset(), predicates=frozenset(), atomicity=(), id='insn', within_inames=frozenset({'p0'}), within_inames_is_final=False, temp_var_type=Optional(), no_sync_with=frozenset()), Assignment(expression=Sum((Variable('t1'), Product((Subscript(Variable('t0'), (Variable('p0'), Variable('i'))), Subscript(Variable('w_0'), (FloorDiv(..., 3), Sum((..., ...)), 0)))))), groups=frozenset(), priority=0, tags=frozenset(), depends_on_is_final=True, depends_on=frozenset({'insn'}), assignee=Variable('t1'), conflicts_with_groups=frozenset(), predicates=frozenset(), atomicity=(), id='insn_0', within_inames=frozenset({'i', 'p0'}), within_inames_is_final=False, temp_var_type=Optional(), no_sync_with=frozenset()), Assignment(expression=Sum((Subscript(Variable('A'), (FloorDiv(Variable('p0'), 3), Sum((Variable('p0'), Product((-3, ...)))), 0)), If(LogicalNot(Comparison(Call(..., (...,)), '<', 0.1)), 1.0, 0.0))), groups=frozenset(), priority=0, tags=frozenset(), depends_on_is_final=True, depends_on=frozenset({'insn_0'}), assignee=Subscript(Variable('A'), (FloorDiv(Variable('p0'), 3), Sum((Variable('p0'), Product((-3, FloorDiv(..., 3))))), 0)), conflicts_with_groups=frozenset(), predicates=frozenset(), atomicity=(), id='insn_1', within_inames=frozenset({'p0'}), within_inames_is_final=False, temp_var_type=Optional(), no_sync_with=frozenset()), CInstruction(iname_exprs=(), groups=frozenset(), priority=0, read_variables=frozenset({'w_0', 'A'}), depends_on_is_final=True, tags=frozenset(), code='', depends_on=frozenset({'insn_1'}), conflicts_with_groups=frozenset(), predicates=frozenset(), assignees=(), id='insn_2', within_inames=frozenset(), within_inames_is_final=True, no_sync_with=frozenset())], args=[<A: type: np:dtype('float64'), shape: (1, 3, 1), dim_tags: (N2:stride:3, N1:stride:1, N0:stride:1) in/out aspace: global>, <w_0: type: np:dtype('float64'), shape: (1, 3, 2), dim_tags: (N2:stride:6, N1:stride:2, N0:stride:1) in aspace: global>], assumptions=BasicSet("{  :  }"), temporary_variables={'t0': <t0: type: np:dtype('float64'), shape: (3, 3), dim_tags: (N1:stride:3, N0:stride:1) aspace: local>, 't1': <t1: type: np:dtype('float64'), shape: () aspace: local>}, inames={'i': Iname(name='i', tags=frozenset()), 'p0': Iname(name='p0', tags=frozenset())}, substitutions={}, options=Options(enforce_array_accesses_within_bounds=True, return_dict=False, build_options=[], write_wrapper=False, trace_assignments=False, cl_exec_manage_array_events=True, check_dep_resolution=True, insert_gbarriers=False, no_numpy=False, trace_assignment_values=False, edit_code=False, skip_arg_checks=False, write_code=False, allow_terminal_colors=True, disable_global_barriers=False, annotate_inames=False, allow_fp_reordering=True, enforce_variable_access_ordered=True), target=<loopy.target.c.CWithGNULibcTarget object at 0x7f468dc94f90>, tags=frozenset(), state=<KernelState.INITIAL: 0>, name='expression_kernel', preambles=(), preamble_generators=(_PreambleGen(preamble='#include <complex.h>\n#include <math.h>\n#include <petsc.h>'),), symbol_manglers=(), linearization=None, iname_slab_increments=immutables.Map({}), loop_priority=frozenset({('p0', 'i')}), applied_iname_rewrites=(), index_dtype=np:dtype('int32'), silenced_warnings=['summing_if_branches_ops'], overridden_get_grid_sizes_for_insn_ids=None), arg_id_to_dtype=None)}), func_id_to_in_knl_callable_mappers=[], target=<loopy.target.c.CWithGNULibcTarget object at 0x7f469476e1d0>),), {})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skramer/tstnot.py", line 5, in <module>
    interpolate(conditional(Not(abs(x)<.1),1,0), V)
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/skramer/firedrake/src/firedrake/firedrake/interpolation.py", line 62, in interpolate
    return Interpolator(expr, V, subset=subset, access=access).interpolate(ad_block_tag=ad_block_tag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/skramer/firedrake/src/firedrake/firedrake/adjoint/interpolate.py", line 22, in wrapper
    output = interpolate(interpolator, *function, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/firedrake/firedrake/interpolation.py", line 120, in interpolate
    assembled_interpolator = self.callable()
                             ^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/firedrake/firedrake/interpolation.py", line 232, in callable
    l()
  File "/home/skramer/firedrake/src/PyOP2/pyop2/parloop.py", line 206, in compute
    self()
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/skramer/firedrake/src/PyOP2/pyop2/parloop.py", line 215, in __call__
    self._compute(self.iterset.core_part)
  File "/home/skramer/firedrake/src/PyOP2/pyop2/parloop.py", line 197, in _compute
    self.global_kernel(self.comm, part.offset, part.offset+part.size, *self.arglist)
  File "/home/skramer/firedrake/src/PyOP2/pyop2/global_kernel.py", line 316, in __call__
    func = self.compile(comm)
           ^^^^^^^^^^^^^^^^^^
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/skramer/firedrake/src/PyOP2/pyop2/global_kernel.py", line 387, in compile
    return compilation.load(self, extension, self.name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/PyOP2/pyop2/compilation.py", line 606, in load
    dll = compiler(cppargs, ldargs, cpp=cpp, comm=comm).get_so(code, extension)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/PyOP2/pyop2/compilation.py", line 345, in get_so
    f.write(jitmodule.code_to_compile)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/PyOP2/pyop2/global_kernel.py", line 357, in code_to_compile
    code = lp.generate_code_v2(wrapper)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/codegen/__init__.py", line 598, in generate_code_v2
    program = preprocess_program(program)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/tools.py", line 949, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/preprocess.py", line 811, in preprocess_program
    program = infer_unknown_types(program, expect_completion=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/type_inference.py", line 1067, in infer_unknown_types
    return clbl_inf_ctx.finish_program(program)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skramer/firedrake/src/loopy/loopy/translation_unit.py", line 622, in finish_program
    old_func_id = history[new_id]
                  ~~~~~~~^^^^^^^^
KeyError: 'abs'
```

**Comment by connorjward** [comment]
My fix is also failing in complex mode. I'll keep digging.

**Comment by connorjward** [comment]
I've tracked this down to a [bug in loopy](https://github.com/inducer/loopy/issues/789). This is also why my fix is failing to work in complex mode.

**Comment by stephankramer** [comment]
Thanks! Fixed after updating loopy (https://github.com/inducer/loopy/pull/790) indeed
