### ISSUE TITLE
BUG: Function.assign(scalar * Function) fails with a complex build

### ISSUE THREAD

**Issue by jrmaddison** [firedrakeproject/firedrake#3047]
**Describe the bug**
`Function.assign(scalar * Function)` is value with a real build, but leads to an error with a complex build.

**Steps to Reproduce**
```
from firedrake import *
from firedrake.utils import complex_mode

mesh = UnitIntervalMesh(10)
space = FunctionSpace(mesh, "Lagrange", 1)

u = Function(space)
v = Function(space)

if complex_mode:
    c = 1.0 + 1.0j
else:
    c = 1.0

v.assign(c * u)
```

**Expected behavior**
The product is in the expected space, and so an assignment can be performed.

**Error message**
With a complex build:
```
Traceback (most recent call last):
  File "/home/maddison/test.py", line 15, in <module>
    v.assign(c * u)
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/maddison/firedrake_complex/firedrake/src/firedrake/firedrake/adjoint/function.py", line 118, in wrapper
    ret = assign(self, other, *args, **kwargs)
  File "/home/maddison/firedrake_complex/firedrake/src/firedrake/firedrake/function.py", line 425, in assign
    Assigner(self, expr, subset).assign()
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/maddison/firedrake_complex/firedrake/src/firedrake/firedrake/assign.py", line 197, in assign
    func_halos_valid = all(f.dat.halo_valid for f in self._functions)
  File "/home/maddison/firedrake_complex/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/maddison/firedrake_complex/firedrake/src/firedrake/firedrake/assign.py", line 229, in _functions
    return tuple(c for (c, _) in self._weighted_coefficients if _isfunction(c))
  File "/home/maddison/firedrake_complex/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/maddison/firedrake_complex/firedrake/src/firedrake/firedrake/assign.py", line 254, in _weighted_coefficients
    return map_expr_dag(self._coefficient_collector, self._expression)
  File "/home/maddison/firedrake_complex/firedrake/src/ufl/ufl/corealg/map_dag.py", line 36, in map_expr_dag
    result, = map_expr_dags(function, [expression], compress=compress,
  File "/home/maddison/firedrake_complex/firedrake/src/ufl/ufl/corealg/map_dag.py", line 99, in map_expr_dags
    r = handlers[v._ufl_typecode_](v, *[vcache[u] for u in v.ufl_operands])
  File "/home/maddison/firedrake_complex/firedrake/src/firedrake/firedrake/assign.py", line 56, in product
    raise ValueError("Expressions containing the product of two vector-valued "
ValueError: Expressions containing the product of two vector-valued subexpressions cannot be used for assignment. Consider using interpolate instead
```

**Environment:**
Ubuntu 22.04

**Comment by connorjward** [comment]
Fixed by https://github.com/firedrakeproject/firedrake/pull/3052 (one line fix). Thanks for reporting this.
