### ISSUE TITLE
INSTALL: When installing loopy, subprocess.CalledProcessError

### ISSUE THREAD

**Issue by handraqui** [firedrakeproject/firedrake#3095]
**Describe the error**
I can't install Firedrake due to an error while trying to install loopy.

**Steps to Reproduce**
Brand new Ubuntu 22.04.3 LTS, I only ran:

```wget https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install

sudo apt install build-essential

sudo apt install gfortran

python3 firedrake-install`

Then, I also tried 

$ pip install -U setuptools
```

before installing.

**Expected behavior**
I expected it to install, but I got:

**Error message**
```Installing loopy/
Traceback (most recent call last):
  File "/home/henrique/firedrake-install", line 1917, in <module>
    install("loopy/")
  File "/home/henrique/firedrake-install", line 1058, in install
    run_pip_install(["-e", package])
  File "/home/henrique/firedrake-install", line 979, in run_pip_install
    check_call(pipinstall + pipargs)
  File "/home/henrique/firedrake-install", line 666, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/henrique/firedrake/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,islpy,numpy', '-vvv', '-e', 'loopy/']' returned non-zero exit status 1.
```

firedrake-install.log
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/12566543/firedrake-install.log)

petsc/configure.log:
[configure.log](https://github.com/firedrakeproject/firedrake/files/12566545/configure.log)

**Environment:**
 - OS: Ubuntu 22.04.3 LTS
 - Python version: 3.10.12
 - Any relevant environment variables or modifications: None.

**Additional context**
None, but I had to manually install those other packages.

**Comment by handraqui** [comment]
My workaround:

Activating the firedrake venv, then:
```firedrake-update //probably unnecessary
pip install loopy
firadrake-update```.

Now it's working, and I hope it's all fine.
