### ISSUE TITLE
BUG: derivative of atan2 not defined

### ISSUE THREAD

**Issue by tommbendall** [firedrakeproject/firedrake#3111]
We picked up the change in UFL last week of `atan_2` moving to `atan2`. It seems that the derivative of `atan2` has not been defined in UFL.

**Minimum failing example:**
```
from firedrake import (IcosahedralSphereMesh, atan2, SpatialCoordinate,
                       VectorFunctionSpace, Function, grad)

mesh = IcosahedralSphereMesh(1.0)
x, y, _ = SpatialCoordinate(mesh)

expr = atan2(y, x)
V = VectorFunctionSpace(mesh, "DG", 1)
f = Function(V)
f.project(grad(expr))
```

**Error message**
```
Traceback (most recent call last):
  File "/home/thomas/firedrake/src/gusto/odds_and_ends/atan2_mfe.py", line 10, in <module>
    f.project(grad(expr))
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/thomas/firedrake/src/firedrake/firedrake/adjoint_utils/function.py", line 47, in wrapper
    output = project(self, b, *args, **kwargs)
  File "/home/thomas/firedrake/src/firedrake/firedrake/function.py", line 357, in project
    return projection.project(b, self, *args, **kwargs)
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/thomas/firedrake/src/firedrake/firedrake/adjoint_utils/projection.py", line 34, in wrapper
    output = project(*args, **kwargs)
  File "/home/thomas/firedrake/src/firedrake/firedrake/projection.py", line 78, in project
    use_slate_for_inverse=use_slate_for_inverse).project()
  File "/home/thomas/firedrake/src/firedrake/firedrake/projection.py", line 181, in project
    self.apply_massinv(self.target, self.rhs)
  File "/home/thomas/firedrake/src/firedrake/firedrake/projection.py", line 226, in rhs
    self.assembler()
  File "/home/thomas/firedrake/src/firedrake/firedrake/assemble.py", line 434, in assemble
    self.execute_parloops()
  File "/home/thomas/firedrake/src/firedrake/firedrake/assemble.py", line 580, in execute_parloops
    for parloop in self.parloops:
  File "/home/thomas/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/thomas/firedrake/src/firedrake/firedrake/assemble.py", line 499, in parloops
    for lknl, gknl in zip(self.local_kernels, self.global_kernels)
  File "/home/thomas/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/thomas/firedrake/src/firedrake/firedrake/assemble.py", line 470, in local_kernels
    return tsfc_interface.compile_form(self._form, "form", diagonal=self.diagonal,
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/thomas/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 229, in compile_form
    kinfos = TSFCKernel(f, prefix, parameters,
  File "/home/thomas/firedrake/src/PyOP2/pyop2/caching.py", line 207, in __new__
    obj = make_obj()
  File "/home/thomas/firedrake/src/PyOP2/pyop2/caching.py", line 197, in make_obj
    obj.__init__(*args, **kwargs)
  File "/home/thomas/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 131, in __init__
    tree = tsfc_compile_form(form, prefix=name, parameters=parameters,
  File "/home/thomas/firedrake/src/tsfc/tsfc/driver.py", line 79, in compile_form
    fd = ufl_utils.compute_form_data(form, complex_mode=complex_mode)
  File "/home/thomas/firedrake/src/tsfc/tsfc/ufl_utils.py", line 55, in compute_form_data
    fd = ufl_compute_form_data(
  File "/home/thomas/firedrake/src/ufl/ufl/algorithms/compute_form_data.py", line 259, in compute_form_data
    form = apply_derivatives(form)
  File "/home/thomas/firedrake/src/ufl/ufl/algorithms/apply_derivatives.py", line 1139, in apply_derivatives
    return map_integrand_dags(rules, expression)
  File "/home/thomas/firedrake/src/ufl/ufl/algorithms/map_integrands.py", line 65, in map_integrand_dags
    return map_integrands(lambda expr: map_expr_dag(function, expr, compress),
  File "/home/thomas/firedrake/src/ufl/ufl/algorithms/map_integrands.py", line 28, in map_integrands
    mapped_integrals = [map_integrands(function, itg, only_integral_type)
  File "/home/thomas/firedrake/src/ufl/ufl/algorithms/map_integrands.py", line 28, in <listcomp>
    mapped_integrals = [map_integrands(function, itg, only_integral_type)
  File "/home/thomas/firedrake/src/ufl/ufl/algorithms/map_integrands.py", line 36, in map_integrands
    return itg.reconstruct(function(itg.integrand()))
  File "/home/thomas/firedrake/src/ufl/ufl/algorithms/map_integrands.py", line 65, in <lambda>
    return map_integrands(lambda expr: map_expr_dag(function, expr, compress),
  File "/home/thomas/firedrake/src/ufl/ufl/corealg/map_dag.py", line 36, in map_expr_dag
    result, = map_expr_dags(function, [expression], compress=compress,
  File "/home/thomas/firedrake/src/ufl/ufl/corealg/map_dag.py", line 99, in map_expr_dags
    r = handlers[v._ufl_typecode_](v, *[vcache[u] for u in v.ufl_operands])
  File "/home/thomas/firedrake/src/ufl/ufl/algorithms/apply_derivatives.py", line 1070, in grad
    return map_expr_dag(rules, f,
  File "/home/thomas/firedrake/src/ufl/ufl/corealg/map_dag.py", line 36, in map_expr_dag
    result, = map_expr_dags(function, [expression], compress=compress,
  File "/home/thomas/firedrake/src/ufl/ufl/corealg/map_dag.py", line 97, in map_expr_dags
    r = handlers[v._ufl_typecode_](v)
  File "/home/thomas/firedrake/src/ufl/ufl/algorithms/apply_derivatives.py", line 51, in expr
    raise ValueError(f"Missing differentiation handler for type {o._ufl_class_.__name__}. "
ValueError: Missing differentiation handler for type Atan2. Have you added a new type?
```

**Comment by angus-g** [comment]
We've just hit this too, looks like there are a couple of causes:
1. The `ufl.utils.formatting.camel2undercase` function still translates `Atan2 -> atan_2`, so the differentation handler isn't set up to a valid function. 
2. TSFC doesn't set up the correct multifunction handler (it's still called `atan_2` over there: https://github.com/firedrakeproject/tsfc/blob/b378c0879fea5a7cc88cabf9eae6c52b9921c34b/tsfc/ufl2gem.py#L81-L82)

This seems to be a sufficient patch to catch the missing changes:
```diff
diff --git a/ufl/utils/formatting.py b/ufl/utils/formatting.py
index d35164be..4df63cd9 100644
--- a/ufl/utils/formatting.py
+++ b/ufl/utils/formatting.py
@@ -11,7 +11,7 @@ def camel2underscore(name):
     letters = []
     lastlower = False
     for i in name:
-        thislower = i.islower()
+        thislower = i.islower() or i.isdigit()
         if not thislower:
             # Don't insert _ between multiple upper case letters
             if lastlower:
diff --git a/tsfc/ufl2gem.py b/tsfc/ufl2gem.py
index fc1c760..e283fb1 100644
--- a/tsfc/ufl2gem.py
+++ b/tsfc/ufl2gem.py
@@ -78,7 +78,7 @@ class Mixin(object):
     def math_function(self, o, expr):
         return MathFunction(o._name, expr)
 
-    def atan_2(self, o, y, x):
+    def atan2(self, o, y, x):
         return MathFunction("atan2", y, x)
 
     def bessel_i(self, o, nu, arg):
```

**Comment by dham** [comment]
I think the TSFC thing is a red herring, because `atan2` will get caught by the generic `MathFunction` handler on line 78. We should probably delete the `atan_2` handler.

**Comment by angus-g** [comment]
Curious, I needed that fix after making the change in UFL. There's a traceback in https://github.com/g-adopt/g-adopt/pull/22#issuecomment-1731038985 showing the result with only the UFL fix. It does seem to make more sense to use the generic handler, however.

**Comment by dham** [comment]
https://github.com/FEniCS/ufl/pull/216

**Comment by dham** [comment]
also https://github.com/firedrakeproject/tsfc/pull/299

**Comment by dham** [comment]
Those PRs have landed and I have updated our UFL fork. I believe this is now fixed.
