### ISSUE TITLE
BUG: Marking cells in parallel fails.

### ISSUE THREAD

**Issue by miguelcoolchips** [firedrakeproject/firedrake#3118]
EDIT: I updated the MFE so that it also fails with the latest firedrake installed on a MacOS

**Describe the bug**
Bug when marking cells in parallel 

**Steps to Reproduce**
```python
import firedrake as fd
import numpy as np

from firedrake.cython.dmcommon import FACE_SETS_LABEL, CELL_SETS_LABEL
from firedrake.cython import dmcommon
from collections import namedtuple


def test_mfe():
    # mesh = fd.UnitSquareMesh(40, 8)  # Only fails in docker
    # n_verts_cell = 3# Only fails in docker
    mesh = fd.UnitSquareMesh(5, 1, quadrilateral=True)  # Fails on macos as well
    n_verts_cell = 4  # Fails on macos as well

    region_solid = namedtuple("Region", ["x0", "y0", "dx", "dy"])(0.0, 0.0, 0.5, 1e50)

    dm = mesh.topology_dm
    sec = dm.getCoordinateSection()
    coords = dm.getCoordinatesLocal()
    dm.createLabel(FACE_SETS_LABEL)
    dm.markBoundaryFaces("boundary_faces")

    cStart, cEnd = dm.getHeightStratum(0)

    marker = 100

    for cell in range(cStart, cEnd):
        vertices = dm.vecGetClosure(sec, coords, cell).reshape(n_verts_cell, 2)
        x_centroid, y_centroid = np.sum(vertices, axis=0) / n_verts_cell

        for region in [region_solid]:
            xmin = region.x0
            ymin = region.y0
            xmax = region.x0 + region.dx
            ymax = region.y0 + region.dy
            is_cell_in_region = (
                x_centroid >= xmin
                and x_centroid <= xmax
                and y_centroid >= ymin
                and y_centroid <= ymax
            )
            if is_cell_in_region:
                dm.setLabelValue(CELL_SETS_LABEL, cell, marker)
            # Marking all the cells will make it work too
            # else:
            #    dm.setLabelValue(CELL_SETS_LABEL, cell, 2)

    if mesh.topology.comm.size > 1:
        dmcommon.set_adjacency_callback(mesh.topology.topology_dm)
        original_name = mesh.topology.topology_dm.getName()
        overlap = 1
        sfBC = mesh.topology.topology_dm.distributeOverlap(overlap)
        mesh.topology.topology_dm.setName(original_name)
        mesh.topology.sfBC = (
            mesh.topology.sfBC.compose(sfBC) if mesh.topology.sfBC else sfBC
        )
        dmcommon.clear_adjacency_callback(mesh.topology.topology_dm)
        mesh.topology._grown_halos = True

    for name in [FACE_SETS_LABEL, "exterior_facets", "interior_facets"]:
        if dm.hasLabel(name):
            print(f"Checking label {name}")
            label = dm.getLabel(name)
            dm.labelComplete(label)
            print(f"Label is good {name}")

    # Will fail here anyways
    print(fd.assemble(fd.Constant(1.0) * fd.dx(marker, domain=mesh)))


if __name__ == "__main__":
    test_mfe()

```
with `mpiexec -n 2 python3 test_mfe.py`

**Expected behavior**
Expected not to crash

**Error message**
```
Checking label Face Sets
Checking label Face Sets
Traceback (most recent call last):
  File "/Users/miguel/work/glacierware/tests/test_mfe.py", line 72, in <module>
Traceback (most recent call last):
  File "/Users/miguel/work/glacierware/tests/test_mfe.py", line 72, in <module>
    test_mfe()
  File "/Users/miguel/work/glacierware/tests/test_mfe.py", line 64, in test_mfe
    test_mfe()
  File "/Users/miguel/work/glacierware/tests/test_mfe.py", line 64, in test_mfe
    dm.labelComplete(label)
  File "petsc4py/PETSc/DMPlex.pyx", line 490, in petsc4py.PETSc.DMPlex.labelComplete
petsc4py.PETSc.Error: error code 63
[1] DMPlexLabelComplete() at /Users/miguel/repos/firedrake-21-June-2023/src/petsc/src/dm/impls/plex/plexsubmesh.c:227
[1] DMPlexLabelComplete_Internal() at /Users/miguel/repos/firedrake-21-June-2023/src/petsc/src/dm/impls/plex/plexsubmesh.c:159
[1] DMPlexGetTransitiveClosure() at /Users/miguel/repos/firedrake-21-June-2023/src/petsc/src/dm/impls/plex/plex.c:3833
[1] DMPlexGetTransitiveClosure_Internal() at /Users/miguel/repos/firedrake-21-June-2023/src/petsc/src/dm/impls/plex/plex.c:3777
[1] DMPlexGetCellType() at /Users/miguel/repos/firedrake-21-June-2023/src/petsc/src/dm/impls/plex/plex.c:5169
[1] Argument out of range
[1] Cell 10 has not been assigned a cell type
Abort(1) on node 1 (rank 1 in comm 496): application called MPI_Abort(PYOP2_COMM_WORLD, 1) - process 1
    dm.labelComplete(label)
  File "petsc4py/PETSc/DMPlex.pyx", line 490, in petsc4py.PETSc.DMPlex.labelComplete
petsc4py.PETSc.Error: error code 63
[0] DMPlexLabelComplete() at /Users/miguel/repos/firedrake-21-June-2023/src/petsc/src/dm/impls/plex/plexsubmesh.c:227
[0] DMPlexLabelComplete_Internal() at /Users/miguel/repos/firedrake-21-June-2023/src/petsc/src/dm/impls/plex/plexsubmesh.c:159
[0] DMPlexGetTransitiveClosure() at /Users/miguel/repos/firedrake-21-June-2023/src/petsc/src/dm/impls/plex/plex.c:3833
[0] DMPlexGetTransitiveClosure_Internal() at /Users/miguel/repos/firedrake-21-June-2023/src/petsc/src/dm/impls/plex/plex.c:3777
[0] DMPlexGetCellType() at /Users/miguel/repos/firedrake-21-June-2023/src/petsc/src/dm/impls/plex/plex.c:5169
[0] Argument out of range
[0] Cell 9 has not been assigned a cell type
Abort(1) on node 0 (rank 0 in comm 496): application called MPI_Abort(PYOP2_COMM_WORLD, 1) - process 0
```

**Environment:**
 - OS: Linux
 - Python version:  Python 3.11.0rc2
 - Output of `firedrake-status`:
 ```
(firedrake) firedrake@0b6438b6a535:~$ firedrake-status
/Users/miguel/repos/firedrake-21-June-2023/bin/firedrake-status:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('firedrake==0.13.0+5857.gca687792e')
Firedrake Configuration:
    package_manager: True
    minimal_petsc: False
    mpicc: mpicc
    mpicxx: mpicxx
    mpif90: mpif90
    mpiexec: mpiexec
    disable_ssh: False
    honour_petsc_dir: False
    with_parmetis: False
    slepc: True
    packages: []
    honour_pythonpath: False
    opencascade: False
    tinyasm: False
    torch: False
    petsc_int_type: int32
    cache_dir: /Users/miguel/repos/firedrake-21-June-2023/.cache
    complex: False
    remove_build_files: False
    with_blas: None
    netgen: False
Additions:
    None
Environment:
    PYTHONPATH: None
    PETSC_ARCH: None
    PETSC_DIR: None
Status of components:
---------------------------------------------------------------------------
|Package             |Branch                        |Revision  |Modified  |
---------------------------------------------------------------------------
|FInAT               |master                        |f493084   |False     |
|PyOP2               |master                        |da14715c  |False     |
|fiat                |master                        |e440a06   |False     |
|firedrake           |master                        |ca687792e |False     |
|h5py                |firedrake                     |6cc4c912  |False     |
|libspatialindex     |master                        |4768bf3   |True      |
|libsupermesh        |master                        |dbe226b   |False     |
|loopy               |main                          |8158afdb  |False     |
|petsc               |firedrake                     |9364cb008b|False     |
|pyadjoint           |master                        |d532d41   |False     |
|pytest-mpi          |main                          |a478bc8   |False     |
|slepc               |firedrake                     |e438e4993 |False     |
|tsfc                |master                        |47c1324   |False     |
|ufl                 |master                        |cf66c4b3  |False     |
---------------------------------------------------------------------------
```
 - Any relevant environment variables or modifications [eg: PYOP2_DEBUG=1]

**Comment by ksagiyam** [comment]
`dm.setLabelValue(CELL_SETS_LABEL, cell, marker)` implicitly creates `CELL_SETS_LABEL` on the `dm`, but if this function is called or not on a given rank depends on the mesh data, and the local `dm` can end up not having `CELL_SETS_LABEL`, which seems to be causing the issue. To avoid this, you can put `dm.createLabel(CELL_SETS_LABEL)` explicitly before the for loop.

**Comment by miguelcoolchips** [comment]
Perfect! Thanks a lot!
