### ISSUE TITLE
BUG: Failing to compute the Jacobian of a FormSum

### ISSUE THREAD

**Issue by pbrubeck** [firedrakeproject/firedrake#3206]
**Describe the bug**
We fail to compute the symbolic Jacobian when the residual is provided as a `FormSum`.

**Steps to Reproduce**
```
from firedrake import *

mesh = UnitIntervalMesh(1)
V = FunctionSpace(mesh, "DG", 0)
v = TestFunction(V)
u = TrialFunction(V)
c = Cofunction(V.dual())

z = Function(V)
a = inner(v, u)*dx
L = action(c, v)

F = action(a, z) - L

solve(a == L, z) # works
solve(F == 0, z, J=a) # works
solve(F == 0, z) # fails
```

**Expected behavior**
All three cases should work.

**Error message**
```
Traceback (most recent call last):
  File "/home/pbrubeck/git/dphil_thesis/static_condensation/snippets/test_cofunction.py", line 17, in <module>
    solve(F == 0, z) # fails
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/firedrake/firedrake/adjoint_utils/solving.py", line 57, in wrapper
    output = solve(*args, **kwargs)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/firedrake/firedrake/solving.py", line 128, in solve
    _solve_varproblem(*args, **kwargs)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/firedrake/firedrake/solving.py", line 174, in _solve_varproblem
    solver = vs.NonlinearVariationalSolver(problem, solver_parameters=solver_parameters,
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/pyadjoint/pyadjoint/tape.py", line 109, in wrapper
    return function(*args, **kwargs)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/firedrake/firedrake/adjoint_utils/variational_solver.py", line 44, in wrapper
    init(self, problem, *args, **kwargs)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/firedrake/firedrake/variational_solver.py", line 210, in __init__
    ctx.set_jacobian(self.snes)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/firedrake/firedrake/solving_utils.py", line 302, in set_jacobian
    snes.setJacobian(self.form_jacobian, J=self._jac.petscmat,
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/firedrake/firedrake/solving_utils.py", line 504, in _jac
    return allocate_matrix(self.J,
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/pbrubeck/firedrake-dev-20221228-mpich/src/firedrake/firedrake/assemble.py", line 387, in allocate_matrix
    integral_types = set(i.integral_type() for i in expr.integrals())
AttributeError: 'FormSum' object has no attribute 'integrals'
```

**Comment by nbouziani** [comment]
Given that `c` is in a know function on $`V^{*}`$ ( $`c : V \mapsto \mathbb{R} `$), I don't think the following line makes sense:

```
L = action(c, v)
```

since `v` is a `TestFunction` (unknown function on $`V`$) and not a `Function`. `L` should be `c`.

However, replacing `L` by the cofunction `c` won't change the problem, which is caused by the fact that `allocate_matrix` only supports `Matrix` and `ImplicitMatrix`. I think the solution would be to extend it to support arbitrary `BaseForm` objects such as the Jacobian of `F` in your case.

**Comment by nbouziani** [comment]
Although the fact that `AssembledMatrix` doesn't make any assumption about the sparsity of the matrix might be problematic for allocation.
