### ISSUE TITLE
BUG: Point Forcing Failure

### ISSUE THREAD

**Issue by ReubenHill** [firedrakeproject/firedrake#3217]
**Describe the bug**
Point forcing of the poisson problem doesn't work, despite not strictly requiring symbolic interpolation.

**Steps to Reproduce**

Run the following
```python
from firedrake import *
import numpy as np

omega = UnitSquareMesh(2, 2)
coords = np.asarray([[0.5, 0.25], [0.5, 0.75], [0.25, 0.5], [0.75, 0.5]])
omega_v = VertexOnlyMesh(omega, coords)
U = FunctionSpace(omega, "CG", 1)
x, y = SpatialCoordinate(omega)
f = Function(U).interpolate(x*y)
P0DG = FunctionSpace(omega_v, "DG", 0)
I = Interpolator(TestFunction(U), P0DG)
f_v = I.interpolate(f)
v_v = TestFunction(P0DG)
cofunction_f_v = assemble(f_v*v_v*dx)
cofunction_f_v_omega = I.interpolate(cofunction_f_v, transpose=True)

u = Function(U)
v = TestFunction(U)

temp_cofunction = assemble(v*dx)
# cofunction_f_v_omega has type Function(U) but it should be a cofunction, I
# force that here.
temp_cofunction.dat.data_wo[:] = cofunction_f_v_omega.dat.data_ro

F = inner(grad(u), grad(v)) * dx
F = assemble(F)
F = F - temp_cofunction
bc = DirichletBC(U, 0, "on_boundary")
solve(F == 0, u, bc)
```

**Expected behavior**
Produce a solution. This does not need symbolic interpolation, because the solution itself is not interpolated. Were the solution interpolated, it would have to be recalculated inside the newton loop each time, but that is not the case here.

**Error message**
Fails on the last line (solve)
```
Traceback (most recent call last):
  File "/Users/rwh10/thesis/test.py", line 27, in <module>
    solve(F == 0, u, bc)
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/Users/rwh10/firedrake-current/src/firedrake/firedrake/adjoint_utils/solving.py", line 57, in wrapper
    output = solve(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rwh10/firedrake-current/src/firedrake/firedrake/solving.py", line 128, in solve
    _solve_varproblem(*args, **kwargs)
  File "/Users/rwh10/firedrake-current/src/firedrake/firedrake/solving.py", line 171, in _solve_varproblem
    problem = vs.NonlinearVariationalProblem(eq.lhs, u, bcs, J, Jp,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/Users/rwh10/firedrake-current/src/pyadjoint/pyadjoint/tape.py", line 109, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rwh10/firedrake-current/src/firedrake/firedrake/adjoint_utils/variational_solver.py", line 26, in wrapper
    self._ad_adj_F = adjoint(dFdu)
                     ^^^^^^^^^^^^^
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/Users/rwh10/firedrake-current/src/firedrake/firedrake/ufl_expr.py", line 336, in adjoint
    return ufl.adjoint(form, reordered_arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rwh10/firedrake-current/src/ufl/ufl/formoperators.py", line 169, in adjoint
    return Adjoint(form)
           ^^^^^^^^^^^^^
  File "/Users/rwh10/firedrake-current/src/ufl/ufl/adjoint.py", line 42, in __new__
    return ZeroBaseForm(form.arguments()[::-1])
                        ^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'arguments'
```

**Environment:**
 - OS: MacOS
 - Python version: 3.11.3
 - Output of `firedrake-status`
```
Firedrake Configuration:
    package_manager: True
    minimal_petsc: False
    mpicc: None
    mpicxx: None
    mpif90: None
    mpiexec: None
    disable_ssh: False
    honour_petsc_dir: False
    with_parmetis: False
    slepc: False
    packages: []
    honour_pythonpath: False
    opencascade: False
    tinyasm: False
    torch: False
    petsc_int_type: int32
    cache_dir: /Users/rwh10/firedrake-current/.cache
    complex: False
    remove_build_files: False
    with_blas: download
    netgen: False
Additions:
    None
Environment:
    PYTHONPATH: None
    PETSC_ARCH: None
    PETSC_DIR: None
Status of components:
---------------------------------------------------------------------------
|Package             |Branch                        |Revision  |Modified  |
---------------------------------------------------------------------------
|FInAT               |master                        |f493084   |False     |
|PyOP2               |master                        |da14715c  |False     |
|fiat                |master                        |e440a06   |False     |
|firedrake           |master                        |7e8bd413d |False     |
|h5py                |firedrake                     |6cc4c912  |False     |
|libspatialindex     |master                        |4768bf3   |True      |
|libsupermesh        |master                        |dbe226b   |False     |
|loopy               |main                          |8158afdb  |False     |
|petsc               |firedrake                     |37b8d52976|False     |
|pyadjoint           |master                        |cefba3f   |False     |
|pytest-mpi          |main                          |a478bc8   |False     |
|tsfc                |master                        |47c1324   |False     |
|ufl                 |master                        |cf66c4b3  |False     |
---------------------------------------------------------------------------
```

**Additional Info**
None

**Comment by ReubenHill** [comment]
@nbouziani is this something you've encountered and fixed in your interpolation branch?

**Comment by ReubenHill** [comment]
With an older firedrake:
```
Firedrake Configuration:
    package_manager: True
    minimal_petsc: False
    mpicc: None
    mpicxx: None
    mpif90: None
    mpiexec: None
    disable_ssh: False
    honour_petsc_dir: False
    with_parmetis: False
    slepc: False
    packages: []
    honour_pythonpath: False
    opencascade: False
    tinyasm: False
    torch: False
    petsc_int_type: int32
    cache_dir: /Users/rwh10/firedrake/.cache
    complex: False
    remove_build_files: False
    with_blas: None
    netgen: False
Additions:
    None
Environment:
    PYTHONPATH: None
    PETSC_ARCH: None
    PETSC_DIR: None
Status of components:
---------------------------------------------------------------------------
|Package             |Branch                        |Revision  |Modified  |
---------------------------------------------------------------------------
|FInAT               |master                        |47f6c37   |False     |
|PyOP2               |master                        |8e4ad930  |False     |
|fiat                |master                        |8333cc1   |True      |
|firedrake           |master                        |99cd48e8a |False     |
|h5py                |firedrake                     |6cc4c912  |False     |
|libspatialindex     |master                        |4768bf3   |True      |
|libsupermesh        |master                        |b145b65   |False     |
|loopy               |main                          |8158afdb  |False     |
|petsc               |firedrake                     |9364cb008b|False     |
|pyadjoint           |master                        |42959ef   |False     |
|pytest-mpi          |main                          |a478bc8   |False     |
|tsfc                |master                        |6f72c9c   |False     |
|ufl                 |interp_dual                   |c26ea4f3  |False     |
---------------------------------------------------------------------------
```

I get the following
```
Traceback (most recent call last):
  File "/Users/rwh10/thesis/test.py", line 29, in <module>
    solve(F == 0, u, bc)
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/Users/rwh10/firedrake/src/firedrake/firedrake/adjoint_utils/solving.py", line 57, in wrapper
    output = solve(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rwh10/firedrake/src/firedrake/firedrake/solving.py", line 131, in solve
    return _la_solve(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rwh10/firedrake/src/firedrake/firedrake/solving.py", line 231, in _la_solve
    solver = ls.LinearSolver(A, solver_parameters=solver_parameters,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/Users/rwh10/firedrake/src/firedrake/firedrake/linear_solver.py", line 49, in __init__
    raise TypeError("Provided operator is a '%s', not a MatrixBase" % type(A).__name__)
TypeError: Provided operator is a 'bool', not a MatrixBase
```

**Comment by nbouziani** [comment]
I am confused with the problem you are solving. Why are you doing:

```
F = assemble(F)
```
before solving the PDE ? Now you get a residual that doesn't even depend on `u`.

**Comment by ReubenHill** [comment]
Well by assembling that bit of F I get a concrete cofunction I can add to my adjoint interpolation cofunction to give the whole of F

**Comment by nbouziani** [comment]
You can't do that because now you have a residual form that doesn't know about `u`. The residual doesn't need to be assembled when passed into `solve`, it is just a symbolic linear form that depends on the solution `u`. The actual assembly happens later on when solving the linearised problem.

The right way to do the above example is:

```
a = inner(grad(u), grad(v)) * dx
L = temp_cofunction
bc = DirichletBC(U, 0, "on_boundary")
solve(a == L, u, bc)
```

which should now work.

**Comment by ReubenHill** [comment]
That works! Though I have to change `a` to be a bilinear form (`u = TrialFunction(U)`).

It doesn't work with the old Firedrake though. Any idea what was changed that lets this work?

**Comment by ReubenHill** [comment]
Running
```
from firedrake import *
import numpy as np

omega = UnitSquareMesh(2, 2)
coords = np.asarray([[0.5, 0.25], [0.5, 0.75], [0.25, 0.5], [0.75, 0.5]])
omega_v = VertexOnlyMesh(omega, coords)
U = FunctionSpace(omega, "CG", 1)
x, y = SpatialCoordinate(omega)
f = Function(U).interpolate(x*y)
P0DG = FunctionSpace(omega_v, "DG", 0)
I = Interpolator(TestFunction(U), P0DG)
f_v = I.interpolate(f)
v_v = TestFunction(P0DG)
cofunction_f_v = assemble(f_v*v_v*dx)
cofunction_f_v_omega = I.interpolate(cofunction_f_v, transpose=True)

u = TrialFunction(U)
v = TestFunction(U)
sol = Function(U)

L = assemble(v*dx)
# cofunction_f_v_omega has type Function(U) but it should be a cofunction, I
# force that here.
L.dat.data_wo[:] = cofunction_f_v_omega.dat.data_ro

a = inner(grad(u), grad(v)) *dx
bc = DirichletBC(U, 0, "on_boundary")
solve(a == L, sol, bc)
```
works with the initially reported `firedrake-status` but fails with the older `firedrake-status` giving this error message:
```
Traceback (most recent call last):
  File "/Users/rwh10/thesis/test.py", line 28, in <module>
    solve(a == L, sol, bc)
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/Users/rwh10/firedrake/src/firedrake/firedrake/adjoint_utils/solving.py", line 57, in wrapper
    output = solve(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rwh10/firedrake/src/firedrake/firedrake/solving.py", line 128, in solve
    _solve_varproblem(*args, **kwargs)
  File "/Users/rwh10/firedrake/src/firedrake/firedrake/solving.py", line 169, in _solve_varproblem
    raise TypeError("Only '0' support on RHS of nonlinear Equation, not %r" % eq.rhs)
TypeError: Only '0' support on RHS of nonlinear Equation, not Coefficient(WithGeometry(FunctionSpace(<firedrake.mesh.MeshTopology object at 0x12b889d90>, FiniteElement('Lagrange', triangle, 1), name=None), Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 1)), 30)
```

**Comment by nbouziani** [comment]
Great! I am not sure what has changed and it depends on how old was your firedrake, as the ability to solve problems with a cofunction RHS was fixed at the last UFL sprint.

**Comment by ReubenHill** [comment]
> Great! I am not sure what has changed and it depends on how old was your firedrake, as the ability to solve problems with a cofunction RHS was fixed at the last UFL sprint.

That'll be it
