### ISSUE TITLE
INSTALL: 

### ISSUE THREAD

**Issue by liangaomng** [firedrakeproject/firedrake#3232]
**Describe the error**
hello，i repory an issue
 Traceback (most recent call last):
  File "firedrake-install", line 1714, in <module>
    run_pip(["install", "-U", "setuptools==59.2.0"])  # Unpin this when numpy will build with latest setuptools
  File "firedrake-install", line 956, in run_pip
    check_call(pip + args)
  File "firedrake-install", line 653, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/liangaoming/hydrogym/third_party/firedrake/scripts/path/to/venv/bin/python', '-m', 'pip', 'install', '-U', 'setuptools==59.2.0']' returned non-zero exit status 2.

**Steps to Reproduce**

ie: The exact command used for installation/update  '...'

**Expected behavior**
Describe what you expected to happen.

**Error message**
Add error message with full backtrace.
Please add these as text using three backticks (`) for highlighting.
Please do not add screenshots.

Please also include either `firedrake-install.log` which is found in
the directory `firedrake-install` was run or `firedrake-update.log`
found in the virtualenv directory.

Additionally please include the PETSc configure log located in
`$VIRTUAL_ENV/src/petsc/configure.log`.

**Environment:**
 - ubuntu:18.04
 - python:3.6

**Additional context**

**Comment by liangaomng** [comment]
2023-11-15 09:57:54,747 INFO     installed.
2023-11-15 09:57:54,747 INFO   Checking for presence of package python3-venv...
2023-11-15 09:57:54,747 DEBUG  Running command 'dpkg-query -s python3-venv'
2023-11-15 09:57:54,752 DEBUG  Package: python3-venv
Status: install ok installed
Priority: optional
Section: python
Installed-Size: 11
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: allowed
Source: python3-defaults
Version: 3.6.7-1~18.04
Depends: python3.6-venv (>= 3.6.7-1~), python3 (= 3.6.7-1~18.04), python3-distutils (>= 3.6.7-1~)
Description: pyvenv-3 binary for python3 (default python3 version)
 Python, the high-level, interactive object oriented language,
 includes an extensive class library with lots of goodies for
 network programming, system administration, sounds and graphics.
 .
 This package is a dependency package, which depends on Debian's default
 Python 3 version (currently v3.6).
Homepage: https://www.python.org/
Original-Maintainer: Matthias Klose <doko@debian.org>

2023-11-15 09:57:54,752 INFO     installed.
2023-11-15 09:57:54,752 INFO   Checking for presence of package zlib1g-dev...
2023-11-15 09:57:54,752 DEBUG  Running command 'dpkg-query -s zlib1g-dev'
2023-11-15 09:57:54,757 DEBUG  Package: zlib1g-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 448
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: zlib
Version: 1:1.2.11.dfsg-0ubuntu2.2
Provides: libz-dev
Depends: zlib1g (= 1:1.2.11.dfsg-0ubuntu2.2), libc6-dev | libc-dev
Conflicts: zlib1-dev
Description: compression library - development
 zlib is a library implementing the deflate compression method found
 in gzip and PKZIP.  This package includes the development support
 files.
Homepage: http://zlib.net/
Original-Maintainer: Mark Brown <broonie@debian.org>

2023-11-15 09:57:54,757 INFO     installed.
2023-11-15 09:57:54,757 INFO   Checking for presence of package libboost-dev...
2023-11-15 09:57:54,757 DEBUG  Running command 'dpkg-query -s libboost-dev'
2023-11-15 09:57:54,762 DEBUG  Package: libboost-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 10
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: boost-defaults
Version: 1.65.1.0ubuntu1
Depends: libboost1.65-dev
Suggests: libboost-doc
Description: Boost C++ Libraries development files (default version)
 The Boost web site provides free, peer-reviewed, portable C++ source
 libraries. The emphasis is on libraries which work well with the C++
 Standard Library. One goal is to establish "existing practice" and
 provide reference implementations so that the Boost libraries are
 suitable for eventual standardization. Some of the libraries have
 already been proposed for inclusion in the C++ Standards Committee's
 upcoming C++ Standard Library Technical Report.
 .
 This package provides headers for all Boost libraries.
 .
 Extended precision arithmetic package libmpfrc++-dev or libntl-dev is
 required to use the Boost.Multiprecision wrapping of the respective
 library.
 .
 This package is a dependency package, which depends on Debian's default
 Boost version (currently 1.65).
Homepage: http://www.boost.org/
Original-Maintainer: Debian Boost Team <pkg-boost-devel@lists.alioth.debian.org>

2023-11-15 09:57:54,762 INFO     installed.
2023-11-15 09:57:54,762 INFO   Checking for presence of package libopenblas-dev...
2023-11-15 09:57:54,762 DEBUG  Running command 'dpkg-query -s libopenblas-dev'
2023-11-15 09:57:54,767 DEBUG  Package: libopenblas-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 52155
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: openblas
Version: 0.2.20+ds-4
Provides: libblas.so, liblapack.so
Depends: libopenblas-base (= 0.2.20+ds-4)
Breaks: libatlas-base-dev (<< 3.10.3-4~), libblas-dev (<< 3.7.1-2~), liblapack-dev (<< 3.7.1-2~)
Description: Optimized BLAS (linear algebra) library (development files)
 OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version.
 .
 Unlike Atlas, OpenBLAS provides a multiple architecture library.
 .
 All kernel will be included in the library and dynamically switched to
 the best architecture at run time (only on x86 arches).
 .
 This package includes the static libraries and symbolic links
 needed for program development.
Original-Maintainer: Debian Science Team <debian-science-maintainers@lists.alioth.debian.org>
Built-Using: lapack (= 3.7.1-3ubuntu2)
Homepage: https://github.com/xianyi/OpenBLAS

2023-11-15 09:57:54,767 INFO     installed.
2023-11-15 09:57:54,767 INFO   Creating firedrake venv in '/liangaoming/hydrogym/third_party/firedrake/scripts/path/to/venv'.
2023-11-15 09:57:55,528 DEBUG  Running command '/liangaoming/hydrogym/third_party/firedrake/scripts/path/to/venv/bin/python -m pip install -U setuptools==59.2.0'
2023-11-15 09:57:56,043 DEBUG  Exception:
Traceback (most recent call last):
  File "/liangaoming/hydrogym/third_party/firedrake/scripts/path/to/venv/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/liangaoming/hydrogym/third_party/firedrake/scripts/path/to/venv/lib/python3.6/site-packages/pip/commands/install.py", line 290, in run
    with self._build_session(options) as session:
  File "/liangaoming/hydrogym/third_party/firedrake/scripts/path/to/venv/lib/python3.6/site-packages/pip/basecommand.py", line 69, in _build_session
    if options.cache_dir else None
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not int

2023-11-15 09:57:56,044 INFO

Install log saved in /liangaoming/hydrogym/third_party/firedrake/scripts/firedrake-install.log

**Comment by liangaomng** [comment]
update：
Eigen tarball hash valid
Depending on your platform, PETSc may take an hour or more to build!
Installing pip dependencies for loopy
Installing pip dependencies for petsc4py
No dependencies found. Skipping.
Installing pip dependencies for ufl
No dependencies found. Skipping.
Installing pip dependencies for fiat
No dependencies found. Skipping.
Installing pip dependencies for FInAT
Traceback (most recent call last):
  File "/liangaoming/hydrogym/third_party/firedrake/scripts/firedrake-install", line 1864, in <module>
    pip_requirements(p, compiler_env)
  File "/liangaoming/hydrogym/third_party/firedrake/scripts/firedrake-install", line 991, in pip_requirements
    run_pip_install_wrap(reqs, parallel_compiler_env)
  File "/liangaoming/hydrogym/third_party/firedrake/scripts/firedrake-install", line 984, in run_pip_install_wrap
    run_pip_install([req])
  File "/liangaoming/hydrogym/third_party/firedrake/scripts/firedrake-install", line 965, in run_pip_install
    check_call(pipinstall + pipargs)
  File "/liangaoming/hydrogym/third_party/firedrake/scripts/firedrake-install", line 653, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/root/liangaoming/miniconda3/envs/myenv/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/root/liangaoming/miniconda3/envs/myenv/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/liangaoming/hydrogym/third_party/firedrake/scripts/venv/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,islpy,numpy', '-vvv', 'numpy>=1.16']' returned non-zero exit status 2.

**Comment by JDBetteridge** [comment]
It's very hard to read your error message, please use triple backticks to format multiline code blocks.

I notice two things immediately:
- You are using Python 3.6 which is not supported, see https://www.firedrakeproject.org/download.html#system-requirements .
- The fact that this doesn't throw an error and that `eigen` is being downloaded suggests that your install script is long out of date.

Please delete `firedrake-install` and follow the instructions here: https://www.firedrakeproject.org/download.html#obtaining-firedrake

**Comment by JDBetteridge** [comment]
I'm going to close this issue as there has been no response, feel free to open a new issue if you are still having problems.
