### ISSUE TITLE
BUG: failing to project into vector function space (Hdiv in horizontal and broken in vertical) on extruded mesh

### ISSUE THREAD

**Issue by karinakowalczyk** [firedrakeproject/firedrake#3244]
**Describe the bug**
After firedrake-update the projection into a specific vector function space (using Hdiv-conforming basis function in the horizontal and broken basis functions in vertical) on extruded meshes produces an error 
**Steps to Reproduce**
```
from firedrake import *
m = IntervalMesh(10, 1)
mesh = ExtrudedMesh(m,  5, layer_height=1/5, name='mesh')
horizontal_degree =1
vertical_degree =1

cell = mesh._base_mesh.ufl_cell().cellname()
#horizontal base spaces
S1 = FiniteElement("CG", cell, horizontal_degree + 1) 
S2 = FiniteElement("DG", cell, horizontal_degree, variant="equispaced")

# vertical base spaces
T0 = FiniteElement("CG", interval, vertical_degree + 1, variant="equispaced")
T1 = FiniteElement("DG", interval, vertical_degree, variant="equispaced")

# build spaces V2, V3, Vt
V2h_elt = HDiv(TensorProductElement(S1, T1))
V2v_elt = HDiv(TensorProductElement(S2, T0))
V2v_elt_broken = BrokenElement(V2v_elt)
V2_elt = EnrichedElement(V2h_elt, V2v_elt_broken)

V = FunctionSpace(mesh, V2_elt, name="new_velocity")

u = Function(V)
uexpr = as_vector([0., 1.])
u.project(uexpr)

```

**Error message**

```
Traceback (most recent call last):
  File "/Users/kk120/PhD-Code/compressible_Euler/test.py", line 27, in <module>
    u.project(uexpr)
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/Users/kk120/firedrake/src/firedrake/firedrake/adjoint_utils/function.py", line 47, in wrapper
    output = project(self, b, *args, **kwargs)
  File "/Users/kk120/firedrake/src/firedrake/firedrake/function.py", line 364, in project
    return projection.project(b, self, *args, **kwargs)
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/Users/kk120/firedrake/src/firedrake/firedrake/adjoint_utils/projection.py", line 34, in wrapper
    output = project(*args, **kwargs)
  File "/Users/kk120/firedrake/src/firedrake/firedrake/projection.py", line 79, in project
    use_slate_for_inverse=use_slate_for_inverse).project()
  File "/Users/kk120/firedrake/src/firedrake/firedrake/projection.py", line 182, in project
    self.apply_massinv(self.target, self.rhs)
  File "/Users/kk120/firedrake/src/firedrake/firedrake/projection.py", line 171, in apply_massinv
    return self.solver.solve
  File "/Users/kk120/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/kk120/firedrake/src/firedrake/firedrake/projection.py", line 158, in solver
    return firedrake.LinearSolver(self.A, solver_parameters=self.solver_parameters)
  File "/Users/kk120/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/kk120/firedrake/src/firedrake/firedrake/projection.py", line 151, in A
    A = firedrake.assemble(a, bcs=self.bcs,
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/Users/kk120/firedrake/src/firedrake/firedrake/adjoint_utils/assembly.py", line 19, in wrapper
    output = assemble(*args, **kwargs)
  File "/Users/kk120/firedrake/src/firedrake/firedrake/assemble.py", line 104, in assemble
    return assemble_base_form(expr, *args, **kwargs)
  File "/Users/kk120/firedrake/src/firedrake/firedrake/assemble.py", line 191, in assemble_base_form
    visited[e] = base_form_assembly_visitor(e, tensor, bcs, diagonal,
  File "/Users/kk120/firedrake/src/firedrake/firedrake/assemble.py", line 276, in base_form_assembly_visitor
    return _assemble_form(expr, tensor=tensor, bcs=bcs,
  File "/Users/kk120/firedrake/src/firedrake/firedrake/assemble.py", line 545, in _assemble_form
    return assembler.assemble()
  File "/Users/kk120/firedrake/src/firedrake/firedrake/assemble.py", line 682, in assemble
    self.execute_parloops()
  File "/Users/kk120/firedrake/src/firedrake/firedrake/assemble.py", line 702, in execute_parloops
    for parloop in self.parloops:
  File "/Users/kk120/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/kk120/firedrake/src/firedrake/firedrake/assemble.py", line 761, in parloops
    self.local_kernels, self.global_kernels
  File "/Users/kk120/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/kk120/firedrake/src/firedrake/firedrake/assemble.py", line 726, in local_kernels
    kernels = tsfc_interface.compile_form(
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/Users/kk120/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 261, in compile_form
    kinfos = TSFCKernel(f, prefix, parameters,
  File "/Users/kk120/firedrake/src/PyOP2/pyop2/caching.py", line 207, in __new__
    obj = make_obj()
  File "/Users/kk120/firedrake/src/PyOP2/pyop2/caching.py", line 197, in make_obj
    obj.__init__(*args, **kwargs)
  File "/Users/kk120/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 146, in __init__
    tree = tsfc_compile_form(form, prefix=name, parameters=parameters,
  File "/Users/kk120/firedrake/src/tsfc/tsfc/driver.py", line 79, in compile_form
    fd = ufl_utils.compute_form_data(form, complex_mode=complex_mode)
  File "/Users/kk120/firedrake/src/tsfc/tsfc/ufl_utils.py", line 56, in compute_form_data
    fd = ufl_compute_form_data(
  File "/Users/kk120/firedrake/src/ufl/ufl/algorithms/compute_form_data.py", line 281, in compute_form_data
    form = attach_estimated_degrees(form)
  File "/Users/kk120/firedrake/src/ufl/ufl/algorithms/compute_form_data.py", line 207, in attach_estimated_degrees
    degree = estimate_total_polynomial_degree(integral.integrand())
  File "/Users/kk120/firedrake/src/ufl/ufl/algorithms/estimate_degrees.py", line 380, in estimate_total_polynomial_degree
    degrees = map_expr_dags(de, [e])
  File "/Users/kk120/firedrake/src/ufl/ufl/corealg/map_dag.py", line 98, in map_expr_dags
    r = handlers[v._ufl_typecode_](v)
  File "/Users/kk120/firedrake/src/ufl/ufl/algorithms/estimate_degrees.py", line 77, in argument
    return v.ufl_element().embedded_superdegree  # FIXME: Use component to improve accuracy for mixed elements
  File "/Users/kk120/firedrake/src/FInAT/finat/ufl/enrichedelement.py", line 111, in embedded_superdegree
    return max(e.embedded_superdegree for e in self._elements)
TypeError: '>' not supported between instances of 'tuple' and 'int'
```

**Comment by connorjward** [comment]
This looks basically the same as https://github.com/firedrakeproject/firedrake/issues/3243.

**Comment by connorjward** [comment]
Yep. Almost identical. I'll have this merged ASAP.

**Comment by connorjward** [comment]
Fixed by https://github.com/FInAT/FInAT/pull/113
