### ISSUE TITLE
BUG: trace space doesn't have the correct embedded_superdegree property

### ISSUE THREAD

**Issue by tommbendall** [firedrakeproject/firedrake#3251]
**Describe the bug**
One set of the failures in Gusto following the UFL upgrade is related to determining the `embedded_superdegree` of a mixed system that includes a trace space on an extruded mesh.

The `embedded_superdegree` of a mixed element is found from:
```
max(e.embedded_superdegree for e in self.sub_elements)
```

However when `e` corresponds to a trace space on an extruded mesh, `e.embedded_superdegree` is a tuple. See below for an example of this.

This may be more appropriate as a FInAT issue but I can easily produce a minimum failing example in Firedrake that matches the failures in Gusto.

**Steps to Reproduce**
Here is a minimum failing example:
```
from firedrake import (IntervalMesh, ExtrudedMesh, FunctionSpace, Constant,
                       MixedFunctionSpace, TestFunctions, TrialFunctions,
                       dx, dS_h, dS_v, ds_b, ds_t, ds_v, lhs, rhs, Function,
                       LinearVariationalProblem, LinearVariationalSolver)

base_mesh = IntervalMesh(3, 10.0)
mesh = ExtrudedMesh(base_mesh, 3, 1.0)

# Create spaces
Vrho = FunctionSpace(mesh, "DG", 1)
Vtrace = FunctionSpace(mesh, "HDiv Trace", degree=(1, 1))  # <-- this no longer seems to be supported

# Create mixed problem
M = MixedFunctionSpace((Vrho, Vtrace))
phi, dl = TestFunctions(M)
rho, l0 = TrialFunctions(M)

# Constants to set rho and l0 to
rho_value = Constant(1.5)
l0_value = Constant(0.5)

# Details of mixed system are not important -- just set trial functions to be constants
eqn = (phi*(rho - rho_value)*dx
       + dl('+')*(l0('+') - l0_value)*(dS_h + dS_v)
       + dl('-')*(l0('-') + l0_value)*(dS_h + dS_v)
       + dl*(l0 - l0_value)*(ds_b + ds_t + ds_v))

# Solve problem
aeqn = lhs(eqn)
Leqn = rhs(eqn)

# Function for the full solution
rhol0 = Function(M)

prb = LinearVariationalProblem(aeqn, Leqn, rhol0)
solver = LinearVariationalSolver(prb)
solver.solve()   # <-- fails here!
```

**Expected behaviour**
This previously worked!

**Error message**
```
Traceback (most recent call last):
  File "/home/thomas/firedrake/src/gusto/odds_and_ends/trace_space_mfe.py", line 34, in <module>
    solver.solve()
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/thomas/firedrake/src/firedrake/firedrake/adjoint_utils/variational_solver.py", line 89, in wrapper
    out = solve(self, **kwargs)
  File "/home/thomas/firedrake/src/firedrake/firedrake/variational_solver.py", line 283, in solve
    self.snes.solve(None, work)
  File "petsc4py/PETSc/SNES.pyx", line 1555, in petsc4py.PETSc.SNES.solve
  File "petsc4py/PETSc/PETSc.pyx", line 323, in petsc4py.PETSc.PetscPythonErrorHandler
  File "petsc4py/PETSc/PETSc.pyx", line 323, in petsc4py.PETSc.PetscPythonErrorHandler
  File "petsc4py/PETSc/PETSc.pyx", line 323, in petsc4py.PETSc.PetscPythonErrorHandler
  File "petsc4py/PETSc/petscsnes.pxi", line 325, in petsc4py.PETSc.SNES_Function
  File "/home/thomas/firedrake/src/firedrake/firedrake/solving_utils.py", line 415, in form_function
    ctx._assemble_residual()
  File "/home/thomas/firedrake/src/firedrake/firedrake/assemble.py", line 682, in assemble
    self.execute_parloops()
  File "/home/thomas/firedrake/src/firedrake/firedrake/assemble.py", line 854, in execute_parloops
    for parloop in self.parloops:
  File "/home/thomas/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/thomas/firedrake/src/firedrake/firedrake/assemble.py", line 761, in parloops
    self.local_kernels, self.global_kernels
  File "/home/thomas/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/thomas/firedrake/src/firedrake/firedrake/assemble.py", line 726, in local_kernels
    kernels = tsfc_interface.compile_form(
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/thomas/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 261, in compile_form
    kinfos = TSFCKernel(f, prefix, parameters,
  File "/home/thomas/firedrake/src/PyOP2/pyop2/caching.py", line 207, in __new__
    obj = make_obj()
  File "/home/thomas/firedrake/src/PyOP2/pyop2/caching.py", line 197, in make_obj
    obj.__init__(*args, **kwargs)
  File "/home/thomas/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 146, in __init__
    tree = tsfc_compile_form(form, prefix=name, parameters=parameters,
  File "/home/thomas/firedrake/src/tsfc/tsfc/driver.py", line 79, in compile_form
    fd = ufl_utils.compute_form_data(form, complex_mode=complex_mode)
  File "/home/thomas/firedrake/src/tsfc/tsfc/ufl_utils.py", line 56, in compute_form_data
    fd = ufl_compute_form_data(
  File "/home/thomas/firedrake/src/ufl/ufl/algorithms/compute_form_data.py", line 281, in compute_form_data
    form = attach_estimated_degrees(form)
  File "/home/thomas/firedrake/src/ufl/ufl/algorithms/compute_form_data.py", line 207, in attach_estimated_degrees
    degree = estimate_total_polynomial_degree(integral.integrand())
  File "/home/thomas/firedrake/src/ufl/ufl/algorithms/estimate_degrees.py", line 380, in estimate_total_polynomial_degree
    degrees = map_expr_dags(de, [e])
  File "/home/thomas/firedrake/src/ufl/ufl/corealg/map_dag.py", line 98, in map_expr_dags
    r = handlers[v._ufl_typecode_](v)
  File "/home/thomas/firedrake/src/ufl/ufl/algorithms/estimate_degrees.py", line 87, in coefficient
    d = e.embedded_superdegree  # FIXME: Use component to improve accuracy for mixed elements
  File "/home/thomas/firedrake/src/FInAT/finat/ufl/mixedelement.py", line 264, in embedded_superdegree
    return max(e.embedded_superdegree for e in self.sub_elements)
TypeError: '>' not supported between instances of 'tuple' and 'int'
```

**Comment by connorjward** [comment]
I fixed some of these issues in FInAT yesterday. Is your Firedrake/FInAT newer than that?
It's entirely possible that cases were missed so if this is still an issue for you I will fix it ASAP.

**Comment by tommbendall** [comment]
Yes I was hoping that our failures were all the same as #3244 -- thanks for fixing that!

I think that did fix some of our failures so I updated my FInAT last but still had these failures. I think `FunctionSpace(mesh, "HDiv Trace", (h_degree, v_degree))` doesn't create a hdiv element, but actually just a plain `FiniteElement`

**Comment by connorjward** [comment]
OK. I'll hunt this down today 👍

**Comment by connorjward** [comment]
I have a [simple FInAT fix](https://github.com/FInAT/FInAT/pull/116) that you are welcome to try out. This makes the initial error go away but the MFE is still not passing due to needing to add some restrictions. I'm not really familiar enough with the finite element machinery to be confident that my fix is the right thing to do though.

**Comment by tommbendall** [comment]
I have tried your branch on my local machine which fixes many of the Gusto failures -- thanks!

I think your fix is correct, I think that trace spaces on extruded meshes should have a degree that is a tuple.

I have also updated my MFE so that it is actually expected to pass. It passes on my machine with your branch (while the MFE fails when running with FInAT master and a clean cache)
