### ISSUE TITLE
INSTALL: 

### ISSUE THREAD

**Issue by lynntf** [firedrakeproject/firedrake#3256]
**Describe the error**
Installation fails during petsc build

**Steps to Reproduce**
```zsh
curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
python3 firedrake-install
```

**Expected behavior**
I had a working installation of Firedrake before, I tried to update it using `firedrake-update`, that failed during the petsc build so I tried reinstalling from scratch, and that also failed during the petsc build.

**Error message**
Add error message with full backtrace.
```
/Users/tlynn/Code/firedrake/firedrake-install:20: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources.extern.packaging.version import Version, InvalidVersion
Running firedrake-install
Installing command line tools...
Checking brew doctor...
Installing required packages via homebrew...
Required package 'gcc' is already installed via Homebrew.
Required package 'autoconf' is already installed via Homebrew.
Required package 'make' is already installed via Homebrew.
Required package 'automake' is already installed via Homebrew.
Required package 'cmake' is already installed via Homebrew.
Required package 'libtool' is already installed via Homebrew.
Required package 'boost' is already installed via Homebrew.
Creating firedrake venv in '/Users/tlynn/Code/firedrake/firedrake'.
We use pybind11==2.9.2 until the issue with pybind11==2.10.0 is resolved.

BLAS config is {'BLAS': '/Users/tlynn/Code/firedrake/firedrake/src/petsc/default', 'OPENBLAS': '/Users/tlynn/Code/firedrake/firedrake/src/petsc/default', 'LDFLAGS': '-L/opt/homebrew/opt/gcc/lib/gcc/13'}
Configuration saved to /Users/tlynn/Code/firedrake/firedrake/.configuration.json
Cloning firedrake

Failed to clone firedrake using ssh, falling back to https.
Successfully cloned repository firedrake.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Creating firedrake-update script.
Pip installing VTK for Python 3.11 to venv
Cloning the dependencies of firedrake
Cloning ufl

Failed to clone ufl using ssh, falling back to https.
Successfully cloned repository ufl.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning fiat

Failed to clone fiat using ssh, falling back to https.
Successfully cloned repository fiat.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning FInAT

Failed to clone FInAT using ssh, falling back to https.
Successfully cloned repository FInAT.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning tsfc

Failed to clone tsfc using ssh, falling back to https.
Successfully cloned repository tsfc.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning PyOP2

Failed to clone PyOP2 using ssh, falling back to https.
Successfully cloned repository PyOP2.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning pyadjoint

Failed to clone pyadjoint using ssh, falling back to https.
Successfully cloned repository pyadjoint.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning petsc

Failed to clone petsc using ssh, falling back to https.
Successfully cloned repository petsc.
Checking out branch firedrake
Successfully checked out branch firedrake
Updating submodules.
Successfully updated submodules.
Cloning pytest-mpi

Failed to clone pytest-mpi using ssh, falling back to https.
Successfully cloned repository pytest-mpi.
Checking out branch main
Successfully checked out branch main
Updating submodules.
Successfully updated submodules.
Cloning the dependencies of PyOP2
Cloning loopy

Failed to clone loopy using ssh, falling back to https.
Successfully cloned repository loopy.
Checking out branch main
Successfully checked out branch main
Updating submodules.
Successfully updated submodules.
Installing petsc/
Depending on your platform, PETSc may take an hour or more to build!
Traceback (most recent call last):
  File "/Users/tlynn/Code/firedrake/firedrake-install", line 1907, in <module>
    install("petsc/")
  File "/Users/tlynn/Code/firedrake/firedrake-install", line 1051, in install
    build_and_install_petsc()
  File "/Users/tlynn/Code/firedrake/firedrake-install", line 1163, in build_and_install_petsc
    check_call([python, "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + petsc_options)
  File "/Users/tlynn/Code/firedrake/firedrake-install", line 664, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/tlynn/Code/firedrake/firedrake/bin/python', './configure', 'PETSC_DIR=/Users/tlynn/Code/firedrake/firedrake/src/petsc', 'PETSC_ARCH=default', '--download-mpich', '--download-scalapack', '--with-x=0', '--download-netcdf', '--download-superlu_dist', '--download-bison', '--with-shared-libraries=1', '--download-hwloc', '--download-metis', "--download-openblas-make-options='USE_THREAD=0 USE_LOCKING=1 USE_OPENMP=0'", '--with-zlib', '--download-mumps', '--download-suitesparse', '--download-hypre', '--LDFLAGS=-Wl,-ld_classic', '--download-hdf5', '--download-pnetcdf', '--download-openblas', '--CFLAGS=-Wno-implicit-function-declaration', '--with-fortran-bindings=0', '--download-chaco', '--download-ptscotch', '--download-mpich-configure-arguments=--disable-opencl', '--with-c2html=0', '--download-pastix', '--with-debugging=0', '--download-hwloc-configure-arguments=--disable-opencl']' returned non-zero exit status 1.


Install log saved in /Users/tlynn/Code/firedrake/firedrake-install.log
```

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/13445797/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/13445802/configure.log)

**Environment:**
 - OS: MacOS: Apple M1 Pro, Sonoma 14.1.1 (23B81)
 - Python version: 3.11.6
 - Any relevant environment variables or modifications: none

**Additional context**
Since I had a working installation before trying `firedrake-update`, I'm not really sure what happened.

**Comment by Ig-dolci** [comment]
Can you please follow these [instructions](https://github.com/firedrakeproject/firedrake/wiki/Installation-Issues-with-Firedrake-on-Xcode-15-for-MacOS-Users)? Keep us informed if it works for you.

**Comment by lynntf** [comment]
Thanks for the instructions.

I downloaded Xcode 15.1 Beta 315C5059c as `Xcode_15.1_beta_3.xip`. I then extracted `Xcode-beta.app` from it. I ran the app and it asked what platform I would be developing for and I selected MacOS. It then installed, but I do not know where. I have been unable to find where it was actually installed so I do not know where to direct the code in the shared instructions:
```
sudo xcode-select --switch /local_path_to_Xcode15beta
```

Where is Xcode installed?

I thought that perhaps the installation via the `.app` would have fixed the problem, so I tried `python3 firedrake-install` again, but encountered the same issue as before.

Thank you for your help.

**Comment by Ig-dolci** [comment]
Where your `Xcode-beta.app` is? Can you please add here the output of the command `clang -v`?

**Comment by lynntf** [comment]
Before making any changes, the output of `clang -v` is:
```zsh
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I then redirected it to the directory where I placed `Xcode-beta.app`:
```zsh
sudo xcode-select --switch /Applications/Xcode-beta.app
```

The output of `clang -v` after making that change is:
```zsh
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.1.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I will try the installation again now.

**Comment by lynntf** [comment]
The installation has succeeded and I am again able to import Firedrake successfully.

For posterity, the installation command line output is:
```
python3 firedrake-install                              
/Users/tlynn/Code/firedrake/firedrake-install:20: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources.extern.packaging.version import Version, InvalidVersion
Running firedrake-install
Installing command line tools...
Checking brew doctor...
Installing required packages via homebrew...
Required package 'gcc' is already installed via Homebrew.
Required package 'autoconf' is already installed via Homebrew.
Required package 'make' is already installed via Homebrew.
Required package 'automake' is already installed via Homebrew.
Required package 'cmake' is already installed via Homebrew.
Required package 'libtool' is already installed via Homebrew.
Required package 'boost' is already installed via Homebrew.
Creating firedrake venv in '/Users/tlynn/Code/firedrake/firedrake'.
We use pybind11==2.9.2 until the issue with pybind11==2.10.0 is resolved.

BLAS config is {'BLAS': '/Users/tlynn/Code/firedrake/firedrake/src/petsc/default', 'OPENBLAS': '/Users/tlynn/Code/firedrake/firedrake/src/petsc/default', 'LDFLAGS': '-L/opt/homebrew/opt/gcc/lib/gcc/13'}
Configuration saved to /Users/tlynn/Code/firedrake/firedrake/.configuration.json
Cloning firedrake

Failed to clone firedrake using ssh, falling back to https.
Successfully cloned repository firedrake.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Creating firedrake-update script.
Pip installing VTK for Python 3.11 to venv
Cloning the dependencies of firedrake
Cloning ufl

Failed to clone ufl using ssh, falling back to https.
Successfully cloned repository ufl.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning fiat

Failed to clone fiat using ssh, falling back to https.
Successfully cloned repository fiat.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning FInAT

Failed to clone FInAT using ssh, falling back to https.
Successfully cloned repository FInAT.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning tsfc

Failed to clone tsfc using ssh, falling back to https.
Successfully cloned repository tsfc.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning PyOP2

Failed to clone PyOP2 using ssh, falling back to https.
Successfully cloned repository PyOP2.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning pyadjoint

Failed to clone pyadjoint using ssh, falling back to https.
Successfully cloned repository pyadjoint.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning petsc

Failed to clone petsc using ssh, falling back to https.
Successfully cloned repository petsc.
Checking out branch firedrake
Successfully checked out branch firedrake
Updating submodules.
Successfully updated submodules.
Cloning pytest-mpi

Failed to clone pytest-mpi using ssh, falling back to https.
Successfully cloned repository pytest-mpi.
Checking out branch main
Successfully checked out branch main
Updating submodules.
Successfully updated submodules.
Cloning the dependencies of PyOP2
Cloning loopy

Failed to clone loopy using ssh, falling back to https.
Successfully cloned repository loopy.
Checking out branch main
Successfully checked out branch main
Updating submodules.
Successfully updated submodules.
Installing petsc/
Depending on your platform, PETSc may take an hour or more to build!
Installing numpy using setuptools==59.2.0 and wheel==0.37.0 and Cython==0.29.36
Installing numpy==1.24 due to performance regression
Updating setuptools and wheel to latest versions
Installing pip dependencies for loopy
Installing pip dependencies for petsc4py
No dependencies found. Skipping.
Installing pip dependencies for ufl
No dependencies found. Skipping.
Installing pip dependencies for fiat
No dependencies found. Skipping.
Installing pip dependencies for FInAT
Installing pip dependencies for tsfc
Installing pip dependencies for PyOP2
Installing pip dependencies for pyadjoint
No dependencies found. Skipping.
Installing pip dependencies for pytest-mpi
No dependencies found. Skipping.
Installing pip dependencies for firedrake
Installing h5py
Cloning h5py

Failed to clone h5py using ssh, falling back to https.
Successfully cloned repository h5py.
Checking out branch firedrake
Successfully checked out branch firedrake
Updating submodules.
Successfully updated submodules.
Linking h5py against HDF5_DIR=/Users/tlynn/Code/firedrake/firedrake/src/petsc/default

Removing existing h5py installations

Installing h5py/
Installing libsupermesh
Cloning libsupermesh

Failed to clone libsupermesh using ssh, falling back to https.
Successfully cloned repository libsupermesh.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Installing libspatialindex
Cloning libspatialindex

Failed to clone libspatialindex using ssh, falling back to https.
Successfully cloned repository libspatialindex.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Installing loopy/
Installing petsc4py/
Installing ufl/
Installing fiat/
Installing FInAT/
Installing tsfc/
Installing PyOP2/
Installing pyadjoint/
Installing pytest-mpi/
Installing firedrake/


Successfully installed Firedrake.


Firedrake has been installed in a python venv. You activate it with:

  . /Users/tlynn/Code/firedrake/firedrake/bin/activate

The venv can be deactivated by running:

  deactivate


To upgrade Firedrake activate the venv and run firedrake-update



Install log saved in /Users/tlynn/Code/firedrake/firedrake-install.log
```

The installation logs:
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/13452758/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/13452760/configure.log)

Thank you for your help.
