### ISSUE TITLE
BUG: BDM elements cannot be projected on different meshes

### ISSUE THREAD

**Issue by zhyxue0** [firedrakeproject/firedrake#3264]
Hello everyone! BDM elements cannot be projected on different meshes.
Here is my code
```python3
from firedrake import *

Lx = 2 
Ly = 2

Nx = 4
Ny = Nx


mesh_1 = RectangleMesh(Nx, Ny, Lx, Ly)
mesh_2 = RectangleMesh(2*Nx, 2*Ny, Lx, Ly)

V_1 = FunctionSpace(mesh_1, "BDM", 1)
V_2 = FunctionSpace(mesh_2, "BDM", 1)

u_1 = Function(V_1)
u_2 = project(u_1, V_2)
```
Here is the report:
```shell
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[12], line 17
     14 V_2 = FunctionSpace(mesh_2, "BDM", 1)
     16 u_1 = Function(V_1)
---> 17 u_2 = project(u_1, V_2)

File petsc4py/PETSc/Log.pyx:115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func()

File petsc4py/PETSc/Log.pyx:116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func()

File /home/firedrake/firedrake/src/firedrake/firedrake/adjoint/projection.py:34, in annotate_project..wrapper(*args, **kwargs)
     31             block = ProjectBlock(args[0], V, output, bcs, ad_block_tag=ad_block_tag, **sb_kwargs)
     33 with stop_annotating():
---> 34     output = project(*args, **kwargs)
     36 if annotate:
     37     tape = get_working_tape()

File /home/firedrake/firedrake/src/firedrake/firedrake/projection.py:78, in project(v, V, bcs, solver_parameters, form_compiler_parameters, use_slate_for_inverse, name, ad_block_tag)
     48 @PETSc.Log.EventDecorator()
     49 @annotate_project
     50 def project(v, V, bcs=None,
   (...)
     54             name=None,
     55             ad_block_tag=None):
     56     """Project a UFL expression into a :class:`.FunctionSpace`
     57     It is possible to project onto the trace space 'DGT', but not onto
     58     other trace spaces e.g. into the restriction of CG onto the facets.
   (...)
     73     then ``v`` is projected into a new :class:`.Function` and that
     74     :class:`.Function` is returned."""
     76     val = Projector(v, V, bcs=bcs, solver_parameters=solver_parameters,
     77                     form_compiler_parameters=form_compiler_parameters,
---> 78                     use_slate_for_inverse=use_slate_for_inverse).project()
     79     val.rename(name)
     80     return val

File /home/firedrake/firedrake/src/firedrake/firedrake/projection.py:181, in ProjectorBase.project(self)
    180 def project(self):
--> 181     self.apply_massinv(self.target, self.rhs)
    182     return self.target

File /home/firedrake/firedrake/src/firedrake/firedrake/projection.py:240, in SupermeshProjector.rhs(self)
    237 @property
    238 def rhs(self):
    239     with self.source.dat.vec_ro as u, self.residual.dat.vec_wo as v:
--> 240         self.mixed_mass.mult(u, v)
    241     return self.residual

File /home/firedrake/firedrake/src/PyOP2/pyop2/utils.py:62, in cached_property.__get__(self, obj, cls)
     60 if obj is None:
     61     return self
---> 62 obj.__dict__[self.__name__] = result = self.fget(obj)
     63 return result

File /home/firedrake/firedrake/src/firedrake/firedrake/projection.py:234, in SupermeshProjector.mixed_mass(self)
    231 @cached_property
    232 def mixed_mass(self):
    233     from firedrake.supermeshing import assemble_mixed_mass_matrix
--> 234     return assemble_mixed_mass_matrix(self.source.function_space(),
    235                                       self.target.function_space())

File petsc4py/PETSc/Log.pyx:115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func()

File petsc4py/PETSc/Log.pyx:116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func()

File /home/firedrake/firedrake/src/firedrake/firedrake/supermeshing.py:76, in assemble_mixed_mass_matrix(V_A, V_B)
     70     if V_A.ufl_element().mapping() != "identity" or V_B.ufl_element().mapping() != "identity":
     71         msg = """
     72 Sorry, only implemented for affine maps for now. To do non-affine, we'd need to
     73 import much more of the assembly engine of UFL/TSFC/etc to do the assembly on
     74 each supermesh cell.
     75 """
---> 76         raise NotImplementedError(msg)
     78     mesh_A = V_A.mesh()
     79     mesh_B = V_B.mesh()

NotImplementedError: 
Sorry, only implemented for affine maps for now. To do non-affine, we'd need to
import much more of the assembly engine of UFL/TSFC/etc to do the assembly on
each supermesh cell.
```

**Comment by colinjcotter** [comment]
You can do this by remapping the function to the enclosing DG space and transferring that, then remapping back to BDM.

**Comment by zhyxue0** [comment]
> You can do this by remapping the function to the enclosing DG space and transferring that, then remapping back to BDM.

Thanks. @colinjcotter   It works. But there also seemed to be new issues with reading the mesh when running in parallel on multiple cores.

Here is my code:
```python
from firedrake import *


num_refs = 3
Lx = 2 
Ly = 2


mesh_table = []
for i in range(num_refs):

    Nx = 4*2**(i)
    Ny = Nx
    mesh_1 = RectangleMesh(Nx, Ny, Lx, Ly)
    V_1 = VectorFunctionSpace(mesh_1, "DG", 1)
    
    u_1 = Function(V_1)
 
    mesh_table.append(mesh_1)


V_DG = VectorFunctionSpace(mesh_table[0], "DG", 1)
u_2 = project(u_1, V_DG)
    
```

Here is the report:
```shell
Traceback (most recent call last):
  File "/home/text_1.py", line 31, in <module>
Traceback (most recent call last):
  File "/home/text_1.py", line 31, in <module>
    u_2 = project(u_1, V_DG)
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
    u_2 = project(u_1, V_DG)
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/firedrake/src/firedrake/firedrake/adjoint/projection.py", line 34, in wrapper
  File "/home/firedrake/firedrake/src/firedrake/firedrake/adjoint/projection.py", line 34, in wrapper
    output = project(*args, **kwargs)
  File "/home/firedrake/firedrake/src/firedrake/firedrake/projection.py", line 78, in project
    output = project(*args, **kwargs)
  File "/home/firedrake/firedrake/src/firedrake/firedrake/projection.py", line 78, in project
    use_slate_for_inverse=use_slate_for_inverse).project()
  File "/home/firedrake/firedrake/src/firedrake/firedrake/projection.py", line 181, in projecTraceback (most recent call last):
  File "/home/text_1.py", line 19, in <module>
Traceback (most recent call last):
  File "/home/text_1.py", line 19, in <module>
    u_2 = project(u_1, V_DG)
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
    u_2 = project(u_1, V_DG)
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/firedrake/src/firedrake/firedrake/adjoint/projection.py", line 34, in wrapper
  File "/home/firedrake/firedrake/src/firedrake/firedrake/adjoint/projection.py", line 34, in wrapper
    output = project(*args, **kwargs)
  File "/home/firedrake/firedrake/src/firedrake/firedrake/projection.py", line 78, in project
    output = project(*args, **kwargs)
  File "/home/firedrake/firedrake/src/firedrake/firedrake/projection.py", line 78, in project
    use_slate_for_inverse=use_slate_for_inverse).project()
  File "/home/firedrake/firedrake/src/firedrake/firedrake/projection.py", line 181, in project
    use_slate_for_inverse=use_slate_for_inverse).project()
  File "/home/firedrake/firedrake/src/firedrake/firedrake/projection.py", line 181, in project
    self.apply_massinv(self.target, self.rhs)
  File "/home/firedrake/firedrake/src/firedrake/firedrake/projection.py", line 240, in rhs
    self.apply_massinv(self.target, self.rhs)
  File "/home/firedrake/firedrake/src/firedrake/firedrake/projection.py", line 240, in rhs
    self.mixed_mass.mult(u, v)
  File "/home/firedrake/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    self.mixed_mass.mult(u, v)
  File "/home/firedrake/firedrake/src/PyOP2/pyop2/utils.py", line 62, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/firedrake/firedrake/src/firedrake/firedrake/projection.py", line 234, in mixed_mass
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/firedrake/firedrake/src/firedrake/firedrake/projection.py", line 234, in mixed_mass
    return assemble_mixed_mass_matrix(self.source.function_space(),
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
    return assemble_mixed_mass_matrix(self.source.function_space(),
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/firedrake/src/firedrake/firedrake/supermeshing.py", line 97, in assemble_mixed_mass_matrix
  File "/home/firedrake/firedrake/src/firedrake/firedrake/supermeshing.py", line 97, in assemble_mixed_mass_matrix
    intersections = intersection_finder(mesh_A, mesh_B)
  File "firedrake/cython/supermeshimpl.pyx", line 132, in firedrake.cython.supermeshimpl.intersection_finder
    intersections = intersection_finder(mesh_A, mesh_B)
  File "firedrake/cython/supermeshimpl.pyx", line 132, in firedrake.cython.supermeshimpl.intersection_finder
AssertionError: Whoever made mesh_B should explicitly mark mesh_A as having a compatible parallel layout.
application called MPI_Abort(PYOP2_COMM_WORLD, 1) - process 0
AssertionError: Whoever made mesh_B should explicitly mark mesh_A as having a compatible parallel layout.
application called MPI_Abort(PYOP2_COMM_WORLD, 1) - process 1
```
