### ISSUE TITLE
BUG: problem with .assign()

### ISSUE THREAD

**Issue by hiroe-** [firedrakeproject/firedrake#3448]
I get `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()` when doing

```
N = Function(W)
A = Function(W)
A.assign(weights[0]*N)
```

where `W` is a mixed function space:

```
V1 = FunctionSpace(mesh, "BDM", 2)
V2 = FunctionSpace(mesh, "DG", 1)
W = MixedFunctionSpace((V1, V2))
```

and `weights` is a list of float numbers. The full error message is below.

```
Traceback (most recent call last):
  File "/home/hyamazak/repos/sketchpad/averaging/disc_aver_sw_paradiag.py", line 1062, in <module>
    average(U0, V1, t=t)
  File "/home/hyamazak/repos/sketchpad/averaging/disc_aver_sw_paradiag.py", line 754, in average
    Average.assign(Average+dt*weights[0]*N)
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/hyamazak/firedrake/src/firedrake/firedrake/adjoint_utils/function.py", line 118, in wrapper
    ret = assign(self, other, *args, **kwargs)
  File "/home/hyamazak/firedrake/src/firedrake/firedrake/function.py", line 459, in assign
    elif expr == 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

The error disappears when using Constant() around weights[0]:

```
N = Function(W)
A = Function(W)
A.assign(Constant(weights[0])*N)
```

The relevant code is here at line 754:

https://github.com/colinjcotter/sketchpad/blob/a85a61b6b06c105d4f5aa3d45527893f94d910ce/averaging/disc_aver_sw_paradiag.py

To reproduce the error, get rid of Constant() from line 754 and run the code with

$ mpiexec -n 2 python disc_aver_sw_paradiag.py 

**Environment:**
- Ubuntu 22.04
- Python 3.10.6
- Output of `firedrake-status`
```
Firedrake Configuration:
    package_manager: True
    minimal_petsc: False
    mpicc: None
    mpicxx: None
    mpif90: None
    mpiexec: None
    disable_ssh: False
    honour_petsc_dir: False
    with_parmetis: False
    slepc: False
    packages: []
    honour_pythonpath: False
    opencascade: False
    tinyasm: False
    torch: False
    petsc_int_type: int32
    cache_dir: /home/hyamazak/firedrake/.cache
    complex: False
    remove_build_files: False
    with_blas: None
    netgen: False
Additions:
    None
Environment:
    PYTHONPATH: None
    PETSC_ARCH: None
    PETSC_DIR: None
Status of components:
---------------------------------------------------------------------------
|Package             |Branch                        |Revision  |Modified  |
---------------------------------------------------------------------------
|FInAT               |master                        |e2805c4   |False     |
|PyOP2               |master                        |ad0c4303  |False     |
|fiat                |master                        |e7b2909   |False     |
|firedrake           |master                        |ef503daef |False     |
|h5py                |firedrake                     |4c01efa9  |False     |
|libspatialindex     |master                        |4768bf3   |True      |
|libsupermesh        |master                        |dbe226b   |False     |
|loopy               |main                          |8158afdb  |False     |
|petsc               |firedrake                     |09f36907a6|False     |
|pyadjoint           |master                        |2c6614d   |False     |
|pytest-mpi          |main                          |a478bc8   |False     |
|tsfc                |master                        |799191d   |False     |
|ufl                 |master                        |054b0617  |False     |
---------------------------------------------------------------------------
```

**Comment by connorjward** [comment]
So this is an interesting bit of Python and numpy magic that is going on. If you multiply a *numpy* float by a container (think list, tuple, array etc) then numpy actually goes and does the vectorised thing and multiplies by each element to produce a new array. E.g. `np.float64(0.1) * [1, 2, 3] == [0.1, 0.2, 0.3]`.

I was able to produce a minimal example showing that custom data types need to define `__len__` and `__getitem__` for this to happen:
```py
import numpy as np


class MyContainer:
    def __init__(self, data):
        self._data = data

    def __len__(self):
        return len(self._data)

    def __getitem__(self, index):
        return self._data[index]

    # Uncommenting this line prevents the behaviour
    # __iter__ = None


myobj = MyContainer([1, 2, 3])

print(np.float64(0.1) * myobj)  # prints [0.1, 0.2, 0.3]
print(0.1 * myobj)  # errors
```

What is happening specifically here is that `Functions` are iterable (i.e. you can write `for indexed in my_function: ...`) and so multiplying by a numpy data type unpacks this and an array is passed through to `assign`, which confuses it.

I think there are 3 solutions here:
1. Document this as a confusing foot gun to avoid in `assign`.
2. Make `assign` work with arrays.
3. Make `Functions` not be iterable (set `__iter__` to `None`).

I prefer option 3 but that would require changes in UFL that might be breaking. I don't think that it makes sense for `Functions` to be iterable.

@dham what is your opinion?

**Comment by connorjward** [comment]
Leaving an idea from @jrmaddison for resolving this:

> A custom __array__ufunc__ might be able to workaround this. Something vaguely like (probably wrong or overcomplicated)
```
    def __array_ufunc__(self, ufunc, method, *inputs, **kwargs):
        from numbers import Real
        if ufunc == np.multiply and method == "__call__":
            a, b = inputs
            if isinstance(a, Real):
                return float(a) * b
        inputs = list(inputs)
        for i, input in enumerate(inputs):
            if input is self:
                inputs[i] = np.array(input)
        return getattr(ufunc, method)(*inputs, **kwargs)
```

A quick search also yielded [this potentially useful forum post](https://stackoverflow.com/questions/55386602/how-to-overide-numpy-ufunc-with-array-ufunc).
