### ISSUE TITLE
BUG: VertexOnlyMesh does not find a vertex of the domain on a surface

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#3462]
**Describe the bug**
I wanted to create a VertexOnlyMesh associated with a vertex of a surface (a hemisphere). I fetch the coordinates from `mesh.coordinates.dat.data` and pass them to the `VertexOnlyMesh` constructor, but it fails.

**Steps to Reproduce**

[bug.tar.gz](https://github.com/firedrakeproject/firedrake/files/14665827/bug.tar.gz)

1. Extract the .tar.gz
2. Run bug.py

**Expected behavior**
I expected the `VertexOnlyMesh` to successfully locate the vertex.

**Error message**
```
ERROR: Index_Intersects_id failed in libspatialindex!Traceback (most recent call last):
  File "/home/farrellp/git/umberto/poking-sphere/tdnns-formulation/bug.py", line 9, in <module>
    vom_mesh = VertexOnlyMesh(mesh, [vertex_coordinates])
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/farrellp/git/install-scripts/firedrake/firedrake-dev-20240123-mpich/src/firedrake/firedrake/mesh.py", line 3005, in VertexOnlyMesh
    raise error
firedrake.mesh.VertexOnlyMeshMissingPointsError: 1 vertices are outside the mesh and have been removed from the VertexOnlyMesh.
```

**Environment:**
 - OS: Ubuntu 22.04
 - Python version: 3.10.12
 - Output of `firedrake-status`
 
```
Firedrake Configuration:
    package_manager: False
    minimal_petsc: False
    mpicc: /home/farrellp/local/firedrake/firedrake-dev-20240123-mpich/src/petsc/linux-gnu-c-opt/bin/mpicc
    mpicxx: /home/farrellp/local/firedrake/firedrake-dev-20240123-mpich/src/petsc/linux-gnu-c-opt/bin/mpicxx
    mpif90: /home/farrellp/local/firedrake/firedrake-dev-20240123-mpich/src/petsc/linux-gnu-c-opt/bin/mpif90
    mpiexec: /home/farrellp/local/firedrake/firedrake-dev-20240123-mpich/src/petsc/linux-gnu-c-opt/bin/mpiexec
    disable_ssh: False
    honour_petsc_dir: True
    with_parmetis: True
    slepc: True
    packages: ['git+ssh://github.com/firedrakeproject/Irksome.git#egg=Irksome']
    honour_pythonpath: False
    opencascade: False
    tinyasm: False
    torch: False
    petsc_int_type: int32
    cache_dir: /home/farrellp/git/install-scripts/firedrake/firedrake-dev-20240123-mpich/.cache
    complex: False
    remove_build_files: False
    with_blas: None
    netgen: True
Additions:
    None
Environment:
    PYTHONPATH: None
    PETSC_ARCH: linux-gnu-c-opt
    PETSC_DIR: /home/farrellp/local/firedrake/firedrake-dev-20240123-mpich/src/petsc
Status of components:
---------------------------------------------------------------------------
|Package             |Branch                        |Revision  |Modified  |
---------------------------------------------------------------------------
|FInAT               |master                        |e3a869d   |False     |
|Irksome             |master                        |8dcaecf   |False     |
|PyOP2               |master                        |e0a4d3a9  |False     |
|fiat                |master                        |dbc1c5d   |False     |
|firedrake           |master                        |6f596f12f |True      |
|h5py                |firedrake                     |6b512e5e  |False     |
|libspatialindex     |master                        |4768bf3   |True      |
|libsupermesh        |master                        |84becef   |False     |
|loopy               |main                          |8158afdb  |True      |
|ngsPETSc            |main                          |e0f9628   |True      |
|petsc               |firedrake                     |09f36907a6|True      |
|pyadjoint           |master                        |f8cb3aa   |False     |
|pytest-mpi          |main                          |8241bdc   |False     |
|slepc               |firedrake                     |a3f39c853 |True      |
|tsfc                |master                        |90c20c5   |False     |
|ufl                 |master                        |054b0617  |True      |
---------------------------------------------------------------------------
```
 - Any relevant environment variables or modifications [eg: PYOP2_DEBUG=1]
None

**Additional Info**
None

**Comment by connorjward** [comment]
This works for me on a fresh install. I think `firedrake-update` got a bit messed up recently which has broken elements of point location. Can you check whether a fresh install of Firedrake fixes things?

**Comment by UZerbinati** [comment]
After a fresh firedrake install this is now working also on my side !

**Comment by pefarrell** [comment]
A fresh install also fixes it for me. Weird.
