### ISSUE TITLE
BUG: cannot create real function space on general hexahedral meshes

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#3547]
**Describe the bug**
I was expecting to be able to create real function spaces on hexahedral meshes, but it doesn't appear to work.

**Steps to Reproduce**
Run

```
from firedrake import *
mesh = UnitCubeMesh(2, 2, 2, hexahedral=True)
R = FunctionSpace(mesh, "R", 0)
```

**Expected behavior**
I expected this to work successfully.

**Error message**
```
Traceback (most recent call last):
  File "/tmp/mfe.py", line 4, in <module>
    R = FunctionSpace(mesh, "R", 0)
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/farrellp/git/install-scripts/firedrake/firedrake-dev-20240320-mpich/src/firedrake/firedrake/functionspace.py", line 105, in FunctionSpace
    return impl.WithGeometry.make_function_space(mesh, element, name=name)
  File "/home/farrellp/git/install-scripts/firedrake/firedrake-dev-20240320-mpich/src/firedrake/firedrake/functionspaceimpl.py", line 368, in make_function_space
    check_element(element)
  File "/home/farrellp/git/install-scripts/firedrake/firedrake-dev-20240320-mpich/src/firedrake/firedrake/functionspaceimpl.py", line 54, in check_element
    raise NotImplementedError("Currently can only use 'Q' and/or 'DQ' elements on hexahedral meshes, not", element.family())
NotImplementedError: ("Currently can only use 'Q' and/or 'DQ' elements on hexahedral meshes, not", 'Real')
```

**Environment:**
 - OS: Linux, Ubuntu 22.04
 - Python version: 3.10.12
 - Output of `firedrake-status`
 
 ```
 Firedrake Configuration:
    package_manager: False
    minimal_petsc: False
    mpicc: /home/farrellp/local/firedrake/firedrake-dev-20240320-mpich/src/petsc/linux-gnu-c-opt/bin/mpicc
    mpicxx: /home/farrellp/local/firedrake/firedrake-dev-20240320-mpich/src/petsc/linux-gnu-c-opt/bin/mpicxx
    mpif90: /home/farrellp/local/firedrake/firedrake-dev-20240320-mpich/src/petsc/linux-gnu-c-opt/bin/mpif90
    mpiexec: /home/farrellp/local/firedrake/firedrake-dev-20240320-mpich/src/petsc/linux-gnu-c-opt/bin/mpiexec
    disable_ssh: False
    honour_petsc_dir: True
    with_parmetis: True
    slepc: True
    packages: ['git+ssh://github.com/firedrakeproject/Irksome.git#egg=Irksome']
    honour_pythonpath: False
    opencascade: False
    tinyasm: False
    torch: False
    petsc_int_type: int32
    cache_dir: /home/farrellp/git/install-scripts/firedrake/firedrake-dev-20240320-mpich/.cache
    complex: False
    remove_build_files: False
    with_blas: None
    netgen: True
Additions:
    None
Environment:
    PYTHONPATH: None
    PETSC_ARCH: linux-gnu-c-opt
    PETSC_DIR: /home/farrellp/local/firedrake/firedrake-dev-20240320-mpich/src/petsc
Status of components:
---------------------------------------------------------------------------
|Package             |Branch                        |Revision  |Modified  |
---------------------------------------------------------------------------
|FInAT               |master                        |e3a869d   |False     |
|Irksome             |master                        |4526f43   |False     |
|PyOP2               |master                        |f424fb5f  |False     |
|fiat                |master                        |dbc1c5d   |False     |
|firedrake           |master                        |6cdf035ec |True      |
|h5py                |firedrake                     |6b512e5e  |False     |
|libsupermesh        |master                        |84becef   |False     |
|loopy               |main                          |6f7f72a4  |False     |
|ngsPETSc            |main                          |f83b50a   |False     |
|petsc               |firedrake                     |fe466959bc|False     |
|pyadjoint           |master                        |908b636   |False     |
|pytest-mpi          |main                          |8241bdc   |False     |
|slepc               |firedrake                     |ba5c3effc |False     |
|tsfc                |master                        |90c20c5   |False     |
|ufl                 |master                        |fbd288e6  |False     |
---------------------------------------------------------------------------
```

 - Any relevant environment variables or modifications [eg: PYOP2_DEBUG=1]
 
 `PYOP2_CFLAGS` is set to `-DEIGEN_STACK_ALLOCATION_LIMIT=0`.

**Additional Info**
N/A

**Comment by ksagiyam** [comment]
Relaxed the check: https://github.com/firedrakeproject/firedrake/pull/3549.

**Comment by ksagiyam** [comment]
Merged https://github.com/firedrakeproject/firedrake/pull/3549
