### ISSUE TITLE
running error for Marmousi model 

### ISSUE THREAD

**Issue by acse-yw11823** [firedrakeproject/firedrake#3646]
Hello, I need to download the Meshes and associated velocity models from [here](https://zenodo.org/record/5172307#.YRFJoS1h1pQ). And for the 2D FWI, the guess meshes are generated by running the Python script ```make_guess_meshes.py``` which uses the Python package [SeismicMesh](https://github.com/krober10nd/SeismicMesh). I meet the following error when I running ```make_guess_meshes.py``` :
```
(firedrake) (base) yw11823@IC-FVFL80FW1WGC FWI_2D_DATA % pyth
on make_guess_problem.py 
Traceback (most recent call last):
  File "/Users/yw11823/ACSE/irp/spyro/FWI_2D_DATA/make_guess_problem.py", line 14, in <module>
    ef = get_sizing_function_from_segy(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yw11823/ACSE/irp/firedrake/lib/python3.11/site-packages/SeismicMesh/sizing/mesh_size_function.py", line 135, in get_sizing_function_from_segy
    vp, nz, nx, ny = read_velocity_model(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/Users/yw11823/ACSE/irp/firedrake/lib/python3.11/site-packages/SeismicMesh/sizing/mesh_size_function.py", line 602, in read_velocity_model
    return _read_segy(filename)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/yw11823/ACSE/irp/firedrake/lib/python3.11/site-packages/SeismicMesh/sizing/mesh_size_function.py", line 637, in _read_segy
    with segyio.open(filename, ignore_geometry=True) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yw11823/ACSE/irp/firedrake/lib/python3.11/site-packages/segyio/open.py", line 162, in open
    fd = _segyio.segyiofd(str(filename), mode, endians[endian])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
```
I could not find ```vp_guess4.segy``` from anywhere. Does anyone have any clue??

Many thanks for the help!!!

**Comment by connorjward** [comment]
I recommend getting in touch with the code author and asking them. This isn't really a problem with Firedrake itself. Sorry we can't be more help.

**Comment by Ig-dolci** [comment]
This issue is not related to Firedrake and is being addressed [here](https://github.com/NDF-Poli-USP/spyro/issues/109#issuecomment-2186944492).
