### ISSUE TITLE
INSTALL: ImportError when running firedrake-update on Linux

### ISSUE THREAD

**Issue by adiegel** [firedrakeproject/firedrake#3653]
I recently attempted to update firedrake on my Linux machine (running Ubuntu 22.04.4 LTS). It has been a couple of years since I ran the update and I am not sure if that is the reason for the failure. If so, I can try uninstalling and reinstalling, but wanted to seek advice before doing so.

I got the following error:

**Error message**
Updating the git repository for h5py
Traceback (most recent call last):
  File "/home/mathstudent/firedrake/src/../bin/firedrake-update", line 2014, in <module>
    build_and_install_h5py()
  File "/home/mathstudent/firedrake/src/../bin/firedrake-update", line 1225, in build_and_install_h5py
    changed |= not is_installed("h5py")
  File "/home/mathstudent/firedrake/src/../bin/firedrake-update", line 1763, in is_installed
    importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mathstudent/firedrake/lib/python3.10/site-packages/h5py/__init__.py", line 25, in <module>
    from . import _errors
ImportError: libhdf5.so.200: cannot open shared object file: No such file or directory

I am also including the file `firedrake-install.log` and the 'configure.log' file.

[firedrake-update.log](https://github.com/user-attachments/files/15991607/firedrake-update.log)
[configure.log](https://github.com/user-attachments/files/15991616/configure.log)

**Comment by connorjward** [comment]
`firedrake-update` is unlikely to work if you haven't run it for a long time. Rather than debugging the issues I would strongly recommend a fresh install.

**Comment by adiegel** [comment]
Thanks! I will do that.
