### ISSUE TITLE
INSTALL: Linux (Ubuntu 22.04.4 LTS)

### ISSUE THREAD

**Issue by adiegel** [firedrakeproject/firedrake#3654]
**Describe the error**
I am attempting to install firedrake on a Linux machine running Ubuntu 22.04.4 LTS. My python version is Python 3.10.12. It appears that the installation failed. I am attaching the logs to this post. Any help is appreciated.

**Error message**
Traceback (most recent call last):
  File "/home/mathstudent/firedrake-install", line 1877, in <module>
    install(p+"/")
  File "/home/mathstudent/firedrake-install", line 1058, in install
    run_pip_install(["-e", package])
  File "/home/mathstudent/firedrake-install", line 991, in run_pip_install
    check_call(pipinstall + pipargs)
  File "/home/mathstudent/firedrake-install", line 672, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/mathstudent/firedrake/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,numpy', '--no-deps', '-v', '-e', 'firedrake/']' returned non-zero exit status 1.

[firedrake-install.log](https://github.com/user-attachments/files/15992827/firedrake-install.log)
[configure.log](https://github.com/user-attachments/files/15992833/configure.log)

**Comment by connorjward** [comment]
So the error message is
```
    gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
```
Looking online ([here](https://stackoverflow.com/questions/39455741/gcc-error-trying-to-exec-cc1plus-execvp-no-such-file-or-directory) and [here](https://askubuntu.com/questions/637014/gcc-error-trying-to-exec-cc1plus-execvp-no-such-file-or-directory)) it seems like you may just need to run

```
$ sudo apt install g++
```

This is the sort of thing that should happen automatically in the install script though so this is a bit confusing.

Please can you try making sure that your system is up-to-date and then try again? I recommend running the following:
```
$ sudo apt update
$ sudo apt upgrade
$ sudo apt install g++
```

It may be possible at that point to just run `firedrake-update` (with the venv activated) instead of `firedrake-install`. I recommend trying that before doing a full install from scratch again.

**Comment by adiegel** [comment]
Hi Connor,
Thank you for your help. Unfortunately, that did not work. I also tried reinstalling firedrake. I am attaching the new logs, but it looks to be the same issue. Could my g++ compiler be on a version that is newer than firedrake requires? When I run $sudo apt install g++, I get the following:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
g++ is already the newest version (4:11.2.0-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```

[firedrake-install.log](https://github.com/user-attachments/files/16030769/firedrake-install.log)
[configure.log](https://github.com/user-attachments/files/16030778/configure.log)

**Comment by connorjward** [comment]
OK this looks like an issue with the [recent work done on tinyASM](https://github.com/firedrakeproject/firedrake/pull/3604). @JDBetteridge is there something wrong with the compiler invocation? I wonder if we should be calling `mpicxx` instead of `mpicc` below?

```
    building 'tinyasm._tinyasm' extension
    creating build/temp.linux-x86_64-cpython-310/tinyasm
    /home/mathstudent/firedrake/src/petsc/default/bin/mpicc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/mathstudent/firedrake/lib/python3.10/site-packages/petsc4py/include -I/home/mathstudent/firedrake/src/petsc/include -I/home/mathstudent/firedrake/src/petsc/default/include -I/home/mathstudent/firedrake/lib/python3.10/site-packages/pybind11/include -I/home/mathstudent/firedrake/include -I/usr/include/python3.10 -c tinyasm/matinvert.cpp -o build/temp.linux-x86_64-cpython-310/tinyasm/matinvert.o -fvisibility=hidden -g0 -std=c++11
    gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
    compilation terminated.
```

**Comment by zwenju** [comment]
I got the same error as  [adiegel](https://github.com/adiegel)   on a Linux machine running Ubuntu 22.04.4 LTS.

File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/usr/lib/python3.10/subprocess.py", line 526, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/mathstudent/firedrake/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,numpy', '--no-deps', '-v', '-e', 'firedrake/']' returned non-zero exit status 1.

**Comment by JDBetteridge** [comment]
I could not reproduce this error on a fresh Ubuntu 22.04 image. In order to be able to assist further, please check your system configuration and provide more details of exactly how you are trying to install.

My best guess at this point is that you have a broken C++ compiler on your system and this needs to be fixed before you will be able to install.

**Comment by zwenju** [comment]
Thanks [JDBetteridge](https://github.com/JDBetteridge).  
I found this error is induced by the gcc compiler with  memory aligned optimization.
By increasing the size of memory to 8G,  there will no any error on ubuntu 22.04.

**Comment by adiegel** [comment]
Hi @zwenju,
I am glad you figured it out. Could you expand on how you fixed the issue. What did you do to increase the memory? 

Thanks!

**Comment by zwenju** [comment]
[@adiegel    adiegel](https://github.com/adiegel)When I was see   [@JDBetteridge] successfully install firedrake on ubuntu 22.04，
I tracked the compilation of petsc4py  and found that  there is a gcc parameter related to  aligned memory for optimization.
So  I change a computer with 8G memory instead
The errors related to petsc4py did not appear again.

**Comment by adiegel** [comment]
Hi All,

I'm sorry. I guess I am being super dumb, but I am still not sure what to do to fix the issue. My machine has much more than 8G of memory. Do you mean I need to increase the amount of memory allocated to the gcc compiler. If so, could someone help me figure out how to do this?

Thanks.

**Comment by zwenju** [comment]
[adiegel](https://github.com/adiegel)  try to install a fresh ubuntu 22.04 with intel cpu.

**Comment by JDBetteridge** [comment]
I'm going to suggest that you are potentially having similar but unrelated issues, which is why we always encourage users to upload their log files.

@adiegel could you try compiling a simple C++ program with `g++` and then `mpicxx` to check the compiler is working correctly.

**Comment by adiegel** [comment]
Thanks @JDBetteridge. I tried a simple "hello world" C++ program and it ran fine with g++ but I got errors with the mpicxx compiler. Specifically, I got the following:

```
/usr/bin/ld: cannot find -lmpi_cxx: No such file or directory
/usr/bin/ld: cannot find -lmpi: No such file or directory
/usr/bin/ld: cannot find -lopen-rte: No such file or directory
/usr/bin/ld: cannot find -lopen-pal: No such file or directory
/usr/bin/ld: cannot find -lhwloc: No such file or directory
/usr/bin/ld: cannot find -levent_core: No such file or directory
/usr/bin/ld: cannot find -levent_pthreads: No such file or directory
collect2: error: ld returned 1 exit status
```

So, it seems to be an issue with the mpicxx compiler. Any thoughts?

**Comment by adiegel** [comment]
Hi @JDBetteridge,

If I am in the firedrake venv, I can compile a very basic hello_world.cc with both g++ and mpicxx. If I am not in the firedrake venv, g++ compiles just fine, but I get the following when I try to compile with mpicxx:

```
/usr/bin/ld: cannot find -lmpi_cxx: No such file or directory
/usr/bin/ld: cannot find -lmpi: No such file or directory
/usr/bin/ld: cannot find -lopen-rte: No such file or directory
/usr/bin/ld: cannot find -lopen-pal: No such file or directory
/usr/bin/ld: cannot find -lhwloc: No such file or directory
/usr/bin/ld: cannot find -levent_core: No such file or directory
/usr/bin/ld: cannot find -levent_pthreads: No such file or directory
collect2: error: ld returned 1 exit status
```

Does this help?

**Comment by adiegel** [comment]
@JDBetteridge, do you have any thoughts on how I can fix this issue? I tried updating my OS and redownloading Firedrake today but am still running into an error. Here is my updated .log file. I really need to get this running, so any help is greatly appreciated.

[firedrake-install.log](https://github.com/user-attachments/files/16431215/firedrake-install.log)

**Comment by JDBetteridge** [comment]
@adiegel I'm still not 100% sure what the issue here is, but I have 2 suggestions:

1. If you really need this running (and you aren't changing Firedrake or it's dependencies in any way) you can always use the docker container, which has the latest version of Firedrake installed.
```bash
sudo apt-get install docker.io
# mumble do something like enable the docker service
```
(Wouldn't it be great if Ubuntu [documented](https://wiki.archlinux.org/title/Docker) this stuff properly(!) ) try:
```bash
sudo systemctl enable docker
sudo systemctl start docker
```

Then download and run the container
```
sudo docker pull firedrakeproject/firedrake
sudo docker run -it firedrakeproject/firedrake
```
More info on [running containers](https://epcced.github.io/2024-04-16_containers_bham/).

2. We continue to debug this issue, but I need some more information:

### Without the virtualenv activated
 - Output of `dpkg-query -s gcc`
 - Output of `dpkg-query -s g++`
 - Output of `update-alternatives --all`
 - Create a file called `exe.c` with the following contents:
 
 ```c
#include <stdio.h>

int main(){return 0;};
```
(This looks odd but is compilable and runnable C (and C++) )

 - Output of `gcc --version` and `gcc exe.c` (should be nothing)
 - Output of `g++ --version` and `g++ exe.c` (might be nothing)
 - Output of `gcc -x c++ exe.c` (might be a clue)

### With the venv activated
 - Output of `mpicc --version` and `mpicc exe.c`
 - Output of `mpic++ --version` and `mpic++ exe.c`
 - Output of `mpicc -x c++ exe.c`

### Rationale
Your logs contain mismatched versions of C and C++ as detected by PETSc and also libsupermesh:
```
-- The C compiler identification is GNU 10.5.0
-- The CXX compiler identification is GNU 11.4.0
-- The Fortran compiler identification is GNU 11.4.0
```

It's possible that the `cc1plus` executable is only missing for a specific version of GCC, which is why installing `g++` didn't fix the problem.

**Comment by adiegel** [comment]
Thanks, @JDBetteridge. Going off your latest response, I have spent a good deal of time upgrading python, and my g++, gcc, and gfortran compilers. However, the install still failed. Here are the requested outputs and new log files.

### Without the virtualenv activated

**Output of `dpkg-query -s gcc`**
```
Package: gcc
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 50
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: gcc-defaults (1.193ubuntu1)
Version: 4:11.2.0-1ubuntu1
Provides: c-compiler, gcc-x86-64-linux-gnu (= 4:11.2.0-1ubuntu1)
Depends: cpp (= 4:11.2.0-1ubuntu1), gcc-11 (>= 11.2.0-1~)
Recommends: libc6-dev | libc-dev
Suggests: gcc-multilib, make, manpages-dev, autoconf, automake, libtool, flex, bison, gdb, gcc-doc
Conflicts: gcc-doc (<< 1:2.95.3)
Description: GNU C compiler
 This is the GNU C compiler, a fairly portable optimizing compiler for C.
 .
 This is a dependency package providing the default GNU C compiler.
Original-Maintainer: Debian GCC Maintainers <debian-gcc@lists.debian.org>
```

**Output of `dpkg-query -s g++`**
```
Package: g++
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 16
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: gcc-defaults (1.193ubuntu1)
Version: 4:11.2.0-1ubuntu1
Provides: c++-compiler, g++-x86-64-linux-gnu (= 4:11.2.0-1ubuntu1)
Depends: cpp (= 4:11.2.0-1ubuntu1), gcc (= 4:11.2.0-1ubuntu1), g++-11 (>= 11.2.0-1~), gcc-11 (>= 11.2.0-1~)
Suggests: g++-multilib
Description: GNU C++ compiler
 This is the GNU C++ compiler, a fairly portable optimizing compiler for C++.
 .
 This is a dependency package providing the default GNU C++ compiler.
Original-Maintainer: Debian GCC Maintainers <debian-gcc@lists.debian.org>
```
**Output of `update-alternatives --all`**
```
There is only one alternative in link group arptables (providing /usr/sbin/arptables): /usr/sbin/arptables-nft
Nothing to configure.
There is only one alternative in link group automake (providing /usr/bin/automake): /usr/bin/automake-1.16
Nothing to configure.
There is only one alternative in link group awk (providing /usr/bin/awk): /usr/bin/mawk
Nothing to configure.
There is only one alternative in link group builtins.7.gz (providing /usr/share/man/man7/builtins.7.gz): /usr/share/man/man7/bash-builtins.7.gz
Nothing to configure.
There is only one alternative in link group c++ (providing /usr/bin/c++): /usr/bin/g++
Nothing to configure.
There is only one alternative in link group c89 (providing /usr/bin/c89): /usr/bin/c89-gcc
Nothing to configure.
There is only one alternative in link group c99 (providing /usr/bin/c99): /usr/bin/c99-gcc
Nothing to configure.
There is only one alternative in link group cc (providing /usr/bin/cc): /usr/bin/gcc
Nothing to configure.
There is only one alternative in link group cpp (providing /lib/cpp): /usr/bin/cpp
Nothing to configure.
There is only one alternative in link group default.plymouth (providing /usr/share/plymouth/themes/default.plymouth): /usr/share/plymouth/themes/bgrt/bgrt.plymouth
Nothing to configure.
There is only one alternative in link group ebtables (providing /usr/sbin/ebtables): /usr/sbin/ebtables-nft
Nothing to configure.
There are 3 choices for the alternative editor (providing /usr/bin/editor).

  Selection    Path               Priority   Status
------------------------------------------------------------
* 0            /bin/nano           40        auto mode
  1            /bin/ed            -100       manual mode
  2            /bin/nano           40        manual mode
  3            /usr/bin/vim.tiny   15        manual mode

Press <enter> to keep the current choice[*], or type selection number: 
There is only one alternative in link group ex (providing /usr/bin/ex): /usr/bin/vim.tiny
Nothing to configure.
There is only one alternative in link group f77 (providing /usr/bin/f77): /usr/bin/gfortran
Nothing to configure.
There is only one alternative in link group f95 (providing /usr/bin/f95): /usr/bin/gfortran
Nothing to configure.
There are 2 choices for the alternative fakeroot (providing /usr/bin/fakeroot).

  Selection    Path                    Priority   Status
------------------------------------------------------------
* 0            /usr/bin/fakeroot-sysv   50        auto mode
  1            /usr/bin/fakeroot-sysv   50        manual mode
  2            /usr/bin/fakeroot-tcp    30        manual mode

Press <enter> to keep the current choice[*], or type selection number: 
There is only one alternative in link group ftp (providing /usr/bin/ftp): /usr/bin/tnftp
Nothing to configure.
There is only one alternative in link group futurize (providing /usr/bin/futurize): /usr/bin/python3-futurize
Nothing to configure.
There are 3 choices for the alternative gdm-smartcard (providing /etc/pam.d/gdm-smartcard).

  Selection    Path                                       Priority   Status
------------------------------------------------------------
* 0            /etc/pam.d/gdm-smartcard-sssd-exclusive     50        auto mode
  1            /etc/pam.d/gdm-smartcard-pkcs11-exclusive   30        manual mode
  2            /etc/pam.d/gdm-smartcard-sssd-exclusive     50        manual mode
  3            /etc/pam.d/gdm-smartcard-sssd-or-password   40        manual mode

Press <enter> to keep the current choice[*], or type selection number: 
There are 2 choices for the alternative gdm-theme.gresource (providing /usr/share/gnome-shell/gdm-theme.gresource).

  Selection    Path                                                           Priority   Status
------------------------------------------------------------
* 0            /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource   15        auto mode
  1            /usr/share/gnome-shell/gnome-shell-theme.gresource              10        manual mode
  2            /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource   15        manual mode

Press <enter> to keep the current choice[*], or type selection number: 
There is only one alternative in link group gnome-text-editor (providing /usr/bin/gnome-text-editor): /usr/bin/gedit
Nothing to configure.
There is only one alternative in link group gnome-www-browser (providing /usr/bin/gnome-www-browser): /usr/bin/firefox
Nothing to configure.
There is only one alternative in link group gnustep-back-029 (providing /usr/lib/GNUstep/Bundles/libgnustep-back-029.bundle): /usr/lib/GNUstep/Bundles/libgnustep-cairo-029.bundle
Nothing to configure.
There is only one alternative in link group gstreamer-codec-install (providing /usr/bin/gstreamer-codec-install): /usr/libexec/pk-gstreamer-install
Nothing to configure.
There is only one alternative in link group infobrowser (providing /usr/bin/infobrowser): /usr/bin/info
Nothing to configure.
There are 2 choices for the alternative ip6tables (providing /usr/sbin/ip6tables).

  Selection    Path                        Priority   Status
------------------------------------------------------------
* 0            /usr/sbin/ip6tables-nft      20        auto mode
  1            /usr/sbin/ip6tables-legacy   10        manual mode
  2            /usr/sbin/ip6tables-nft      20        manual mode

Press <enter> to keep the current choice[*], or type selection number: 
There are 2 choices for the alternative iptables (providing /usr/sbin/iptables).

  Selection    Path                       Priority   Status
------------------------------------------------------------
* 0            /usr/sbin/iptables-nft      20        auto mode
  1            /usr/sbin/iptables-legacy   10        manual mode
  2            /usr/sbin/iptables-nft      20        manual mode

Press <enter> to keep the current choice[*], or type selection number: 
There is only one alternative in link group libblas.so.3-x86_64-linux-gnu (providing /usr/lib/x86_64-linux-gnu/libblas.so.3): /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
Nothing to configure.
There is only one alternative in link group libblas.so-x86_64-linux-gnu (providing /usr/lib/x86_64-linux-gnu/libblas.so): /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so
Nothing to configure.
There is only one alternative in link group liblapack.so.3-x86_64-linux-gnu (providing /usr/lib/x86_64-linux-gnu/liblapack.so.3): /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3
Nothing to configure.
There is only one alternative in link group liblapack.so-x86_64-linux-gnu (providing /usr/lib/x86_64-linux-gnu/liblapack.so): /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so
Nothing to configure.
There is only one alternative in link group libopenblas.so.0-x86_64-linux-gnu (providing /usr/lib/x86_64-linux-gnu/libopenblas.so.0): /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblas.so.0
Nothing to configure.
There is only one alternative in link group libopenblas.so-x86_64-linux-gnu (providing /usr/lib/x86_64-linux-gnu/libopenblas.so): /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblas.so
Nothing to configure.
There is only one alternative in link group libpsm_infinipath.so.1 (providing /usr/lib/x86_64-linux-gnu/libpsm_infinipath.so.1): /usr/lib/libpsm1/libpsm_infinipath.so.1.16
Nothing to configure.
There is only one alternative in link group lzma (providing /usr/bin/lzma): /usr/bin/xz
Nothing to configure.
There is only one alternative in link group mpi (providing /usr/bin/mpicc): /usr/bin/mpicc.openmpi
Nothing to configure.
There is only one alternative in link group mpirun (providing /usr/bin/mpirun): /usr/bin/mpirun.openmpi
Nothing to configure.
There is only one alternative in link group mt (providing /bin/mt): /bin/mt-gnu
Nothing to configure.
There is only one alternative in link group my.cnf (providing /etc/mysql/my.cnf): /etc/mysql/my.cnf.fallback
Nothing to configure.
There is only one alternative in link group nc (providing /bin/nc): /bin/nc.openbsd
Nothing to configure.
There are 2 choices for the alternative newt-palette (providing /etc/newt/palette).

  Selection    Path                        Priority   Status
------------------------------------------------------------
* 0            /etc/newt/palette.ubuntu     50        auto mode
  1            /etc/newt/palette.original   20        manual mode
  2            /etc/newt/palette.ubuntu     50        manual mode

Press <enter> to keep the current choice[*], or type selection number: 
There are 2 choices for the alternative open (providing /usr/bin/open).

  Selection    Path                  Priority   Status
------------------------------------------------------------
* 0            /usr/bin/xdg-open      50        auto mode
  1            /usr/bin/run-mailcap   30        manual mode
  2            /usr/bin/xdg-open      50        manual mode

Press <enter> to keep the current choice[*], or type selection number: 
There are 2 choices for the alternative pager (providing /usr/bin/pager).

  Selection    Path            Priority   Status
------------------------------------------------------------
* 0            /usr/bin/less    77        auto mode
  1            /bin/more        50        manual mode
  2            /usr/bin/less    77        manual mode

Press <enter> to keep the current choice[*], or type selection number: 
There is only one alternative in link group pasteurize (providing /usr/bin/pasteurize): /usr/bin/python3-pasteurize
Nothing to configure.
There is only one alternative in link group pico (providing /usr/bin/pico): /bin/nano
Nothing to configure.
There are 2 choices for the alternative pinentry (providing /usr/bin/pinentry).

  Selection    Path                      Priority   Status
------------------------------------------------------------
* 0            /usr/bin/pinentry-gnome3   90        auto mode
  1            /usr/bin/pinentry-curses   50        manual mode
  2            /usr/bin/pinentry-gnome3   90        manual mode

Press <enter> to keep the current choice[*], or type selection number: 
There is only one alternative in link group pinentry-x11 (providing /usr/bin/pinentry-x11): /usr/bin/pinentry-gnome3
Nothing to configure.
There is only one alternative in link group python3 (providing /usr/bin/python3): /usr/bin/python3.12
Nothing to configure.
There is only one alternative in link group rcp (providing /usr/bin/rcp): /usr/bin/scp
Nothing to configure.
There is only one alternative in link group rlogin (providing /usr/bin/rlogin): /usr/bin/slogin
Nothing to configure.
There is only one alternative in link group rmt (providing /usr/sbin/rmt): /usr/sbin/rmt-tar
Nothing to configure.
There is only one alternative in link group rsh (providing /usr/bin/rsh): /usr/bin/ssh
Nothing to configure.
There is only one alternative in link group rview (providing /usr/bin/rview): /usr/bin/vim.tiny
Nothing to configure.
There are 2 choices for the alternative shimx64.efi.signed (providing /usr/lib/shim/shimx64.efi.signed).

  Selection    Path                                       Priority   Status
------------------------------------------------------------
* 0            /usr/lib/shim/shimx64.efi.signed.latest     100       auto mode
  1            /usr/lib/shim/shimx64.efi.signed.latest     100       manual mode
  2            /usr/lib/shim/shimx64.efi.signed.previous   50        manual mode

Press <enter> to keep the current choice[*], or type selection number: 
There is only one alternative in link group telnet (providing /usr/bin/telnet): /usr/bin/telnet.netkit
Nothing to configure.
There is only one alternative in link group text.plymouth (providing /usr/share/plymouth/themes/text.plymouth): /usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth
Nothing to configure.
There is only one alternative in link group vi (providing /usr/bin/vi): /usr/bin/vim.tiny
Nothing to configure.
There is only one alternative in link group view (providing /usr/bin/view): /usr/bin/vim.tiny
Nothing to configure.
There are 2 choices for the alternative vtrgb (providing /etc/vtrgb).

  Selection    Path                          Priority   Status
------------------------------------------------------------
* 0            /etc/console-setup/vtrgb       50        auto mode
  1            /etc/console-setup/vtrgb       50        manual mode
  2            /etc/console-setup/vtrgb.vga   20        manual mode

Press <enter> to keep the current choice[*], or type selection number: 
There is only one alternative in link group which (providing /usr/bin/which): /usr/bin/which.debianutils
Nothing to configure.
There is only one alternative in link group write (providing /usr/bin/write): /usr/bin/write.ul
Nothing to configure.
There are 7 choices for the alternative x-cursor-theme (providing /usr/share/icons/default/index.theme).

  Selection    Path                                     Priority   Status
------------------------------------------------------------
* 0            /usr/share/icons/DMZ-White/cursor.theme   100       auto mode
  1            /etc/X11/cursors/core.theme               30        manual mode
  2            /etc/X11/cursors/handhelds.theme          20        manual mode
  3            /etc/X11/cursors/redglass.theme           20        manual mode
  4            /etc/X11/cursors/whiteglass.theme         20        manual mode
  5            /usr/share/icons/Adwaita/cursor.theme     90        manual mode
  6            /usr/share/icons/DMZ-Black/cursor.theme   30        manual mode
  7            /usr/share/icons/DMZ-White/cursor.theme   100       manual mode

Press <enter> to keep the current choice[*], or type selection number: 
There is only one alternative in link group x-session-manager (providing /usr/bin/x-session-manager): /usr/bin/gnome-session
Nothing to configure.
There is only one alternative in link group x-terminal-emulator (providing /usr/bin/x-terminal-emulator): /usr/bin/gnome-terminal.wrapper
Nothing to configure.
There is only one alternative in link group x-www-browser (providing /usr/bin/x-www-browser): /usr/bin/firefox
Nothing to configure.
There is only one alternative in link group yacc (providing /usr/bin/yacc): /usr/bin/bison.yacc
Nothing to configure.

```

    **Output of `gcc --version` and `gcc exe.c` (should be nothing)**
   ```
gcc --version
gcc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
`gcc exe.c` 
nothing

**Output of  `g++ --version` and `g++ exe.c`(might be nothing)**
```
 g++ --version
g++ (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
`g++ exe.c` 
nothing

**Output of `gcc -x c++ exe.c` (might be a clue)**
nothing


### With the venv activated

**Output of `mpicc --version `and` mpicc exe.c`**

```
mpicc --version
gcc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
`mpicc exe.c`
nothing

**Output of `mpic++ --version` and `mpic++ exe.c`**
```
mpic++ --version
g++ (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
mpic++ exe.c
/usr/bin/ld: cannot find -lmpi_cxx: No such file or directory
/usr/bin/ld: cannot find -lmpi: No such file or directory
/usr/bin/ld: cannot find -lopen-rte: No such file or directory
/usr/bin/ld: cannot find -lopen-pal: No such file or directory
/usr/bin/ld: cannot find -lhwloc: No such file or directory
/usr/bin/ld: cannot find -levent_core: No such file or directory
/usr/bin/ld: cannot find -levent_pthreads: No such file or directory
collect2: error: ld returned 1 exit status

```

**Output of `mpicc -x c++ exe.c`**
nothing


[firedrake-install.log](https://github.com/user-attachments/files/16553023/firedrake-install.log)
[configure.log](https://github.com/user-attachments/files/16553025/configure.log)

**Comment by JDBetteridge** [comment]
@adiegel this on might be a quick fix, first I notice that you are running Python 3.12.4
```
2024-08-08 14:31:22,225 INFO   Running firedrake-install
2024-08-08 14:31:22,240 DEBUG  Installer running with: /usr/bin/python3
2024-08-08 14:31:22,241 DEBUG  Python version: 3.12.4 (main, Jun  8 2024, 18:29:57) [GCC 11.4.0]
```
but the `python-dev` that you have installed is for Python 3.10.6
```
2024-08-08 14:31:22,383 DEBUG  Running command 'dpkg-query -s python3-dev'
2024-08-08 14:31:22,393 DEBUG  Package: python3-dev
Status: install ok installed
Priority: optional
Section: python
Installed-Size: 145
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: allowed
Source: python3-defaults
Version: 3.10.6-1~22.04
Replaces: python3 (<< 3.9.2-1~), python3.1 (<< 3.1.2+20100706-3)
Depends: python3 (= 3.10.6-1~22.04), libpython3-dev (= 3.10.6-1~22.04), python3.10-dev (>= 3.10.6-1~), python3-distutils (>= 3.10.6-1~), libjs-sphinxdoc (>= 4.3)
Breaks: python3 (<< 3.9.2-1~)
Description: header files and a static library for Python (default)
 Header files, a static library and development tools for building
 Python modules, extending the Python interpreter or embedding Python
 in applications.
 .
 This package is a dependency package, which depends on Debian's default
 Python 3 version's headers (currently v3.10).
Original-Maintainer: Matthias Klose <doko@debian.org>
Built-Using: sphinx (= 4.3.2-1)
Homepage: https://www.python.org/

2024-08-08 14:31:22,393 INFO     installed.
```
This might be why Cython cannot find the right Python.h file. You need to find out how to update the `python-dev` package to the same version as your `python` package. 

After fixing this try running `firedrake-update` inside the virtual-env, the install might pick up where it left off.


I spotted :
```
Collecting mpi4py
  Downloading mpi4py-4.0.0.tar.gz (464 kB)
```
In the log. If the update fails share the log. We currently have to pin mpi4py at 3.1.6 (the update script will fetch the latest version of itself, which pins the dependency) due to [this issue](https://gitlab.com/petsc/petsc/-/issues/1625).

**Comment by adiegel** [comment]
@JDBetteridge, we have a successful install! I could not figure out how to update the python3-dev to python 3.12, so I downgraded my python back to python3.10. Hopefully that will continue to work for a while. Thanks for all your help!

**Comment by JDBetteridge** [comment]
Glad everything is finally working! We'll aim to support Python 3.10 until 2026 (basically for as long as [Python plan to support it](https://devguide.python.org/versions/))
