### ISSUE TITLE
INSTALL: 

### ISSUE THREAD

**Issue by adiegel** [firedrakeproject/firedrake#3717]
**Describe the error**
"returned non-zero exit status 1" error on MacOS Ventura installation. (Experiencing a similar issue on a Linux OS system.)

**Steps to Reproduce**
python3 firedrake-install

**Error message**
```
Traceback (most recent call [last):]
  File "/Users/aed388/firedrake-install", line 1816, in <module>
    install("petsc/")
  File "/Users/aed388/firedrake-install", line 1043, in install
    build_and_install_petsc()
  File "/Users/aed388/firedrake-install", line 1155, in build_and_install_petsc
    check_call([python, "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + petsc_options)
  File "/Users/aed388/firedrake-install", line 672, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/aed388/firedrake/bin/python', './configure', 'PETSC_DIR=/Users/aed388/firedrake/src/petsc', 'PETSC_ARCH=default', '--with-c2html=0', '--download-hdf5', '--CFLAGS=-Wno-implicit-function-declaration', '--download-hwloc-configure-arguments=--disable-opencl', '--download-scalapack', '--download-openblas', '--with-shared-libraries=1', '--download-hwloc', '--download-mpich', '--download-superlu_dist', '--with-fortran-bindings=0', '--download-mumps', '--download-pnetcdf', '--with-zlib', '--with-x=0', '--download-pastix', '--with-debugging=0', '--download-metis', '--download-bison', '--download-ptscotch', '--download-mpich-configure-arguments=--disable-opencl', '--download-netcdf', "--download-openblas-make-options='USE_THREAD=0 USE_LOCKING=1 USE_OPENMP=0'", '--download-hypre', '--download-suitesparse']' returned non-zero exit status 1.
```
[firedrake-install.log](https://github.com/user-attachments/files/16432808/firedrake-install.log)

[configure.log](https://github.com/user-attachments/files/16432801/configure.log)

**Environment:**
 - OS: MacOS Ventura 13.6.8
 - Python version: Python 3.12.4

**Additional context**
I seem to be experiencing a similar issue on my Linux machine. I have no idea why I am experiencing these difficulties.

**Comment by Ig-dolci** [comment]
You have to update CMake on your computer. You have the following error:

```
  A package requires CMake version 3.22.0 (detected version is 3.18.1)
```

**Comment by adiegel** [comment]
Thanks, @Ig-dolci. I have updated CMake and reinstalled python3 using Homebrew. I have now gotten a new error. Here are the new Error Message and log files.

Error Message

```
Installing h5py/
Traceback (most recent call last):
  File "/Users/aed388/firedrake-install", line 1850, in <module>
    build_and_install_h5py()
  File "/Users/aed388/firedrake-install", line 1242, in build_and_install_h5py
    install("h5py/")
  File "/Users/aed388/firedrake-install", line 1052, in install
    run_pip_install(["--no-build-isolation", package])
  File "/Users/aed388/firedrake-install", line 991, in run_pip_install
    check_call(pipinstall + pipargs)
  File "/Users/aed388/firedrake-install", line 672, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/aed388/firedrake/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,numpy', '-v', '--no-build-isolation', 'h5py/']' returned non-zero exit status 1.


Install log saved in /Users/aed388/firedrake-install.log
```

[firedrake-install.log](https://github.com/user-attachments/files/16446449/firedrake-install.log)
[configure.log](https://github.com/user-attachments/files/16446452/configure.log)

**Comment by Ig-dolci** [comment]
I think you are not using Homebrew Python for the firedrake installation. Can you please try `/opt/homebrew/bin/python3 firedrake-install`?

**Comment by adiegel** [comment]
Okay. I had installed python3 with homebrew originally. But, I just reinstalled and that seems to have fixed the issue. Thanks. Now to figure out what is going on with the linux machine.
