### ISSUE TITLE
INSTALL: PETSCs building issues

### ISSUE THREAD

**Issue by federicamusazzi** [firedrakeproject/firedrake#3779]
I have tried installing firedrake following the exact procedure reported on the website. My computer (Mac book air 2019 - intel) refuse to do it. When it tries to build PETSc the installation crashes.

Steps followed to install firedrake:
1. curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
2. python3.11 firedrake-install

Error message:
Depending on your platform, PETSc may take an hour or more to build!
Traceback (most recent call last):
  File "/Users/federicamusazzi/firedrake-install", line 1836, in <module>
    install("petsc/")
  File "/Users/federicamusazzi/firedrake-install", line 1056, in install
    build_and_install_petsc()
  File "/Users/federicamusazzi/firedrake-install", line 1168, in build_and_install_petsc
    check_call([python, "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + petsc_options)
  File "/Users/federicamusazzi/firedrake-install", line 676, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/federicamusazzi/firedrake/bin/python', './configure', 'PETSC_DIR=/Users/federicamusazzi/firedrake/src/petsc', 'PETSC_ARCH=default', '--download-mpich-configure-arguments=--disable-opencl', '--with-debugging=0', '--download-pnetcdf', '--with-x=0', '--download-netcdf', '--download-suitesparse', '--download-superlu_dist', '--download-scalapack', '--download-openblas', '--with-zlib', '--CFLAGS=-Wno-implicit-function-declaration', '--LDFLAGS=-Wl,-ld_classic,-dead_strip_dylibs', '--download-metis', '--download-pastix', '--with-c2html=0', '--download-bison', '--with-fortran-bindings=0', '--download-hdf5', '--download-hwloc', '--download-mpich', '--download-hwloc-configure-arguments=--disable-opencl', "--download-openblas-make-options='USE_THREAD=0 USE_LOCKING=1 USE_OPENMP=0'", '--download-hypre', '--download-mumps', '--with-shared-libraries=1', '--download-ptscotch']' returned non-zero exit status 1.
Install log saved in /Users/federicamusazzi/firedrake-install.log

[firedrake-install.log](https://github.com/user-attachments/files/17110351/firedrake-install.log)
[configure.log](https://github.com/user-attachments/files/17110381/configure.log)

Environment
 - MacOS Sonoma 14.6.1
 - Python version:  3.11

Thank you if you can solve my issue!

**Comment by Ig-dolci** [comment]
Are you using homebrew python? This is a requirement for MacOS firedrake install.

**Comment by Ig-dolci** [comment]
> Yes I am using python 3.11 installed by homebrew

Ok. We can try these two ways:

-  Update Xcode version to 15.4 and `python3 firedrake-install` again
- Or keep the Xcode version to 15.3 and try `python3 firedrake-install` with this [`firedrake-install` script](https://github.com/firedrakeproject/firedrake/blob/dolci/remove_ldclassic/scripts/firedrake-install).

**Comment by connorjward** [comment]
@federicamusazzi have you managed to get things working?

**Comment by federicamusazzi** [comment]
Nothing to do, I also formatted my computer  but it didn't work, I just got a different error
[firedrake-install.log](https://github.com/user-attachments/files/17428868/firedrake-install.log)
[configure.log](https://github.com/user-attachments/files/17428886/configure.log)


So I decided to give up and start  using Firedrake on Colab, it is not the best idea as I need an internet connection to work but at least I can work.

**Comment by connorjward** [comment]
Have you got an up-to-date Xcode and homebrew?

Also, since you have an intel Mac you might have some success using one of our Docker containers: https://hub.docker.com/r/firedrakeproject/firedrake.
