### ISSUE TITLE
BUG: checkpointing produces error

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#3840]
**Describe the bug**

I get an error message when I try to save functions to a checkpoint file.

**Steps to Reproduce**
```
from firedrake import *
mesh = IcosahedralSphereMesh(radius=1.0,
                                refinement_level=4,
                                degree=1, name="mesh")
V = FunctionSpace(mesh, "CG", 1)
u = Function(V, name="u").assign(1.0)

with CheckpointFile('test.h5', 'w') as afile:
    afile.save_function(u)
```

**Expected behavior**

**Error message**
```
(firedrake) journal todo +cjc1@cjc1-HP-Z840-Workstation:~/repositories/sw_timestepping$ python test_chk.py 
Traceback (most recent call last):
  File "/home/cjc1/repositories/sw_timestepping/test_chk.py", line 9, in <module>
    afile.save_mesh(mesh)
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/cjc1/firedrake/src/firedrake/firedrake/checkpointing.py", line 638, in save_mesh
    self._save_function_topology(mesh._coordinates)
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/cjc1/firedrake/src/firedrake/firedrake/checkpointing.py", line 971, in _save_function_topology
    self._save_function_space_topology(tV)
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/cjc1/firedrake/src/firedrake/firedrake/checkpointing.py", line 866, in _save_function_space_topology
    self._save_mesh_topology(tmesh)
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/cjc1/firedrake/src/firedrake/firedrake/checkpointing.py", line 703, in _save_mesh_topology
    raise ValueError(f"Mesh ({tmesh_name}) already exists in {self.filename}, but the global number of DMPlex points is inconsistent: {order_array_size1} ({self.filename}) != {order_array_size} ({tmesh_name})")
ValueError: Mesh (firedrake_default_topology) already exists in test.h5, but the global number of DMPlex points is inconsistent: 9 (test.h5) != 15362 (firedrake_default_topology)
```

**Environment:**
 - Linux 24.04
 - Python 3.12.3
Firedrake Configuration:
    package_manager: True
    minimal_petsc: False
    mpicc: None
    mpicxx: None
    mpif90: None
    mpiexec: None
    disable_ssh: False
    honour_petsc_dir: False
    with_parmetis: False
    slepc: False
    packages: []
    honour_pythonpath: False
    opencascade: False
    torch: False
    jax: False
    petsc_int_type: int32
    cache_dir: /home/cjc1/firedrake/.cache
    complex: False
    remove_build_files: False
    with_blas: None
    netgen: False
Additions:
    None
Environment:
    PYTHONPATH: None
    PETSC_ARCH: None
    PETSC_DIR: None
Status of components:
---------------------------------------------------------------------------
|Package             |Branch                        |Revision  |Modified  |
---------------------------------------------------------------------------
|FInAT               |master                        |ba0e9bb   |False     |
|PyOP2               |master                        |31471a60  |False     |
|fiat                |master                        |13131da   |False     |
|firedrake           |master                        |4e6cba30b |False     |
|h5py                |firedrake                     |db2ab02f  |False     |
|libsupermesh        |master                        |b80408e   |False     |
|loopy               |main                          |d9876d83  |False     |
|petsc               |firedrake                     |1c1d65e4821|False     |
|pyadjoint           |master                        |b9574fb   |False     |
|pytest-mpi          |main                          |f4a9692   |False     |
|tsfc                |master                        |0ec9234   |False     |
|ufl                 |master                        |c1a8afb1  |False     |
---------------------------------------------------------------------------

**Additional Info**

**Comment by connorjward** [comment]
Are you using an up-to-date Firedrake branch? I think @ksagiyam fixed this a short while ago.

**Comment by ksagiyam** [comment]
https://github.com/firedrakeproject/firedrake/pull/3792/files

It seems you managed to update your Firedrake after our PETSc fork was updated, but before the matching Firedrake PR went in.

**Comment by colinjcotter** [comment]
ohh ok! Thanks!
