### ISSUE TITLE
Compilation error: 'j' undeclared

### ISSUE THREAD

**Issue by ctjacobs** [firedrakeproject/firedrake#425]
I've just updated my Firedrake installation and "everything else" (PETSc, petsc4py, FFC, UFL, PyOP2, etc).

I'm now getting the following error:

```
pyop2:INFO Compiling wrapper...
Traceback (most recent call last):
  File "old.py", line 57, in <module>
    solver.solve()
  File "<string>", line 2, in solve
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_148_g8a1955c-py2.7-linux-x86_64.egg/pyop2/profiling.py", line 197, in wrapper
    return f(*args, **kwargs)
  File "/data/firedrake/firedrake/variational_solver.py", line 252, in solve
    self.snes.solve(None, v)
  File "PETSc/SNES.pyx", line 511, in petsc4py.PETSc.SNES.solve (src/petsc4py.PETSc.c:155735)
  File "PETSc/petscsnes.pxi", line 282, in petsc4py.PETSc.SNES_Jacobian (src/petsc4py.PETSc.c:31081)
  File "/data/firedrake/firedrake/variational_solver.py", line 201, in form_jacobian
    self._jac_tensor.M._force_evaluation()
  File "/data/firedrake/firedrake/matrix.py", line 145, in M
    self._M._force_evaluation()
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_148_g8a1955c-py2.7-linux-x86_64.egg/pyop2/base.py", line 1534, in _force_evaluation
    _trace.evaluate(reads, writes)
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_148_g8a1955c-py2.7-linux-x86_64.egg/pyop2/base.py", line 154, in evaluate
    comp._run()
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_148_g8a1955c-py2.7-linux-x86_64.egg/pyop2/base.py", line 3827, in _run
    return self.compute()
  File "<string>", line 2, in compute
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_148_g8a1955c-py2.7-linux-x86_64.egg/pyop2/profiling.py", line 197, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_148_g8a1955c-py2.7-linux-x86_64.egg/pyop2/base.py", line 3836, in compute
    self._compute(self.it_space.iterset.core_part)
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_148_g8a1955c-py2.7-linux-x86_64.egg/pyop2/sequential.py", line 154, in _compute
    fun(*self._jit_args, argtypes=self._argtypes, restype=None)
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_148_g8a1955c-py2.7-linux-x86_64.egg/pyop2/host.py", line 632, in __call__
    return self.compile(argtypes, restype)(*args)
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_148_g8a1955c-py2.7-linux-x86_64.egg/pyop2/host.py", line 735, in compile
    compiler=compiler.get('name'))
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_148_g8a1955c-py2.7-linux-x86_64.egg/pyop2/compilation.py", line 255, in load
    dll = compiler.get_so(src, extension)
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_148_g8a1955c-py2.7-linux-x86_64.egg/pyop2/compilation.py", line 131, in get_so
    Compile errors in %s""" % (e.cmd, e.returncode, logfile, errfile))
pyop2.exceptions.CompilationError: Command "['mpicc', '-std=c99', '-fPIC', '-Wall', '-g', '-O3', '-fno-tree-vectorize', '-I/usr/local/lib/python2.7/dist-packages/petsc/include', '-I/data/firedrake/firedrake', '-I/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_148_g8a1955c-py2.7-linux-x86_64.egg/pyop2', '-msse', '-o', '/tmp/pyop2-cache-uid1000/00c6978d3d2f320b1ef296b0d1103cfd.so.tmp', '/tmp/pyop2-cache-uid1000/00c6978d3d2f320b1ef296b0d1103cfd.c', '-shared', '-L/usr/local/lib/python2.7/dist-packages/petsc/lib', '-Wl,-rpath,/usr/local/lib/python2.7/dist-packages/petsc/lib', '-lpetsc', '-lm']" return error status 1.
Unable to compile code
Compile log in /tmp/pyop2-cache-uid1000/00c6978d3d2f320b1ef296b0d1103cfd.log
Compile errors in /tmp/pyop2-cache-uid1000/00c6978d3d2f320b1ef296b0d1103cfd.err
```

when running:

```
from firedrake import *

mesh = UnitSquareMesh(2, 2)

# Define the mixed function space
U = VectorFunctionSpace(mesh, "CG", 2)
H = FunctionSpace(mesh, "CG", 1)
W = MixedFunctionSpace([U, H])

# The solution field defined on the mixed function space
solution = Function(W)
u, h = split(solution)
w, v = TestFunctions(W)

# Define the compulsory shallow water fields
solution_old = Function(W)
solution_old.interpolate(Expression(("0.1*sin(pi*x[0])", "1e-16", "cos(pi*x[0])")))
u_old, h_old = split(solution_old)

# The solution should first hold the initial condition.
solution.assign(solution_old)

# Mean free surface height
h_mean = Function(W.sub(1)).interpolate(Expression("50"))

# The total height of the free surface.
h_total = h_mean + h

# Time-step size
dt = 0.05

# The form, F
F = 0
M_momentum = (1.0/dt)*(inner(w, u) - inner(w, u_old))*dx
F += M_momentum

A_momentum = inner(dot(grad(u), u), w)*dx
F += A_momentum

viscosity = Constant(0.7)
K_momentum = -viscosity*inner(grad(u) + grad(u).T, grad(w))*dx
F -= K_momentum
            
C_momentum = -9.81*inner(w, grad(h))*dx
F += C_momentum

M_continuity = (1.0/dt)*(inner(v, h) - inner(v, h_old))*dx
F += M_continuity

Ct_continuity = inner(v, div(h_total*u))*dx
F += Ct_continuity

# Construct the solver objects
problem = NonlinearVariationalProblem(F, solution, bcs=[])
solver = NonlinearVariationalSolver(problem)

solver.solve()
```

00c6978d3d2f320b1ef296b0d1103cfd.err: https://gist.github.com/ctjacobs/719fa554448774c2ef08
00c6978d3d2f320b1ef296b0d1103cfd.log: https://gist.github.com/ctjacobs/463f3c2ec62f0839dec6
00c6978d3d2f320b1ef296b0d1103cfd.c: https://gist.github.com/ctjacobs/ae2a1f5073cff579f0b2

If I remove the grad(u).T term, the error does not occur.

**Comment by FabioLuporini** [comment]
Hi Christian, I think I've fixed the issue (https://github.com/coneoproject/COFFEE/issues/13)

Can you update COFFEE and let me know if this now works for you? 

Andrew was right at pointing out a problem with the code hoisted

**Comment by wence-** [comment]
So the form now compiles at least, but with coffee switched on I get a diverged line search in the solve (which doesn't happen if coffee is off).  Christian, if you still have problems is it OK to close this and open a new issue?

**Comment by ctjacobs** [comment]
Yes, ok.
