### ISSUE TITLE
Cannot assign Constants of the right size to MixedFunctionSpaces

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#471]
The following code works with dolfin, but not with firedrake:

    from firedrake import *

    mesh = UnitSquareMesh(2, 2)
    V = FunctionSpace(mesh, "CG", 1)
    Z = MixedFunctionSpace([V, V, V])

    z = Function(Z)
    z.assign(Constant((0, 0, 0)))

Even though z has three components, for some reason it errors when given a constant with three components:

    [pfarrell@saoirse:/tmp]$ python demo.py 
    Traceback (most recent call last):
      File "demo.py", line 8, in <module>
        z.assign(Constant((0, 0, 0)))
      File "/home/pfarrell/local/firedrake/install-20150219/lib/python2.7/site-packages/firedrake/function.py", line 383, in assign
        assemble_expressions.Assign(self, expr), subset)
      File "/home/pfarrell/local/firedrake/install-20150219/lib/python2.7/site-packages/firedrake/assemble_expressions.py", line 546, in evaluate_expression
        e, args, _ = ExpressionWalker().walk(tree)
      File "/home/pfarrell/local/firedrake/install-20150219/lib/python2.7/site-packages/firedrake/assemble_expressions.py", line 404, in walk
        return (self.visit(expr),
      File "/home/pfarrell/local/firedrake/install-20150219/lib/python2.7/site-packages/ufl/algorithms/transformer.py", line 106, in visit
        r = h(o)
      File "/home/pfarrell/local/firedrake/install-20150219/lib/python2.7/site-packages/firedrake/assemble_expressions.py", line 491, in operator
        operands = [operands[0], self.visit(operands[1])]
      File "/home/pfarrell/local/firedrake/install-20150219/lib/python2.7/site-packages/ufl/algorithms/transformer.py", line 106, in visit
        r = h(o)
      File "/home/pfarrell/local/firedrake/install-20150219/lib/python2.7/site-packages/firedrake/assemble_expressions.py", line 445, in coefficient
        raise ValueError("Constant has mismatched shape for expression function space")
    ValueError: Constant has mismatched shape for expression function space

**Comment by dham** [comment]
I think this one goes to the heart of the difference in the way Firedrake thinks about mixed fields compared with Dolfin. Essentially, Firedrake is not built on the concept that mixed spaces and vectors are interchangeable. This goes quite deep in the code and I'm not sure it is easy to replicate Dolfin's behaviour in this case (well, a hack that made this particular case work would be not too hard but more general cases get difficult).

**Comment by wence-** [comment]
Splatting constants across mixed functions like this is actually not difficult, merge request on the way.

**Comment by dham** [comment]
Constants, no. But surely the next question will be arbitrary vector-valued expression....

**Comment by wence-** [comment]
Work around is to do `z.sub(0).assign(Constant(0))`, etc...

**Comment by wence-** [comment]
This particular case now does at least work.  Assigning from a vector function space (or indeed vector-valued expression) into a mixed space is unlikely to come.  Please instead assign to each sub-component of the mixed space separately.
