### ISSUE TITLE
Solving nonlinear problem on extruded mesh with boundary conditions fails

### ISSUE THREAD

**Issue by tkarna** [firedrakeproject/firedrake#472]
The following code fails for the latter solve. Works without the boundary integral. Also works fine on the parent mesh.

```
from firedrake import *

mesh2d = UnitSquareMesh(5, 5)
mesh = ExtrudedMesh(mesh2d, layers=10, layer_height=0.1)

P1 = FunctionSpace(mesh, 'CG', 1)

test = TestFunction(P1)
tri = TrialFunction(P1)
sol = Function(P1)
func = Function(P1)
func.interpolate(Expression('4.5'))

# works
A = inner(test, tri)*dx
L = inner(func, test)*dx + inner(func, test)*ds_v
solve(A == L, sol)
print 'solution', sol.dat.data.min(), sol.dat.data.max()

# fails
F = inner(test, sol)*dx - inner(func, test)*dx - inner(func, test)*ds_v
solve(F == 0, sol)
print 'solution', sol.dat.data.min(), sol.dat.data.max()
```

Error:
```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    solve(F == 0, sol)
  File ".../lib/python2.7/site-packages/firedrake/solving.py", line 119, in solve
    _solve_varproblem(*args, **kwargs)
  File ".../lib/python2.7/site-packages/firedrake/solving.py", line 154, in _solve_varproblem
    nullspace=nullspace)
  File ".../lib/python2.7/site-packages/firedrake/variational_solver.py", line 214, in __init__
    ctx = _SNESContext(problem)
  File ".../lib/python2.7/site-packages/firedrake/variational_solver.py", line 75, in __init__
    form_compiler_parameters=problem.form_compiler_parameters)
  File ".../lib/python2.7/site-packages/firedrake/assemble.py", line 58, in assemble
    form_compiler_parameters=form_compiler_parameters)
  File ".../lib/python2.7/site-packages/firedrake/assemble.py", line 79, in _assemble
    kernels = ffc_interface.compile_form(f, "form", parameters=form_compiler_parameters)
  File ".../lib/python2.7/site-packages/firedrake/ffc_interface.py", line 279, in compile_form
    ((kernel, needs_orientations), ) = ffc_kernel.kernels
ValueError: need more than 0 values to unpack
```

**Comment by wence-** [comment]
I think the reference merge request fixes this problem, can you confirm please?

**Comment by wence-** [comment]
Should now work in up-to-date master.

**Comment by tkarna** [comment]
Yep, looks good now.

**Comment by kalogirou** [comment]
I have a similar issue. Can you please let me know what (PETSc, petsc4py, FIAT, UFL, FFC, COFFEE, PyOP2, Firedrake) needs an update to get this fix?

**Comment by wence-** [comment]
If you haven't updated within the last month, all of those: the fix itself was in firedrake, but in the mean time we're using new fixes/features in, I think, all dependent packages!
