### ISSUE TITLE
Error message upon solving mixed problem with 3 spaces

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#525]
The following code:
https://gist.github.com/colinjcotter/03c93354a07b9ebac01c

raises the following:
```
Traceback (most recent call last):
  File "test-bug.py", line 88, in <module>
    usolver.solve()
  File "<string>", line 2, in solve
  File "/home/cjc1/firedrake/PyOP2/pyop2/profiling.py", line 203, in wrapper
    return f(*args, **kwargs)
  File "/home/cjc1/firedrake/firedrake/firedrake/variational_solver.py", line 161, in solve
    self.snes.solve(None, v)
  File "SNES.pyx", line 516, in petsc4py.PETSc.SNES.solve (src/petsc4py.PETSc.c:158930)
  File "petscsnes.pxi", line 284, in petsc4py.PETSc.SNES_Jacobian (src/petsc4py.PETSc.c:30730)
  File "/home/cjc1/firedrake/firedrake/firedrake/solving_utils.py", line 226, in form_jacobian
    ctx._jacs[lvl].M._force_evaluation()
  File "/home/cjc1/firedrake/firedrake/firedrake/matrix.py", line 145, in M
    self._M._force_evaluation()
  File "/home/cjc1/firedrake/PyOP2/pyop2/base.py", line 1559, in _force_evaluation
    _trace.evaluate(reads, writes)
  File "/home/cjc1/firedrake/PyOP2/pyop2/base.py", line 167, in evaluate
    comp._run()
  File "/home/cjc1/firedrake/PyOP2/pyop2/base.py", line 3914, in _run
    return self.compute()
  File "/home/cjc1/firedrake/PyOP2/pyop2/base.py", line 3938, in compute
    fun = self._jitmodule
  File "/home/cjc1/firedrake/PyOP2/pyop2/utils.py", line 64, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/cjc1/firedrake/PyOP2/pyop2/sequential.py", line 158, in _jitmodule
    direct=self.is_direct, iterate=self.iteration_region)
  File "/home/cjc1/firedrake/PyOP2/pyop2/caching.py", line 203, in __new__
    obj = make_obj()
  File "/home/cjc1/firedrake/PyOP2/pyop2/caching.py", line 193, in make_obj
    obj.__init__(*args, **kwargs)
  File "/home/cjc1/firedrake/PyOP2/pyop2/host.py", line 632, in __init__
    self.compile()
  File "/home/cjc1/firedrake/PyOP2/pyop2/host.py", line 676, in compile
    """ % {'code': self._kernel.code(),
  File "/home/cjc1/firedrake/PyOP2/pyop2/base.py", line 3711, in code
    self._code = self._ast_to_c(self._ast, self._opts)
  File "/home/cjc1/firedrake/PyOP2/pyop2/host.py", line 58, in _ast_to_c
    ast_handler.plan_cpu(self._opts)
  File "/home/cjc1/firedrake/COFFEE/coffee/plan.py", line 395, in plan_cpu
    loop_opts = _generate_cpu_code(self, kernel, **params)
  File "/home/cjc1/firedrake/COFFEE/coffee/plan.py", line 226, in _generate_cpu_code
    loop_opt.rewrite(rewrite)
  File "/home/cjc1/firedrake/COFFEE/coffee/optimizer.py", line 139, in rewrite
    merged_loops = lm.merge()
  File "/home/cjc1/firedrake/COFFEE/coffee/loop_scheduler.py", line 182, in merge
    if self.expr_graph.is_written(ws, lws):
  File "/home/cjc1/firedrake/COFFEE/coffee/ast_analyzer.py", line 178, in is_written
    elif nx.has_path(self.deps, s.symbol, target_sym.symbol):
  File "/usr/local/lib/python2.7/dist-packages/networkx/algorithms/shortest_paths/generic.py", line 35, in has_path
    sp = nx.shortest_path(G,source, target)
  File "/usr/local/lib/python2.7/dist-packages/networkx/algorithms/shortest_paths/generic.py", line 136, in shortest_path
    paths=nx.bidirectional_shortest_path(G,source,target)
  File "/usr/local/lib/python2.7/dist-packages/networkx/algorithms/shortest_paths/unweighted.py", line 138, in bidirectional_shortest_path
    results=_bidirectional_pred_succ(G,source,target)
  File "/usr/local/lib/python2.7/dist-packages/networkx/algorithms/shortest_paths/unweighted.py", line 197, in _bidirectional_pred_succ
    for w in Gpred(v):
  File "/usr/local/lib/python2.7/dist-packages/networkx/classes/digraph.py", line 675, in predecessors_iter
    raise NetworkXError("The node %s is not in the digraph."%(n,))
networkx.exception.NetworkXError: The node F0 is not in the digraph.
```

**Comment by wence-** [comment]
I think this is working after coffee fixes.
