### ISSUE TITLE
interpolate doesn't work with Constants

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#526]
```python
from firedrake import *
mesh = UnitSquareMesh(20, 20)
V = FunctionSpace(mesh, "CG", 1)
u = interpolate(Constant(1), V)
```

yields

```
Traceback (most recent call last):
  File "/tmp/xy", line 4, in <module>
    u = interpolate(Constant(1), V)
  File "/home/pfarrell/local/firedrake/firedrake-20150526/lib/python2.7/site-packages/firedrake/function.py", line 37, in interpolate
    return Function(V).interpolate(expr)
  File "/home/pfarrell/local/firedrake/firedrake-20150526/lib/python2.7/site-packages/firedrake/function.py", line 203, in interpolate
    if np.prod(expression.value_shape(), dtype=int) != sum(dims):
AttributeError: 'Constant' object has no attribute 'value_shape'
```

**Comment by wence-** [comment]
This is API-compat, right?  i.e.:

```python
u = interpolate(Constant(...), V)
```

should turn into:

```python
u = Function(V).assign(Constant(...))
```

Obviously this doesn't work for nodes that are not point evaluation, but currently interpolate doesn't work for that use case anyway.
