### ISSUE TITLE
Mass lumping with vector functions

### ISSUE THREAD

**Issue by ctjacobs** [firedrakeproject/firedrake#539]
I'm trying the following to mass lump with a vector `Function`, but it's currently failing with `ufl.log.UFLException: Division by non-scalar is undefined.`

```
from firedrake import *

mesh = UnitSquareMesh(10, 10)
U = VectorFunctionSpace(mesh, "CG", 1)

w = TestFunction(U)
u = TrialFunction(U)

u0 = Function(U).interpolate(Expression(("cos(x[0])", "sin(x[1])")))
F = inner(grad(w), grad(u0))*dx

one = Function(U).interpolate(Expression(("1",) * U.cdim))
M_lumped = assemble(action(inner(w, u)*dx, one))

print type(M_lumped)
result = (assemble(rhs(F)))/M_lumped
```

Is this a limitation on the UFL side of things?

**Comment by wence-** [comment]
Workaround:

```python

inv_lumped = Function(U).assign(1)

inv_lumped /= M_lumped

result = assemble(rhs(F)))*inv_lumped
```

**Comment by wence-** [comment]
yes, it is a limitation on the UFL side of things.

**Comment by ctjacobs** [comment]
Thanks. I tried with `result = assemble(rhs(F))*inv_lumped` but this gave:

```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    result = assemble(rhs(F))*inv_lumped
  File "/usr/local/lib/python2.7/dist-packages/ufl/exproperators.py", line 164, in _mul
    return _mult(self, o)
  File "/usr/local/lib/python2.7/dist-packages/ufl/exproperators.py", line 142, in _mult
    error("Invalid ranks {0} and {1} in product.".format(r1, r2))
  File "/usr/local/lib/python2.7/dist-packages/ufl/log.py", line 151, in error
    raise self._exception_type(self._format_raw(*message))
ufl.log.UFLException: Invalid ranks 1 and 1 in product.
```

Changing to

```
result = Function(U).assign(assemble(rhs(F)))
result *= inv_lumped
```

seems to work.
