### ISSUE TITLE
Support for building TensorFunctionSpaces on quadrilateral meshes

### ISSUE THREAD

**Issue by ctjacobs** [firedrakeproject/firedrake#542]
Another one for the wishlist.

```
from firedrake import *
mesh = UnitSquareMesh(10, 10, quadrilateral=True)
T = TensorFunctionSpace(mesh, "CG", 1)
```

fails with

```
Traceback (most recent call last):
  File "quads.py", line 3, in <module>
    T = TensorFunctionSpace(mesh, "CG", 1)
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_333_g5773d39-py2.7-linux-x86_64.egg/pyop2/caching.py", line 161, in __new__
    obj = make_obj()
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_333_g5773d39-py2.7-linux-x86_64.egg/pyop2/caching.py", line 142, in make_obj
    obj.__init__(*args, **kwargs)
  File "/data/firedrake/firedrake/functionspace.py", line 609, in __init__
    raise NotImplementedError("Cannot currently build a TensorFunctionSpace on a quadrilateral mesh.")
NotImplementedError: Cannot currently build a TensorFunctionSpace on a quadrilateral mesh.
```

**Comment by wence-** [comment]
You're out of date, already works.
