### ISSUE TITLE
Quasi-Newton Broyden: Unassembled matrix?

### ISSUE THREAD

**Issue by anriseth** [firedrakeproject/firedrake#545]
I can't seem to get Quasi-Newton with Jacobian restarts to work with Firedrake. Broyden complains about an unassembled matrix, and LBFGS blows up.

Tested on http://firedrakeproject.org/demos/burgers.py, with options prefix "od_". I have dumped the output below.

Broyden:
```
  0 SNES Function norm 2.128973860906e-02 
Traceback (most recent call last):
  File "burgers.py", line 102, in <module>
    solve(F == 0, u, options_prefix='od_')
  File "/home/riseth/.virtualenvs/firedrake/local/lib/python2.7/site-packages/firedrake/solving.py", line 119, in solve
    _solve_varproblem(*args, **kwargs)
  File "/home/riseth/.virtualenvs/firedrake/local/lib/python2.7/site-packages/firedrake/solving.py", line 161, in _solve_varproblem
    solver.solve()
  File "<string>", line 2, in solve
  File "/home/riseth/.virtualenvs/firedrake/local/lib/python2.7/site-packages/PyOP2-0.11.0_333_g5773d39-py2.7-linux-x86_64.egg/pyop2/profiling.py", line 203, in wrapper
    return f(*args, **kwargs)
  File "/home/riseth/.virtualenvs/firedrake/local/lib/python2.7/site-packages/firedrake/variational_solver.py", line 169, in solve
    self.snes.solve(None, v)
  File "PETSc/SNES.pyx", line 520, in petsc4py.PETSc.SNES.solve (src/petsc4py.PETSc.c:162855)
petsc4py.PETSc.Error: error code 73
[0] SNESSolve() line 3894 in /home/riseth/.virtualenvs/firedrake/build/petsc/src/snes/interface/snes.c
[0] SNESSolve_QN() line 398 in /home/riseth/.virtualenvs/firedrake/build/petsc/src/snes/impls/qn/qn.c
[0] SNESQNApply_Broyden() line 57 in /home/riseth/.virtualenvs/firedrake/build/petsc/src/snes/impls/qn/qn.c
[0] KSPSolve() line 546 in /home/riseth/.virtualenvs/firedrake/build/petsc/src/ksp/ksp/interface/itfunc.c
[0] KSPSetUp() line 332 in /home/riseth/.virtualenvs/firedrake/build/petsc/src/ksp/ksp/interface/itfunc.c
[0] PCSetUp() line 982 in /home/riseth/.virtualenvs/firedrake/build/petsc/src/ksp/pc/interface/precon.c
[0] PCSetUp_ILU() line 194 in /home/riseth/.virtualenvs/firedrake/build/petsc/src/ksp/pc/impls/factor/ilu/ilu.c
[0] MatGetOrdering() line 189 in /home/riseth/.virtualenvs/firedrake/build/petsc/src/mat/order/sorder.c
[0] Object is in wrong state
[0] Not for unassembled matrix
************************************************************************************************************************
***             WIDEN YOUR WINDOW TO 120 CHARACTERS.  Use 'enscript -r -fCourier9' to print this document            ***
************************************************************************************************************************

---------------------------------------------- PETSc Performance Summary: ----------------------------------------------

burgers.py on a arch-python-linux-x86_64 named mystique.maths.ox.ac.uk with 1 processor, by riseth Tue Jun 23 10:57:58 2015
Using Petsc Development GIT revision: v3.5.2-3547-gf6dae19  GIT Date: 2015-06-08 16:14:54 -0600

                         Max       Max/Min        Avg      Total 
Time (sec):           2.651e+00      1.00000   2.651e+00
Objects:              1.590e+02      1.00000   1.590e+02
Flops:                9.902e+06      1.00000   9.902e+06  9.902e+06
Flops/sec:            3.735e+06      1.00000   3.735e+06  3.735e+06
MPI Messages:         0.000e+00      0.00000   0.000e+00  0.000e+00
MPI Message Lengths:  0.000e+00      0.00000   0.000e+00  0.000e+00
MPI Reductions:       0.000e+00      0.00000

Flop counting convention: 1 flop = 1 real number operation of type (multiply/divide/add/subtract)
                            e.g., VecAXPY() for real vectors of length N --> 2N flops
                            and VecAXPY() for complex vectors of length N --> 8N flops

Summary of Stages:   ----- Time ------  ----- Flops -----  --- Messages ---  -- Message Lengths --  -- Reductions --
                        Avg     %Total     Avg     %Total   counts   %Total     Avg         %Total   counts   %Total 
 0:      Main Stage: 2.6509e+00 100.0%  9.9016e+06 100.0%  0.000e+00   0.0%  0.000e+00        0.0%  0.000e+00   0.0% 

------------------------------------------------------------------------------------------------------------------------
See the 'Profiling' chapter of the users' manual for details on interpreting output.
Phase summary info:
   Count: number of times phase was executed
   Time and Flops: Max - maximum over all processors
                   Ratio - ratio of maximum to minimum over all processors
   Mess: number of messages sent
   Avg. len: average message length (bytes)
   Reduct: number of global reductions
   Global: entire computation
   Stage: stages of a computation. Set stages with PetscLogStagePush() and PetscLogStagePop().
      %T - percent time in this phase         %F - percent flops in this phase
      %M - percent messages in this phase     %L - percent message lengths in this phase
      %R - percent reductions in this phase
   Total Mflop/s: 10e-6 * (sum of flops over all processors)/(max time over all processors)
------------------------------------------------------------------------------------------------------------------------
Event                Count      Time (sec)     Flops                             --- Global ---  --- Stage ---   Total
                   Max Ratio  Max     Ratio   Max  Ratio  Mess   Avg len Reduct  %T %F %M %L %R  %T %F %M %L %R Mflop/s
------------------------------------------------------------------------------------------------------------------------

--- Event Stage 0: Main Stage

VecTDot               30 1.0 1.3757e-04 1.0 2.92e+05 1.0 0.0e+00 0.0e+00 0.0e+00  0  3  0  0  0   0  3  0  0  0  2122
VecNorm               18 1.0 9.7036e-05 1.0 1.80e+05 1.0 0.0e+00 0.0e+00 0.0e+00  0  2  0  0  0   0  2  0  0  0  1851
VecCopy               11 1.0 6.2704e-05 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
VecSet                30 1.0 5.0163e-04 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
VecAXPY               32 1.0 1.1826e-04 1.0 3.11e+05 1.0 0.0e+00 0.0e+00 0.0e+00  0  3  0  0  0   0  3  0  0  0  2627
VecAYPX               13 1.0 8.0824e-05 1.0 1.27e+05 1.0 0.0e+00 0.0e+00 0.0e+00  0  1  0  0  0   0  1  0  0  0  1574
MatMult               15 1.0 1.0340e-03 1.0 2.97e+06 1.0 0.0e+00 0.0e+00 0.0e+00  0 30  0  0  0   0 30  0  0  0  2873
MatSolve              17 1.0 1.5481e-03 1.0 3.27e+06 1.0 0.0e+00 0.0e+00 0.0e+00  0 33  0  0  0   0 33  0  0  0  2109
MatLUFactorNum         2 1.0 1.6952e-03 1.0 2.76e+06 1.0 0.0e+00 0.0e+00 0.0e+00  0 28  0  0  0   0 28  0  0  0  1626
MatILUFactorSym        2 1.0 8.3709e-04 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
MatAssemblyBegin       6 1.0 3.8147e-06 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
MatAssemblyEnd         6 1.0 1.1611e-04 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
MatGetRowIJ            2 1.0 9.5367e-07 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
MatGetOrdering         2 1.0 1.1206e-04 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
MatZeroEntries         3 1.0 4.0007e-04 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
PCApply               17 1.0 1.5659e-03 1.0 3.27e+06 1.0 0.0e+00 0.0e+00 0.0e+00  0 33  0  0  0   0 33  0  0  0  2085
KSPSetUp               3 1.0 2.6274e-04 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
SNESFunctionEval       3 1.0 2.6328e-01 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00 10  0  0  0  0  10  0  0  0  0     0
SNESJacobianEval       3 1.0 3.5669e-01 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00 13  0  0  0  0  13  0  0  0  0     0
DMPlexInterp           1 1.0 4.0340e-03 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
DMPlexStratify         3 1.0 1.8210e-03 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
SFSetGraph             9 1.0 5.3859e-04 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
------------------------------------------------------------------------------------------------------------------------

Memory usage is given in bytes:

Object Type          Creations   Destructions     Memory  Descendants' Mem.
Reports information only for process 0.

--- Event Stage 0: Main Stage

           Container     8              4         2272     0
              Viewer     1              0            0     0
           Index Set    15             14       137136     0
   IS L to G Mapping     2              0            0     0
             Section    27              6         3984     0
              Vector    40             27      1086088     0
              Matrix     7              4      1825704     0
      Preconditioner     3              3         3000     0
       Krylov Solver     3              3        20792     0
     DMKSP interface     2              0            0     0
                SNES     3              3         4136     0
      SNESLineSearch     3              3         2584     0
              DMSNES     2              0            0     0
    Distributed Mesh     9              3        14152     0
    GraphPartitioner     3              2         1208     0
Star Forest Bipartite Graph    22             11         8800     0
     Discrete System     9              3         2544     0
========================================================================================================================
Average time to get PetscTime(): 9.53674e-08
#PETSc Option Table entries:
-log_summary
-od_snes_max_it 5
-od_snes_monitor
-od_snes_qn_m 1
-od_snes_qn_monitor
-od_snes_qn_restart_type periodic
-od_snes_qn_scale_type jacobian
-od_snes_qn_type broyden
-od_snes_type qn
#End of PETSc Option Table entries
Compiled without FORTRAN kernels
Compiled with full precision matrices (default)
sizeof(short) 2 sizeof(int) 4 sizeof(long) 8 sizeof(void*) 8 sizeof(PetscScalar) 8 sizeof(PetscInt) 4
Configure options: --prefix=/home/riseth/.virtualenvs/firedrake/lib/python2.7/site-packages/petsc PETSC_ARCH=arch-python-linux-x86_64 --with-shared-libraries=1 --with-debugging=0 --with-c2html=0 --with-cc=/usr/bin/mpicc --with-cxx=/usr/bin/mpicxx --with-fc=/usr/bin/mpif90 --download-ctetgen --download-triangle --download-chaco --download-mumps --download-scalapack --download-parmetis --download-metis --download-superlu_dist --download-hypre --download-hdf5 --download-ml
-----------------------------------------
Libraries compiled on Wed Jun 10 09:48:49 2015 on mystique.maths.ox.ac.uk 
Machine characteristics: Linux-3.16.0-38-generic-x86_64-with-Ubuntu-14.04-trusty
Using PETSc directory: /home/riseth/.virtualenvs/firedrake/build/petsc
Using PETSc arch: arch-python-linux-x86_64
-----------------------------------------

Using C compiler: /usr/bin/mpicc  -fPIC -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -O  ${COPTFLAGS} ${CFLAGS}
Using Fortran compiler: /usr/bin/mpif90  -fPIC -Wall -Wno-unused-variable -ffree-line-length-0 -Wno-unused-dummy-argument -O   ${FOPTFLAGS} ${FFLAGS} 
-----------------------------------------

Using include paths: -I/home/riseth/.virtualenvs/firedrake/build/petsc/arch-python-linux-x86_64/include -I/home/riseth/.virtualenvs/firedrake/build/petsc/include -I/home/riseth/.virtualenvs/firedrake/build/petsc/include -I/home/riseth/.virtualenvs/firedrake/build/petsc/arch-python-linux-x86_64/include -I/home/riseth/.virtualenvs/firedrake/lib/python2.7/site-packages/petsc/include -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi
-----------------------------------------

Using C linker: /usr/bin/mpicc
Using Fortran linker: /usr/bin/mpif90
Using libraries: -Wl,-rpath,/home/riseth/.virtualenvs/firedrake/build/petsc/arch-python-linux-x86_64/lib -L/home/riseth/.virtualenvs/firedrake/build/petsc/arch-python-linux-x86_64/lib -lpetsc -Wl,-rpath,/home/riseth/.virtualenvs/firedrake/lib/python2.7/site-packages/petsc/lib -L/home/riseth/.virtualenvs/firedrake/lib/python2.7/site-packages/petsc/lib -lcmumps -ldmumps -lsmumps -lzmumps -lmumps_common -lpord -lscalapack -lml -Wl,-rpath,/usr/lib/openmpi/lib -L/usr/lib/openmpi/lib -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -lmpi_cxx -lstdc++ -lsuperlu_dist_4.0 -lHYPRE -lmpi_cxx -lstdc++ -llapack -lblas -lparmetis -lmetis -lctetgen -ltriangle -lX11 -lhdf5hl_fortran -lhdf5_fortran -lhdf5_hl -lhdf5 -lssl -lcrypto -lchaco -lm -lmpi_f90 -lmpi_f77 -lgfortran -lm -lgfortran -lm -lquadmath -lm -lmpi_cxx -lstdc++ -Wl,-rpath,/usr/lib/openmpi/lib -L/usr/lib/openmpi/lib -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -ldl -lmpi -lhwloc -lgcc_s -lpthread -ldl 
-----------------------------------------

```

LBFGS:
```
  0 SNES Function norm 2.128973860906e-02 
  1 SNES Function norm 4.223015653749e-03 
    it: 1 k: 0 alpha:        1.171088547398e-08
  2 SNES Function norm 3.121919580074e-03 
    restart! |0.000000000000e+00| > 1.00*|6.945405525772e-310| or i_r = 1
  3 SNES Function norm 2.750357100426e-03 
    it: 1 k: 0 alpha:        -5.530226890232e-09
  4 SNES Function norm 4.759382388579e-03 
    restart! |0.000000000000e+00| > 1.00*|6.945405525772e-310| or i_r = 1
  5 SNES Function norm 1.422345639352e-02 
Traceback (most recent call last):
  File "burgers.py", line 102, in <module>
    solve(F == 0, u, options_prefix='od_')
  File "/home/riseth/.virtualenvs/firedrake/local/lib/python2.7/site-packages/firedrake/solving.py", line 119, in solve
    _solve_varproblem(*args, **kwargs)
  File "/home/riseth/.virtualenvs/firedrake/local/lib/python2.7/site-packages/firedrake/solving.py", line 161, in _solve_varproblem
    solver.solve()
  File "<string>", line 2, in solve
  File "/home/riseth/.virtualenvs/firedrake/local/lib/python2.7/site-packages/PyOP2-0.11.0_333_g5773d39-py2.7-linux-x86_64.egg/pyop2/profiling.py", line 203, in wrapper
    return f(*args, **kwargs)
  File "/home/riseth/.virtualenvs/firedrake/local/lib/python2.7/site-packages/firedrake/variational_solver.py", line 171, in solve
    solving_utils.check_snes_convergence(self.snes)
  File "/home/riseth/.virtualenvs/firedrake/local/lib/python2.7/site-packages/firedrake/solving_utils.py", line 62, in check_snes_convergence
    %s""" % (snes.getIterationNumber(), msg))
RuntimeError: Nonlinear solve failed to converge after 5 nonlinear iterations.
Reason:
   DIVERGED_MAX_IT
************************************************************************************************************************
***             WIDEN YOUR WINDOW TO 120 CHARACTERS.  Use 'enscript -r -fCourier9' to print this document            ***
************************************************************************************************************************

---------------------------------------------- PETSc Performance Summary: ----------------------------------------------

burgers.py on a arch-python-linux-x86_64 named mystique.maths.ox.ac.uk with 1 processor, by riseth Tue Jun 23 10:57:43 2015
Using Petsc Development GIT revision: v3.5.2-3547-gf6dae19  GIT Date: 2015-06-08 16:14:54 -0600

                         Max       Max/Min        Avg      Total 
Time (sec):           2.022e+00      1.00000   2.022e+00
Objects:              1.840e+02      1.00000   1.840e+02
Flops:                1.060e+07      1.00000   1.060e+07  1.060e+07
Flops/sec:            5.244e+06      1.00000   5.244e+06  5.244e+06
MPI Messages:         0.000e+00      0.00000   0.000e+00  0.000e+00
MPI Message Lengths:  0.000e+00      0.00000   0.000e+00  0.000e+00
MPI Reductions:       0.000e+00      0.00000

Flop counting convention: 1 flop = 1 real number operation of type (multiply/divide/add/subtract)
                            e.g., VecAXPY() for real vectors of length N --> 2N flops
                            and VecAXPY() for complex vectors of length N --> 8N flops

Summary of Stages:   ----- Time ------  ----- Flops -----  --- Messages ---  -- Message Lengths --  -- Reductions --
                        Avg     %Total     Avg     %Total   counts   %Total     Avg         %Total   counts   %Total 
 0:      Main Stage: 2.0216e+00 100.0%  1.0601e+07 100.0%  0.000e+00   0.0%  0.000e+00        0.0%  0.000e+00   0.0% 

------------------------------------------------------------------------------------------------------------------------
See the 'Profiling' chapter of the users' manual for details on interpreting output.
Phase summary info:
   Count: number of times phase was executed
   Time and Flops: Max - maximum over all processors
                   Ratio - ratio of maximum to minimum over all processors
   Mess: number of messages sent
   Avg. len: average message length (bytes)
   Reduct: number of global reductions
   Global: entire computation
   Stage: stages of a computation. Set stages with PetscLogStagePush() and PetscLogStagePop().
      %T - percent time in this phase         %F - percent flops in this phase
      %M - percent messages in this phase     %L - percent message lengths in this phase
      %R - percent reductions in this phase
   Total Mflop/s: 10e-6 * (sum of flops over all processors)/(max time over all processors)
------------------------------------------------------------------------------------------------------------------------
Event                Count      Time (sec)     Flops                             --- Global ---  --- Stage ---   Total
                   Max Ratio  Max     Ratio   Max  Ratio  Mess   Avg len Reduct  %T %F %M %L %R  %T %F %M %L %R Mflop/s
------------------------------------------------------------------------------------------------------------------------

--- Event Stage 0: Main Stage

VecDot                10 1.0 7.7248e-05 1.0 1.49e+05 1.0 0.0e+00 0.0e+00 0.0e+00  0  1  0  0  0   0  1  0  0  0  1927
VecTDot               30 1.0 1.3804e-04 1.0 2.92e+05 1.0 0.0e+00 0.0e+00 0.0e+00  0  3  0  0  0   0  3  0  0  0  2115
VecNorm               18 1.0 8.6069e-05 1.0 1.80e+05 1.0 0.0e+00 0.0e+00 0.0e+00  0  2  0  0  0   0  2  0  0  0  2086
VecCopy               62 1.0 2.9111e-04 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
VecSet                53 1.0 8.3137e-04 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
VecAXPY               48 1.0 2.4581e-04 1.0 5.49e+05 1.0 0.0e+00 0.0e+00 0.0e+00  0  5  0  0  0   0  5  0  0  0  2233
VecAYPX               13 1.0 7.6771e-05 1.0 1.27e+05 1.0 0.0e+00 0.0e+00 0.0e+00  0  1  0  0  0   0  1  0  0  0  1658
VecReduceArith        21 1.0 1.3685e-04 1.0 3.13e+05 1.0 0.0e+00 0.0e+00 0.0e+00  0  3  0  0  0   0  3  0  0  0  2284
VecReduceComm          7 1.0 3.0994e-06 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
MatMult               15 1.0 1.0176e-03 1.0 2.97e+06 1.0 0.0e+00 0.0e+00 0.0e+00  0 28  0  0  0   0 28  0  0  0  2919
MatSolve              17 1.0 1.4577e-03 1.0 3.27e+06 1.0 0.0e+00 0.0e+00 0.0e+00  0 31  0  0  0   0 31  0  0  0  2240
MatLUFactorNum         2 1.0 1.6801e-03 1.0 2.76e+06 1.0 0.0e+00 0.0e+00 0.0e+00  0 26  0  0  0   0 26  0  0  0  1641
MatILUFactorSym        2 1.0 8.2326e-04 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
MatConvert             2 1.0 1.0340e-03 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
MatAssemblyBegin       8 1.0 1.9073e-06 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
MatAssemblyEnd         8 1.0 1.2589e-04 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
MatGetRowIJ            2 1.0 9.5367e-07 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
MatGetOrdering         2 1.0 8.0109e-05 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
MatZeroEntries         5 1.0 3.2473e-04 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
PCApply               17 1.0 1.4699e-03 1.0 3.27e+06 1.0 0.0e+00 0.0e+00 0.0e+00  0 31  0  0  0   0 31  0  0  0  2222
KSPSetUp               7 1.0 6.0797e-04 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
SNESSolve              3 1.0 6.2059e-01 1.0 1.06e+07 1.0 0.0e+00 0.0e+00 0.0e+00 31100  0  0  0  31100  0  0  0    17
SNESFunctionEval      13 1.0 2.4188e-01 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00 12  0  0  0  0  12  0  0  0  0     0
SNESJacobianEval       5 1.0 3.6484e-01 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00 18  0  0  0  0  18  0  0  0  0     0
SNESLineSearch         5 1.0 2.1861e-02 1.0 5.21e+05 1.0 0.0e+00 0.0e+00 0.0e+00  1  5  0  0  0   1  5  0  0  0    24
DMPlexInterp           1 1.0 3.3619e-03 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
DMPlexStratify         3 1.0 1.5140e-03 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
SFSetGraph             9 1.0 4.8566e-04 1.0 0.00e+00 0.0 0.0e+00 0.0e+00 0.0e+00  0  0  0  0  0   0  0  0  0  0     0
------------------------------------------------------------------------------------------------------------------------

Memory usage is given in bytes:

Object Type          Creations   Destructions     Memory  Descendants' Mem.
Reports information only for process 0.

--- Event Stage 0: Main Stage

           Container     8              4         2272     0
              Viewer     1              0            0     0
           Index Set    15             14       137136     0
   IS L to G Mapping     2              0            0     0
             Section    27              6         3984     0
              Vector    63             30      1269280     0
              Matrix     9              6      4935584     0
      Preconditioner     3              3         3000     0
       Krylov Solver     3              3        89016     0
     DMKSP interface     2              0            0     0
                SNES     3              3         4136     0
      SNESLineSearch     3              3         2584     0
              DMSNES     2              0            0     0
    Distributed Mesh     9              3        14152     0
    GraphPartitioner     3              2         1208     0
Star Forest Bipartite Graph    22             11         8800     0
     Discrete System     9              3         2544     0
========================================================================================================================
Average time to get PetscTime(): 0
#PETSc Option Table entries:
-log_summary
-od_snes_max_it 5
-od_snes_monitor
-od_snes_qn_m 1
-od_snes_qn_monitor
-od_snes_qn_restart_type periodic
-od_snes_qn_scale_type jacobian
-od_snes_qn_type lbfgs
-od_snes_type qn
#End of PETSc Option Table entries
Compiled without FORTRAN kernels
Compiled with full precision matrices (default)
sizeof(short) 2 sizeof(int) 4 sizeof(long) 8 sizeof(void*) 8 sizeof(PetscScalar) 8 sizeof(PetscInt) 4
Configure options: --prefix=/home/riseth/.virtualenvs/firedrake/lib/python2.7/site-packages/petsc PETSC_ARCH=arch-python-linux-x86_64 --with-shared-libraries=1 --with-debugging=0 --with-c2html=0 --with-cc=/usr/bin/mpicc --with-cxx=/usr/bin/mpicxx --with-fc=/usr/bin/mpif90 --download-ctetgen --download-triangle --download-chaco --download-mumps --download-scalapack --download-parmetis --download-metis --download-superlu_dist --download-hypre --download-hdf5 --download-ml
-----------------------------------------
Libraries compiled on Wed Jun 10 09:48:49 2015 on mystique.maths.ox.ac.uk 
Machine characteristics: Linux-3.16.0-38-generic-x86_64-with-Ubuntu-14.04-trusty
Using PETSc directory: /home/riseth/.virtualenvs/firedrake/build/petsc
Using PETSc arch: arch-python-linux-x86_64
-----------------------------------------

Using C compiler: /usr/bin/mpicc  -fPIC -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -O  ${COPTFLAGS} ${CFLAGS}
Using Fortran compiler: /usr/bin/mpif90  -fPIC -Wall -Wno-unused-variable -ffree-line-length-0 -Wno-unused-dummy-argument -O   ${FOPTFLAGS} ${FFLAGS} 
-----------------------------------------

Using include paths: -I/home/riseth/.virtualenvs/firedrake/build/petsc/arch-python-linux-x86_64/include -I/home/riseth/.virtualenvs/firedrake/build/petsc/include -I/home/riseth/.virtualenvs/firedrake/build/petsc/include -I/home/riseth/.virtualenvs/firedrake/build/petsc/arch-python-linux-x86_64/include -I/home/riseth/.virtualenvs/firedrake/lib/python2.7/site-packages/petsc/include -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi
-----------------------------------------

Using C linker: /usr/bin/mpicc
Using Fortran linker: /usr/bin/mpif90
Using libraries: -Wl,-rpath,/home/riseth/.virtualenvs/firedrake/build/petsc/arch-python-linux-x86_64/lib -L/home/riseth/.virtualenvs/firedrake/build/petsc/arch-python-linux-x86_64/lib -lpetsc -Wl,-rpath,/home/riseth/.virtualenvs/firedrake/lib/python2.7/site-packages/petsc/lib -L/home/riseth/.virtualenvs/firedrake/lib/python2.7/site-packages/petsc/lib -lcmumps -ldmumps -lsmumps -lzmumps -lmumps_common -lpord -lscalapack -lml -Wl,-rpath,/usr/lib/openmpi/lib -L/usr/lib/openmpi/lib -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -lmpi_cxx -lstdc++ -lsuperlu_dist_4.0 -lHYPRE -lmpi_cxx -lstdc++ -llapack -lblas -lparmetis -lmetis -lctetgen -ltriangle -lX11 -lhdf5hl_fortran -lhdf5_fortran -lhdf5_hl -lhdf5 -lssl -lcrypto -lchaco -lm -lmpi_f90 -lmpi_f77 -lgfortran -lm -lgfortran -lm -lquadmath -lm -lmpi_cxx -lstdc++ -Wl,-rpath,/usr/lib/openmpi/lib -L/usr/lib/openmpi/lib -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -ldl -lmpi -lhwloc -lgcc_s -lpthread -ldl 
-----------------------------------------

```

**Comment by wence-** [comment]
Huh, odd. I'm not sure what's going on here since I think we always feed an assembled matrix back to petsc. I'll have a chance to look at this next week maybe (but probably the week after)
