### ISSUE TITLE
"negative dimensions are not allowed" error when printing OP2.Mat values

### ISSUE THREAD

**Issue by ctjacobs** [firedrakeproject/firedrake#548]
The following code fails when printing out the OP2.Mat values:

```
from firedrake import *
Lx = 300.0
Ly = 150.0
h = 2.5
mesh = RectangleMesh(int(Lx/h), int(Ly/h), Lx, Ly)

vfs = VectorFunctionSpace(mesh, "DG", 1)
w = TestFunction(vfs)
u = TrialFunction(vfs)

inverse_mass_velocity = assemble(inner(w, u)*dx, inverse=True)
inverse_mass_velocity.assemble()
print inverse_mass_velocity.M.values
```

```
Traceback (most recent call last):
  File "negative_index.py", line 13, in <module>
    print inverse_mass_velocity.M.values
  File "<string>", line 2, in values
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_333_g5773d39-py2.7-linux-x86_64.egg/pyop2/versioning.py", line 111, in modifies
    retval = method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_333_g5773d39-py2.7-linux-x86_64.egg/pyop2/petsc_base.py", line 724, in values
    return self.handle[:, :]
  File "PETSc/Mat.pyx", line 218, in petsc4py.PETSc.Mat.__getitem__ (src/petsc4py.PETSc.c:107020)
  File "PETSc/petscmat.pxi", line 962, in petsc4py.PETSc.mat_getitem (src/petsc4py.PETSc.c:28596)
  File "PETSc/petscmat.pxi", line 876, in petsc4py.PETSc.matgetvalues (src/petsc4py.PETSc.c:27328)
  File "PETSc/arraynpy.pxi", line 85, in petsc4py.PETSc.empty_s (src/petsc4py.PETSc.c:7670)
ValueError: negative dimensions are not allowed
```

The error not longer occurs if the values in the call to `RectangleMesh` are changed to, say, `10, 10, 10, 10`.

**Comment by wence-** [comment]
You're trying to get a dense matrix that is 86400x86400.  You're therefore failing to allocate memory for it.

**Comment by wence-** [comment]
PEBKAC.  Latest PyOP2 now raises a sensible error when you try and do this.
