### ISSUE TITLE
Cannot assign when identical FunctionSpaces are built in different ways

### ISSUE THREAD

**Issue by dorugeber** [firedrakeproject/firedrake#568]
```
from firedrake import *

parameters["pyop2_options"]["lazy_evaluation"] = False

m = UnitSquareMesh(1, 1)
mesh = ExtrudedMesh(m, layers=1)

h_elt = FiniteElement("DG", triangle, 1)
v_elt = FiniteElement("DG", interval, 1)

V = FunctionSpace(mesh, OuterProductElement(h_elt, v_elt))
W = FunctionSpace(mesh, "DG", 1)

a = Function(V).assign(5)
b = Function(W)

b.assign(a)
```

`V` and `W` are the same function space but built in different ways, which prevents assignment.

```
atm112@ubuntu:~$ python bork.py 
Discontinuous Lagrange element requested on OuterProductCell, creating DQ element.
Traceback (most recent call last):
  File "bork.py", line 17, in <module>
    b.assign(a)
  File "/home/atm112/local/firedrake/firedrake/function.py", line 422, in assign
    assemble_expressions.Assign(self, expr), subset)
  File "/home/atm112/local/firedrake/firedrake/assemble_expressions.py", line 574, in evaluate_expression
    for tree in ExpressionSplitter().split(expr):
  File "/home/atm112/local/firedrake/firedrake/assemble_expressions.py", line 289, in split
    return [expr.reconstruct(*ops) for ops in zip(*map(self.visit, (lhs, rhs)))]
  File "/home/atm112/local/ufl/ufl/algorithms/transformer.py", line 106, in visit
    r = h(o)
  File "/home/atm112/local/firedrake/firedrake/assemble_expressions.py", line 325, in terminal
    raise ValueError("Coefficient %r is not indexed" % o)
ValueError: Coefficient Coefficient(OuterProductElement(*[FiniteElement('Discontinuous Lagrange', Domain(Cell('triangle', 2), label=None, data=None), 1, quad_scheme=None), FiniteElement('Discontinuous Lagrange', Domain(Cell('interval', 1), label=None, data=None), 1, quad_scheme=None)], Domain(Coefficient(OuterProductVectorElement(OuterProductElement(*[FiniteElement('Lagrange', Domain(Cell('triangle', 2), label=None, data=None), 1, quad_scheme=None), FiniteElement('Lagrange', Domain(Cell('interval', 1), label=None, data=None), 1, quad_scheme=None)], Domain(OuterProductCell(*[Cell('triangle', 2), Cell('interval', 1)]), label=None, data='<data with id 140124393206352>')), dim=3), 4))), 9) is not indexed
```

**Comment by miklos1** [comment]
`ExpressionSplitter` checks for the equality of function spaces. Since they don't have a custom equality operator defined, it falls back to object equality. This is were the object cache fixes the behaviour in certain cases. Unfortunately the UFL expansion of function space abbreviation happens only after the cache key is generated.

**Comment by miklos1** [comment]
Related to #401.
