### ISSUE TITLE
Cannot assemble form with multiple manually-set quadrature degrees

### ISSUE THREAD

**Issue by dorugeber** [firedrakeproject/firedrake#580]
I don't know whether this is expected to work, but here goes...

```
from firedrake import *

mesh = UnitSquareMesh(4, 4)

V = FunctionSpace(mesh, "CG", 3)

f = Function(V).interpolate(Expression("pow(x[0], 3)"))

# print assemble(f*dx(degree=1) + f*dx(degree=3))
print assemble(f*dx(degree=1))
print assemble(f*dx(degree=3))
```

As written, the output is
```
0.244791666666
0.25
```

Uncommenting the relevant line leads to an FFC error
```
Traceback (most recent call last):
  File "borkbork.py", line 11, in <module>
    print assemble(f*dx(degree=1) + f*dx(degree=3))
  File "/home/atm112/local/firedrake/firedrake/assemble.py", line 67, in assemble
    inverse=inverse, nest=nest)
  File "/home/atm112/local/firedrake/firedrake/assemble.py", line 100, in _assemble
    inverse=inverse)
  File "/home/atm112/local/firedrake/firedrake/ffc_interface.py", line 278, in compile_form
    parameters).kernels)]
  File "/home/atm112/local/PyOP2/pyop2/caching.py", line 203, in __new__
    obj = make_obj()
  File "/home/atm112/local/PyOP2/pyop2/caching.py", line 193, in make_obj
    obj.__init__(*args, **kwargs)
  File "/home/atm112/local/firedrake/firedrake/ffc_interface.py", line 194, in __init__
    ffc_tree = ffc_compile_form(form, prefix=name, parameters=parameters)
  File "/home/atm112/local/ffc/ffc/compiler.py", line 177, in compile_form
    pyop2_ir = [generate_pyop2_ir(ir, prefix, parameters) for ir in oir[2]]
  File "/home/atm112/local/ffc/ffc/quadrature/quadraturepyop2ir.py", line 48, in generate_pyop2_ir
    body_ir = _tabulate_tensor(ir, parameters)
  File "/home/atm112/local/ffc/ffc/quadrature/quadraturepyop2ir.py", line 143, in _tabulate_tensor
    opt_par, parameters)
  File "/home/atm112/local/ffc/ffc/quadrature/quadraturepyop2ir.py", line 387, in _generate_element_tensor
    ffc_assert(1 == len(integrals), "This function is not capable of handling multiple integrals.")
  File "/home/atm112/local/ffc/ffc/log.py", line 44, in ffc_assert
    condition or error(*message)
  File "<string>", line 1, in <lambda>
  File "/home/atm112/local/ufl/ufl/log.py", line 151, in error
    raise self._exception_type(self._format_raw(*message))
Exception: This function is not capable of handling multiple integrals.
```

I half-expected the FormSplitter to split based on quadrature degree, but perhaps it never has done...?

Due to the way we use `action(a, out) - L` for our RHS integral, this stops us from manually setting different quadrature degrees on the LHS and RHS of our equations, for example.

**Comment by wence-** [comment]
I think this patch to ffc does the right thing:

```patch
diff --git a/ffc/quadrature/quadraturepyop2ir.py b/ffc/quadrature/quadraturepyop2ir.py
index a3c077e..b0d6852 100644
--- a/ffc/quadrature/quadraturepyop2ir.py
+++ b/ffc/quadrature/quadraturepyop2ir.py
@@ -384,13 +384,11 @@ def _generate_element_tensor(integrals, sets, optimise_parameters, parameters):
     # Initialise return values.
     tensor_ops_count = 0
 
-    ffc_assert(1 == len(integrals), "This function is not capable of handling multiple integrals.")
-
     # We receive a dictionary {num_points: form,}.
     # Loop points and forms.
+    nest_ir = []
     for points, terms, functions, ip_consts, coordinate, conditionals in integrals:
 
-        nest_ir = []
         ip_ir = []
         num_ops = 0
 

```

**Comment by wence-** [comment]
It turns out that is not enough.  If I do that thing, then I get kernels that have multiple quadrature loops in them.  COFFEE then barfs.

e.g.

```python
def test_simple_mass():
    mesh = UnitSquareMesh(4, 4)

    V = FunctionSpace(mesh, "CG", 2)

    f = Function(V)

    f.interpolate(Expression("x[0]*x[1]"))
    dx1 = dx(degree=5)
    dx2 = dx(degree=6)

    u = TrialFunction(V)

    v = TestFunction(V)

    g = Function(V)
    solve(u*v*dx1 == f*v*dx2, g)

    assert np.allclose(g.dat.data_ro, f.dat.data_ro)
```

```
../deps/COFFEE/coffee/plan.py:396: in plan_cpu
    _generate_cpu_code(self, kernel, **params)
../deps/COFFEE/coffee/plan.py:232: in _generate_cpu_code
    loop_opt.rewrite(rewrite)
../deps/COFFEE/coffee/optimizer.py:135: in rewrite
    ew.licm(only_outdomain=True)
../deps/COFFEE/coffee/rewriter.py:114: in licm
    self.expr_hoister.licm(**kwargs)
../deps/COFFEE/coffee/rewriter.py:587: in licm
    extracted = self._extract(self.stmt.rvalue, symbols, **kwargs)
../deps/COFFEE/coffee/rewriter.py:553: in _extract
    __extract(node, dep_subexprs)
../deps/COFFEE/coffee/rewriter.py:492: in __extract
    return (__extract(node.child, dep_subexprs))
../deps/COFFEE/coffee/rewriter.py:503: in __extract
    dep_l, info_l = __extract(left, dep_subexprs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

node = <coffee.base.Symbol object at 0x7f951d2ed810>, dep_subexprs = defaultdict(<type 'list'>, {})

    def __extract(node, dep_subexprs):
        if isinstance(node, Symbol):
>           return (symbols[node], INVARIANT)
E           KeyError: <coffee.base.Symbol object at 0x7f951d2ed810>

../deps/COFFEE/coffee/rewriter.py:489: KeyError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /data/lmitche1/src/deps/COFFEE/coffee/rewriter.py(489)__extract()
    488             if isinstance(node, Symbol):
--> 489                 return (symbols[node], INVARIANT)
    490 

```

@FabioLuporini I guess this is not something you ever expected to see?  However, I would really like not to make two kernels for this (that I then have to loop-fuse so I get data reuse).  It's arguable whether specifying different quadrature degrees for different terms is the "right thing", but if we don't want to support it, we should say so.

**Comment by FabioLuporini** [comment]
Actually, COFFEE should just be capable of handling this. It can perform the expression rewriting correctly, but it fails on the vectorizer (padding/data alignment). It's not a trivial fix, but I agree with you we should handle this. It's not complicated, it just needs a bit of thinking -- will provide a reasonable fix soon
