### ISSUE TITLE
Provide RW and RO accessors to PETSc matrices

### ISSUE THREAD

**Issue by kalogirou** [firedrakeproject/firedrake#661]
The following code works fine when sluice_gate = 'True' and wave_maker = 'False' (switches in the parameters.py file), but fails with the error below when the True-False are reversed. This case corresponds to the function etaR in Lphi (linear form for phi_solver) begin zero.

[files.zip](https://github.com/firedrakeproject/firedrake/files/59731/files.zip)

Traceback (most recent call last):
  File "buoy-swe.py", line 131, in <module>
    (phi0, eta0, W0, Z0) = solvers_SV(rhs, mu0_5, mu_solver0_5, phi_solver0_5, eta_solver1, phi_solver1, eta0, phi0, Z0, W0, eta1, phi1, Z1, W1, W0_5, step_b, rho, Mass, dt);
  File "/e/data1/users/matak/opt/firedrake/Ship/Modules/Wave-maker/solvers.py", line 164, in solvers_SV
    phi_solver0_5.solve()                           # Solve for phi0_5
  File "<string>", line 2, in solve
  File "/opt/firedrake/3.0/lib/python2.7/site-packages/PyOP2-0.11.0_173_g1e3c1eb-py2.7-linux-x86_64.egg/pyop2/profiling.py", line 197, in wrapper
    return f(_args, *_kwargs)
  File "/opt/firedrake/3.0/lib/python2.7/site-packages/firedrake/variational_solver.py", line 287, in solve
    self.snes.solve(None, v)
  File "PETSc/SNES.pyx", line 516, in petsc4py.PETSc.SNES.solve (src/petsc4py.PETSc.c:161228)
  File "PETSc/petscsnes.pxi", line 284, in petsc4py.PETSc.SNES_Jacobian (src/petsc4py.PETSc.c:31311)
  File "/opt/firedrake/3.0/lib/python2.7/site-packages/firedrake/variational_solver.py", line 175, in form_jacobian
    ctx._jac.M._force_evaluation()
  File "/opt/firedrake/3.0/lib/python2.7/site-packages/firedrake/matrix.py", line 143, in M
    self.assemble()
  File "/opt/firedrake/3.0/lib/python2.7/site-packages/firedrake/matrix.py", line 72, in assemble
    self._assembly_callback(self.bcs)
  File "/opt/firedrake/3.0/lib/python2.7/site-packages/firedrake/assembly_cache.py", line 340, in inner
    PETSc.Mat.Structure.DIFFERENT_NONZERO_PATTERN)
  File "PETSc/Mat.pyx", line 616, in petsc4py.PETSc.Mat.copy (src/petsc4py.PETSc.c:113902)
petsc4py.PETSc.Error: error code 73
[0] SNESSolve() line 3840 in /tmp/pip-0XEmR8-build/src/snes/interface/snes.c
[0] SNESSolve_KSPONLY() line 41 in /tmp/pip-0XEmR8-build/src/snes/impls/ksponly/ksponly.c
[0] SNESComputeJacobian() line 2203 in /tmp/pip-0XEmR8-build/src/snes/interface/snes.c
[0] MatCopy() line 3771 in /tmp/pip-0XEmR8-build/src/mat/interface/matrix.c
[0] Object is in wrong state
[0] Not for factored matrix

**Comment by wence-** [comment]
Hi Anna, this is slightly subtle.

in your `solver_mu` function you do:

```python

    M_form  = mu*v*dx
...
    M  = assemble(M_form).M.handle
# The matrix M is now also in the assembly cache
...
# Now you factor it, so it can't be used except in a MatSolve
    M.factorLU(r, c)

```

Later on, presumably at some later point you end up something that's equivalent to `mu*v*dx` again.  But when Firedrake tries to pull the matrix out of the assembly cache it can't, because it's already factored.

This isn't a use case we had in mind when designing the assembly cache!

You can fix this by just copying that one matrix in your `solver_mu` call:

```python
    M  = assemble(M_form).M.handle.copy()
```

I don't think we can realistically fix this in firedrake because we can't inspect enough of what you do with matrices that you access in this "raw" manner.

**Comment by wence-** [comment]
Oh wait, maybe we could.  We could add `ro` and `rw` like properties to `Mat` objects (similar to the ones that already exist for `Dat`s).  Then you could say how you want to access the matrix and if you want read-write access, then the assembly cache copy can be done before you mess with the values.

**Comment by wence-** [comment]
Hi Anna, can you confirm the workaround I suggested works for you?

**Comment by kalogirou** [comment]
Hi Lawrence,

Yes it works! Thank you!


On 15 Dec 2015, at 19:16, Lawrence Mitchell <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Anna, can you confirm the workaround I suggested works for you?

**Comment by wence-** [comment]
OK good.  In the longer run, we should provide "read-only" and "read-write" access to the PETSc Mat objects (in the same way we do with Vecs).  Then we can handle this case transparently as long as you use the appropriate RW or READ access.

**Comment by wence-** [comment]
No longer necessary since the demise of the assembly cache.
