### ISSUE TITLE
Loading gmsh file fails

### ISSUE THREAD

**Issue by hbuesing** [firedrakeproject/firedrake#664]
I tried to load a simple rectangular gmsh file with a hole in the middle (test1.msh): 

mymesh = Mesh("test1.msh")
elt = FiniteElement("CG","triangle", 1)
CG1 = FunctionSpace(mymesh, elt)

When constructing the finite element space I get the error below. I attached the meshfile (test1.msh) and an example that reproduces the error (test.py). 

Henrik
 

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    CG1 = FunctionSpace(mymesh, elt)
  File "/home/hb111949/.local/lib/python2.7/site-packages/PyOP2-0.11.0_425_g64db689-py2.7-linux-x86_64.egg/pyop2/caching.py", line 161, in __new__
    obj = make_obj()
  File "/home/hb111949/.local/lib/python2.7/site-packages/PyOP2-0.11.0_425_g64db689-py2.7-linux-x86_64.egg/pyop2/caching.py", line 142, in make_obj
    obj.__init__(*args, **kwargs)
  File "/home/hb111949/Code/firedrake/firedrake/functionspace.py", line 578, in __init__
    mesh.init()
  File "/home/hb111949/Code/firedrake/firedrake/mesh.py", line 480, in init
    self._callback(self)
  File "/home/hb111949/Code/firedrake/firedrake/mesh.py", line 404, in callback
    old_to_new = self._plex.getOrdering(PETSc.Mat.OrderingType.RCM).indices
  File "PETSc/DMPlex.pyx", line 601, in petsc4py.PETSc.DMPlex.getOrdering (src/petsc4py.PETSc.c:224945)
petsc4py.PETSc.Error: error code 77
[0] DMPlexGetOrdering() line 136 in /rwthfs/rz/cluster/home/hb111949/Code/petsc/src/dm/impls/plex/plexreorder.c
[0] DMPlexCreateOrderingClosure_Static() line 43 in /rwthfs/rz/cluster/home/hb111949/Code/petsc/src/dm/impls/plex/plexreorder.c
[0] Petsc has generated inconsistent data
[0] Number of depth 1 faces 40 does not match permuted nubmer 38

```python
from firedrake import *
import time

parameters["pyop2_options"]["log_level"] = "WARNING"

# Load mesh
mymesh = Mesh("test1.msh")

# Construction of FV mesh
elt = FiniteElement("CG","triangle", 1)
CG1 = FunctionSpace(mymesh, elt)
```
[test1.msh.txt](https://github.com/firedrakeproject/firedrake/files/61329/test1.msh.txt)

**Comment by wence-** [comment]
This looks like the mesh contains some points that are not in the closure of any of the cells.  The entity numbering algorithm that we have fails in this case, because it assumes it can reach all vertices (and edges and faces) by traversing the closure of the cells.  This is clearly not the case here.  I think if you regenerate the mesh, ensuring that the points at the centre of the hole are not physical points (and therefore don't appear in the mesh file) things should work.

We should add some error checking to the renumbering step in Firedrake that asserts that we actually numbered all the mesh points so we can provide a useful error message rather than dying somewhere in PETSc.
