### ISSUE TITLE
Code not compiling on recent firedrake versions

### ISSUE THREAD

**Issue by tommbendall** [firedrakeproject/firedrake#682]
=================Description==========================
I'm trying to run some code that compiles on a previous version of firedrake, but doesn't work now.

Any help would be really appreciated!

==================Step to reproduce=======================

The program can be found at https://gist.github.com/tommbendall/4e2fc6471d8fb97ef60a

=========================Error message=============
Traceback (most recent call last):
  File "sqg.py", line 121, in <module>
    psi_solver.solve() #deterministic part of streamfunction
  File "<decorator-gen-288>", line 2, in solve
  File "/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/pyop2/profiling.py", line 203, in wrapper
    return f(*args, **kwargs)
  File "/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/firedrake/variational_solver.py", line 173, in solve
    self.snes.solve(None, v)
  File "PETSc/SNES.pyx", line 520, in petsc4py.PETSc.SNES.solve (src/petsc4py.PETSc.c:170828)
  File "PETSc/petscsnes.pxi", line 286, in petsc4py.PETSc.SNES_Jacobian (src/petsc4py.PETSc.c:34041)
  File "/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/firedrake/solving_utils.py", line 231, in form_jacobian
    ctx._jacs[lvl].M._force_evaluation()
  File "/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/firedrake/matrix.py", line 147, in M
    self._M._force_evaluation()
  File "/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/pyop2/base.py", line 1566, in _force_evaluation
    _trace.evaluate(reads, writes)
  File "/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/pyop2/base.py", line 170, in evaluate
    comp._run()
  File "/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/pyop2/base.py", line 4073, in _run
    return self.compute()
  File "/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/pyop2/base.py", line 4114, in compute
    fun = self._jitmodule
  File "/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/pyop2/utils.py", line 64, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/pyop2/sequential.py", line 151, in _jitmodule
    direct=self.is_direct, iterate=self.iteration_region)
  File "/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/pyop2/caching.py", line 203, in __new__
    obj = make_obj()
  File "/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/pyop2/caching.py", line 193, in make_obj
    obj.__init__(*args, **kwargs)
  File "/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/pyop2/host.py", line 700, in __init__
    self.compile()
  File "/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/pyop2/host.py", line 803, in compile
    compiler=compiler.get('name'))
  File "/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/pyop2/compilation.py", line 292, in load
    dll = compiler.get_so(src, extension)
  File "/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/pyop2/compilation.py", line 146, in get_so
    Compile errors in %s""" % (e.cmd, e.returncode, logfile, errfile))
pyop2.exceptions.CompilationError: Command "['mpicc', '-std=c99', '-fPIC', '-Wall', '-march=native', '-O3', '-fno-ivopts', '-I/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/petsc/include', '-I/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/firedrake', '-I/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/pyop2', '-msse', '-o', '/tmp/pyop2-cache-uid791676/8cb54d057f356021355f5bb7b054c73e_p6718.so.tmp', '/tmp/pyop2-cache-uid791676/8cb54d057f356021355f5bb7b054c73e_p6718.c', '-shared', '-L/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/petsc/lib', '-Wl,-rpath,/home/tmb15/src/firedrake/local/lib/python2.7/site-packages/petsc/lib', '-lpetsc', '-lm']" return error status 1.
Unable to compile code
Compile log in /tmp/pyop2-cache-uid791676/8cb54d057f356021355f5bb7b054c73e_p6718.log
Compile errors in /tmp/pyop2-cache-uid791676/8cb54d057f356021355f5bb7b054c73e_p6718.err
[3]+  Done                    emacs /tmp/pyop2-cache-uid791676/8cb54d057f356021355f5bb7b054c73e_p5011.err

=====================Error Log===================

The error log can be found here: https://gist.github.com/tommbendall/226517a9a8711cd7ebc2

**Comment by miklos1** [comment]
Could you please check if using COFFEE branch `fix-min-temporaries` fixes your problem?

**Comment by tommbendall** [comment]
I'm really sorry, I'm just starting with firedrake and I don't know what that means!

**Comment by colinjcotter** [comment]
Hi Thomas,
  You need to go into src/coffee, and type

git checkout fix-min-temporaries

and then try to run again.

This will indicate whether a fix for a previous bug which has not yet made
it into the master branch will also fix your problem.

all the best
--cjc

On 25 January 2016 at 10:51, tommbendall <notifications@github.com> wrote:

> I'm really sorry, I'm just starting with firedrake and I don't know what
> that means!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firedrakeproject/firedrake/issues/682#issuecomment-174468498>
> .
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by tommbendall** [comment]
I've given this a try and unfortunately it seems to give the same error

**Comment by miklos1** [comment]
I've merged that branch. Can you please switch back to master on COFFEE, and use the update script to update your Firedrake installation?

**Comment by tommbendall** [comment]
Hmm, still not working!

**Comment by miklos1** [comment]
Fixed.
