### ISSUE TITLE
Installation script does not warn if PYTHONPATH is set

### ISSUE THREAD

**Issue by funsim** [firedrakeproject/firedrake#785]
A set PYTHONPATH can cause the firedrake-install script to crash. In my case the error was

```bash
Traceback (most recent call last):
  File "/home/sf1409/foo/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 14, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 30, in <module>
    from pip._vendor.retrying import retry
ImportError: No module named retrying
```
 
This issue is resolved by unsetting the PYTHONPATH, which should be done in the install script.

**Comment by miklos1** [comment]
Related to #699.

**Comment by miklos1** [comment]
It does since #887.
