### ISSUE TITLE
Can't copy vectors from mixed spaces

### ISSUE THREAD

**Issue by rckirby** [firedrakeproject/firedrake#861]

**Comment by rckirby** [comment]
Minimal example:

from firedrake import *

mesh = UnitSquareMesh(1, 1)
V1 = FunctionSpace(mesh, "CG", 1)
V2 = FunctionSpace(mesh, "CG", 2)
Z = MixedFunctionSpace([V1, V2])

f = Function(Z)
fv = f.vector()

fv.copy()

This produces the traceback and error:

Traceback (most recent call last):
  File "minex.py", line 11, in <module>
    fv.copy()
  File "/home/rkirby/Code/firedrake/src/firedrake/firedrake/vector.py", line 120, in copy
    return Vector(op2.Dat(self.dat))
  File "/home/rkirby/Code/firedrake/src/PyOP2/pyop2/backends.py", line 118, in __call__
    return t(*args, **kwargs)
  File "<decorator-gen-245>", line 2, in __init__
  File "/home/rkirby/Code/firedrake/src/PyOP2/pyop2/utils.py", line 130, in wrapper
    return f(*args, **kwargs)
  File "<decorator-gen-244>", line 2, in __init__
  File "/home/rkirby/Code/firedrake/src/PyOP2/pyop2/utils.py", line 130, in wrapper
    return f(*args, **kwargs)
  File "/home/rkirby/Code/firedrake/src/PyOP2/pyop2/base.py", line 1669, in __init__
    name="copy_of_%s" % dataset.name, soa=dataset.soa)
  File "/home/rkirby/Code/firedrake/src/PyOP2/pyop2/utils.py", line 64, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/rkirby/Code/firedrake/src/PyOP2/pyop2/base.py", line 1542, in name
    return self._name
AttributeError: 'MixedDat' object has no attribute '_name'
