### ISSUE TITLE
*Real FS* Mixed FS instantiation with >2 spaces fails when some FS is Real

### ISSUE THREAD

**Issue by dorugeber** [firedrakeproject/firedrake#862]
```
from firedrake import *

mesh = PeriodicUnitIntervalMesh(10)

V1 = FunctionSpace(mesh, "CG", 1)
V2 = TensorFunctionSpace(mesh, "CG", 1)
V3 = FunctionSpace(mesh, "Real", 0)
V = V2*V3  # lives
V = V1*V2*V1  # lives
V = V1*V2*V3  # dies
```

fails with

```
Traceback (most recent call last):
  File "bug.py", line 10, in <module>
    V = V1*V2*V3  # dies
  File "/home/andrew/firedrake/src/firedrake/firedrake/functionspaceimpl.py", line 203, in __mul__
    return MixedFunctionSpace((self, other))
  File "/home/andrew/firedrake/src/firedrake/firedrake/functionspace.py", line 258, in MixedFunctionSpace
    new = impl.MixedFunctionSpace(spaces, name=name)
  File "/home/andrew/firedrake/src/firedrake/firedrake/functionspaceimpl.py", line 529, in __init__
    self.comm = self.node_set.comm
  File "/home/andrew/firedrake/src/PyOP2/pyop2/utils.py", line 64, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/andrew/firedrake/src/firedrake/firedrake/functionspaceimpl.py", line 622, in node_set
    return op2.MixedSet(s.node_set for s in self._spaces)
  File "/home/andrew/firedrake/src/PyOP2/pyop2/backends.py", line 118, in __call__
    return t(*args, **kwargs)
  File "/home/andrew/firedrake/src/PyOP2/pyop2/caching.py", line 156, in __new__
    obj = make_obj()
  File "/home/andrew/firedrake/src/PyOP2/pyop2/caching.py", line 137, in make_obj
    obj.__init__(*args, **kwargs)
  File "/home/andrew/firedrake/src/PyOP2/pyop2/base.py", line 979, in __init__
    self.comm = reduce(lambda a, b: a if a is None else a.comm or b if b is None else b.comm, sets)
  File "/home/andrew/firedrake/src/PyOP2/pyop2/base.py", line 979, in <lambda>
    self.comm = reduce(lambda a, b: a if a is None else a.comm or b if b is None else b.comm, sets)
AttributeError: 'mpi4py.MPI.Intracomm' object has no attribute 'comm'
```

**Comment by dorugeber** [comment]
Suggestion from @miklos1:
`self.comm = reduce(lambda a, b: a or b, map(lambda s: s if s is None else s.comm, sets))`

**Comment by dorugeber** [comment]
Similar problem in the `iterset` when constructing a NVS:

```
...
  File "/home/andrew/firedrake/src/PyOP2/pyop2/base.py", line 3366, in iterset
    return reduce(lambda a, b: a if a is None else a.iterset or b if b is None else b.iterset, self._maps)
  File "/home/andrew/firedrake/src/PyOP2/pyop2/base.py", line 3366, in <lambda>
    return reduce(lambda a, b: a if a is None else a.iterset or b if b is None else b.iterset, self._maps)
AttributeError: 'Set' object has no attribute 'iterset'
```

**Comment by colinjcotter** [comment]
@dorugeber any chance you could try those patches and see if it works?

**Comment by dorugeber** [comment]
What?

**Comment by colinjcotter** [comment]
You wrote "suggested patch" etc

**Comment by dorugeber** [comment]
Yes.  Those patches make those snippets of code work.  The code I wanted to run then failed, per #863

**Comment by colinjcotter** [comment]
OK thanks for clarifying. Code in #863 is not expected to work.

**Comment by miklos1** [comment]
@dorugeber: What's the state of this? Are the suggested patches in master yet, and can this be closed?

**Comment by wence-** [comment]
Seems to work now.
