### ISSUE TITLE
*Real FS* solve breaks with monolithic matrix

### ISSUE THREAD

**Issue by dorugeber** [firedrakeproject/firedrake#863]
```
from firedrake import *

mesh = UnitIntervalMesh(10)
parameters["pyop2_options"]["lazy_evaluation"] = False
parameters["matnest"] = False

V1 = FunctionSpace(mesh, "CG", 1)
V2 = FunctionSpace(mesh, "Real", 0)

V = V1*V2

ab = Function(V)
a, b = split(ab)
c, d = TestFunctions(V)

F = (a*c + b*d)*dx

solve(F == 0, ab)
```

fails with

```
Traceback (most recent call last):
  File "bug.py", line 18, in <module>
    solve(F == 0, ab)
  File "/home/andrew/firedrake/src/firedrake/firedrake/solving.py", line 119, in solve
    _solve_varproblem(*args, **kwargs)
  File "/home/andrew/firedrake/src/firedrake/firedrake/solving.py", line 162, in _solve_varproblem
    options_prefix=options_prefix)
  File "/home/andrew/firedrake/src/firedrake/firedrake/variational_solver.py", line 127, in __init__
    ctx = solving_utils._SNESContext(problem, pre_jacobian_callback, pre_function_callback)
  File "/home/andrew/firedrake/src/firedrake/firedrake/solving_utils.py", line 111, in __init__
    for problem in problems)
  File "/home/andrew/firedrake/src/firedrake/firedrake/solving_utils.py", line 111, in <genexpr>
    for problem in problems)
  File "/home/andrew/firedrake/src/firedrake/firedrake/assemble.py", line 67, in assemble
    inverse=inverse, nest=nest)
  File "<decorator-gen-294>", line 2, in _assemble
  File "/home/andrew/firedrake/src/firedrake/firedrake/utils.py", line 62, in wrapper
    return f(*args, **kwargs)
  File "/home/andrew/firedrake/src/firedrake/firedrake/assemble.py", line 179, in _assemble
    nest=nest)
  File "/home/andrew/firedrake/src/PyOP2/pyop2/backends.py", line 118, in __call__
    return t(*args, **kwargs)
  File "/home/andrew/firedrake/src/PyOP2/pyop2/caching.py", line 156, in __new__
    obj = make_obj()
  File "/home/andrew/firedrake/src/PyOP2/pyop2/caching.py", line 137, in make_obj
    obj.__init__(*args, **kwargs)
  File "/home/andrew/firedrake/src/PyOP2/pyop2/base.py", line 3546, in __init__
    block=self._block_sparse)
  File "pyop2/sparsity.pyx", line 259, in pyop2.sparsity.build_sparsity (pyop2/sparsity.cpp:5665)
  File "pyop2/sparsity.pyx", line 61, in pyop2.sparsity.set_writeable (pyop2/sparsity.cpp:3096)
AttributeError: 'NoneType' object has no attribute 'values_with_halo'
```

**Comment by wence-** [comment]
Afaiaa, @dham definitely hasn't implemented this case yet.

**Comment by dham** [comment]
Yes. This isn't ever expected to work. I agree it would be good to fail more gracefully.

**Comment by dorugeber** [comment]
As in, there are no plans to support assembly into monolithic matrices with the Real function space?

**Comment by dham** [comment]
Correct. It would amount to basically doing all the work again because the mechanism is so different.

**Comment by dorugeber** [comment]
Oh, okay.  I was using Real precisely because I wanted to use a direct solver on an otherwise-singular system (my attempt at driving MUMPS to work with singular systems failed).

We now have an iterative method that works reliably, so this isn't a feature request right now.
