### ISSUE TITLE
Cannot interpolate as_vector([v1, v2])

### ISSUE THREAD

**Issue by APaganini** [firedrakeproject/firedrake#898]
Consider the following code:

```
from firedrake import *

class MyExpr(Expression):
    def eval(self, value, x):
        value[:] = x[0]

mesh = UnitSquareMesh(20, 20)
x = SpatialCoordinate(mesh)
U = FunctionSpace(mesh, "CG", 1)
W = VectorFunctionSpace(mesh, "CG", 1)

# This works
u = interpolate(MyExpr(), U)

# This doesn't
v = as_vector([MyExpr(), MyExpr()])
u = interpolate(v, W)

```

The second interpolate gives an error:

```
(firedrake) koala-brothers:tmp% python firedrakebug.py 
Traceback (most recent call last):
  File "firedrakebug.py", line 17, in <module>
    u = interpolate(v, W)
  File "/home/paganini/Documents/firedrake/src/firedrake/firedrake/interpolation.py", line 36, in interpolate
    return Interpolator(expr, V, subset=subset).interpolate()
  File "/home/paganini/Documents/firedrake/src/firedrake/firedrake/interpolation.py", line 56, in __init__
    self.callable = make_interpolator(expr, V, subset)
  File "/home/paganini/Documents/firedrake/src/firedrake/firedrake/interpolation.py", line 111, in make_interpolator
    loops.append(_interpolator(V, f.dat, expr, subset))
  File "/home/paganini/Documents/firedrake/src/firedrake/firedrake/interpolation.py", line 162, in _interpolator
    kernel, oriented, coefficients = compile_ufl_kernel(expr, to_pts, to_element, V)
  File "/home/paganini/Documents/firedrake/src/firedrake/firedrake/interpolation.py", line 210, in compile_ufl_kernel
    expression = apply_algebra_lowering(expression)
  File "/home/paganini/Documents/firedrake/src/ufl/ufl/algorithms/apply_algebra_lowering.py", line 180, in apply_algebra_lowering
    return map_integrand_dags(LowerCompoundAlgebra(), expr)
  File "/home/paganini/Documents/firedrake/src/ufl/ufl/algorithms/map_integrands.py", line 58, in map_integrand_dags
    form, only_integral_type)
  File "/home/paganini/Documents/firedrake/src/ufl/ufl/algorithms/map_integrands.py", line 51, in map_integrands
    return function(integrand)
  File "/home/paganini/Documents/firedrake/src/ufl/ufl/algorithms/map_integrands.py", line 57, in <lambda>
    return map_integrands(lambda expr: map_expr_dag(function, expr, compress),
  File "/home/paganini/Documents/firedrake/src/ufl/ufl/corealg/map_dag.py", line 37, in map_expr_dag
    result, = map_expr_dags(function, [expression], compress=compress)
  File "/home/paganini/Documents/firedrake/src/ufl/ufl/corealg/map_dag.py", line 77, in map_expr_dags
    for v in traversal(expression):
  File "/home/paganini/Documents/firedrake/src/ufl/ufl/corealg/traversal.py", line 127, in unique_post_traversal
    if o is not None and o not in visited:
  File "/home/paganini/Documents/firedrake/src/ufl/ufl/core/compute_expr_hash.py", line 33, in compute_expr_hash
    if expr._hash is not None:
AttributeError: _hash
```

I don't think there's any reason in principle why this is different than making a vector-valued Expression; could it be supported in firedrake?

**Comment by miklos1** [comment]
You cannot compose Python `Expression` classes with UFL expressions. Write `as_vector([x[0], x[0]])` instead where `x` is the spatial coordinate.

**Comment by APaganini** [comment]
ok, thanks
