### ISSUE TITLE
firedrake-install no longer works after bc1a6a53eebcec2cd4d67fc28f82ebc0e9dde085

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#906]
With version bc1a6a53eebcec2cd4d67fc28f82ebc0e9dde085:

```
[pfarrell@saoirse:~/local/firedrake] (git:master) $ python ~/src/firedrake/scripts/firedrake-install --help
Traceback (most recent call last):
  File "/home/pfarrell/src/firedrake/scripts/firedrake-install", line 142, in <module>
    args = parser.parse_args()
  File "/usr/lib/python2.7/argparse.py", line 1701, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1939, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python2.7/argparse.py", line 1879, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python2.7/argparse.py", line 1807, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python2.7/argparse.py", line 996, in __call__
    parser.print_help()
  File "/usr/lib/python2.7/argparse.py", line 2340, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python2.7/argparse.py", line 2314, in format_help
    return formatter.format_help()
  File "/usr/lib/python2.7/argparse.py", line 281, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python2.7/argparse.py", line 211, in format_help
    func(*args)
  File "/usr/lib/python2.7/argparse.py", line 319, in _format_usage
    action_usage = format(optionals + positionals, groups)
  File "/usr/lib/python2.7/argparse.py", line 390, in _format_actions_usage
    start = actions.index(group._group_actions[0])
IndexError: list index out of range
```

After `git show 8c7cfe772676e159232b7171adab55cb57e44b04:scripts/firedrake-install > scripts/firedrake-install`:

```
[pfarrell@saoirse:~/local/firedrake] (git:master) $ python ~/src/firedrake/scripts/firedrake-install --help
usage: firedrake-install [-h] [--developer] [--sudo] [--adjoint] [--slope]
...
```

**Comment by dham** [comment]
Odd. The build tests pass.

**Comment by dham** [comment]
OK I can reproduce this locally. Maybe it depends on which version of argparse you have....

**Comment by miklos1** [comment]
I had the same problem and pushed a fix.

**Comment by miklos1** [comment]
I claim this is fixed.
