### ISSUE TITLE
Cannot create mixed function space on quadrilateral mesh?

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#908]
I have a quad mesh (generated automatically from a VTK file by meshio-convert). Gmsh loads the quad mesh fine, and so does Plex, so my prior is that it is OK.

If I run the following code:

```
from firedrake import *

mesh = Mesh("mesh0.msh")
Vele = VectorElement("CG", triangle, 2, dim=3)
Qele = FiniteElement("DG", triangle, 0)
Zele = MixedElement([Vele, Qele])
Z = FunctionSpace(mesh, Zele)
```

then I get the following exception:

```
Traceback (most recent call last):
  File "fbug.py", line 7, in <module>
    Z = FunctionSpace(mesh, Zele)
  File "<decorator-gen-292>", line 2, in FunctionSpace
  File "/home/pfarrell/local/firedrake/firedrake/src/PyOP2/pyop2/profiling.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/functionspace.py", line 124, in FunctionSpace
    return MixedFunctionSpace(element, mesh=mesh, name=name)
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/functionspace.py", line 234, in MixedFunctionSpace
    spaces = [FunctionSpace(mesh, element) for element in sub_elements]
  File "<decorator-gen-292>", line 2, in FunctionSpace
  File "/home/pfarrell/local/firedrake/firedrake/src/PyOP2/pyop2/profiling.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/functionspace.py", line 131, in FunctionSpace
    new = impl.FunctionSpace(topology, element, name=name)
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/functionspaceimpl.py", line 249, in __init__
    sdata = get_shared_data(mesh, fiat_element)
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/functionspacedata.py", line 554, in get_shared_data
    return FunctionSpaceData(mesh, fiat_element)
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/functionspacedata.py", line 307, in __init__
    self.entity_node_lists = get_entity_node_lists(mesh, edofs_key, entity_dofs, global_numbering)
  File "<decorator-gen-278>", line 2, in get_entity_node_lists
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/functionspacedata.py", line 55, in cached
    result = f(mesh, key, *args, **kwargs)
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/functionspacedata.py", line 146, in get_entity_node_lists
    cell_node_list = get_cell_node_list(mesh, entity_dofs, global_numbering)
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/functionspacedata.py", line 111, in get_cell_node_list
    return mesh.make_cell_node_list(global_numbering, entity_dofs)
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/mesh.py", line 573, in make_cell_node_list
    entity_dofs)
  File "firedrake/dmplex.pyx", line 453, in firedrake.dmplex.get_cell_nodes (firedrake/dmplex.c:7213)
AssertionError
```

Is this a bug in firedrake, or is there something wrong with the mesh?
[mesh0.msh.zip](https://github.com/firedrakeproject/firedrake/files/521487/mesh0.msh.zip)

**Comment by pefarrell** [comment]
Sorry, I just realised the mesh is non-conforming! Please disregard.

**Comment by dorugeber** [comment]
Also, our standard notation is to create VFS V, FS Q, then `Z = V * Q`
