### ISSUE TITLE
Cannot use `VectorFunctionSpace(mesh, "R", 0)`

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#924]
```
The following code

from firedrake import *
mesh = UnitIntervalMesh(2)
V = VectorFunctionSpace(mesh, "R", 0, dim=3)

u = TrialFunction(V)
v = TestFunction(V)
A = assemble(inner(grad(u), grad(v))*dx)
```

gives the error

```
Traceback (most recent call last):
  File "firebug.py", line 7, in <module>
    A = assemble(inner(grad(u), grad(v))*dx)
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/assemble.py", line 81, in assemble
    inverse=inverse, mat_type=mat_type, appctx=appctx)
  File "<decorator-gen-291>", line 2, in _assemble
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/utils.py", line 62, in wrapper
    return f(*args, **kwargs)
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/assemble.py", line 120, in _assemble
    inverse=inverse)
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 189, in compile_form
    number_map).kernels
  File "/home/pfarrell/local/firedrake/firedrake/src/PyOP2/pyop2/caching.py", line 198, in __new__
    obj = make_obj()
  File "/home/pfarrell/local/firedrake/firedrake/src/PyOP2/pyop2/caching.py", line 188, in make_obj
    obj.__init__(*args, **kwargs)
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 110, in __init__
    tree = tsfc_compile_form(form, prefix=name, parameters=parameters)
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/driver.py", line 43, in compile_form
    kernels.append(compile_integral(integral_data, fd, prefix, parameters))
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/driver.py", line 217, in compile_integral
    facetarea=facetarea)
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/fem.py", line 405, in compile_ufl
    return map_expr_dags(translator, expressions)
  File "/home/pfarrell/local/firedrake/firedrake/src/ufl/ufl/corealg/map_dag.py", line 84, in map_expr_dags
    r = handlers[v._ufl_typecode_](v)
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/ufl_utils.py", line 107, in _modified_terminal
    return self.modified_terminal(o)
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/fem.py", line 254, in modified_terminal
    return translate(mt.terminal, mt, self.parameters)
  File "/home/pfarrell/local/firedrake/firedrake/local/lib/python2.7/site-packages/singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/fem.py", line 339, in translate_argument
    return iterate_shape(mt, callback)
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/fem.py", line 282, in iterate_shape
    result.append(callback((ufl_element, c, flat_deriv)))
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/fem.py", line 330, in callback
    table = params.tabulation_manager[key]
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/fem.py", line 118, in __getitem__
    return self.tables[key]
KeyError: (VectorElement(FiniteElement('Real', interval, 0), dim=3), 0, (1,))
```

I understand from slack that this isn't implemented yet, but wanted to submit a bug to track its progress.

**Comment by pefarrell** [comment]
Also, one cannot use a `MixedFunctionSpace` to work around

```
from firedrake import *
mesh = UnitIntervalMesh(2)
#V = VectorFunctionSpace(mesh, "R", 0, dim=3)
R = FunctionSpace(mesh, "R", 0)
V = MixedFunctionSpace([R, R, R])

u = TrialFunction(V)
v = TestFunction(V)
A = assemble(inner(grad(u), grad(v))*dx)
```

gives

```
Traceback (most recent call last):
  File "firebug.py", line 9, in <module>
    A = assemble(inner(grad(u), grad(v))*dx)
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/assemble.py", line 81, in assemble
    inverse=inverse, mat_type=mat_type, appctx=appctx)
  File "<decorator-gen-291>", line 2, in _assemble
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/utils.py", line 62, in wrapper
    return f(*args, **kwargs)
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/assemble.py", line 120, in _assemble
    inverse=inverse)
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 189, in compile_form
    number_map).kernels
  File "/home/pfarrell/local/firedrake/firedrake/src/PyOP2/pyop2/caching.py", line 198, in __new__
    obj = make_obj()
  File "/home/pfarrell/local/firedrake/firedrake/src/PyOP2/pyop2/caching.py", line 188, in make_obj
    obj.__init__(*args, **kwargs)
  File "/home/pfarrell/local/firedrake/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 110, in __init__
    tree = tsfc_compile_form(form, prefix=name, parameters=parameters)
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/driver.py", line 43, in compile_form
    kernels.append(compile_integral(integral_data, fd, prefix, parameters))
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/driver.py", line 217, in compile_integral
    facetarea=facetarea)
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/fem.py", line 405, in compile_ufl
    return map_expr_dags(translator, expressions)
  File "/home/pfarrell/local/firedrake/firedrake/src/ufl/ufl/corealg/map_dag.py", line 84, in map_expr_dags
    r = handlers[v._ufl_typecode_](v)
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/ufl_utils.py", line 107, in _modified_terminal
    return self.modified_terminal(o)
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/fem.py", line 254, in modified_terminal
    return translate(mt.terminal, mt, self.parameters)
  File "/home/pfarrell/local/firedrake/firedrake/local/lib/python2.7/site-packages/singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/fem.py", line 339, in translate_argument
    return iterate_shape(mt, callback)
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/fem.py", line 282, in iterate_shape
    result.append(callback((ufl_element, c, flat_deriv)))
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/fem.py", line 330, in callback
    table = params.tabulation_manager[key]
  File "/home/pfarrell/local/firedrake/firedrake/src/tsfc/tsfc/fem.py", line 118, in __getitem__
    return self.tables[key]
KeyError: (FiniteElement('Real', interval, 0), 0, (1,))
```

**Comment by wence-** [comment]
Maybe the latter now works (although good luck looking at the matrix), and this particular example simplifies to zero.
