### ISSUE TITLE
python expressions do not work for extruded meshes

### ISSUE THREAD

**Issue by tkarna** [firedrakeproject/firedrake#947]
... or I'm doing something wrong. This example

```python
from firedrake import *
parameters['pyop2_options']['lazy_evaluation'] = False

mesh2d = UnitSquareMesh(5, 5)
mesh = ExtrudedMesh(mesh2d, layers=6, layer_height=0.1)

V = FunctionSpace(mesh, 'DG', 1)


class MyExpression(Expression):
    def eval(self, value, x):
        value[:] = 4.5

    def value_shape(self):
        return ()

f = Function(V)
f.interpolate(MyExpression())

print f.dat.data.min(), f.dat.data.max()
```

dies with

```
Traceback (most recent call last):
  File "test_expression.py", line 22, in <module>
    f.interpolate(MyExpression())
  File "/home/tuomas_master/sources/firedrake/src/firedrake/firedrake/function.py", line 328, in interpolate
    return interpolation.interpolate(expression, self, subset=subset)
  File "/home/tuomas_master/sources/firedrake/src/firedrake/firedrake/interpolation.py", line 38, in interpolate
    return Interpolator(expr, V, subset=subset).interpolate()
  File "<decorator-gen-294>", line 2, in interpolate
  File "/home/tuomas_master/sources/firedrake/src/firedrake/firedrake/utils.py", line 62, in wrapper
    return f(*args, **kwargs)
  File "/home/tuomas_master/sources/firedrake/src/firedrake/firedrake/interpolation.py", line 66, in interpolate
    return self.callable()
  File "/home/tuomas_master/sources/firedrake/src/firedrake/firedrake/interpolation.py", line 132, in callable
    l()
  File "<decorator-gen-269>", line 2, in par_loop
  File "/home/tuomas_master/sources/firedrake/src/PyOP2/pyop2/versioning.py", line 154, in modifies_arguments
    retval = func(*args, **kwargs)
  File "/home/tuomas_master/sources/firedrake/src/PyOP2/pyop2/op2.py", line 273, in par_loop
    return backends._BackendSelector._backend.par_loop(kernel, iterset, *args, **kwargs)
  File "/home/tuomas_master/sources/firedrake/src/PyOP2/pyop2/base.py", line 4563, in par_loop
    return pyparloop.ParLoop(pyparloop.Kernel(kernel), it_space, *args, **kwargs).enqueue()
  File "/home/tuomas_master/sources/firedrake/src/PyOP2/pyop2/base.py", line 80, in enqueue
    _trace.append(self)
  File "/home/tuomas_master/sources/firedrake/src/PyOP2/pyop2/base.py", line 97, in append
    computation._run()
  File "/home/tuomas_master/sources/firedrake/src/PyOP2/pyop2/base.py", line 4203, in _run
    return self.compute()
  File "/home/tuomas_master/sources/firedrake/src/PyOP2/pyop2/base.py", line 4246, in compute
    self._compute(iterset.core_part, fun, *arglist)
  File "/home/tuomas_master/sources/firedrake/src/PyOP2/pyop2/pyparloop.py", line 109, in _compute
    raise NotImplementedError
```

**Comment by wence-** [comment]
No, you're not doing anything wrong.  See also #514

**Comment by miklos1** [comment]
Are there any legitimate use cases for Python `Expression`s other than DOLFIN compatibility?

**Comment by tkarna** [comment]
In this case I had a complex numpy expression that I wanted to use. I guess I could re-write it in ufl instead.

**Comment by wence-** [comment]
Will close, I think, due to `Expression` deprecation: we can fix this if it is _really_ needed, but I would rather do it another way.
