### ISSUE TITLE
firedrake-clean: No module named h5py

### ISSUE THREAD

**Issue by APaganini** [firedrakeproject/firedrake#968]
Hi, I have updated firedrake (succesfully) with `firedrake-activate`.

However, calling `firedrake-clean` returns

```
(firedrakeAdjoint) $ firedrake-clean
Traceback (most recent call last):
  File "/Volumes/Scratch/Users/paalbert/Documents/FIREDRAKE/firedrakeAdjoint/bin/firedrake-clean", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Volumes/Scratch/Users/paalbert/Documents/FIREDRAKE/firedrakeAdjoint/src/firedrake/scripts/firedrake-clean", line 3, in <module>
    from firedrake.tsfc_interface import clear_cache, TSFCKernel
  File "/Volumes/Scratch/Users/paalbert/Documents/FIREDRAKE/firedrakeAdjoint/src/firedrake/firedrake/__init__.py", line 31, in <module>
    from firedrake.checkpointing import *
  File "/Volumes/Scratch/Users/paalbert/Documents/FIREDRAKE/firedrakeAdjoint/src/firedrake/firedrake/checkpointing.py", line 4, in <module>
    from firedrake import hdf5interface as h5i
  File "firedrake/hdf5interface.pyx", line 1, in init firedrake.hdf5interface (firedrake/hdf5interface.c:2322)
ImportError: No module named h5py
```
which is not very promising.

**Comment by miklos1** [comment]
Does #965 help?

**Comment by wence-** [comment]
I just merged that, please run `firedrake-update --rebuild`.

**Comment by APaganini** [comment]
This solves the issue, thanks.
