### ISSUE TITLE
firedrake-install not working out of the box on Ubuntu trusty

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#974]
Dear firedrake experts,

I run `firedrake-install --adjoint --slepc --disable-ssh` on an Ubuntu trusty machine; everything appears to install fine.

But if I try to use it in another terminal, I get

```
[farrellp@longshot:~]$ . /scratch/farrellp/firedrake/firedrake/bin/activate
(firedrake)[farrellp@longshot:~]$ ipython
imPython 2.7.6 (default, Oct 26 2016, 20:30:19) 
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import firedrake
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-1a13c89f4bd7> in <module>()
----> 1 import firedrake

/scratch/farrellp/firedrake/firedrake/src/firedrake/firedrake/__init__.py in <module>()
      1 from __future__ import absolute_import
      2 # Ensure petsc is initialised by us before anything else gets in there.
----> 3 import firedrake.petsc as petsc
      4 del petsc
      5 

/scratch/farrellp/firedrake/firedrake/src/firedrake/firedrake/petsc.py in <module>()
      3 import petsc4py
      4 import sys
----> 5 petsc4py.init(sys.argv)
      6 from petsc4py import PETSc  # NOQA: F401

/scratch/farrellp/firedrake/firedrake/local/lib/python2.7/site-packages/petsc4py/__init__.pyc in init(args, arch, comm)
     40     """
     41     import petsc4py.lib
---> 42     PETSc = petsc4py.lib.ImportPETSc(arch)
     43     args  = petsc4py.lib.getInitArgs(args)
     44     PETSc._initialize(args, comm)

/scratch/farrellp/firedrake/firedrake/local/lib/python2.7/site-packages/petsc4py/lib/__init__.pyc in ImportPETSc(arch)
     27     """
     28     path, arch = getPathArchPETSc(arch)
---> 29     return Import('petsc4py', 'PETSc', path, arch)
     30 
     31 def getPathArchPETSc(arch=None):

/scratch/farrellp/firedrake/firedrake/local/lib/python2.7/site-packages/petsc4py/lib/__init__.pyc in Import(pkg, name, path, arch)
     62     pathlist = [os.path.join(path, arch)]
     63     fo, fn, stuff = imp.find_module(name, pathlist)
---> 64     module = imp.load_module(fullname, fo, fn, stuff)
     65     module.__arch__ = arch # save arch value
     66     setattr(sys.modules[pkg], name, module)

/home/farrellp/PETSc/arraynpy.pxi in init petsc4py.PETSc (src/petsc4py.PETSc.c:256092)()

ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
```

Bizarrely, it works in the terminal where I installed it.

**Comment by wence-** [comment]
Can you provide the output (in firedrake-status.log) of `firedrake-status --log` in both the working terminal and the broken one?

**Comment by pefarrell** [comment]
[working.log.zip](https://github.com/firedrakeproject/firedrake/files/661930/working.log.zip)

Here is the output of `firedrake-status --log` from the working terminal.

If I try in the broken terminal, I get

```
(firedrake)[farrellp@longshot:/tmp]$ firedrake-status --log > /tmp/failing.log
Traceback (most recent call last):
  File "/scratch/farrellp/firedrake/firedrake/bin/firedrake-status", line 4, in <module>
    __import__('pkg_resources').require('firedrake==0.13.0+923.g24b6e32')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 595, in resolve
    requirements = list(requirements)[::-1]  # set up the stack
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2583, in scan_list
    "Expected ',' or end-of-list in",line,"at",line[p:]
ValueError: ("Expected ',' or end-of-list in", 'firedrake==0.13.0+923.g24b6e32', 'at', '+923.g24b6e32')
(firedrake)[farrellp@longshot:/tmp]$ 
```

**Comment by wence-** [comment]
OK, in the broken terminal, what does `env` say?  I am suspicious of this line: `/home/farrellp/PETSc/arraynpy.pxi` that doesn't look like the "right" PETSc?

**Comment by pefarrell** [comment]
Sure:

```
(firedrake)[farrellp@longshot:~]$ env
GREEN=\[\033[0;32m\]
XDG_SESSION_ID=168
NONE=\[\033[0m\]
TERM=xterm-256color
SHELL=/bin/bash
HISTSIZE=1000000
XDG_SESSION_COOKIE=c75b192872b2edec022285b7546f5a0c-1482233694.253084-130261470
YELLOW=\[\033[0;33m\]
SSH_CLIENT=129.67.184.29 58588 22
SSH_TTY=/dev/pts/15
HISTFILESIZE=1000000
USER=farrellp
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
BLUE=\[\033[0;34m\]
SSH_AUTH_SOCK=/tmp/ssh-JtVaVCCM5B/agent.16662
VIRTUAL_ENV=/scratch/farrellp/firedrake/firedrake
MAIL=/var/mail/farrellp
PATH=/scratch/farrellp/firedrake/firedrake/bin:/home/farrellp/.local/bin:/home/farrellp/bin:/mi/bin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
QT_QPA_PLATFORMTHEME=appmenu-qt5
PWD=/home/farrellp
EDITOR=vim
LANG=en_GB.UTF8
PS1=(firedrake)\[\033[0;33m\][\[\033[0;34m\]\u\[\033[0;33m\]@\[\033[0;34m\]\h:\[\033[0;33m\]\w\[\033[0;33m\]]\[\033[0;32m\]$(/home/farrellp/bin/vcprompt -f ' (%s:%b) ')\[\033[0;31m\]$\[\033[0m\] 
RED=\[\033[0;31m\]
SHLVL=1
HOME=/home/farrellp
PURPLE=\[\033[0;35m\]
LANGUAGE=en_GB:
PYTHONPATH=/scratch/farrellp/src/fenics-shells:/scratch/farrellp/defcon:/scratch/farrellp/nld:/scratch/farrellp/upmc:/scratch/farrellp/src/pragmatic/python:/scratch/farrellp/install/usr/local/lib/python2.7/dist-packages:/scratch/farrellp/install/lib/python2.7/site-packages/:/data/pfarrell/src/dolfin-adjoint:
LOGNAME=farrellp
SSH_CONNECTION=129.67.184.29 58588 129.67.184.175 22
LESSOPEN=| /usr/bin/lesspipe %s
XDG_RUNTIME_DIR=/run/user/20314
CYAN=\[\033[0;36m\]
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/env
```

Ahh, if I unset PYTHONPATH then it works. I guess my .bashrc is adding something to PYTHONPATH that is conflicting. I wonder what ..

In any case, this isn't a problem with firedrake. Sorry for the noise.
